//! Part 4 of the English question bank: Taboo.
use super::super::questions::{q, q_open, Category, Difficulty, Question};

pub static QUESTIONS_EN_4: &[Question] = &[
    // ================= Art =================
    q!(Category::Art, Difficulty::Hard, "Which Verdi opera is set in Egypt?", 1, ["Rigoletto", "Aida", "La Traviata", "Otello"]),
    q!(Category::Art, Difficulty::Hard, "Which Spanish painter painted 'The Naked Maja'?", 1, ["Velázquez", "Goya", "Murillo", "Zurbarán"]),
    q!(Category::Art, Difficulty::Hard, "Which writer wrote 'El Buscón'?", 1, ["Cervantes", "Quevedo", "Lope", "Gracián"]),
    q!(Category::Art, Difficulty::Hard, "Which art movement has Dalí as its greatest exponent?", 1, ["Cubism", "Surrealism", "Dadaism", "Futurism"]),
    // ================= Taboo =================
    // -- Easy --
    q!(Category::Taboo, Difficulty::Easy, "It's a farm animal that lays eggs. What is it?", 0, ["The hen", "The cow", "The pig", "The sheep"]),
    q!(Category::Taboo, Difficulty::Easy, "It has 8 legs and spins webs. What is it?", 1, ["The ant", "The spider", "The bee", "The fly"]),
    q!(Category::Taboo, Difficulty::Easy, "It's yellow, long and monkeys love it. What is it?", 0, ["The banana", "The pear", "The lemon", "The mango"]),
    q!(Category::Taboo, Difficulty::Easy, "It's used to write and erase on the board. What is it?", 1, ["The marker", "The chalk", "The pencil", "The pen"]),
    q!(Category::Taboo, Difficulty::Easy, "It has hands and tells the time. What is it?", 2, ["The calendar", "The compass", "The clock", "The stopwatch"]),
    q!(Category::Taboo, Difficulty::Easy, "It's a means of transport with two wheels. What is it?", 3, ["The car", "The motorbike", "The scooter", "The bicycle"]),
    q!(Category::Taboo, Difficulty::Easy, "You use it to tie your shoes. What is it?", 0, ["The shoelace", "The belt", "The velcro", "The zipper"]),
    q!(Category::Taboo, Difficulty::Easy, "It's a long metal musical instrument that sounds loud. What is it?", 2, ["The flute", "The violin", "The trumpet", "The drum"]),
    q!(Category::Taboo, Difficulty::Easy, "It's a place where books are lent. What is it?", 1, ["The bookstore", "The library", "The stationery shop", "The printing press"]),
    q!(Category::Taboo, Difficulty::Easy, "It's used to look at yourself and see your reflection. What is it?", 1, ["The window", "The mirror", "The photo", "The screen"]),
    // -- Medium --
    q!(Category::Taboo, Difficulty::Medium, "It's used to measure fever. What is it?", 0, ["The thermometer", "The barometer", "The blood pressure monitor", "The clock"]),
    q!(Category::Taboo, Difficulty::Medium, "It has keys and is used to do calculations. What is it?", 1, ["The keyboard", "The calculator", "The typewriter", "The computer"]),
    q!(Category::Taboo, Difficulty::Medium, "It stores food and keeps it cold. What is it?", 0, ["The fridge", "The oven", "The freezer", "The pantry"]),
    q!(Category::Taboo, Difficulty::Medium, "Firefighters use it to put out fires. What is it?", 1, ["The ladder", "The hose", "The shovel", "The fire extinguisher"]),
    q!(Category::Taboo, Difficulty::Medium, "It hangs on the wall and shows the day and the month. What is it?", 3, ["The schedule", "The map", "The planner", "The calendar"]),
    q!(Category::Taboo, Difficulty::Medium, "It has pages and is used to take notes. What is it?", 0, ["The notebook", "The book", "The newspaper", "The sheet of paper"]),
    q!(Category::Taboo, Difficulty::Medium, "It rings in the morning to wake you up. What is it?", 2, ["The bell", "The siren", "The alarm clock", "The doorbell"]),
    q!(Category::Taboo, Difficulty::Medium, "It's planted in the ground and a plant grows from it. What is it?", 3, ["The root", "The flower", "The leaf", "The seed"]),
    q!(Category::Taboo, Difficulty::Medium, "You open it to enter or leave a room. What is it?", 1, ["The window", "The door", "The gate", "The grille"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to fish in the river with a fishing line. What is it?", 1, ["The net", "The fishing rod", "The harpoon", "The boat"]),
    // -- Hard --
    q!(Category::Taboo, Difficulty::Hard, "Optical instrument that sailors used to see far away. What is it?", 0, ["The spyglass", "The telescope", "The binoculars", "The microscope"]),
    q!(Category::Taboo, Difficulty::Hard, "It flies in the sky and takes off from a runway. What is it?", 2, ["The helicopter", "The balloon", "The airplane", "The drone"]),
    q!(Category::Taboo, Difficulty::Hard, "It's used to cut paper in a straight line. What is it?", 1, ["The box cutter", "The scissors", "The knife", "The letter opener"]),
    q!(Category::Taboo, Difficulty::Hard, "It has a trunk, big ears and is very heavy. What is it?", 0, ["The elephant", "The rhinoceros", "The hippopotamus", "The mammoth"]),
    q!(Category::Taboo, Difficulty::Hard, "It's placed on your head to protect you from the sun. What is it?", 2, ["The cap", "The visor", "The hat", "The helmet"]),
    q!(Category::Taboo, Difficulty::Hard, "It's used to open canned food. What is it?", 0, ["The can opener", "The bottle opener", "The knife", "The tongs"]),
    q!(Category::Taboo, Difficulty::Hard, "It gives light at night and works with batteries. What is it?", 1, ["The candle", "The flashlight", "The lamp", "The lighthouse"]),
    q!(Category::Taboo, Difficulty::Hard, "It's the place where the sick are treated. What is it?", 3, ["The pharmacy", "The clinic", "The health center", "The hospital"]),
    q!(Category::Taboo, Difficulty::Hard, "It's used to draw at school and has a lead. What is it?", 0, ["The pencil", "The pen", "The chalk", "The marker"]),
    q!(Category::Taboo, Difficulty::Hard, "It's a device with wheels to carry the shopping. What is it?", 1, ["The backpack", "The trolley", "The suitcase", "The basket"]),
    // -- Easy (massive batch) --
    q!(Category::Taboo, Difficulty::Easy, "It's a red, round fruit with seeds in the middle. What is it?", 1, ["The pear", "The apple", "The orange", "The strawberry"]),
    q!(Category::Taboo, Difficulty::Easy, "It has four legs, a tail and barks. What is it?", 2, ["The cat", "The rabbit", "The dog", "The horse"]),
    q!(Category::Taboo, Difficulty::Easy, "You carry it in your hand so you don't get wet when it rains. What is it?", 0, ["The umbrella", "The raincoat", "The waterproof coat", "The cagoule"]),
    q!(Category::Taboo, Difficulty::Easy, "It's an animal that gives milk and says 'moo'. What is it?", 1, ["The sheep", "The cow", "The goat", "The sow"]),
    q!(Category::Taboo, Difficulty::Easy, "It's used to see the time on your wrist. What is it?", 1, ["The alarm clock", "The wristwatch", "The stopwatch", "The wall clock"]),
    q!(Category::Taboo, Difficulty::Easy, "It's round, made of glass and used for drinking. What is it?", 1, ["The mug", "The glass", "The bottle", "The plate"]),
    q!(Category::Taboo, Difficulty::Easy, "You use it to cut food at the table. What is it?", 1, ["The spoon", "The knife", "The fork", "The napkin"]),
    q!(Category::Taboo, Difficulty::Easy, "It's a place with many trees where people go for a walk. What is it?", 0, ["The forest", "The beach", "The desert", "The river"]),
    q!(Category::Taboo, Difficulty::Easy, "It has wings and sings in the morning. What is it?", 1, ["The cat", "The bird", "The fish", "The dog"]),
    q!(Category::Taboo, Difficulty::Easy, "You use it to sleep and it has a pillow. What is it?", 1, ["The sofa", "The bed", "The chair", "The table"]),
    q!(Category::Taboo, Difficulty::Easy, "It's an animal that swims and has scales. What is it?", 1, ["The whale", "The fish", "The dolphin", "The seal"]),
    q!(Category::Taboo, Difficulty::Easy, "You carry it on your back for school. What is it?", 1, ["The suitcase", "The backpack", "The bag", "The satchel"]),
    q!(Category::Taboo, Difficulty::Easy, "It's sweet, colorful and kids eat it. What is it?", 1, ["The vegetable", "The candy", "The bread", "The soup"]),
    q!(Category::Taboo, Difficulty::Easy, "It has a bell and rings when someone arrives. What is it?", 1, ["The bell", "The doorbell", "The alarm", "The siren"]),
    q!(Category::Taboo, Difficulty::Easy, "It's white and used to write on the board. What is it?", 1, ["The pencil", "The chalk", "The marker", "The pen"]),
    q!(Category::Taboo, Difficulty::Easy, "You use it to dry your hands. What is it?", 1, ["The paper", "The towel", "The handkerchief", "The sponge"]),
    q!(Category::Taboo, Difficulty::Easy, "It's an animal that flies and goes 'cheep cheep'. What is it?", 1, ["The butterfly", "The chick", "The bee", "The fly"]),
    q!(Category::Taboo, Difficulty::Easy, "It's used to turn on the light in the room. What is it?", 1, ["The candle", "The light switch", "The lamp", "The spotlight"]),
    q!(Category::Taboo, Difficulty::Easy, "It's a hot brown drink you have in the morning. What is it?", 1, ["The tea", "The coffee", "The chocolate", "The milk"]),
    q!(Category::Taboo, Difficulty::Easy, "You use it to clean your teeth. What is it?", 1, ["The soap", "The toothbrush", "The comb", "The towel"]),
    q!(Category::Taboo, Difficulty::Easy, "It's a big animal with a trunk and tusks. What is it?", 1, ["The rhinoceros", "The elephant", "The hippopotamus", "The giraffe"]),
    q!(Category::Taboo, Difficulty::Easy, "It's used to heat up food. What is it?", 1, ["The fridge", "The microwave", "The dishwasher", "The washing machine"]),
    q!(Category::Taboo, Difficulty::Easy, "It's a means of transport that flies high. What is it?", 1, ["The boat", "The airplane", "The train", "The bus"]),
    q!(Category::Taboo, Difficulty::Easy, "You use it to tie your hair. What is it?", 1, ["The zipper", "The hair tie", "The belt", "The shoelace"]),
    q!(Category::Taboo, Difficulty::Easy, "It's an animal that jumps and eats carrots. What is it?", 1, ["The hamster", "The rabbit", "The hare", "The mouse"]),
    q!(Category::Taboo, Difficulty::Easy, "It's used to open the door with a key. What is it?", 1, ["The lock", "The doorknob", "The key", "The bolt"]),
    q!(Category::Taboo, Difficulty::Easy, "It's a place where children play on swings. What is it?", 1, ["The park", "The square", "The playground", "The garden"]),
    q!(Category::Taboo, Difficulty::Easy, "It's sweet and they put it on the birthday cake. What is it?", 1, ["The chocolate", "The candle", "The sugar", "The honey"]),
    q!(Category::Taboo, Difficulty::Easy, "It's an animal that lives in the water and has a shell. What is it?", 1, ["The frog", "The turtle", "The crab", "The snail"]),
    q!(Category::Taboo, Difficulty::Easy, "It's used to watch television. What is it?", 1, ["The radio", "The remote control", "The computer", "The phone"]),
    q!(Category::Taboo, Difficulty::Easy, "It's an animal with a mane that roars. What is it?", 1, ["The tiger", "The lion", "The wolf", "The bear"]),
    q!(Category::Taboo, Difficulty::Easy, "You use it to take photos. What is it?", 1, ["The phone", "The camera", "The tablet", "The mirror"]),
    q!(Category::Taboo, Difficulty::Easy, "It's a long, orange vegetable that rabbits eat. What is it?", 1, ["The cucumber", "The carrot", "The zucchini", "The potato"]),
    q!(Category::Taboo, Difficulty::Easy, "It's used to wash dirty clothes. What is it?", 1, ["The microwave", "The washing machine", "The iron", "The dishwasher"]),
    q!(Category::Taboo, Difficulty::Easy, "It's an animal that has black and white stripes. What is it?", 1, ["The zebra", "The cow", "The panda", "The tiger"]),
    q!(Category::Taboo, Difficulty::Easy, "You use it to write with ink. What is it?", 1, ["The pencil", "The pen", "The chalk", "The marker"]),
    q!(Category::Taboo, Difficulty::Easy, "It's a place where you buy bread. What is it?", 1, ["The market", "The bakery", "The greengrocer's", "The butcher's"]),
    q!(Category::Taboo, Difficulty::Easy, "It's an animal that meows and hunts mice. What is it?", 1, ["The dog", "The cat", "The mouse", "The owl"]),
    q!(Category::Taboo, Difficulty::Easy, "It's used to store food and keep it fresh. What is it?", 1, ["The wardrobe", "The pantry", "The fridge", "The basket"]),
    q!(Category::Taboo, Difficulty::Easy, "It's a round toy that bounces. What is it?", 1, ["The die", "The ball", "The balloon", "The marble"]),
    // -- Medium (massive batch) --
    q!(Category::Taboo, Difficulty::Medium, "It's used to see the bones of the body at the hospital. What is it?", 1, ["The ultrasound", "The X-ray", "The MRI", "The thermometer"]),
    q!(Category::Taboo, Difficulty::Medium, "It's a device that sucks up dust from the floor. What is it?", 1, ["The broom", "The vacuum cleaner", "The mop", "The rag"]),
    q!(Category::Taboo, Difficulty::Medium, "It hangs around the neck and keeps you warm. What is it?", 1, ["The jacket", "The scarf", "The sweater", "The coat"]),
    q!(Category::Taboo, Difficulty::Medium, "It's a place where cars are stored. What is it?", 1, ["The workshop", "The garage", "The petrol station", "The parking lot"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to go upstairs without effort. What is it?", 1, ["The ladder", "The elevator", "The ramp", "The escalator"]),
    q!(Category::Taboo, Difficulty::Medium, "It's an instrument that measures air pressure. What is it?", 1, ["The thermometer", "The barometer", "The hygrometer", "The rain gauge"]),
    q!(Category::Taboo, Difficulty::Medium, "It's put on your eyes to see better. What is it?", 1, ["The sunglasses", "The glasses", "The magnifying glass", "The monocle"]),
    q!(Category::Taboo, Difficulty::Medium, "It's an animal that hibernates and eats honey. What is it?", 1, ["The wolf", "The bear", "The deer", "The wild boar"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to fish in the sea from a boat. What is it?", 1, ["The fishing rod", "The net", "The harpoon", "The hook"]),
    q!(Category::Taboo, Difficulty::Medium, "It's a device that measures time in races. What is it?", 1, ["The clock", "The stopwatch", "The timer", "The alarm clock"]),
    q!(Category::Taboo, Difficulty::Medium, "It's put in the car to protect the head in a crash. What is it?", 1, ["The seat belt", "The airbag", "The helmet", "The pillow"]),
    q!(Category::Taboo, Difficulty::Medium, "It's a place where books are stored in order. What is it?", 1, ["The bookstore", "The library", "The shelf", "The newsstand"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to cut the grass in the garden. What is it?", 1, ["The scissors", "The lawnmower", "The sickle", "The shovel"]),
    q!(Category::Taboo, Difficulty::Medium, "It's a small brown coin. What is it?", 1, ["The banknote", "The cent", "The card", "The euro"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to light the fire in the fireplace. What is it?", 1, ["The lighter", "The matches", "The flame", "The spark"]),
    q!(Category::Taboo, Difficulty::Medium, "It's an animal that lives in the desert and has a hump. What is it?", 1, ["The llama", "The camel", "The dromedary", "The alpaca"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to type on the computer. What is it?", 1, ["The mouse", "The keyboard", "The screen", "The printer"]),
    q!(Category::Taboo, Difficulty::Medium, "It's a sweet that is eaten at Christmas. What is it?", 1, ["The roscón", "The nougat", "The marzipan", "The polvorones"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to measure the height of people. What is it?", 1, ["The meter", "The stadiometer", "The ruler", "The measuring tape"]),
    q!(Category::Taboo, Difficulty::Medium, "It's a place where movies are made. What is it?", 1, ["The theater", "The film set", "The cinema", "The studio"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to protect your eyes from the sun at the beach. What is it?", 1, ["The cap", "The sunglasses", "The hat", "The visor"]),
    q!(Category::Taboo, Difficulty::Medium, "It's an animal that camouflages itself and changes color. What is it?", 1, ["The chameleon", "The snake", "The lizard", "The frog"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to crush ice in summer. What is it?", 1, ["The glass", "The blender", "The juicer", "The crusher"]),
    q!(Category::Taboo, Difficulty::Medium, "It's a device that flies without a pilot. What is it?", 1, ["The helicopter", "The drone", "The airplane", "The balloon"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to clean the window panes. What is it?", 1, ["The rag", "The cloth", "The window cleaner", "The sponge"]),
    q!(Category::Taboo, Difficulty::Medium, "It's an animal that has a horn on its head. What is it?", 1, ["The rhinoceros", "The unicorn", "The bull", "The antelope"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to pay in stores without cash. What is it?", 1, ["The banknote", "The card", "The check", "The coin"]),
    q!(Category::Taboo, Difficulty::Medium, "It's a place where movies are seen on a big screen. What is it?", 1, ["The theater", "The cinema", "The park", "The museum"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to make orange juice. What is it?", 1, ["The blender", "The juicer", "The liquidizer", "The press"]),
    q!(Category::Taboo, Difficulty::Medium, "It's an animal that has a pouch for its young. What is it?", 1, ["The koala", "The kangaroo", "The sloth", "The wombat"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to see the stars at night. What is it?", 1, ["The spyglass", "The telescope", "The binoculars", "The microscope"]),
    q!(Category::Taboo, Difficulty::Medium, "It's a board game with squares and dice. What is it?", 1, ["Chess", "Parcheesi", "Cards", "Dominoes"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to transport the sick in the hospital. What is it?", 1, ["The ambulance", "The stretcher", "The wheelchair", "The stairs"]),
    q!(Category::Taboo, Difficulty::Medium, "It's a device that plays music without wires. What is it?", 1, ["The radio", "The speaker", "The headphones", "The record player"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to do homework and is made of wood. What is it?", 1, ["The chair", "The table", "The desk", "The wardrobe"]),
    q!(Category::Taboo, Difficulty::Medium, "It's an animal that has feathers and doesn't fly. What is it?", 1, ["The chicken", "The penguin", "The ostrich", "The turkey"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to keep money at the bank. What is it?", 1, ["The piggy bank", "The account", "The wallet", "The safe"]),
    q!(Category::Taboo, Difficulty::Medium, "It's a tool that makes soap bubbles. What is it?", 1, ["The straw", "The ring", "The wand", "The balloon"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to measure time in the kitchen. What is it?", 1, ["The clock", "The timer", "The stopwatch", "The bell"]),
    q!(Category::Taboo, Difficulty::Medium, "It's a place where ships dock. What is it?", 1, ["The port", "The shipyard", "The beach", "The pier"]),
    // -- Hard (massive batch) --
    q!(Category::Taboo, Difficulty::Hard, "Navigation instrument that points to the north. What is it?", 1, ["The map", "The compass", "The sextant", "The GPS"]),
    q!(Category::Taboo, Difficulty::Hard, "Device that measures wind speed. What is it?", 1, ["The barometer", "The anemometer", "The rain gauge", "The thermometer"]),
    q!(Category::Taboo, Difficulty::Hard, "Science that studies fossils. What is it?", 1, ["Archeology", "Paleontology", "Geology", "Biology"]),
    q!(Category::Taboo, Difficulty::Hard, "Device that picks up radio waves and turns them into sound. What is it?", 1, ["The antenna", "The radio", "The speaker", "The amplifier"]),
    q!(Category::Taboo, Difficulty::Hard, "Carpenter's tool for hammering. What is it?", 1, ["The saw", "The hammer", "The screwdriver", "The pliers"]),
    q!(Category::Taboo, Difficulty::Hard, "Instrument used to measure angles at school. What is it?", 1, ["The ruler", "The protractor", "The compass", "The set square"]),
    q!(Category::Taboo, Difficulty::Hard, "Device that projects images on the classroom wall. What is it?", 1, ["The television", "The projector", "The overhead projector", "The board"]),
    q!(Category::Taboo, Difficulty::Hard, "Object used to hang pictures on the wall. What is it?", 1, ["The tack", "The nail", "The screw", "The staple"]),
    q!(Category::Taboo, Difficulty::Hard, "Device that detects metals underground. What is it?", 1, ["The radar", "The metal detector", "The compass", "The sonar"]),
    q!(Category::Taboo, Difficulty::Hard, "Doctor's instrument to listen to the heart. What is it?", 1, ["The thermometer", "The stethoscope", "The blood pressure monitor", "The pulse monitor"]),
    q!(Category::Taboo, Difficulty::Hard, "Gardener's tool for digging the earth. What is it?", 1, ["The rake", "The shovel", "The hoe", "The pitchfork"]),
    q!(Category::Taboo, Difficulty::Hard, "Device that turns sunlight into electricity. What is it?", 1, ["The turbine", "The solar panel", "The generator", "The battery"]),
    q!(Category::Taboo, Difficulty::Hard, "Instrument used to draw circles. What is it?", 1, ["The ruler", "The compass", "The set square", "The protractor"]),
    q!(Category::Taboo, Difficulty::Hard, "Device that measures the altitude of an airplane. What is it?", 1, ["The barometer", "The altimeter", "The speedometer", "The radar"]),
    q!(Category::Taboo, Difficulty::Hard, "Locksmith's tool for opening locks. What is it?", 1, ["The key", "The lockpick", "The screwdriver", "The pliers"]),
    q!(Category::Taboo, Difficulty::Hard, "Device that stores electrical energy to use it later. What is it?", 1, ["The generator", "The battery", "The transformer", "The motor"]),
    q!(Category::Taboo, Difficulty::Hard, "Astronomer's instrument to observe the planets. What is it?", 1, ["The spyglass", "The telescope", "The microscope", "The binoculars"]),
    q!(Category::Taboo, Difficulty::Hard, "Science that studies earthquakes. What is it?", 1, ["Meteorology", "Seismology", "Volcanology", "Geology"]),
    q!(Category::Taboo, Difficulty::Hard, "Device used in the operating room to see inside the body. What is it?", 1, ["The X-ray", "The endoscope", "The ultrasound", "The scanner"]),
    q!(Category::Taboo, Difficulty::Hard, "Electrician's tool for cutting cables. What is it?", 1, ["The box cutter", "The wire cutters", "The scissors", "The saw"]),
    q!(Category::Taboo, Difficulty::Hard, "Instrument that measures air humidity. What is it?", 1, ["The barometer", "The hygrometer", "The rain gauge", "The thermometer"]),
    q!(Category::Taboo, Difficulty::Hard, "Device that makes water come out of a tap. What is it?", 1, ["The pump", "The pipe", "The tank", "The cistern"]),
    q!(Category::Taboo, Difficulty::Hard, "Builder's tool for leveling. What is it?", 1, ["The plumb line", "The level", "The set square", "The measuring tape"]),
    q!(Category::Taboo, Difficulty::Hard, "Device that records the voice and plays it back. What is it?", 1, ["The microphone", "The recorder", "The speaker", "The headset"]),
    q!(Category::Taboo, Difficulty::Hard, "Wind instrument with three valves. What is it?", 1, ["The trumpet", "The trombone", "The tuba", "The clarinet"]),
    q!(Category::Taboo, Difficulty::Hard, "Device used to cook with steam. What is it?", 1, ["The deep fryer", "The pressure cooker", "The steamer", "The frying pan"]),
    q!(Category::Taboo, Difficulty::Hard, "Mechanic's tool for tightening nuts. What is it?", 1, ["The screwdriver", "The wrench", "The pliers", "The clamps"]),
    q!(Category::Taboo, Difficulty::Hard, "Science that studies the stars and the planets. What is it?", 1, ["Astrology", "Astronomy", "Cosmology", "Astrophysics"]),
    q!(Category::Taboo, Difficulty::Hard, "Device used in the laboratory to weigh. What is it?", 1, ["The scale", "The test tube", "The flask", "The beaker"]),
    q!(Category::Taboo, Difficulty::Hard, "Instrument that measures the amount of rain. What is it?", 1, ["The hygrometer", "The rain gauge", "The barometer", "The anemometer"]),
    q!(Category::Taboo, Difficulty::Hard, "Device that projects the shadow of an object. What is it?", 1, ["The lamp", "The overhead projector", "The projector", "The spotlight"]),
    q!(Category::Taboo, Difficulty::Hard, "Tailor's tool for sewing. What is it?", 1, ["The needle", "The sewing machine", "The thimble", "The scissors"]),
    q!(Category::Taboo, Difficulty::Hard, "Device used on ships to measure depth. What is it?", 1, ["The radar", "The sonar", "The sextant", "The probe"]),
    q!(Category::Taboo, Difficulty::Hard, "Musical instrument with keys and bellows. What is it?", 1, ["The organ", "The accordion", "The piano", "The concertina"]),
    q!(Category::Taboo, Difficulty::Hard, "Device that desalinates sea water. What is it?", 1, ["The water treatment plant", "The desalination plant", "The purification plant", "The filter plant"]),
    q!(Category::Taboo, Difficulty::Hard, "Sculptor's tool for shaping stone. What is it?", 1, ["The chisel", "The hammer", "The gouge", "The rasp"]),
    q!(Category::Taboo, Difficulty::Hard, "Science that studies plants. What is it?", 1, ["Zoology", "Botany", "Ecology", "Agronomy"]),
    q!(Category::Taboo, Difficulty::Hard, "Device used to measure the pulse. What is it?", 1, ["The thermometer", "The pulse monitor", "The blood pressure monitor", "The glucose meter"]),
    q!(Category::Taboo, Difficulty::Hard, "Surveyor's instrument to measure distances. What is it?", 1, ["The ruler", "The theodolite", "The level", "The plumb line"]),
    q!(Category::Taboo, Difficulty::Hard, "Barber's tool for shaving. What is it?", 1, ["The razor blade", "The shaver", "The straight razor", "The scissors"]),
    // ================= Open questions =================
    // -- Math --
    q_open!(Category::Math, Difficulty::Easy, "What is 6 x 7?", "42"),
    q_open!(Category::Math, Difficulty::Medium, "What is the square root of 144?", "12"),
    q_open!(Category::Math, Difficulty::Hard, "How many degrees do the angles of a triangle add up to?", "180"),
    // -- History --
    q_open!(Category::History, Difficulty::Easy, "In what year did Columbus discover America?", "1492"),
    q_open!(Category::History, Difficulty::Medium, "In what year did World War II begin?", "1939"),
    q_open!(Category::History, Difficulty::Hard, "In what year did the Berlin Wall fall?", "1989"),
    // -- Computer science --
    q_open!(Category::Cs, Difficulty::Easy, "How many bits are there in a byte?", "8"),
    q_open!(Category::Cs, Difficulty::Medium, "What language is this game programmed in?", "Rust"),
    q_open!(Category::Cs, Difficulty::Hard, "What does AI stand for?", "Artificial intelligence"),
    // -- Geography --
    q_open!(Category::Geography, Difficulty::Easy, "What is the capital of France?", "Paris"),
    q_open!(Category::Geography, Difficulty::Medium, "What is the largest country in the world?", "Russia"),
    q_open!(Category::Geography, Difficulty::Hard, "What strait separates Spain from Morocco?", "Gibraltar"),
    // -- Science --
    q_open!(Category::Science, Difficulty::Easy, "How many planets does the solar system have?", "8"),
    q_open!(Category::Science, Difficulty::Medium, "What is the chemical formula for water?", "H2O"),
    q_open!(Category::Science, Difficulty::Hard, "Which scientist formulated the theory of relativity?", "Einstein"),
    // -- Art --
    q_open!(Category::Art, Difficulty::Easy, "How many colors does the rainbow have?", "7"),
    q_open!(Category::Art, Difficulty::Medium, "Who painted 'Las Meninas'?", "Velázquez"),
];