//! Parte 5 del banco en inglés: preguntas abiertas (tanda inicial).
use super::super::questions::{q_open, Category, Difficulty, Question};

pub static QUESTIONS_EN_5: &[Question] = &[
    q_open!(Category::Art, Difficulty::Hard, "Who composed the Ninth Symphony?", "Beethoven"),
    // -- Taboo --
    q_open!(Category::Taboo, Difficulty::Easy, "Farm animal that lays eggs. What is it?", "hen"),
    q_open!(Category::Taboo, Difficulty::Medium, "Instrument with keys used to do calculations. What is it?", "calculator"),
    // ============ Open questions (massive batch) ============
    // -- Mathematics --
    q_open!(Category::Math, Difficulty::Easy, "How much is 7 + 8?", "15"),
    q_open!(Category::Math, Difficulty::Easy, "How much is 9 x 9?", "81"),
    q_open!(Category::Math, Difficulty::Easy, "How many sides does a square have?", "4"),
    q_open!(Category::Math, Difficulty::Easy, "What is half of 50?", "25"),
    q_open!(Category::Math, Difficulty::Easy, "How much is 100 - 35?", "65"),
    q_open!(Category::Math, Difficulty::Easy, "How many minutes are in an hour?", "60"),
    q_open!(Category::Math, Difficulty::Easy, "How much is 12 x 4?", "48"),
    q_open!(Category::Math, Difficulty::Easy, "How many days are in a normal year?", "365"),
    q_open!(Category::Math, Difficulty::Easy, "How much is 3 x 9?", "27"),
    q_open!(Category::Math, Difficulty::Easy, "How many months are in a year?", "12"),
    q_open!(Category::Math, Difficulty::Medium, "What is 50% of 90?", "45"),
    q_open!(Category::Math, Difficulty::Medium, "How much is 2 to the power of 10?", "1024"),
    q_open!(Category::Math, Difficulty::Medium, "How many degrees is a right angle?", "90"),
    q_open!(Category::Math, Difficulty::Medium, "What is the square root of 81?", "9"),
    q_open!(Category::Math, Difficulty::Medium, "How much is 5/6 of 60?", "50"),
    q_open!(Category::Math, Difficulty::Medium, "What is 25% of 400?", "100"),
    q_open!(Category::Math, Difficulty::Medium, "What is the perimeter of a square with side 8?", "32"),
    q_open!(Category::Math, Difficulty::Medium, "How much is 0.5 x 10?", "5"),
    q_open!(Category::Math, Difficulty::Medium, "How many sides does an octagon have?", "8"),
    q_open!(Category::Math, Difficulty::Medium, "How much is 13 x 3?", "39"),
    q_open!(Category::Math, Difficulty::Hard, "What is the solution to x + 5 = 20?", "15"),
    q_open!(Category::Math, Difficulty::Hard, "How much is 3 to the power of 4?", "81"),
    q_open!(Category::Math, Difficulty::Hard, "How many degrees do the angles of a square add up to?", "360"),
    q_open!(Category::Math, Difficulty::Hard, "What is the square root of 169?", "13"),
    q_open!(Category::Math, Difficulty::Hard, "What is the smallest prime number?", "2"),
    q_open!(Category::Math, Difficulty::Hard, "What is 10% of 350?", "35"),
    q_open!(Category::Math, Difficulty::Hard, "How much is 2 x 2 x 2 x 2 x 2?", "32"),
    q_open!(Category::Math, Difficulty::Hard, "What is the value of pi to two decimal places?", "3.14"),
    q_open!(Category::Math, Difficulty::Hard, "How much is 100 divided by 8?", "12.5"),
    q_open!(Category::Math, Difficulty::Hard, "How many faces does a cube have?", "6"),
    // -- History --
    q_open!(Category::History, Difficulty::Easy, "In what year did man land on the Moon?", "1969"),
    q_open!(Category::History, Difficulty::Easy, "Who painted the Mona Lisa?", "Leonardo da Vinci"),
    q_open!(Category::History, Difficulty::Easy, "In which city is the Colosseum?", "Rome"),
    q_open!(Category::History, Difficulty::Easy, "What is the writing of ancient Egypt called?", "Hieroglyphs"),
    q_open!(Category::History, Difficulty::Easy, "Which people built the pyramids?", "Egyptians"),
    q_open!(Category::History, Difficulty::Easy, "Who was the first man to set foot on the Moon?", "Neil Armstrong"),
    q_open!(Category::History, Difficulty::Easy, "Which Roman emperor was assassinated on the Ides of March?", "Julius Caesar"),
    q_open!(Category::History, Difficulty::Easy, "In what year did World War I end?", "1918"),
    q_open!(Category::History, Difficulty::Easy, "What famous ship sank in 1912?", "Titanic"),
    q_open!(Category::History, Difficulty::Easy, "Who was the king of France known as the 'Sun King'?", "Louis XIV"),
    q_open!(Category::History, Difficulty::Medium, "In what year was America discovered?", "1492"),
    q_open!(Category::History, Difficulty::Medium, "Who wrote the Iliad?", "Homer"),
    q_open!(Category::History, Difficulty::Medium, "Which emperor divided the Roman Empire?", "Theodosius"),
    q_open!(Category::History, Difficulty::Medium, "In what year did Constantinople fall?", "1453"),
    q_open!(Category::History, Difficulty::Medium, "Who was the first president of the USA?", "George Washington"),
    q_open!(Category::History, Difficulty::Medium, "Which treaty divided the world between Spain and Portugal?", "Tordesillas"),
    q_open!(Category::History, Difficulty::Medium, "Who was the pharaoh of the Great Pyramid?", "Keops"),
    q_open!(Category::History, Difficulty::Medium, "In what year did World War II end?", "1945"),
    q_open!(Category::History, Difficulty::Medium, "Which civilization built Machu Picchu?", "Incas"),
    q_open!(Category::History, Difficulty::Medium, "Who was the best-known leader of the French Revolution?", "Robespierre"),
    q_open!(Category::History, Difficulty::Hard, "Which battle defeated Napoleon in 1815?", "Waterloo"),
    q_open!(Category::History, Difficulty::Hard, "In what year was the Treaty of Tordesillas signed?", "1494"),
    q_open!(Category::History, Difficulty::Hard, "Who was the first emperor of China?", "Qin Shi Huang"),
    q_open!(Category::History, Difficulty::Hard, "Which English king signed the Magna Carta?", "King John"),
    q_open!(Category::History, Difficulty::Hard, "In what year did the French Revolution begin?", "1789"),
    q_open!(Category::History, Difficulty::Hard, "Which scientist formulated the laws of gravitation?", "Newton"),
    q_open!(Category::History, Difficulty::Hard, "Which city was the capital of the Aztec Empire?", "Tenochtitlan"),
    q_open!(Category::History, Difficulty::Hard, "Who was the last Bourbon king of Spain in 1931?", "Alfonso XIII"),
    q_open!(Category::History, Difficulty::Hard, "In what year was the UN founded?", "1945"),
    q_open!(Category::History, Difficulty::Hard, "Which explorer discovered the strait south of America?", "Magellan"),
    // -- Computing --
    q_open!(Category::Cs, Difficulty::Easy, "How many bytes are in a kilobyte?", "1024"),
    q_open!(Category::Cs, Difficulty::Easy, "What is the email symbol called?", "At sign"),
    q_open!(Category::Cs, Difficulty::Easy, "Which operating system did Microsoft create?", "Windows"),
    q_open!(Category::Cs, Difficulty::Easy, "What is the computer screen called?", "Monitor"),
    q_open!(Category::Cs, Difficulty::Easy, "What device is used to print?", "Printer"),
    q_open!(Category::Cs, Difficulty::Easy, "What is the program to view web pages called?", "Browser"),
    q_open!(Category::Cs, Difficulty::Easy, "Which network connects computers all over the world?", "Internet"),
    q_open!(Category::Cs, Difficulty::Easy, "How many keys does a standard keyboard have approximately?", "104"),
    q_open!(Category::Cs, Difficulty::Easy, "What is used to move the cursor?", "Mouse"),
    q_open!(Category::Cs, Difficulty::Easy, "What is email called in English?", "Email"),
    q_open!(Category::Cs, Difficulty::Medium, "What language is used for web pages?", "HTML"),
    q_open!(Category::Cs, Difficulty::Medium, "What does Ctrl+C do?", "Copy"),
    q_open!(Category::Cs, Difficulty::Medium, "What does Ctrl+V do?", "Paste"),
    q_open!(Category::Cs, Difficulty::Medium, "Which unit is smaller, bit or byte?", "Bit"),
    q_open!(Category::Cs, Difficulty::Medium, "What does WWW mean?", "World Wide Web"),
    q_open!(Category::Cs, Difficulty::Medium, "What is the program that protects against viruses called?", "Antivirus"),
    q_open!(Category::Cs, Difficulty::Medium, "Which network is wireless?", "Wi-Fi"),
    q_open!(Category::Cs, Difficulty::Medium, "What does USB mean?", "Universal Serial Bus"),
    q_open!(Category::Cs, Difficulty::Medium, "What extension does a plain text document have?", "TXT"),
    q_open!(Category::Cs, Difficulty::Medium, "Which key deletes the character to the left?", "Backspace"),
    q_open!(Category::Cs, Difficulty::Hard, "What does CPU mean?", "Central Processing Unit"),
    q_open!(Category::Cs, Difficulty::Hard, "What number base does the computer use?", "Binary"),
    q_open!(Category::Cs, Difficulty::Hard, "What does AI mean?", "Artificial intelligence"),
    q_open!(Category::Cs, Difficulty::Hard, "What is a bug?", "Error"),
    q_open!(Category::Cs, Difficulty::Hard, "What does HTTP mean?", "HyperText Transfer Protocol"),
    q_open!(Category::Cs, Difficulty::Hard, "Which language has cargo as its package manager?", "Rust"),
    q_open!(Category::Cs, Difficulty::Hard, "What command lists files in Linux?", "LS"),
    q_open!(Category::Cs, Difficulty::Hard, "What does DNS mean?", "Domain Name System"),
    q_open!(Category::Cs, Difficulty::Hard, "What is software?", "Programs"),
    q_open!(Category::Cs, Difficulty::Hard, "Which operating system uses the Linux kernel?", "Linux"),
    // -- Geography --
    q_open!(Category::Geography, Difficulty::Easy, "What is the capital of Spain?", "Madrid"),
    q_open!(Category::Geography, Difficulty::Easy, "What is the capital of Italy?", "Rome"),
    q_open!(Category::Geography, Difficulty::Easy, "Which continent is Egypt on?", "Africa"),
    q_open!(Category::Geography, Difficulty::Easy, "What is the capital of Portugal?", "Lisbon"),
    q_open!(Category::Geography, Difficulty::Easy, "Which country is shaped like a boot?", "Italy"),
    q_open!(Category::Geography, Difficulty::Easy, "What is the largest ocean?", "Pacific"),
    q_open!(Category::Geography, Difficulty::Easy, "What is the capital of Germany?", "Berlin"),
    q_open!(Category::Geography, Difficulty::Easy, "Which river passes through Paris?", "Seine"),
    q_open!(Category::Geography, Difficulty::Easy, "What is the capital of Japan?", "Tokyo"),
    q_open!(Category::Geography, Difficulty::Easy, "Which sea bathes the east coast of Spain?", "Mediterranean"),
    q_open!(Category::Geography, Difficulty::Medium, "What is the highest mountain in the world?", "Everest"),
    q_open!(Category::Geography, Difficulty::Medium, "What is the capital of Australia?", "Canberra"),
    q_open!(Category::Geography, Difficulty::Medium, "Which desert is in North Africa?", "Sahara"),
    q_open!(Category::Geography, Difficulty::Medium, "What is the capital of Canada?", "Ottawa"),
    q_open!(Category::Geography, Difficulty::Medium, "Which mountain range separates Spain from France?", "Pyrenees"),
    q_open!(Category::Geography, Difficulty::Medium, "What is the longest river in the world?", "Nile"),
    q_open!(Category::Geography, Difficulty::Medium, "What is the capital of Argentina?", "Buenos Aires"),
    q_open!(Category::Geography, Difficulty::Medium, "Which country is the largest in Europe?", "Russia"),
    q_open!(Category::Geography, Difficulty::Medium, "What is the capital of Brazil?", "Brasilia"),
    q_open!(Category::Geography, Difficulty::Medium, "Which sea is north of Spain?", "Cantabrian"),
    q_open!(Category::Geography, Difficulty::Hard, "What is the deepest point of the ocean?", "Mariana Trench"),
    q_open!(Category::Geography, Difficulty::Hard, "What is the capital of New Zealand?", "Wellington"),
    q_open!(Category::Geography, Difficulty::Hard, "Which strait separates Asia from America?", "Bering"),
    q_open!(Category::Geography, Difficulty::Hard, "What is the driest desert in the world?", "Atacama"),
    q_open!(Category::Geography, Difficulty::Hard, "What is the capital of Turkey?", "Ankara"),
    q_open!(Category::Geography, Difficulty::Hard, "Which country has the most inhabitants in the world?", "India"),
    q_open!(Category::Geography, Difficulty::Hard, "What is the capital of Switzerland?", "Bern"),
    q_open!(Category::Geography, Difficulty::Hard, "Which canal connects the Mediterranean with the Red Sea?", "Suez"),
    q_open!(Category::Geography, Difficulty::Hard, "What is the largest lake in the world?", "Caspian"),
    q_open!(Category::Geography, Difficulty::Hard, "What is the capital of Iceland?", "Reykjavik"),
    // -- Science --
    q_open!(Category::Science, Difficulty::Easy, "Which planet is known as the red planet?", "Mars"),
    q_open!(Category::Science, Difficulty::Easy, "What gas do we need to breathe?", "Oxygen"),
    q_open!(Category::Science, Difficulty::Easy, "How many legs does a spider have?", "8"),
    q_open!(Category::Science, Difficulty::Easy, "What is the largest animal in the world?", "Whale"),
    q_open!(Category::Science, Difficulty::Easy, "How many seasons are in a year?", "4"),
    q_open!(Category::Science, Difficulty::Easy, "Which organ pumps blood?", "Heart"),
    q_open!(Category::Science, Difficulty::Easy, "Which planet is closest to the Sun?", "Mercury"),
    q_open!(Category::Science, Difficulty::Easy, "How many days are in a week?", "7"),
    q_open!(Category::Science, Difficulty::Easy, "Which animal produces honey?", "Bee"),
    q_open!(Category::Science, Difficulty::Easy, "How many fingers do you have in total?", "20"),
    q_open!(Category::Science, Difficulty::Medium, "What is the longest bone in the body?", "Femur"),
    q_open!(Category::Science, Difficulty::Medium, "What force keeps us on the ground?", "Gravity"),
    q_open!(Category::Science, Difficulty::Medium, "How many planets are in the solar system?", "8"),
    q_open!(Category::Science, Difficulty::Medium, "What gas does photosynthesis produce?", "Oxygen"),
    q_open!(Category::Science, Difficulty::Medium, "What is the largest organ of the body?", "Skin"),
    q_open!(Category::Science, Difficulty::Medium, "Which planet has famous rings?", "Saturn"),
    q_open!(Category::Science, Difficulty::Medium, "How many bones does an adult have?", "206"),
    q_open!(Category::Science, Difficulty::Medium, "Which animal can change color?", "Chameleon"),
    q_open!(Category::Science, Difficulty::Medium, "What vitamin does the sun produce?", "Vitamin D"),
    q_open!(Category::Science, Difficulty::Medium, "How many liters of blood does a person have?", "5"),
    q_open!(Category::Science, Difficulty::Hard, "What is the chemical formula for salt?", "NaCl"),
    q_open!(Category::Science, Difficulty::Hard, "Which particle has a negative charge?", "Electron"),
    q_open!(Category::Science, Difficulty::Hard, "What unit measures force?", "Newton"),
    q_open!(Category::Science, Difficulty::Hard, "Which scientist discovered penicillin?", "Fleming"),
    q_open!(Category::Science, Difficulty::Hard, "What is the speed of light in km/s?", "300000"),
    q_open!(Category::Science, Difficulty::Hard, "Which theory explains the origin of the universe?", "Big Bang"),
    q_open!(Category::Science, Difficulty::Hard, "Which planet is the largest?", "Jupiter"),
    q_open!(Category::Science, Difficulty::Hard, "What is the most abundant element in the universe?", "Hydrogen"),
    q_open!(Category::Science, Difficulty::Hard, "Which scale measures earthquakes?", "Richter"),
    q_open!(Category::Science, Difficulty::Hard, "What is the most abundant gas in the air?", "Nitrogen"),
    // -- Art --
    q_open!(Category::Art, Difficulty::Easy, "How many strings does a guitar have?", "6"),
    q_open!(Category::Art, Difficulty::Easy, "Who painted Guernica?", "Picasso"),
    q_open!(Category::Art, Difficulty::Easy, "What color do you get mixing blue and yellow?", "Green"),
    q_open!(Category::Art, Difficulty::Easy, "How many notes are in the musical scale?", "7"),
    q_open!(Category::Art, Difficulty::Easy, "Who sculpted the David?", "Michelangelo"),
    q_open!(Category::Art, Difficulty::Easy, "Which instrument has 88 keys?", "Piano"),
    q_open!(Category::Art, Difficulty::Easy, "Who painted 'The Starry Night'?", "Van Gogh"),
    q_open!(Category::Art, Difficulty::Easy, "What color results from mixing red and white?", "Pink"),
    q_open!(Category::Art, Difficulty::Easy, "How many strings does a violin have?", "4"),
    q_open!(Category::Art, Difficulty::Easy, "Which dance is typical of Andalusia?", "Flamenco"),
    q_open!(Category::Art, Difficulty::Medium, "Who wrote Don Quixote?", "Cervantes"),
    q_open!(Category::Art, Difficulty::Medium, "Which painter painted the sunflowers?", "Van Gogh"),
    q_open!(Category::Art, Difficulty::Medium, "How many complete symphonies did Beethoven write?", "9"),
    q_open!(Category::Art, Difficulty::Medium, "Who painted 'Las Meninas'?", "Velázquez"),
    q_open!(Category::Art, Difficulty::Medium, "Which instrument is a percussion instrument?", "Drum"),
    q_open!(Category::Art, Difficulty::Medium, "Who composed 'The Four Seasons'?", "Vivaldi"),
    q_open!(Category::Art, Difficulty::Medium, "Which poet wrote 'Gypsy Ballads'?", "Lorca"),
    q_open!(Category::Art, Difficulty::Medium, "What color do you get with red and yellow?", "Orange"),
    q_open!(Category::Art, Difficulty::Medium, "Who designed the Sagrada Familia?", "Gaudí"),
    q_open!(Category::Art, Difficulty::Medium, "Which writer wrote 'One Hundred Years of Solitude'?", "García Márquez"),
    q_open!(Category::Art, Difficulty::Hard, "Which painter is famous for the melting clocks?", "Dalí"),
    q_open!(Category::Art, Difficulty::Hard, "Who composed the Ninth Symphony?", "Beethoven"),
    q_open!(Category::Art, Difficulty::Hard, "Which writer wrote 'La Regenta'?", "Clarín"),
    q_open!(Category::Art, Difficulty::Hard, "Which architect designed the Guggenheim in Bilbao?", "Gehry"),
    q_open!(Category::Art, Difficulty::Hard, "Which painter painted the Sistine Chapel?", "Michelangelo"),
    q_open!(Category::Art, Difficulty::Hard, "Which opera did Bizet compose?", "Carmen"),
    q_open!(Category::Art, Difficulty::Hard, "Who wrote 'The House of Bernarda Alba'?", "Lorca"),
    q_open!(Category::Art, Difficulty::Hard, "Which artistic movement did Picasso lead with Guernica?", "Cubism"),
    q_open!(Category::Art, Difficulty::Hard, "Which composer wrote 'Swan Lake'?", "Tchaikovsky"),
    q_open!(Category::Art, Difficulty::Hard, "Which poet wrote 'Leaves of Grass'?", "Whitman"),
    // -- Taboo --
    q_open!(Category::Taboo, Difficulty::Easy, "Animal that lays eggs and says 'cock-a-doodle-doo'. What is it?", "hen"),
    q_open!(Category::Taboo, Difficulty::Easy, "It has 8 legs and weaves webs. What is it?", "spider"),
    q_open!(Category::Taboo, Difficulty::Easy, "It is used to write and erase on the blackboard. What is it?", "chalk"),
    q_open!(Category::Taboo, Difficulty::Easy, "It is yellow and monkeys eat it. What is it?", "banana"),
    q_open!(Category::Taboo, Difficulty::Easy, "It has hands and tells the time. What is it?", "clock"),
    q_open!(Category::Taboo, Difficulty::Easy, "You use it to tie your shoes. What is it?", "shoelace"),
    q_open!(Category::Taboo, Difficulty::Easy, "It is a place where books are borrowed. What is it?", "library"),
    q_open!(Category::Taboo, Difficulty::Easy, "You look at it to see your reflection. What is it?", "mirror"),
    q_open!(Category::Taboo, Difficulty::Easy, "It is round and bounces. What is it?", "ball"),
    q_open!(Category::Taboo, Difficulty::Easy, "It gives light at night and runs on batteries. What is it?", "flashlight"),
    q_open!(Category::Taboo, Difficulty::Medium, "It is used to measure fever. What is it?", "thermometer"),
    q_open!(Category::Taboo, Difficulty::Medium, "It keeps food cold. What is it?", "refrigerator"),
    q_open!(Category::Taboo, Difficulty::Medium, "Firefighters use it to put out fires. What is it?", "hose"),
    q_open!(Category::Taboo, Difficulty::Medium, "It hangs on the wall and shows the day and the month. What is it?", "calendar"),
    q_open!(Category::Taboo, Difficulty::Medium, "It rings in the morning to wake you up. What is it?", "alarm clock"),
    q_open!(Category::Taboo, Difficulty::Medium, "It is planted in the soil and a plant grows from it. What is it?", "seed"),
    q_open!(Category::Taboo, Difficulty::Medium, "You open it to enter or leave a room. What is it?", "door"),
    q_open!(Category::Taboo, Difficulty::Medium, "It is used to fish in the river. What is it?", "fishing rod"),
    q_open!(Category::Taboo, Difficulty::Medium, "It is a means of transport with two wheels. What is it?", "bicycle"),
    q_open!(Category::Taboo, Difficulty::Medium, "It is used to dry yourself after bathing. What is it?", "towel"),
    q_open!(Category::Taboo, Difficulty::Hard, "Instrument that sailors used to see far away. What is it?", "spyglass"),
    q_open!(Category::Taboo, Difficulty::Hard, "It is used to cut paper in a straight line. What is it?", "scissors"),
    q_open!(Category::Taboo, Difficulty::Hard, "It has a trunk and is very heavy. What is it?", "elephant"),
    q_open!(Category::Taboo, Difficulty::Hard, "It is placed on your head to protect you. What is it?", "helmet"),
    q_open!(Category::Taboo, Difficulty::Hard, "It is used to open cans. What is it?", "can opener"),
    q_open!(Category::Taboo, Difficulty::Hard, "It is the place where the sick are healed. What is it?", "hospital"),
    q_open!(Category::Taboo, Difficulty::Hard, "It is used to see the stars at night. What is it?", "telescope"),
    q_open!(Category::Taboo, Difficulty::Hard, "It gives light at night with batteries. What is it?", "flashlight"),
];