//! Part 6 of the English bank: extra batches of new questions.
use super::super::questions::{q, q_open, Category, Difficulty, Question};

pub static QUESTIONS_EN_6: &[Question] = &[
    q_open!(Category::Taboo, Difficulty::Hard, "It's a device that sucks up dust. What is it?", "vacuum cleaner"),
    q_open!(Category::Taboo, Difficulty::Hard, "Instrument for measuring angles. What is it?", "protractor"),

    // ================= Extra batch: 231 new questions =================
    // -- Math (closed) --
    q!(Category::Math, Difficulty::Easy, "What is 9 + 6?", 2, ["13", "14", "15", "16"]),
    q!(Category::Math, Difficulty::Easy, "What is 48 ÷ 6?", 3, ["6", "7", "9", "8"]),
    q!(Category::Math, Difficulty::Easy, "What is 5 x 6?", 0, ["30", "36", "25", "35"]),
    q!(Category::Math, Difficulty::Easy, "How many edges does a cube have?", 1, ["8", "12", "10", "16"]),
    q!(Category::Math, Difficulty::Easy, "What is 27 + 33?", 2, ["50", "55", "60", "65"]),
    q!(Category::Math, Difficulty::Easy, "What is 100 ÷ 25?", 0, ["4", "5", "25", "40"]),
    q!(Category::Math, Difficulty::Easy, "Which of these numbers is odd?", 1, ["42", "43", "44", "46"]),
    q!(Category::Math, Difficulty::Easy, "What is 13 - 5?", 1, ["6", "8", "7", "9"]),
    q!(Category::Math, Difficulty::Medium, "What is 40 % of 250?", 2, ["50", "75", "100", "125"]),
    q!(Category::Math, Difficulty::Medium, "If 5x + 10 = 35, what is x?", 0, ["5", "4", "6", "3"]),
    q!(Category::Math, Difficulty::Medium, "What is the volume of a cube with edge 4?", 3, ["16", "24", "48", "64"]),
    q!(Category::Math, Difficulty::Medium, "What is 2/5 + 1/10?", 1, ["3/5", "1/2", "2/10", "3/10"]),
    q!(Category::Math, Difficulty::Medium, "What is the mean of 4, 8, 12 and 16?", 2, ["8", "9", "10", "12"]),
    q!(Category::Math, Difficulty::Medium, "What is 3 to the power of 4?", 0, ["81", "64", "27", "243"]),
    q!(Category::Math, Difficulty::Medium, "What number comes next in the series 1, 4, 9, 16, ...?", 1, ["20", "25", "24", "36"]),
    q!(Category::Math, Difficulty::Medium, "What is 7 x 12?", 3, ["72", "77", "81", "84"]),
    q!(Category::Math, Difficulty::Hard, "What is the derivative of x²?", 2, ["x", "2", "2x", "x²"]),
    q!(Category::Math, Difficulty::Hard, "What is the square root of 289?", 1, ["16", "17", "19", "23"]),
    q!(Category::Math, Difficulty::Hard, "If log₂(8) = 3, what is log₂(32)?", 3, ["2", "3", "4", "5"]),
    q!(Category::Math, Difficulty::Hard, "What is the probability of rolling a 6 on a die?", 0, ["1/6", "1/5", "1/2", "1/3"]),
    q!(Category::Math, Difficulty::Hard, "What do the interior angles of a pentagon add up to?", 1, ["360°", "540°", "720°", "180°"]),
    q!(Category::Math, Difficulty::Hard, "If f(x) = 2x + 3 and f(a) = 11, what is a?", 2, ["3", "5", "4", "7"]),
    q!(Category::Math, Difficulty::Hard, "What is (a + b)²?", 0, ["a² + 2ab + b²", "a² + b²", "2a + 2b", "a² + ab + b²"]),
    q!(Category::Math, Difficulty::Hard, "What is 7 % of 300?", 1, ["22", "21", "25", "30"]),
    // -- Math (open) --
    q_open!(Category::Math, Difficulty::Easy, "What is 4 + 4 x 4?", "20"),
    q_open!(Category::Math, Difficulty::Easy, "How many seconds are in a minute?", "60"),
    q_open!(Category::Math, Difficulty::Easy, "What is 6 x 6?", "36"),
    q_open!(Category::Math, Difficulty::Medium, "What is 25 % of 80?", "20"),
    q_open!(Category::Math, Difficulty::Medium, "What is the square root of 64?", "8"),
    q_open!(Category::Math, Difficulty::Medium, "What is 1/3 + 1/3?", "2/3"),
    q_open!(Category::Math, Difficulty::Hard, "What is 5 factorial (5!)?", "120"),
    q_open!(Category::Math, Difficulty::Hard, "What is the sum of the first 10 numbers?", "55"),
    q_open!(Category::Math, Difficulty::Hard, "How many degrees does a straight angle have?", "180"),

    // -- History (closed) --
    q!(Category::History, Difficulty::Easy, "Who was the first president of the United States?", 2, ["Lincoln", "Jefferson", "Washington", "Adams"]),
    q!(Category::History, Difficulty::Easy, "In what year did Columbus reach America?", 0, ["1492", "1498", "1500", "1453"]),
    q!(Category::History, Difficulty::Easy, "Which civilization built the pyramids of Giza?", 1, ["Romans", "Egyptians", "Greeks", "Mayas"]),
    q!(Category::History, Difficulty::Easy, "Who was emperor of France in 1810?", 2, ["Louis XVI", "Charles V", "Napoleon", "Henry VIII"]),
    q!(Category::History, Difficulty::Easy, "Which Roman city was buried by Vesuvius in 79 AD?", 0, ["Pompeii", "Rome", "Athens", "Carthage"]),
    q!(Category::History, Difficulty::Easy, "Which wall separated East and West Berlin?", 1, ["Hadrian's Wall", "Berlin Wall", "Great Wall", "Wailing Wall"]),
    q!(Category::History, Difficulty::Easy, "In which century did World War II end?", 3, ["XIX", "XVIII", "XXI", "XX"]),
    q!(Category::History, Difficulty::Easy, "Who wrote the Iliad and the Odyssey?", 0, ["Homer", "Virgil", "Sophocles", "Plato"]),
    q!(Category::History, Difficulty::Medium, "In what year did the Berlin Wall fall?", 1, ["1985", "1989", "1991", "1979"]),
    q!(Category::History, Difficulty::Medium, "Which British queen reigned from 1837 to 1901?", 2, ["Elizabeth I", "Anne", "Victoria", "Elizabeth II"]),
    q!(Category::History, Difficulty::Medium, "Which treaty ended World War I?", 0, ["Versailles", "Vienna", "Geneva", "Paris"]),
    q!(Category::History, Difficulty::Medium, "Who was the leader of the 1959 Cuban Revolution?", 3, ["Che Guevara", "Batista", "José Martí", "Fidel Castro"]),
    q!(Category::History, Difficulty::Medium, "Which empire conquered Constantinople in 1453?", 1, ["Roman", "Ottoman", "Mongol", "Persian"]),
    q!(Category::History, Difficulty::Medium, "In what year did the French Revolution begin?", 0, ["1789", "1799", "1776", "1812"]),
    q!(Category::History, Difficulty::Medium, "Which explorer led the first voyage around the world?", 2, ["Columbus", "Vasco da Gama", "Magellan", "Cortés"]),
    q!(Category::History, Difficulty::Medium, "In what year was the Suez Canal opened?", 3, ["1848", "1857", "1865", "1869"]),
    q!(Category::History, Difficulty::Hard, "Which Roman emperor established the Tetrarchy?", 0, ["Diocletian", "Constantine", "Theodosius", "Augustus"]),
    q!(Category::History, Difficulty::Hard, "Which civilization conquered Greece in 146 BC?", 2, ["Persia", "Egypt", "Rome", "Macedonia"]),
    q!(Category::History, Difficulty::Hard, "Which king of Spain launched the Spanish Armada?", 1, ["Charles I", "Philip II", "Philip III", "Charles II"]),
    q!(Category::History, Difficulty::Hard, "In what year was the Second Spanish Republic proclaimed?", 3, ["1923", "1929", "1936", "1931"]),
    q!(Category::History, Difficulty::Hard, "Which treaty ended the Thirty Years' War?", 0, ["Westphalia", "Utrecht", "Vienna", "Paris"]),
    q!(Category::History, Difficulty::Hard, "Who was the first man to set foot on the Moon?", 1, ["Aldrin", "Armstrong", "Gagarin", "Shepard"]),
    q!(Category::History, Difficulty::Hard, "Which people sacked Rome in the year 410?", 2, ["Vandals", "Huns", "Visigoths", "Franks"]),
    q!(Category::History, Difficulty::Hard, "In what year did the Battle of Covadonga take place?", 3, ["711", "732", "778", "722"]),
    // -- History (open) --
    q_open!(Category::History, Difficulty::Easy, "Who was president of the USA during World War II?", "Roosevelt"),
    q_open!(Category::History, Difficulty::Easy, "In what year did World War I end?", "1918"),
    q_open!(Category::History, Difficulty::Easy, "Who was defeated at the Battle of Waterloo?", "Napoleon"),
    q_open!(Category::History, Difficulty::Medium, "In what year was the US Declaration of Independence signed?", "1776"),
    q_open!(Category::History, Difficulty::Medium, "Who was the last queen of ancient Egypt?", "Cleopatra"),
    q_open!(Category::History, Difficulty::Medium, "Who was the first emperor of Rome?", "Augustus"),
    q_open!(Category::History, Difficulty::Hard, "In what year was the Berlin Wall built?", "1961"),
    q_open!(Category::History, Difficulty::Hard, "Which civilization invented cuneiform writing?", "Sumer"),
    q_open!(Category::History, Difficulty::Hard, "Which war pitted NATO against the Warsaw Pact without direct combat?", "Cold War"),

    // -- Computer Science (closed) --
    q!(Category::Cs, Difficulty::Easy, "What does CPU mean?", 0, ["Central Processing Unit", "Center for Unique Programs", "Unique Personal Computer", "Main Computing Unit"]),
    q!(Category::Cs, Difficulty::Easy, "Which device moves the cursor on screen?", 1, ["Keyboard", "Mouse", "Monitor", "Printer"]),
    q!(Category::Cs, Difficulty::Easy, "How many bits are in a byte?", 2, ["4", "16", "8", "32"]),
    q!(Category::Cs, Difficulty::Easy, "Which operating system is by Microsoft?", 0, ["Windows", "Linux", "Android", "macOS"]),
    q!(Category::Cs, Difficulty::Easy, "What extension do Word documents have?", 1, [".pdf", ".docx", ".txt", ".jpg"]),
    q!(Category::Cs, Difficulty::Easy, "Which key deletes the character to the left of the cursor?", 3, ["Delete", "Enter", "Shift", "Backspace"]),
    q!(Category::Cs, Difficulty::Easy, "Which program is used to browse the internet?", 0, ["Browser", "Processor", "Antivirus", "Compressor"]),
    q!(Category::Cs, Difficulty::Easy, "Which device displays the computer image?", 2, ["Mouse", "Keyboard", "Monitor", "Printer"]),
    q!(Category::Cs, Difficulty::Medium, "What does HTML mean?", 0, ["HyperText Markup Language", "High Tech Modern Language", "Home Tool Markup Language", "Hyperlink Transfer Markup"]),
    q!(Category::Cs, Difficulty::Medium, "How many bytes are in a kibibyte (KiB)?", 1, ["1000", "1024", "512", "2048"]),
    q!(Category::Cs, Difficulty::Medium, "Which programming language does the Bevy engine use?", 2, ["Python", "Java", "Rust", "C#"]),
    q!(Category::Cs, Difficulty::Medium, "Which protocol does a web page use in the browser?", 3, ["FTP", "SMTP", "TCP", "HTTP"]),
    q!(Category::Cs, Difficulty::Medium, "What does RAM mean?", 0, ["Random Access Memory", "Quick Start Memory", "Read-Only Memory", "Mobile Application Register"]),
    q!(Category::Cs, Difficulty::Medium, "What extension do Rust source files have?", 1, [".rust", ".rs", ".r", ".rsrc"]),
    q!(Category::Cs, Difficulty::Medium, "What is an algorithm?", 2, ["A code error", "A type of virus", "A sequence of steps to solve a problem", "A data type"]),
    q!(Category::Cs, Difficulty::Medium, "What does the cd command do in the terminal?", 0, ["Change directory", "Copy data", "Compress data", "Compile data"]),
    q!(Category::Cs, Difficulty::Hard, "What is the time complexity of binary search?", 1, ["O(n)", "O(log n)", "O(n²)", "O(1)"]),
    q!(Category::Cs, Difficulty::Hard, "Which data structure works with LIFO?", 0, ["Stack", "Queue", "List", "Tree"]),
    q!(Category::Cs, Difficulty::Hard, "Which compiler does Rust use by default?", 2, ["gcc", "clang", "rustc", "llvm"]),
    q!(Category::Cs, Difficulty::Hard, "Which port does HTTPS use by default?", 3, ["80", "8080", "21", "443"]),
    q!(Category::Cs, Difficulty::Hard, "Which data structure works with FIFO?", 1, ["Stack", "Queue", "Tree", "Graph"]),
    q!(Category::Cs, Difficulty::Hard, "What does OOP mean in programming?", 0, ["Object-Oriented Programming", "Operating Output Protocol", "Open Order Path", "Object Ordering Process"]),
    q!(Category::Cs, Difficulty::Hard, "Which memory loses its content when the computer is turned off?", 1, ["ROM", "RAM", "Hard drive", "SSD"]),
    q!(Category::Cs, Difficulty::Hard, "Which sorting algorithm compares adjacent pairs?", 2, ["Insertion", "Selection", "Bubble", "Merge"]),
    // -- Computer Science (open) --
    q_open!(Category::Cs, Difficulty::Easy, "What does www mean in a web address?", "World Wide Web"),
    q_open!(Category::Cs, Difficulty::Easy, "Which command lists files in the Linux terminal?", "ls"),
    q_open!(Category::Cs, Difficulty::Easy, "Which operating system is free and open source?", "Linux"),
    q_open!(Category::Cs, Difficulty::Medium, "What extension do Windows executable programs have?", "exe"),
    q_open!(Category::Cs, Difficulty::Medium, "Which protocol sends email?", "SMTP"),
    q_open!(Category::Cs, Difficulty::Medium, "Which unit of information equals 1024 gigabytes?", "Terabyte"),
    q_open!(Category::Cs, Difficulty::Hard, "Which programming language did Graydon Hoare release in 2015?", "Rust"),
    q_open!(Category::Cs, Difficulty::Hard, "Which command compiles and runs a Rust project?", "cargo run"),
    q_open!(Category::Cs, Difficulty::Hard, "Which acronym designates non-volatile read-only memory?", "ROM"),

    // -- Geography (closed) --
    q!(Category::Geography, Difficulty::Easy, "Which is the largest ocean in the world?", 2, ["Atlantic", "Indian", "Pacific", "Arctic"]),
    q!(Category::Geography, Difficulty::Easy, "On which continent is Egypt?", 0, ["Africa", "Asia", "Europe", "America"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of France?", 1, ["London", "Paris", "Rome", "Madrid"]),
    q!(Category::Geography, Difficulty::Easy, "Which country is shaped like a boot?", 3, ["Spain", "Greece", "Portugal", "Italy"]),
    q!(Category::Geography, Difficulty::Easy, "Which is the largest hot desert in the world?", 1, ["Atacama", "Sahara", "Gobi", "Kalahari"]),
    q!(Category::Geography, Difficulty::Easy, "Which sea separates Spain from Africa?", 0, ["Mediterranean", "Cantabrian", "Baltic", "Red"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Japan?", 2, ["Beijing", "Seoul", "Tokyo", "Bangkok"]),
    q!(Category::Geography, Difficulty::Easy, "In which ocean is Hawaii located?", 1, ["Atlantic", "Pacific", "Indian", "Arctic"]),
    q!(Category::Geography, Difficulty::Medium, "Which is the largest country in the world?", 0, ["Russia", "Canada", "China", "USA"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Australia?", 2, ["Sydney", "Melbourne", "Canberra", "Perth"]),
    q!(Category::Geography, Difficulty::Medium, "Which mountain range separates Europe from Asia?", 1, ["Alps", "Urals", "Himalayas", "Carpathians"]),
    q!(Category::Geography, Difficulty::Medium, "Which country has the most inhabitants in the world?", 3, ["China", "USA", "Indonesia", "India"]),
    q!(Category::Geography, Difficulty::Medium, "Which strait separates Spain from Morocco?", 0, ["Gibraltar", "Suez", "Bosphorus", "Magellan"]),
    q!(Category::Geography, Difficulty::Medium, "Which is the deepest lake in the world?", 1, ["Tanganyika", "Baikal", "Caspian", "Superior"]),
    q!(Category::Geography, Difficulty::Medium, "Which South American country is landlocked?", 2, ["Chile", "Peru", "Bolivia", "Ecuador"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Canada?", 3, ["Toronto", "Montreal", "Vancouver", "Ottawa"]),
    q!(Category::Geography, Difficulty::Hard, "Which is the deepest point of the ocean?", 0, ["Mariana Trench", "Puerto Rico Trench", "Java Trench", "Tonga Trench"]),
    q!(Category::Geography, Difficulty::Hard, "Which country has the most time zones?", 1, ["USA", "France", "Russia", "China"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of Kazakhstan?", 2, ["Almaty", "Tashkent", "Astana", "Baku"]),
    q!(Category::Geography, Difficulty::Hard, "Which river flows through the city of Cairo?", 0, ["Nile", "Euphrates", "Tigris", "Jordan"]),
    q!(Category::Geography, Difficulty::Hard, "In which country is Machu Picchu located?", 1, ["Mexico", "Peru", "Bolivia", "Chile"]),
    q!(Category::Geography, Difficulty::Hard, "Which is the smallest country in the world?", 2, ["Monaco", "San Marino", "Vatican City", "Liechtenstein"]),
    q!(Category::Geography, Difficulty::Hard, "Which desert is in Chile?", 3, ["Sahara", "Gobi", "Kalahari", "Atacama"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of New Zealand?", 0, ["Wellington", "Auckland", "Christchurch", "Melbourne"]),
    // -- Geography (open) --
    q_open!(Category::Geography, Difficulty::Easy, "What is the longest river in Spain?", "Tagus"),
    q_open!(Category::Geography, Difficulty::Easy, "What is the capital of Portugal?", "Lisbon"),
    q_open!(Category::Geography, Difficulty::Easy, "Which continent is south of the Mediterranean?", "Africa"),
    q_open!(Category::Geography, Difficulty::Medium, "What is the capital of Germany?", "Berlin"),
    q_open!(Category::Geography, Difficulty::Medium, "What is the highest mountain in the world?", "Everest"),
    q_open!(Category::Geography, Difficulty::Medium, "Which country has the capital Moscow?", "Russia"),
    q_open!(Category::Geography, Difficulty::Hard, "What is the capital of Brazil?", "Brasilia"),
    q_open!(Category::Geography, Difficulty::Hard, "What is the highest point in Africa?", "Kilimanjaro"),
    q_open!(Category::Geography, Difficulty::Hard, "Which Nordic country has the capital Oslo?", "Norway"),

    // -- Science (closed) --
    q!(Category::Science, Difficulty::Easy, "Which organ pumps blood around the body?", 2, ["Lungs", "Kidneys", "Heart", "Liver"]),
    q!(Category::Science, Difficulty::Easy, "How many legs does an insect have?", 0, ["6", "8", "4", "10"]),
    q!(Category::Science, Difficulty::Easy, "Which gas do plants absorb to do photosynthesis?", 1, ["Oxygen", "CO2", "Nitrogen", "Hydrogen"]),
    q!(Category::Science, Difficulty::Easy, "Which planet is the fourth from the Sun?", 3, ["Venus", "Jupiter", "Saturn", "Mars"]),
    q!(Category::Science, Difficulty::Easy, "Which animal is a marine mammal?", 1, ["Shark", "Dolphin", "Octopus", "Jellyfish"]),
    q!(Category::Science, Difficulty::Easy, "What do plants need to make their food?", 0, ["Sunlight", "Darkness", "Ice", "Sand"]),
    q!(Category::Science, Difficulty::Easy, "How many teeth does an adult have?", 2, ["20", "24", "32", "28"]),
    q!(Category::Science, Difficulty::Easy, "Which part of the cell contains the DNA?", 1, ["Membrane", "Nucleus", "Mitochondria", "Cytoplasm"]),
    q!(Category::Science, Difficulty::Medium, "Which organ produces insulin?", 2, ["Liver", "Kidney", "Pancreas", "Stomach"]),
    q!(Category::Science, Difficulty::Medium, "Which is the most abundant metal in the Earth's crust?", 0, ["Aluminium", "Iron", "Copper", "Gold"]),
    q!(Category::Science, Difficulty::Medium, "Which planet is the largest gas giant?", 1, ["Mars", "Jupiter", "Venus", "Mercury"]),
    q!(Category::Science, Difficulty::Medium, "How long does the Earth take to spin on its axis?", 0, ["24 hours", "12 hours", "365 days", "30 days"]),
    q!(Category::Science, Difficulty::Medium, "Which scientist formulated the theory of evolution?", 3, ["Newton", "Einstein", "Galileo", "Darwin"]),
    q!(Category::Science, Difficulty::Medium, "Which is the smallest bone in the human body?", 1, ["Malleus", "Stapes", "Ulna", "Patella"]),
    q!(Category::Science, Difficulty::Medium, "Which blood group is the universal donor?", 2, ["A+", "AB+", "O-", "B-"]),
    q!(Category::Science, Difficulty::Medium, "Which is the unit of electric current?", 0, ["Ampere", "Volt", "Watt", "Ohm"]),
    q!(Category::Science, Difficulty::Hard, "Which particles make up protons and neutrons?", 1, ["Electrons", "Quarks", "Photons", "Neutrinos"]),
    q!(Category::Science, Difficulty::Hard, "What is the chemical formula of water?", 0, ["H2O", "CO2", "O2", "NaCl"]),
    q!(Category::Science, Difficulty::Hard, "Which law of Newton is expressed as F = m · a?", 2, ["First", "Gravitation", "Second", "Third"]),
    q!(Category::Science, Difficulty::Hard, "Which organ produces bile?", 1, ["Pancreas", "Liver", "Gallbladder", "Spleen"]),
    q!(Category::Science, Difficulty::Hard, "Which unit measures frequency?", 3, ["Newton", "Joule", "Pascal", "Hertz"]),
    q!(Category::Science, Difficulty::Hard, "Which chemical element has the symbol Au?", 0, ["Gold", "Silver", "Aluminium", "Argon"]),
    q!(Category::Science, Difficulty::Hard, "Which radiation has the highest frequency?", 2, ["Radio", "Infrared", "Gamma", "Microwave"]),
    q!(Category::Science, Difficulty::Hard, "Which process converts sugar into energy in cells?", 1, ["Photosynthesis", "Cellular respiration", "Lactic fermentation", "Digestion"]),
    // -- Science (open) --
    q_open!(Category::Science, Difficulty::Easy, "Which is the fifth planet of the solar system?", "Jupiter"),
    q_open!(Category::Science, Difficulty::Easy, "Which animal is the fastest in the world?", "Cheetah"),
    q_open!(Category::Science, Difficulty::Easy, "How many bones does the human skull have?", "22"),
    q_open!(Category::Science, Difficulty::Medium, "Which metal is liquid at room temperature?", "Mercury"),
    q_open!(Category::Science, Difficulty::Medium, "Which noble gas is the lightest?", "Helium"),
    q_open!(Category::Science, Difficulty::Medium, "Which organ filters the blood?", "Kidney"),
    q_open!(Category::Science, Difficulty::Hard, "Which particle has a neutral charge?", "Neutron"),
    q_open!(Category::Science, Difficulty::Hard, "Which unit measures pressure?", "Pascal"),
    q_open!(Category::Science, Difficulty::Hard, "Which scientist formulated the laws of motion?", "Newton"),

    // -- Art (closed) --
    q!(Category::Art, Difficulty::Easy, "What color is complementary to red?", 2, ["Blue", "Yellow", "Green", "Orange"]),
    q!(Category::Art, Difficulty::Easy, "Which instrument has black and white keys?", 0, ["Piano", "Violin", "Trumpet", "Guitar"]),
    q!(Category::Art, Difficulty::Easy, "Who painted the Mona Lisa?", 1, ["Michelangelo", "Leonardo da Vinci", "Raphael", "Caravaggio"]),
    q!(Category::Art, Difficulty::Easy, "Which painter cut off his ear?", 3, ["Picasso", "Dalí", "Goya", "Van Gogh"]),
    q!(Category::Art, Difficulty::Easy, "How many black keys does a piano have?", 2, ["52", "32", "36", "44"]),
    q!(Category::Art, Difficulty::Easy, "What is a poem?", 0, ["A text with rhythm and rhyme", "A painting", "A song", "A history book"]),
    q!(Category::Art, Difficulty::Easy, "In which city is the Prado Museum?", 1, ["Barcelona", "Madrid", "Seville", "Valencia"]),
    q!(Category::Art, Difficulty::Easy, "Which instrument is a wind instrument?", 0, ["Flute", "Drum", "Violin", "Piano"]),
    q!(Category::Art, Difficulty::Medium, "Who wrote 'The Divine Comedy'?", 2, ["Boccaccio", "Petrarch", "Dante", "Cervantes"]),
    q!(Category::Art, Difficulty::Medium, "Which artistic movement does Dalí belong to?", 0, ["Surrealism", "Cubism", "Impressionism", "Baroque"]),
    q!(Category::Art, Difficulty::Medium, "Who composed the classic wedding march?", 1, ["Beethoven", "Mendelssohn", "Mozart", "Bach"]),
    q!(Category::Art, Difficulty::Medium, "Which work did Shakespeare write?", 3, ["The Odyssey", "Don Quixote", "Faust", "Hamlet"]),
    q!(Category::Art, Difficulty::Medium, "Which painter painted 'The Persistence of Memory'?", 0, ["Dalí", "Miró", "Picasso", "Gaudí"]),
    q!(Category::Art, Difficulty::Medium, "Which instrument has strings and pedals?", 1, ["Lyre", "Harp", "Guitar", "Zither"]),
    q!(Category::Art, Difficulty::Medium, "Who wrote 'Madame Bovary'?", 2, ["Zola", "Balzac", "Flaubert", "Dumas"]),
    q!(Category::Art, Difficulty::Medium, "Which architectural style does the Alhambra of Granada have?", 0, ["Islamic", "Gothic", "Renaissance", "Baroque"]),
    q!(Category::Art, Difficulty::Hard, "Which Baroque painter painted 'The Surrender of Breda'?", 1, ["Zurbarán", "Velázquez", "Murillo", "El Greco"]),
    q!(Category::Art, Difficulty::Hard, "Who wrote 'Life is a Dream'?", 0, ["Calderón de la Barca", "Lope de Vega", "Quevedo", "Tirso de Molina"]),
    q!(Category::Art, Difficulty::Hard, "Who composed 'The Marriage of Figaro'?", 2, ["Beethoven", "Haydn", "Mozart", "Rossini"]),
    q!(Category::Art, Difficulty::Hard, "Which painter is famous for pointillism?", 1, ["Monet", "Seurat", "Renoir", "Degas"]),
    q!(Category::Art, Difficulty::Hard, "Who wrote 'Moby Dick'?", 3, ["Poe", "Hawthorne", "Twain", "Melville"]),
    q!(Category::Art, Difficulty::Hard, "Which Renaissance painter painted 'The School of Athens'?", 0, ["Raphael", "Michelangelo", "Leonardo", "Titian"]),
    q!(Category::Art, Difficulty::Hard, "Which movement did André Breton found?", 1, ["Dadaism", "Surrealism", "Futurism", "Cubism"]),
    q!(Category::Art, Difficulty::Hard, "Who composed 'The Rite of Spring'?", 2, ["Debussy", "Ravel", "Stravinsky", "Prokofiev"]),
    // -- Art (open) --
    q_open!(Category::Art, Difficulty::Easy, "Who painted the ceiling of the Sistine Chapel?", "Michelangelo"),
    q_open!(Category::Art, Difficulty::Easy, "How many strings does a ukulele have?", "4"),
    q_open!(Category::Art, Difficulty::Easy, "Which Italian city is famous for its canals?", "Venice"),
    q_open!(Category::Art, Difficulty::Medium, "Who wrote 'Romeo and Juliet'?", "Shakespeare"),
    q_open!(Category::Art, Difficulty::Medium, "Which sculptor created 'The Thinker'?", "Rodin"),
    q_open!(Category::Art, Difficulty::Medium, "Who composed 'The Magic Flute'?", "Mozart"),
    q_open!(Category::Art, Difficulty::Hard, "Which Irish writer wrote 'Ulysses'?", "Joyce"),
    q_open!(Category::Art, Difficulty::Hard, "Which Spanish painter painted 'The Witches' Sabbath'?", "Goya"),
    q_open!(Category::Art, Difficulty::Hard, "Which artistic movement is based on small dots of color?", "Pointillism"),

    // -- Taboo (closed) --
    q!(Category::Taboo, Difficulty::Easy, "It's green, it jumps and croaks. What is it?", 2, ["Lizard", "Chameleon", "Frog", "Snake"]),
    q!(Category::Taboo, Difficulty::Easy, "It has white stripes and you cross it in the street. What is it?", 0, ["Zebra crossing", "Traffic light", "Sidewalk", "Curb"]),
    q!(Category::Taboo, Difficulty::Easy, "It's round, it turns and has numbers. What is it?", 1, ["Compass", "Clock", "Thermometer", "Calendar"]),
    q!(Category::Taboo, Difficulty::Easy, "You put it on your head to keep warm. What is it?", 3, ["Scarf", "Gloves", "Coat", "Hat"]),
    q!(Category::Taboo, Difficulty::Easy, "It's used to cut bread. What is it?", 0, ["Knife", "Fork", "Spoon", "Plate"]),
    q!(Category::Taboo, Difficulty::Easy, "It opens with a key and stores valuables. What is it?", 1, ["Backpack", "Safe", "Wallet", "Wardrobe"]),
    q!(Category::Taboo, Difficulty::Easy, "It has petals and smells nice. What is it?", 2, ["Leaf", "Branch", "Flower", "Root"]),
    q!(Category::Taboo, Difficulty::Easy, "It's used to sweep the floor. What is it?", 0, ["Broom", "Mop", "Dust mop", "Vacuum cleaner"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to measure time in a race. What is it?", 1, ["Hourglass", "Stopwatch", "Alarm clock", "Metronome"]),
    q!(Category::Taboo, Difficulty::Medium, "It has keys and bellows, it sounds like a small piano. What is it?", 0, ["Accordion", "Organ", "Synthesizer", "Xylophone"]),
    q!(Category::Taboo, Difficulty::Medium, "Astronauts use it to go out into space. What is it?", 2, ["Parachute", "Oxygen mask", "Space suit", "Balloon"]),
    q!(Category::Taboo, Difficulty::Medium, "It's put on the fire to cook soup. What is it?", 3, ["Frying pan", "Plate", "Tray", "Pot"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to see small letters up close. What is it?", 0, ["Magnifying glass", "Sunglasses", "Binoculars", "Telescope"]),
    q!(Category::Taboo, Difficulty::Medium, "It's an insect that produces honey. What is it?", 1, ["Wasp", "Bee", "Ladybug", "Ant"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to hold your hair. What is it?", 2, ["Necklace", "Earring", "Hair tie", "Ring"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to hammer nails. What is it?", 0, ["Hammer", "Screwdriver", "Pliers", "Wrench"]),
    q!(Category::Taboo, Difficulty::Hard, "Instrument that measures atmospheric pressure. What is it?", 1, ["Thermometer", "Barometer", "Hydrometer", "Speedometer"]),
    q!(Category::Taboo, Difficulty::Hard, "It's used in the lab to measure exact liquids. What is it?", 2, ["Beaker", "Test tube", "Graduated cylinder", "Funnel"]),
    q!(Category::Taboo, Difficulty::Hard, "Instrument that measures wind speed. What is it?", 0, ["Anemometer", "Barometer", "Thermometer", "Hydrometer"]),
    q!(Category::Taboo, Difficulty::Hard, "It's used to measure blood pressure. What is it?", 3, ["Glucometer", "Thermometer", "Stethoscope", "Blood pressure monitor"]),
    q!(Category::Taboo, Difficulty::Hard, "Instrument for listening to heartbeats. What is it?", 2, ["Thermometer", "Blood pressure monitor", "Stethoscope", "Ophthalmoscope"]),
    q!(Category::Taboo, Difficulty::Hard, "Device that measures blood sugar. What is it?", 0, ["Glucometer", "Thermometer", "Barometer", "Taximeter"]),
    q!(Category::Taboo, Difficulty::Hard, "It's used to make holes in wood. What is it?", 3, ["Saw", "Plane", "Sandpaper", "Drill"]),
    q!(Category::Taboo, Difficulty::Hard, "Instrument that measures the depth of the sea. What is it?", 1, ["Radar", "Sounding line", "Periscope", "Kaleidoscope"]),
    // -- Taboo (open) --
    q_open!(Category::Taboo, Difficulty::Easy, "It has hands and never tires of walking. What is it?", "clock"),
    q_open!(Category::Taboo, Difficulty::Easy, "It's used to dry the dishes. What is it?", "dish towel"),
    q_open!(Category::Taboo, Difficulty::Easy, "It's used to type on the computer. What is it?", "keyboard"),
    q_open!(Category::Taboo, Difficulty::Medium, "It hangs on the wall and rings on the hour. What is it?", "bell"),
    q_open!(Category::Taboo, Difficulty::Medium, "It's used to open doors and drawers. What is it?", "key"),
    q_open!(Category::Taboo, Difficulty::Medium, "It's an animal with a hump that lives in the desert. What is it?", "camel"),
    q_open!(Category::Taboo, Difficulty::Hard, "It's used to measure cooking time. What is it?", "timer"),
    q_open!(Category::Taboo, Difficulty::Hard, "Instrument sailors use to navigate by the stars. What is it?", "sextant"),
    q_open!(Category::Taboo, Difficulty::Hard, "Device that measures the kilometres driven by a car. What is it?", "odometer"),

    // ============ Extra batch 2: 315 new questions (19/08/2026) ============
    // -- Math (closed) --
    q!(Category::Math, Difficulty::Easy, "What is 11 + 9?", 3, ["18", "19", "21", "20"]),
    q!(Category::Math, Difficulty::Easy, "What is 7 x 8?", 2, ["54", "55", "56", "57"]),
    q!(Category::Math, Difficulty::Easy, "What is 144 ÷ 12?", 1, ["11", "12", "13", "14"]),
    q!(Category::Math, Difficulty::Easy, "What is the square of 9?", 0, ["81", "72", "90", "64"]),
    q!(Category::Math, Difficulty::Easy, "How many centimetres are in a metre?", 3, ["10", "50", "1000", "100"]),
    q!(Category::Math, Difficulty::Easy, "What is half of 38?", 2, ["18", "20", "19", "17"]),
    q!(Category::Math, Difficulty::Easy, "What is 25 - 17?", 1, ["7", "8", "9", "6"]),
    q!(Category::Math, Difficulty::Easy, "What is 6 x 9?", 0, ["54", "56", "45", "63"]),
    q!(Category::Math, Difficulty::Easy, "Which number is double 15?", 2, ["25", "35", "30", "20"]),
    q!(Category::Math, Difficulty::Easy, "What is 100 - 37?", 3, ["73", "67", "62", "63"]),
    q!(Category::Math, Difficulty::Medium, "What is the area of a rectangle 8 cm long and 5 cm wide?", 1, ["26 cm²", "40 cm²", "45 cm²", "13 cm²"]),
    q!(Category::Math, Difficulty::Medium, "What is 3/4 + 1/4?", 0, ["1", "1/2", "2/4", "3/8"]),
    q!(Category::Math, Difficulty::Medium, "Which of these numbers is prime?", 2, ["21", "25", "17", "27"]),
    q!(Category::Math, Difficulty::Medium, "What is 2 to the power of 10?", 3, ["512", "1000", "2048", "1024"]),
    q!(Category::Math, Difficulty::Medium, "What is the perimeter of a square with side 7?", 0, ["28", "49", "14", "35"]),
    q!(Category::Math, Difficulty::Medium, "What is 10 % of 350?", 1, ["30", "35", "40", "50"]),
    q!(Category::Math, Difficulty::Medium, "What do the interior angles of a triangle add up to?", 2, ["90°", "270°", "180°", "360°"]),
    q!(Category::Math, Difficulty::Medium, "If 3x = 21, what is x?", 0, ["7", "6", "8", "9"]),
    q!(Category::Math, Difficulty::Medium, "Which power of 2 comes after 32?", 1, ["48", "64", "128", "50"]),
    q!(Category::Math, Difficulty::Medium, "What is 0.25 expressed as a fraction?", 3, ["1/2", "1/3", "2/5", "1/4"]),
    q!(Category::Math, Difficulty::Hard, "What is the integral of 2x?", 2, ["2", "2x", "x²", "x"]),
    q!(Category::Math, Difficulty::Hard, "If 2x + 7 = 19, what is x?", 0, ["6", "5", "7", "4"]),
    q!(Category::Math, Difficulty::Hard, "What is the natural logarithm of e?", 1, ["0", "1", "e", "2"]),
    q!(Category::Math, Difficulty::Hard, "What is the slope of the line y = 3x + 2?", 2, ["2", "x", "3", "5"]),
    q!(Category::Math, Difficulty::Hard, "What do the interior angles of a hexagon add up to?", 0, ["720°", "540°", "900°", "1080°"]),
    q!(Category::Math, Difficulty::Hard, "What is the probability of getting two heads when flipping two coins?", 1, ["1/2", "1/4", "1/3", "3/4"]),
    q!(Category::Math, Difficulty::Hard, "What is 15 % of 240?", 3, ["24", "30", "32", "36"]),
    q!(Category::Math, Difficulty::Hard, "If x² = 121, what is x?", 2, ["12", "10", "11", "21"]),
    q!(Category::Math, Difficulty::Hard, "What is 8! divided by 7!?", 0, ["8", "7", "56", "1"]),
    q!(Category::Math, Difficulty::Hard, "What is the median of 3, 5, 7, 9 and 11?", 1, ["5", "7", "9", "6"]),
    // -- Math (open) --
    q_open!(Category::Math, Difficulty::Easy, "What is 12 x 4?", "48"),
    q_open!(Category::Math, Difficulty::Easy, "What is 30 + 45?", "75"),
    q_open!(Category::Math, Difficulty::Easy, "How many sides does a hexagon have?", "6"),
    q_open!(Category::Math, Difficulty::Easy, "What is double 24?", "48"),
    q_open!(Category::Math, Difficulty::Easy, "What is 90 ÷ 3?", "30"),
    q_open!(Category::Math, Difficulty::Medium, "What is the area of a square with side 6?", "36"),
    q_open!(Category::Math, Difficulty::Medium, "What is 3/4 of 100?", "75"),
    q_open!(Category::Math, Difficulty::Medium, "Which prime number comes after 7?", "11"),
    q_open!(Category::Math, Difficulty::Medium, "What is 2 to the power of 8?", "256"),
    q_open!(Category::Math, Difficulty::Medium, "What is the square root of 144?", "12"),
    q_open!(Category::Math, Difficulty::Hard, "If 4x - 5 = 11, what is x?", "4"),
    q_open!(Category::Math, Difficulty::Hard, "What is the derivative of x³?", "3x²"),
    q_open!(Category::Math, Difficulty::Hard, "What do the interior angles of an octagon add up to?", "1080"),
    q_open!(Category::Math, Difficulty::Hard, "What is the probability of drawing an ace from a Spanish deck of 40 cards?", "1/10"),
    q_open!(Category::Math, Difficulty::Hard, "What is 20 % of 150?", "30"),

    // -- History (closed) --
    q!(Category::History, Difficulty::Easy, "In which city is the Colosseum?", 2, ["Athens", "Paris", "Rome", "Madrid"]),
    q!(Category::History, Difficulty::Easy, "Which country built the Great Wall?", 3, ["Japan", "Mongolia", "India", "China"]),
    q!(Category::History, Difficulty::Easy, "Which civilization built Machu Picchu?", 1, ["Mayas", "Incas", "Aztecs", "Olmecs"]),
    q!(Category::History, Difficulty::Easy, "In which country is the Acropolis?", 1, ["Italy", "Greece", "Turkey", "Egypt"]),
    q!(Category::History, Difficulty::Easy, "Who fought against apartheid in South Africa?", 2, ["Luther King", "Gandhi", "Mandela", "Che Guevara"]),
    q!(Category::History, Difficulty::Easy, "In what year did the Western Roman Empire fall?", 0, ["476", "395", "1453", "1066"]),
    q!(Category::History, Difficulty::Easy, "Which queen financed Columbus's voyage?", 1, ["Joanna the Mad", "Isabella I of Castile", "Mary Tudor", "Catherine of Aragon"]),
    q!(Category::History, Difficulty::Easy, "Which Roman general crossed the Rubicon?", 0, ["Caesar", "Nero", "Augustus", "Caligula"]),
    q!(Category::History, Difficulty::Easy, "Which city was the capital of the Inca Empire?", 1, ["Cusco", "Lima", "Quito", "Bogotá"]),
    q!(Category::History, Difficulty::Easy, "Which people reached America before Columbus?", 1, ["Saxons", "Vikings", "Franks", "Huns"]),
    q!(Category::History, Difficulty::Medium, "In what year did World War II begin?", 1, ["1935", "1939", "1941", "1937"]),
    q!(Category::History, Difficulty::Medium, "Which country dropped the atomic bombs in 1945?", 0, ["USA", "Germany", "Japan", "Russia"]),
    q!(Category::History, Difficulty::Medium, "Who was assassinated in Sarajevo in 1914?", 2, ["Wilhelm II", "Nicholas II", "Franz Ferdinand", "Bismarck"]),
    q!(Category::History, Difficulty::Medium, "Which dynasty did Charles I of Spain belong to?", 1, ["Bourbon", "Habsburg", "Trastámara", "Austria"]),
    q!(Category::History, Difficulty::Medium, "Which empire had its capital in Tenochtitlan?", 3, ["Maya", "Inca", "Olmec", "Aztec"]),
    q!(Category::History, Difficulty::Medium, "Which conquistador defeated the Aztec Empire?", 0, ["Cortés", "Pizarro", "Balboa", "Magellan"]),
    q!(Category::History, Difficulty::Medium, "What did Gutenberg invent in the 15th century?", 2, ["Telescope", "Compass", "Printing press", "Gunpowder"]),
    q!(Category::History, Difficulty::Medium, "In what year did the Spanish Civil War end?", 1, ["1936", "1939", "1945", "1931"]),
    q!(Category::History, Difficulty::Medium, "Which treaty ended the War of the Spanish Succession?", 0, ["Utrecht", "Versailles", "Vienna", "Westphalia"]),
    q!(Category::History, Difficulty::Medium, "Who was the first president of Mexico?", 2, ["Juárez", "Santa Anna", "Guadalupe Victoria", "Iturbide"]),
    q!(Category::History, Difficulty::Hard, "In what year was the First Spanish Republic proclaimed?", 1, ["1868", "1873", "1876", "1898"]),
    q!(Category::History, Difficulty::Hard, "Which battle of 1805 did Napoleon win?", 0, ["Austerlitz", "Waterloo", "Trafalgar", "Leipzig"]),
    q!(Category::History, Difficulty::Hard, "Which Roman emperor legalized Christianity?", 2, ["Nero", "Diocletian", "Constantine", "Theodosius"]),
    q!(Category::History, Difficulty::Hard, "Which battle of 1066 did William of Normandy win?", 1, ["Agincourt", "Hastings", "Poitiers", "Covadonga"]),
    q!(Category::History, Difficulty::Hard, "Which Carthaginian general crossed the Alps with elephants?", 3, ["Caesar", "Pompey", "Alexander", "Hannibal"]),
    q!(Category::History, Difficulty::Hard, "In what year was the Treaty of Tordesillas signed?", 2, ["1492", "1493", "1494", "1500"]),
    q!(Category::History, Difficulty::Hard, "Which Ottoman sultan conquered Constantinople?", 0, ["Mehmed II", "Suleiman", "Bayezid", "Osman I"]),
    q!(Category::History, Difficulty::Hard, "Which revolution began in 1910?", 1, ["Russian", "Mexican", "French", "Chinese"]),
    q!(Category::History, Difficulty::Hard, "Which British monarch reigned until 2022?", 2, ["Victoria", "Elizabeth I", "Elizabeth II", "Anne"]),
    q!(Category::History, Difficulty::Hard, "Which civilization developed the most accurate calendar of antiquity?", 1, ["Aztec", "Maya", "Inca", "Egyptian"]),
    // -- History (open) --
    q_open!(Category::History, Difficulty::Easy, "In what year did man reach the Moon?", "1969"),
    q_open!(Category::History, Difficulty::Easy, "Which European country colonized most of South America?", "Spain"),
    q_open!(Category::History, Difficulty::Easy, "In what year was America discovered?", "1492"),
    q_open!(Category::History, Difficulty::Easy, "Which emperor was crowned by the pope in the year 800?", "Charlemagne"),
    q_open!(Category::History, Difficulty::Easy, "Which ancient civilization built the Parthenon?", "Greeks"),
    q_open!(Category::History, Difficulty::Medium, "In what year did World War II end?", "1945"),
    q_open!(Category::History, Difficulty::Medium, "Who led the independence of India?", "Gandhi"),
    q_open!(Category::History, Difficulty::Medium, "Which US president abolished slavery?", "Lincoln"),
    q_open!(Category::History, Difficulty::Medium, "In what year was the Treaty of Maastricht signed?", "1992"),
    q_open!(Category::History, Difficulty::Medium, "Which pharaoh is famous for his golden tomb?", "Tutankhamun"),
    q_open!(Category::History, Difficulty::Hard, "In what year did Constantinople fall?", "1453"),
    q_open!(Category::History, Difficulty::Hard, "Who was the last Western Roman emperor?", "Romulus Augustulus"),
    q_open!(Category::History, Difficulty::Hard, "Which congress of 1815 reorganized Europe after Napoleon?", "Vienna"),
    q_open!(Category::History, Difficulty::Hard, "Which battle of 1521 marked the fall of Tenochtitlan?", "Tenochtitlan"),
    q_open!(Category::History, Difficulty::Hard, "Which country returned Hong Kong to China in 1997?", "United Kingdom"),

    // -- Computer Science (closed) --
    q!(Category::Cs, Difficulty::Easy, "Which key deletes the character to the right of the cursor?", 0, ["Delete", "Shift", "Alt", "Tab"]),
    q!(Category::Cs, Difficulty::Easy, "What extension do digital photos have?", 1, [".txt", ".jpg", ".mp3", ".docx"]),
    q!(Category::Cs, Difficulty::Easy, "Which program is used to do calculations and tables?", 2, ["Word processor", "Browser", "Spreadsheet", "Antivirus"]),
    q!(Category::Cs, Difficulty::Easy, "Which key do you press to accept or enter?", 0, ["Enter", "Esc", "F1", "Shift"]),
    q!(Category::Cs, Difficulty::Easy, "What does the floppy disk button mean in many programs?", 3, ["Open", "Print", "Delete", "Save"]),
    q!(Category::Cs, Difficulty::Easy, "Which device do you use to listen to audio?", 1, ["Keyboard", "Headphones", "Mouse", "Camera"]),
    q!(Category::Cs, Difficulty::Easy, "What does the right mouse button open?", 0, ["A context menu", "Selects everything", "Closes the program", "Copies the text"]),
    q!(Category::Cs, Difficulty::Easy, "What extension do digital songs have?", 2, [".jpg", ".exe", ".mp3", ".doc"]),
    q!(Category::Cs, Difficulty::Easy, "Which technology connects the computer to the internet without cables?", 1, ["Bluetooth", "Wi-Fi", "USB", "HDMI"]),
    q!(Category::Cs, Difficulty::Easy, "Which key refreshes a web page?", 0, ["F5", "F2", "F10", "F12"]),
    q!(Category::Cs, Difficulty::Medium, "Which computing prefix equals about one billion bytes?", 2, ["Mega", "Tera", "Giga", "Peta"]),
    q!(Category::Cs, Difficulty::Medium, "How are the folders of the file system organized?", 1, ["In a list", "In a tree", "In a stack", "In a graph"]),
    q!(Category::Cs, Difficulty::Medium, "What does print() do in Python?", 3, ["Delete text", "Save file", "Read the keyboard", "Show text on screen"]),
    q!(Category::Cs, Difficulty::Medium, "Which unit measures the processor speed?", 0, ["GHz", "GB", "MB", "Watt"]),
    q!(Category::Cs, Difficulty::Medium, "What is a bug?", 2, ["A virus", "A hacker", "An error in the program", "An update"]),
    q!(Category::Cs, Difficulty::Medium, "Which combination copies in Windows?", 1, ["Ctrl + V", "Ctrl + C", "Ctrl + X", "Ctrl + Z"]),
    q!(Category::Cs, Difficulty::Medium, "Which component is in charge of drawing on screen?", 0, ["GPU", "CPU", "RAM", "SSD"]),
    q!(Category::Cs, Difficulty::Medium, "Which protocol transfers files?", 2, ["HTTP", "SMTP", "FTP", "DNS"]),
    q!(Category::Cs, Difficulty::Medium, "What does the S in HTTPS mean?", 1, ["Server", "Secure", "System", "Solo"]),
    q!(Category::Cs, Difficulty::Medium, "Which memory is the fastest?", 3, ["Hard drive", "External SSD", "CD-ROM", "RAM"]),
    q!(Category::Cs, Difficulty::Hard, "What complexity does quicksort have in the average case?", 1, ["O(n)", "O(n log n)", "O(n²)", "O(log n)"]),
    q!(Category::Cs, Difficulty::Hard, "Which structure allows access by index in constant time?", 0, ["Array", "Linked list", "Stack", "Queue"]),
    q!(Category::Cs, Difficulty::Hard, "What is recursion?", 2, ["An infinite loop", "An error", "A function that calls itself", "A global variable"]),
    q!(Category::Cs, Difficulty::Hard, "Which language compiles directly to machine code?", 0, ["C", "Python", "JavaScript", "Ruby"]),
    q!(Category::Cs, Difficulty::Hard, "Which protocol converts domains into IP addresses?", 3, ["HTTP", "FTP", "SMTP", "DNS"]),
    q!(Category::Cs, Difficulty::Hard, "What does Big O notation express?", 0, ["The complexity of the algorithm", "The size of the file", "The speed of the processor", "The number of errors"]),
    q!(Category::Cs, Difficulty::Hard, "What is cache memory?", 1, ["External memory", "Fast memory close to the processor", "Read-only memory", "Virtual memory"]),
    q!(Category::Cs, Difficulty::Hard, "Which search goes through the elements one by one?", 2, ["Binary", "Tree", "Linear", "Hash"]),
    q!(Category::Cs, Difficulty::Hard, "What does API mean?", 0, ["Application Programming Interface", "Application of Internal Protocols", "Automation of Computer Processes", "Personal Access to the Internet"]),
    q!(Category::Cs, Difficulty::Hard, "Which structure implements the browser's back button?", 1, ["Queue", "Stack", "Array", "Hash"]),
    // -- Computer Science (open) --
    q_open!(Category::Cs, Difficulty::Easy, "Which key is used to exit or cancel?", "Esc"),
    q_open!(Category::Cs, Difficulty::Easy, "Which device is used to print?", "Printer"),
    q_open!(Category::Cs, Difficulty::Easy, "What extension do videos have?", "mp4"),
    q_open!(Category::Cs, Difficulty::Easy, "What is used to type on the computer?", "Keyboard"),
    q_open!(Category::Cs, Difficulty::Easy, "Which application plays music and video?", "Player"),
    q_open!(Category::Cs, Difficulty::Medium, "Which language creates interactive web pages?", "JavaScript"),
    q_open!(Category::Cs, Difficulty::Medium, "Which command creates a folder in Linux?", "mkdir"),
    q_open!(Category::Cs, Difficulty::Medium, "Which unit is larger, KB or MB?", "MB"),
    q_open!(Category::Cs, Difficulty::Medium, "Which language styles web pages?", "CSS"),
    q_open!(Category::Cs, Difficulty::Medium, "Which key captures the screen in Windows?", "PrtSc"),
    q_open!(Category::Cs, Difficulty::Hard, "Which sorting algorithm is stable and efficient with nearly sorted lists?", "Insertion sort"),
    q_open!(Category::Cs, Difficulty::Hard, "Which structure allows inserting and deleting at both ends?", "Deque"),
    q_open!(Category::Cs, Difficulty::Hard, "Which git command uploads the changes to the remote?", "git push"),
    q_open!(Category::Cs, Difficulty::Hard, "Which attack impersonates a legitimate website to steal data?", "Phishing"),
    q_open!(Category::Cs, Difficulty::Hard, "Which programming language does the Spring framework use?", "Java"),

    // -- Geography (closed) --
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Italy?", 2, ["Milan", "Naples", "Rome", "Venice"]),
    q!(Category::Geography, Difficulty::Easy, "Which is the largest continent?", 0, ["Asia", "Africa", "America", "Europe"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Argentina?", 1, ["Rosario", "Buenos Aires", "Córdoba", "La Plata"]),
    q!(Category::Geography, Difficulty::Easy, "Which country has the Eiffel Tower?", 3, ["Italy", "Germany", "United Kingdom", "France"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Mexico?", 2, ["Guadalajara", "Monterrey", "Mexico City", "Puebla"]),
    q!(Category::Geography, Difficulty::Easy, "Which is the most populated country in Africa?", 1, ["Egypt", "Nigeria", "Ethiopia", "South Africa"]),
    q!(Category::Geography, Difficulty::Easy, "Which river flows through Paris?", 0, ["Seine", "Rhône", "Loire", "Garonne"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Chile?", 3, ["Valparaíso", "Concepción", "Viña del Mar", "Santiago"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Peru?", 1, ["Arequipa", "Lima", "Cusco", "Trujillo"]),
    q!(Category::Geography, Difficulty::Easy, "On which continent is Australia?", 0, ["Oceania", "Asia", "Europe", "Africa"]),
    q!(Category::Geography, Difficulty::Medium, "Which is the most voluminous river in the world?", 2, ["Nile", "Yangtze", "Amazon", "Mississippi"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Sweden?", 1, ["Oslo", "Stockholm", "Copenhagen", "Helsinki"]),
    q!(Category::Geography, Difficulty::Medium, "Which strait separates Asia from America?", 0, ["Bering", "Panama", "Suez", "Magellan"]),
    q!(Category::Geography, Difficulty::Medium, "Which is the highest peak in Europe?", 1, ["Mont Blanc", "Elbrus", "Teide", "Aneto"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Turkey?", 2, ["Istanbul", "Izmir", "Ankara", "Antalya"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Poland?", 0, ["Warsaw", "Kraków", "Gdańsk", "Łódź"]),
    q!(Category::Geography, Difficulty::Medium, "Which desert is in Mongolia?", 1, ["Sahara", "Gobi", "Kalahari", "Atacama"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Austria?", 3, ["Salzburg", "Graz", "Innsbruck", "Vienna"]),
    q!(Category::Geography, Difficulty::Medium, "Which country has the largest population in South America?", 0, ["Brazil", "Argentina", "Colombia", "Peru"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Ireland?", 1, ["Belfast", "Dublin", "Cork", "Galway"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of Uzbekistan?", 2, ["Samarkand", "Bukhara", "Tashkent", "Almaty"]),
    q!(Category::Geography, Difficulty::Hard, "Which is the longest river in Asia?", 0, ["Yangtze", "Ganges", "Euphrates", "Ob"]),
    q!(Category::Geography, Difficulty::Hard, "Which is the lowest point of the emerged land?", 1, ["Caspian Sea", "Dead Sea", "Lake Baikal", "Death Valley"]),
    q!(Category::Geography, Difficulty::Hard, "Which Oceanian country is also a continent?", 3, ["New Zealand", "Papua", "Fiji", "Australia"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of Ethiopia?", 0, ["Addis Ababa", "Cairo", "Nairobi", "Khartoum"]),
    q!(Category::Geography, Difficulty::Hard, "Which country has the most islands in the world?", 1, ["Japan", "Sweden", "Indonesia", "Philippines"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of Vietnam?", 2, ["Ho Chi Minh City", "Da Nang", "Hanoi", "Huế"]),
    q!(Category::Geography, Difficulty::Hard, "Which is the longest mountain range in the world?", 1, ["Himalayas", "Andes", "Alps", "Rockies"]),
    q!(Category::Geography, Difficulty::Hard, "Which country spans two continents?", 0, ["Russia", "Spain", "Italy", "Poland"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of Iceland?", 3, ["Copenhagen", "Helsinki", "Oslo", "Reykjavík"]),
    // -- Geography (open) --
    q_open!(Category::Geography, Difficulty::Easy, "What is the capital of England?", "London"),
    q_open!(Category::Geography, Difficulty::Easy, "Which is the smallest ocean?", "Arctic"),
    q_open!(Category::Geography, Difficulty::Easy, "On which continent is Brazil?", "South America"),
    q_open!(Category::Geography, Difficulty::Easy, "What is the capital of Greece?", "Athens"),
    q_open!(Category::Geography, Difficulty::Easy, "What is the capital of Cuba?", "Havana"),
    q_open!(Category::Geography, Difficulty::Medium, "What is the capital of South Korea?", "Seoul"),
    q_open!(Category::Geography, Difficulty::Medium, "What is the longest river in America?", "Amazon"),
    q_open!(Category::Geography, Difficulty::Medium, "What is the capital of Switzerland?", "Bern"),
    q_open!(Category::Geography, Difficulty::Medium, "Which Nordic country has the capital Helsinki?", "Finland"),
    q_open!(Category::Geography, Difficulty::Medium, "What is the capital of Morocco?", "Rabat"),
    q_open!(Category::Geography, Difficulty::Hard, "What is the largest desert in Asia?", "Gobi"),
    q_open!(Category::Geography, Difficulty::Hard, "What is the capital of Myanmar?", "Naypyidaw"),
    q_open!(Category::Geography, Difficulty::Hard, "Which country has the highest capital in the world?", "Bolivia"),
    q_open!(Category::Geography, Difficulty::Hard, "What is the highest peak in North America?", "Denali"),
    q_open!(Category::Geography, Difficulty::Hard, "Which Scandinavian country has the capital Copenhagen?", "Denmark"),

    // -- Science (closed) --
    q!(Category::Science, Difficulty::Easy, "Which organ do you use to think?", 2, ["Heart", "Lungs", "Brain", "Stomach"]),
    q!(Category::Science, Difficulty::Easy, "How many legs does a cat have?", 0, ["4", "2", "6", "8"]),
    q!(Category::Science, Difficulty::Easy, "With which body part do you see?", 1, ["Ears", "Eyes", "Nose", "Skin"]),
    q!(Category::Science, Difficulty::Easy, "Which animal lays eggs?", 3, ["Cow", "Dog", "Cat", "Hen"]),
    q!(Category::Science, Difficulty::Easy, "With which organ do you smell?", 2, ["Eyes", "Mouth", "Nose", "Hands"]),
    q!(Category::Science, Difficulty::Easy, "Which is the largest land animal?", 0, ["Elephant", "Giraffe", "Rhinoceros", "Hippopotamus"]),
    q!(Category::Science, Difficulty::Easy, "What does fire need to burn?", 1, ["Water", "Oxygen", "Sand", "Soil"]),
    q!(Category::Science, Difficulty::Easy, "Which is the smallest planet of the solar system?", 2, ["Mars", "Venus", "Mercury", "Pluto"]),
    q!(Category::Science, Difficulty::Easy, "Which gas do you exhale when breathing?", 0, ["CO2", "Oxygen", "Nitrogen", "Hydrogen"]),
    q!(Category::Science, Difficulty::Easy, "Which animal lives in Antarctica?", 1, ["Polar bear", "Penguin", "Lion", "Camel"]),
    q!(Category::Science, Difficulty::Medium, "What energy does a moving ball have?", 2, ["Potential", "Chemical", "Kinetic", "Thermal"]),
    q!(Category::Science, Difficulty::Medium, "Which planet has days longer than its year?", 0, ["Venus", "Mars", "Mercury", "Neptune"]),
    q!(Category::Science, Difficulty::Medium, "Which is the fastest bird in a dive?", 1, ["Eagle", "Peregrine falcon", "Swallow", "Hummingbird"]),
    q!(Category::Science, Difficulty::Medium, "Which metal is used in electrical wires?", 2, ["Iron", "Aluminium", "Copper", "Gold"]),
    q!(Category::Science, Difficulty::Medium, "Which layer of the atmosphere contains the ozone layer?", 0, ["Stratosphere", "Troposphere", "Mesosphere", "Exosphere"]),
    q!(Category::Science, Difficulty::Medium, "Which force keeps the planets orbiting the Sun?", 1, ["Magnetism", "Gravity", "Friction", "Inertia"]),
    q!(Category::Science, Difficulty::Medium, "How long does sunlight take to reach the Earth?", 2, ["1 second", "1 hour", "8 minutes", "24 hours"]),
    q!(Category::Science, Difficulty::Medium, "Which planet has the shortest day?", 1, ["Mars", "Jupiter", "Venus", "Mercury"]),
    q!(Category::Science, Difficulty::Medium, "Which substance gives plants their green color?", 3, ["Melanin", "Hemoglobin", "Keratin", "Chlorophyll"]),
    q!(Category::Science, Difficulty::Medium, "Which organ removes carbon dioxide?", 0, ["Lungs", "Kidneys", "Liver", "Heart"]),
    q!(Category::Science, Difficulty::Hard, "Which is the unit of electrical resistance?", 2, ["Ampere", "Volt", "Ohm", "Watt"]),
    q!(Category::Science, Difficulty::Hard, "Which law of Newton explains the inertia when braking?", 1, ["Second", "First", "Third", "Gravitation"]),
    q!(Category::Science, Difficulty::Hard, "Which particle orbits the nucleus of the atom?", 0, ["Electron", "Proton", "Neutron", "Quark"]),
    q!(Category::Science, Difficulty::Hard, "Which process divides a cell into two?", 3, ["Photosynthesis", "Meiosis", "Digestion", "Mitosis"]),
    q!(Category::Science, Difficulty::Hard, "Which is the most abundant element in the human body?", 1, ["Carbon", "Oxygen", "Hydrogen", "Nitrogen"]),
    q!(Category::Science, Difficulty::Hard, "What happens when the Moon is between the Sun and the Earth?", 2, ["Lunar eclipse", "High tide", "Solar eclipse", "Solstice"]),
    q!(Category::Science, Difficulty::Hard, "Which quantity does the newton measure?", 0, ["Force", "Energy", "Power", "Speed"]),
    q!(Category::Science, Difficulty::Hard, "What is the approximate speed of sound in air?", 1, ["300 m/s", "343 m/s", "1000 m/s", "1500 m/s"]),
    q!(Category::Science, Difficulty::Hard, "Which type of bond shares electrons?", 3, ["Ionic", "Metallic", "Van der Waals", "Covalent"]),
    q!(Category::Science, Difficulty::Hard, "Which planet has the strongest magnetic field?", 0, ["Jupiter", "Earth", "Saturn", "Uranus"]),
    // -- Science (open) --
    q_open!(Category::Science, Difficulty::Easy, "How many eyes does a human being have?", "2"),
    q_open!(Category::Science, Difficulty::Easy, "Which animal is the tallest in the world?", "Giraffe"),
    q_open!(Category::Science, Difficulty::Easy, "Which is the closest star to the Earth?", "Sun"),
    q_open!(Category::Science, Difficulty::Easy, "Which part of the plant absorbs water from the soil?", "Root"),
    q_open!(Category::Science, Difficulty::Easy, "How many hours are in a day?", "24"),
    q_open!(Category::Science, Difficulty::Medium, "What type of animal is the dolphin?", "Mammal"),
    q_open!(Category::Science, Difficulty::Medium, "Which is the hottest planet of the solar system?", "Venus"),
    q_open!(Category::Science, Difficulty::Medium, "Which cell fights infections?", "White blood cell"),
    q_open!(Category::Science, Difficulty::Medium, "Which phenomenon produces lightning in storms?", "Electricity"),
    q_open!(Category::Science, Difficulty::Medium, "Which metal is the best conductor of electricity?", "Silver"),
    q_open!(Category::Science, Difficulty::Hard, "What is the formula of sulfuric acid?", "H2SO4"),
    q_open!(Category::Science, Difficulty::Hard, "Which scientist proposed general relativity?", "Einstein"),
    q_open!(Category::Science, Difficulty::Hard, "What is the SI unit of power?", "Watt"),
    q_open!(Category::Science, Difficulty::Hard, "Which particle is its own antiparticle?", "Photon"),
    q_open!(Category::Science, Difficulty::Hard, "Which process converts nitrogen from the air into compounds useful for plants?", "Nitrogen fixation"),

    // -- Art (closed) --
    q!(Category::Art, Difficulty::Easy, "Which string instrument is played with a bow?", 0, ["Violin", "Guitar", "Piano", "Drums"]),
    q!(Category::Art, Difficulty::Easy, "What are the primary colors?", 1, ["Green, orange and purple", "Red, blue and yellow", "Black, white and grey", "Pink, lilac and turquoise"]),
    q!(Category::Art, Difficulty::Easy, "Who painted 'The Scream'?", 2, ["Dalí", "Picasso", "Munch", "Klimt"]),
    q!(Category::Art, Difficulty::Easy, "Which artwork is hung on the wall?", 1, ["Sculpture", "Painting", "Vessel", "Tapestry"]),
    q!(Category::Art, Difficulty::Easy, "Which famous composer was deaf?", 0, ["Beethoven", "Mozart", "Bach", "Vivaldi"]),
    q!(Category::Art, Difficulty::Easy, "Which percussion instrument is triangular in shape?", 3, ["Flute", "Oboe", "Xylophone", "Triangle"]),
    q!(Category::Art, Difficulty::Easy, "What color comes from mixing red and blue?", 2, ["Green", "Orange", "Purple", "Pink"]),
    q!(Category::Art, Difficulty::Easy, "Which museum in Paris has the Mona Lisa?", 1, ["Prado", "Louvre", "Met", "Hermitage"]),
    q!(Category::Art, Difficulty::Easy, "What is a portrait?", 0, ["The painting of a person", "The painting of a landscape", "The painting of fruit", "Abstract painting"]),
    q!(Category::Art, Difficulty::Easy, "Which percussion instrument is played with drumsticks?", 1, ["Harp", "Drums", "Cello", "Saxophone"]),
    q!(Category::Art, Difficulty::Medium, "Which Spanish painter painted 'The Third of May 1808'?", 2, ["El Greco", "Velázquez", "Goya", "Zurbarán"]),
    q!(Category::Art, Difficulty::Medium, "Which movement uses vivid colors and comic figures?", 0, ["Pop Art", "Baroque", "Renaissance", "Realism"]),
    q!(Category::Art, Difficulty::Medium, "Who wrote 'Pride and Prejudice'?", 1, ["Eliot", "Austen", "Brontë", "Woolf"]),
    q!(Category::Art, Difficulty::Medium, "Which work is by Botticelli?", 2, ["Mona Lisa", "David", "The Birth of Venus", "The Last Supper"]),
    q!(Category::Art, Difficulty::Medium, "Which bowed string instrument is the lowest of the quartet?", 0, ["Cello", "Flute", "Trumpet", "Drums"]),
    q!(Category::Art, Difficulty::Medium, "Which Mexican artist painted famous self-portraits?", 1, ["Rivera", "Frida Kahlo", "Orozco", "Tamayo"]),
    q!(Category::Art, Difficulty::Medium, "Who composed 'The Blue Danube'?", 3, ["Beethoven", "Schubert", "Mahler", "Strauss"]),
    q!(Category::Art, Difficulty::Medium, "Who wrote 'The Three Musketeers'?", 0, ["Dumas", "Hugo", "Verne", "Zola"]),
    q!(Category::Art, Difficulty::Medium, "Which style painted everyday life as it is?", 2, ["Cubism", "Baroque", "Realism", "Surrealism"]),
    q!(Category::Art, Difficulty::Medium, "Which bellows instrument is used in tango?", 1, ["Accordion", "Bandoneon", "Organ", "Harmonica"]),
    q!(Category::Art, Difficulty::Hard, "Which Dutch painter painted 'The Night Watch'?", 2, ["Vermeer", "Van Gogh", "Rembrandt", "Rubens"]),
    q!(Category::Art, Difficulty::Hard, "Who wrote 'War and Peace'?", 0, ["Tolstoy", "Dostoevsky", "Chekhov", "Pushkin"]),
    q!(Category::Art, Difficulty::Hard, "Which Polish composer wrote almost only for piano?", 1, ["Liszt", "Chopin", "Debussy", "Satie"]),
    q!(Category::Art, Difficulty::Hard, "Which Austrian painter painted 'The Kiss'?", 2, ["Schiele", "Kandinsky", "Klimt", "Munch"]),
    q!(Category::Art, Difficulty::Hard, "Which Czech writer wrote 'The Metamorphosis'?", 0, ["Kafka", "Hesse", "Mann", "Musil"]),
    q!(Category::Art, Difficulty::Hard, "Which Impressionist painter painted 'Impression, Sunrise'?", 1, ["Degas", "Monet", "Renoir", "Pissarro"]),
    q!(Category::Art, Difficulty::Hard, "Which opera did Verdi compose?", 2, ["Tosca", "Carmen", "Aida", "Turandot"]),
    q!(Category::Art, Difficulty::Hard, "Which poet wrote 'Fields of Castile'?", 3, ["Unamuno", "Azorín", "Valle-Inclán", "Machado"]),
    q!(Category::Art, Difficulty::Hard, "Which musical style flourished in Vienna in the 18th century?", 0, ["Classicism", "Romanticism", "Baroque", "Renaissance"]),
    q!(Category::Art, Difficulty::Hard, "Which artist created 'Maman', the giant spider?", 1, ["Hirst", "Louise Bourgeois", "Kapoor", "Calder"]),
    // -- Art (open) --
    q_open!(Category::Art, Difficulty::Easy, "Which instrument has 6 strings and is played with a pick?", "Guitar"),
    q_open!(Category::Art, Difficulty::Easy, "Who painted 'The Last Supper'?", "Leonardo da Vinci"),
    q_open!(Category::Art, Difficulty::Easy, "Which famous painting by Leonardo is in the Louvre?", "Mona Lisa"),
    q_open!(Category::Art, Difficulty::Easy, "What is the art of folding paper called?", "Origami"),
    q_open!(Category::Art, Difficulty::Easy, "Which composer wrote the Fifth Symphony?", "Beethoven"),
    q_open!(Category::Art, Difficulty::Medium, "Who wrote 'Crime and Punishment'?", "Dostoevsky"),
    q_open!(Category::Art, Difficulty::Medium, "Which French painter is famous for his water lilies?", "Monet"),
    q_open!(Category::Art, Difficulty::Medium, "Who composed 'The Carnival of the Animals'?", "Saint-Saëns"),
    q_open!(Category::Art, Difficulty::Medium, "Which Spanish writer wrote 'The Hive'?", "Cela"),
    q_open!(Category::Art, Difficulty::Medium, "Which brass wind instrument is S-shaped?", "Saxophone"),
    q_open!(Category::Art, Difficulty::Hard, "Which writer wrote 'The Great Gatsby'?", "Fitzgerald"),
    q_open!(Category::Art, Difficulty::Hard, "Which composer left an unfinished Requiem when he died at 35?", "Mozart"),
    q_open!(Category::Art, Difficulty::Hard, "Which movement was born in Italy with Marinetti's manifesto?", "Futurism"),
    q_open!(Category::Art, Difficulty::Hard, "Which Baroque painter painted 'The Spinners'?", "Velázquez"),
    q_open!(Category::Art, Difficulty::Hard, "Which opera by Puccini takes place in Japan?", "Madama Butterfly"),

    // -- Taboo (closed) --
    q!(Category::Taboo, Difficulty::Easy, "It's long, rolls up and is used to measure. What is it?", 2, ["Ruler", "Compass", "Tape measure", "Set square"]),
    q!(Category::Taboo, Difficulty::Easy, "It's used to erase what you write with a pencil. What is it?", 0, ["Eraser", "Sharpener", "Ruler", "Pen"]),
    q!(Category::Taboo, Difficulty::Easy, "It has many pages and a cover. What is it?", 1, ["Mirror", "Book", "Ball", "Backpack"]),
    q!(Category::Taboo, Difficulty::Easy, "It's put on the window to keep the sun out. What is it?", 3, ["Carpet", "Blanket", "Towel", "Curtain"]),
    q!(Category::Taboo, Difficulty::Easy, "It's an animal that meows. What is it?", 0, ["Cat", "Dog", "Bird", "Rabbit"]),
    q!(Category::Taboo, Difficulty::Easy, "It gives light at night and turns on with a click. What is it?", 2, ["Fan", "Television", "Lamp", "Clock"]),
    q!(Category::Taboo, Difficulty::Easy, "It's used to sit and has a backrest. What is it?", 1, ["Table", "Chair", "Bed", "Stool"]),
    q!(Category::Taboo, Difficulty::Easy, "It's used to wash your hands. What is it?", 3, ["Shampoo", "Toothpaste", "Towel", "Soap"]),
    q!(Category::Taboo, Difficulty::Easy, "It's used to dry your hair. What is it?", 0, ["Hair dryer", "Comb", "Mirror", "Brush"]),
    q!(Category::Taboo, Difficulty::Easy, "It's put under your head to sleep. What is it?", 2, ["Blanket", "Sheet", "Pillow", "Mattress"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to squeeze juice from oranges. What is it?", 1, ["Blender", "Juicer", "Toaster", "Liquidizer"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to iron clothes. What is it?", 0, ["Iron", "Hanger", "Rope", "Clothesline"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to hang pictures on the wall. What is it?", 2, ["Screw", "Nut", "Nail", "Washer"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to keep money and documents. What is it?", 1, ["Backpack", "Wallet", "Handbag", "Suitcase"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used for the baby to sleep. What is it?", 3, ["Sofa", "Armchair", "Hammock", "Crib"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to cut the grass. What is it?", 0, ["Lawn mower", "Scythe", "Trimmer", "Watering can"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to eat soup. What is it?", 2, ["Fork", "Knife", "Spoon", "Chopstick"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to open bottles. What is it?", 1, ["Can opener", "Bottle opener", "Corkscrew", "Scissors"]),
    q!(Category::Taboo, Difficulty::Medium, "It's put on the table and is made of cloth. What is it?", 0, ["Tablecloth", "Napkin", "Apron", "Cloth"]),
    q!(Category::Taboo, Difficulty::Medium, "It's used to hang wet clothes. What is it?", 2, ["Hanger", "Iron", "Clothesline", "Wardrobe"]),
    q!(Category::Taboo, Difficulty::Hard, "It's used to measure the petrol you put in the car. What is it?", 1, ["Pressure gauge", "Petrol pump", "Taximeter", "Stopwatch"]),
    q!(Category::Taboo, Difficulty::Hard, "It's used in the theatre to project light. What is it?", 0, ["Spotlight", "Megaphone", "Speaker", "Microphone"]),
    q!(Category::Taboo, Difficulty::Hard, "Device that measures the speed of the car. What is it?", 2, ["Taximeter", "Odometer", "Speedometer", "Pressure gauge"]),
    q!(Category::Taboo, Difficulty::Hard, "It regulates the temperature of the oven. What is it?", 1, ["Thermometer", "Thermostat", "Barometer", "Hydrometer"]),
    q!(Category::Taboo, Difficulty::Hard, "It's used to polish and shine metals. What is it?", 3, ["Brush", "Paintbrush", "Scraper", "Sandpaper"]),
    q!(Category::Taboo, Difficulty::Hard, "Device that doctors look at in the ear. What is it?", 0, ["Otoscope", "Ophthalmoscope", "Laryngoscope", "Stethoscope"]),
    q!(Category::Taboo, Difficulty::Hard, "It measures the pressure of the car tyres. What is it?", 2, ["Barometer", "Thermometer", "Pressure gauge", "Anemometer"]),
    q!(Category::Taboo, Difficulty::Hard, "It records the electrical activity of the heart. What is it?", 1, ["Electroencephalograph", "Electrocardiograph", "Blood pressure monitor", "Glucometer"]),
    q!(Category::Taboo, Difficulty::Hard, "It's used to tune string instruments. What is it?", 3, ["Metronome", "Sheet music", "Bow", "Tuning fork"]),
    q!(Category::Taboo, Difficulty::Hard, "It measures the distance travelled by a ship. What is it?", 0, ["Log", "Sextant", "Compass", "Astrolabe"]),
    // -- Taboo (open) --
    q_open!(Category::Taboo, Difficulty::Easy, "It has four legs and says 'woof'. What is it?", "dog"),
    q_open!(Category::Taboo, Difficulty::Easy, "It's used to write on paper. What is it?", "pencil"),
    q_open!(Category::Taboo, Difficulty::Easy, "It's used to drink water. What is it?", "glass"),
    q_open!(Category::Taboo, Difficulty::Easy, "It hangs around your neck so you don't lose the keys. What is it?", "keychain"),
    q_open!(Category::Taboo, Difficulty::Easy, "It's used to store pencils. What is it?", "pencil case"),
    q_open!(Category::Taboo, Difficulty::Medium, "It's a device that heats the house in winter. What is it?", "heating"),
    q_open!(Category::Taboo, Difficulty::Medium, "It's used to gather leaves in the garden. What is it?", "rake"),
    q_open!(Category::Taboo, Difficulty::Medium, "It's an animal that says 'quack'. What is it?", "duck"),
    q_open!(Category::Taboo, Difficulty::Medium, "It's used to dry the bathroom floor. What is it?", "mop"),
    q_open!(Category::Taboo, Difficulty::Medium, "It's used to wash dishes by hand. What is it?", "scouring pad"),
    q_open!(Category::Taboo, Difficulty::Hard, "It measures the humidity of the air. What is it?", "hygrometer"),
    q_open!(Category::Taboo, Difficulty::Hard, "It heats substances with a flame in the lab. What is it?", "Bunsen burner"),
    q_open!(Category::Taboo, Difficulty::Hard, "It's used to see tiny objects magnified. What is it?", "microscope"),
    q_open!(Category::Taboo, Difficulty::Hard, "It measures the amount of fallen rain. What is it?", "rain gauge"),
    q_open!(Category::Taboo, Difficulty::Hard, "It indicates the direction of the wind. What is it?", "weather vane"),
];