//! Part 1 of the English question bank: Math and History.
use super::super::questions::{q, Category, Difficulty, Question};

pub static QUESTIONS_EN_1: &[Question] = &[
    // ================= Math =================
    // -- Easy --
    q!(Category::Math, Difficulty::Easy, "How much is 7 x 8?", 1, ["54", "56", "63", "48"]),
    q!(Category::Math, Difficulty::Easy, "What is the result of 15 + 27?", 0, ["42", "43", "41", "45"]),
    q!(Category::Math, Difficulty::Easy, "How many sides does a hexagon have?", 1, ["5", "6", "7", "8"]),
    q!(Category::Math, Difficulty::Easy, "How much is 100 / 4?", 2, ["20", "30", "25", "35"]),
    q!(Category::Math, Difficulty::Easy, "What is the double of 9?", 1, ["16", "18", "17", "19"]),
    q!(Category::Math, Difficulty::Easy, "How much is 12 x 3?", 3, ["32", "34", "38", "36"]),
    q!(Category::Math, Difficulty::Easy, "How many minutes are in an hour?", 0, ["60", "100", "30", "45"]),
    q!(Category::Math, Difficulty::Easy, "What number continues the series 2, 4, 6, ...?", 1, ["7", "8", "9", "10"]),
    q!(Category::Math, Difficulty::Easy, "How many vertices does a cube have?", 2, ["6", "12", "8", "4"]),
    q!(Category::Math, Difficulty::Easy, "How much is 3 + 4 x 2?", 1, ["14", "11", "10", "12"]),
    // -- Medium --
    q!(Category::Math, Difficulty::Medium, "If 3x = 21, what is the value of x?", 0, ["7", "6", "8", "9"]),
    q!(Category::Math, Difficulty::Medium, "How much is 25% of 200?", 2, ["40", "60", "50", "25"]),
    q!(Category::Math, Difficulty::Medium, "What is the area of a triangle with base 10 and height 6?", 1, ["60", "30", "15", "45"]),
    q!(Category::Math, Difficulty::Medium, "How much is 2 raised to the power of 5?", 2, ["25", "16", "32", "64"]),
    q!(Category::Math, Difficulty::Medium, "What is the perimeter of a square with side 7?", 1, ["49", "28", "14", "21"]),
    q!(Category::Math, Difficulty::Medium, "How much is 5/6 of 36?", 0, ["30", "25", "35", "31"]),
    q!(Category::Math, Difficulty::Medium, "Which of these numbers is prime?", 2, ["15", "21", "17", "27"]),
    q!(Category::Math, Difficulty::Medium, "How much is 9 x 9?", 1, ["72", "81", "89", "63"]),
    q!(Category::Math, Difficulty::Medium, "What is 10% of 350?", 0, ["35", "30", "45", "3,5"]),
    q!(Category::Math, Difficulty::Medium, "A triangle has angles of 60° and 70°. How many degrees is the third?", 0, ["50", "60", "40", "70"]),
    // -- Hard --
    q!(Category::Math, Difficulty::Hard, "What are the solutions of x^2 - 9 = 0?", 1, ["Only 9", "3 and -3", "Only 3", "3 and 9"]),
    q!(Category::Math, Difficulty::Hard, "If 2x + 5 = 17, what is the value of x?", 0, ["6", "5", "7", "4"]),
    q!(Category::Math, Difficulty::Hard, "What is the value of pi rounded to two decimal places?", 2, ["3,16", "3,12", "3,14", "3,18"]),
    q!(Category::Math, Difficulty::Hard, "How much is the square root of 144?", 3, ["11", "14", "13", "12"]),
    q!(Category::Math, Difficulty::Hard, "How many degrees do the angles of a triangle add up to?", 1, ["360", "180", "90", "270"]),
    q!(Category::Math, Difficulty::Hard, "How much is 15% of 80?", 0, ["12", "8", "15", "10"]),
    q!(Category::Math, Difficulty::Hard, "What number continues the series 1, 1, 2, 3, 5, 8, ...?", 1, ["12", "13", "11", "21"]),
    q!(Category::Math, Difficulty::Hard, "What is the area of a circle with radius 3 (π ≈ 3,14)?", 0, ["28,26", "18,84", "9,42", "31,4"]),
    q!(Category::Math, Difficulty::Hard, "How much is (-3) x (-4)?", 1, ["-12", "12", "7", "-7"]),
    q!(Category::Math, Difficulty::Hard, "Which fraction is equivalent to 1/2?", 1, ["2/5", "3/6", "1/4", "5/8"]),
    // -- Easy (mass batch) --
    q!(Category::Math, Difficulty::Easy, "How much is 6 x 9?", 3, ["48", "52", "56", "54"]),
    q!(Category::Math, Difficulty::Easy, "How much is 20 + 15?", 2, ["30", "40", "35", "25"]),
    q!(Category::Math, Difficulty::Easy, "How much is 50 - 17?", 1, ["43", "33", "37", "27"]),
    q!(Category::Math, Difficulty::Easy, "How much is 8 x 7?", 0, ["56", "64", "54", "48"]),
    q!(Category::Math, Difficulty::Easy, "How many tens does the number 80 have?", 0, ["8", "80", "10", "4"]),
    q!(Category::Math, Difficulty::Easy, "How many sides does a square have?", 2, ["3", "5", "4", "6"]),
    q!(Category::Math, Difficulty::Easy, "How much is 9 + 9 + 9?", 1, ["26", "27", "28", "30"]),
    q!(Category::Math, Difficulty::Easy, "How much is 100 - 100?", 1, ["100", "0", "10", "1"]),
    q!(Category::Math, Difficulty::Easy, "What is the number that comes after 99?", 0, ["100", "98", "90", "110"]),
    q!(Category::Math, Difficulty::Easy, "How much is 3 x 3?", 0, ["9", "6", "12", "8"]),
    q!(Category::Math, Difficulty::Easy, "How many fingers do you have on both hands?", 3, ["8", "9", "11", "10"]),
    q!(Category::Math, Difficulty::Easy, "How much is 40 / 8?", 2, ["6", "4", "5", "7"]),
    q!(Category::Math, Difficulty::Easy, "Which number is greater: 345 or 354?", 1, ["345", "354", "Equal", "Unknown"]),
    q!(Category::Math, Difficulty::Easy, "How much is 7 + 8?", 2, ["14", "16", "15", "17"]),
    q!(Category::Math, Difficulty::Easy, "How many hours are in a day?", 1, ["12", "24", "48", "60"]),
    q!(Category::Math, Difficulty::Easy, "How many days are in a week?", 2, ["5", "6", "7", "8"]),
    q!(Category::Math, Difficulty::Easy, "How much is 5 x 5?", 1, ["15", "25", "35", "45"]),
    q!(Category::Math, Difficulty::Easy, "What is half of 30?", 3, ["10", "20", "25", "15"]),
    q!(Category::Math, Difficulty::Easy, "How much is 11 + 11?", 2, ["20", "21", "22", "23"]),
    q!(Category::Math, Difficulty::Easy, "How much is 6 x 4?", 0, ["24", "28", "22", "26"]),
    q!(Category::Math, Difficulty::Easy, "Which number is smaller: 12 or 21?", 0, ["12", "21", "Equal", "Neither"]),
    q!(Category::Math, Difficulty::Easy, "How much is 30 / 3?", 3, ["5", "15", "20", "10"]),
    q!(Category::Math, Difficulty::Easy, "How many months are in a year?", 3, ["10", "11", "13", "12"]),
    q!(Category::Math, Difficulty::Easy, "How much is 2 + 2 x 3?", 0, ["8", "12", "10", "7"]),
    q!(Category::Math, Difficulty::Easy, "What is half of 100?", 2, ["25", "60", "50", "75"]),
    q!(Category::Math, Difficulty::Easy, "How much is 14 - 6?", 3, ["6", "7", "9", "8"]),
    q!(Category::Math, Difficulty::Easy, "How many sides does a pentagon have?", 0, ["5", "6", "4", "7"]),
    q!(Category::Math, Difficulty::Easy, "How much is 3 x 7?", 2, ["24", "20", "21", "27"]),
    q!(Category::Math, Difficulty::Easy, "What is the double of 15?", 1, ["25", "30", "35", "20"]),
    q!(Category::Math, Difficulty::Easy, "How much is 90 / 10?", 0, ["9", "8", "10", "11"]),
    q!(Category::Math, Difficulty::Easy, "How many minutes are in a quarter of an hour?", 2, ["30", "20", "15", "45"]),
    q!(Category::Math, Difficulty::Easy, "How much is 25 + 25?", 3, ["40", "45", "60", "50"]),
    q!(Category::Math, Difficulty::Easy, "What number comes before 50?", 2, ["51", "40", "49", "48"]),
    q!(Category::Math, Difficulty::Easy, "How much is 10 x 10?", 1, ["20", "100", "50", "200"]),
    q!(Category::Math, Difficulty::Easy, "How many centimeters are in a meter?", 3, ["10", "50", "1000", "100"]),
    q!(Category::Math, Difficulty::Easy, "How much is 6 + 6 + 6?", 0, ["18", "16", "20", "12"]),
    q!(Category::Math, Difficulty::Easy, "What is half of 46?", 2, ["20", "26", "23", "33"]),
    q!(Category::Math, Difficulty::Easy, "How much is 4 x 9?", 1, ["40", "36", "32", "44"]),
    q!(Category::Math, Difficulty::Easy, "How much is 75 - 25?", 0, ["50", "40", "60", "25"]),
    q!(Category::Math, Difficulty::Easy, "Which number is even: 7 or 8?", 1, ["7", "8", "Both", "Neither"]),
    // -- Medium (mass batch) --
    q!(Category::Math, Difficulty::Medium, "How much is 20% of 150?", 1, ["20", "30", "40", "25"]),
    q!(Category::Math, Difficulty::Medium, "What is the area of a rectangle of 8 x 5?", 2, ["26", "13", "40", "80"]),
    q!(Category::Math, Difficulty::Medium, "If 4x - 8 = 0, what is the value of x?", 0, ["2", "4", "8", "-2"]),
    q!(Category::Math, Difficulty::Medium, "How much is 7 squared?", 2, ["42", "56", "49", "63"]),
    q!(Category::Math, Difficulty::Medium, "What is the least common multiple of 4 and 6?", 1, ["12", "24", "6", "48"]),
    q!(Category::Math, Difficulty::Medium, "How much is 3/4 + 1/4?", 0, ["1", "3/8", "4/8", "2"]),
    q!(Category::Math, Difficulty::Medium, "How many degrees does a right angle measure?", 1, ["45", "90", "180", "360"]),
    q!(Category::Math, Difficulty::Medium, "What is the perimeter of an equilateral triangle with side 6?", 2, ["12", "20", "18", "24"]),
    q!(Category::Math, Difficulty::Medium, "How much is 1,5 x 2?", 1, ["2,5", "3", "3,5", "4"]),
    q!(Category::Math, Difficulty::Medium, "What is 50% of 78?", 2, ["38", "19,5", "39", "78"]),
    q!(Category::Math, Difficulty::Medium, "If x + 7 = 15, what is the value of x?", 0, ["8", "7", "9", "6"]),
    q!(Category::Math, Difficulty::Medium, "How much is 2^6 (2 raised to the power of 6)?", 3, ["32", "48", "36", "64"]),
    q!(Category::Math, Difficulty::Medium, "What is the area of a square with side 9?", 2, ["36", "72", "81", "18"]),
    q!(Category::Math, Difficulty::Medium, "How much is 5/8 of 64?", 1, ["32", "40", "36", "48"]),
    q!(Category::Math, Difficulty::Medium, "Which of these numbers is not a multiple of 3?", 2, ["18", "27", "25", "36"]),
    q!(Category::Math, Difficulty::Medium, "How much is 0,25 expressed as a fraction?", 0, ["1/4", "1/2", "2/5", "3/4"]),
    q!(Category::Math, Difficulty::Medium, "What is the greatest common divisor of 12 and 18?", 1, ["3", "6", "9", "2"]),
    q!(Category::Math, Difficulty::Medium, "How much is 3 x 4 + 2?", 2, ["18", "10", "14", "20"]),
    q!(Category::Math, Difficulty::Medium, "How much is 15% of 200?", 3, ["20", "25", "35", "30"]),
    q!(Category::Math, Difficulty::Medium, "What number is 5^3?", 1, ["15", "125", "25", "75"]),
    q!(Category::Math, Difficulty::Medium, "What is the median of 3, 5, 7, 9, 11?", 0, ["7", "5", "9", "6"]),
    q!(Category::Math, Difficulty::Medium, "How much is 2/3 of 90?", 2, ["30", "45", "60", "75"]),
    q!(Category::Math, Difficulty::Medium, "How many degrees does a straight angle measure?", 1, ["90", "180", "270", "360"]),
    q!(Category::Math, Difficulty::Medium, "What is the perimeter of a rectangle of 10 x 4?", 0, ["28", "40", "14", "80"]),
    q!(Category::Math, Difficulty::Medium, "How much is 7/10 + 3/10?", 1, ["10/20", "1", "2/10", "0,7"]),
    q!(Category::Math, Difficulty::Medium, "If 2x = 34, what is the value of x?", 3, ["16", "18", "12", "17"]),
    q!(Category::Math, Difficulty::Medium, "What is 30% of 120?", 2, ["30", "24", "36", "40"]),
    q!(Category::Math, Difficulty::Medium, "How much is 8 x 0,5?", 0, ["4", "8", "2", "16"]),
    q!(Category::Math, Difficulty::Medium, "Which fraction is greater: 3/4 or 2/3?", 0, ["3/4", "2/3", "Equal", "Cannot be known"]),
    q!(Category::Math, Difficulty::Medium, "How much is 10^4?", 2, ["400", "1.000", "10.000", "100.000"]),
    q!(Category::Math, Difficulty::Medium, "What is the volume of a cube with edge 3?", 3, ["9", "18", "12", "27"]),
    q!(Category::Math, Difficulty::Medium, "How much is 12,5 + 7,5?", 1, ["19", "20", "21", "18"]),
    q!(Category::Math, Difficulty::Medium, "What is the next number in the series 5, 10, 20, 40, ...?", 0, ["80", "60", "70", "100"]),
    q!(Category::Math, Difficulty::Medium, "How many degrees do the angles of a square add up to?", 3, ["180", "270", "90", "360"]),
    q!(Category::Math, Difficulty::Medium, "How much is 6/2 x 3?", 1, ["6", "9", "12", "18"]),
    q!(Category::Math, Difficulty::Medium, "What is 75% of 80?", 2, ["40", "50", "60", "70"]),
    q!(Category::Math, Difficulty::Medium, "How much is 2 x 3 x 4?", 1, ["20", "24", "28", "32"]),
    q!(Category::Math, Difficulty::Medium, "What is the smallest prime number?", 2, ["0", "1", "2", "3"]),
    q!(Category::Math, Difficulty::Medium, "How much is 100 / 0,5?", 3, ["50", "100", "500", "200"]),
    q!(Category::Math, Difficulty::Medium, "What is the area of a triangle with base 12 and height 5?", 2, ["60", "17", "30", "15"]),
    // -- Hard (mass batch) --
    q!(Category::Math, Difficulty::Hard, "How much is the square root of 225?", 1, ["12", "15", "25", "18"]),
    q!(Category::Math, Difficulty::Hard, "If x^2 = 81, what are the solutions?", 2, ["Only 9", "Only -9", "9 and -9", "9 and 3"]),
    q!(Category::Math, Difficulty::Hard, "How much is 12% of 250?", 0, ["30", "25", "35", "40"]),
    q!(Category::Math, Difficulty::Hard, "What is the slope of the line y = 3x + 2?", 1, ["2", "3", "5", "-3"]),
    q!(Category::Math, Difficulty::Hard, "How much is log10(1000)?", 2, ["1", "2", "3", "10"]),
    q!(Category::Math, Difficulty::Hard, "What is the area of a circle with radius 5 (π ≈ 3,14)?", 3, ["31,4", "62,8", "157", "78,5"]),
    q!(Category::Math, Difficulty::Hard, "How much is 7! (factorial of 7)?", 1, ["720", "5040", "40320", "2520"]),
    q!(Category::Math, Difficulty::Hard, "What is the sine of 30 degrees?", 2, ["1", "√3/2", "1/2", "√2/2"]),
    q!(Category::Math, Difficulty::Hard, "If 3x + 6 = 2x + 10, what is the value of x?", 0, ["4", "6", "2", "-4"]),
    q!(Category::Math, Difficulty::Hard, "How many combinations of 2 elements can be made from 5?", 1, ["5", "10", "20", "15"]),
    q!(Category::Math, Difficulty::Hard, "What is the volume of a sphere with radius 3 (π ≈ 3,14)?", 1, ["37,68", "113,04", "28,26", "75,36"]),
    q!(Category::Math, Difficulty::Hard, "What is the result of 2^10?", 2, ["512", "2048", "1024", "256"]),
    q!(Category::Math, Difficulty::Hard, "What is the sum of the first 100 natural numbers?", 1, ["5000", "5050", "5100", "5150"]),
    q!(Category::Math, Difficulty::Hard, "How much is 0,2 x 0,5?", 0, ["0,1", "0,7", "1", "0,25"]),
    q!(Category::Math, Difficulty::Hard, "What is the derivative of x^3?", 1, ["x^2", "3x^2", "3x", "x^4/4"]),
    q!(Category::Math, Difficulty::Hard, "How much is (-2)^3?", 2, ["8", "6", "-8", "-6"]),
    q!(Category::Math, Difficulty::Hard, "What is the mean of 4, 8, 12 and 16?", 3, ["8", "12", "9", "10"]),
    q!(Category::Math, Difficulty::Hard, "How much is 5/6 - 1/2?", 1, ["1/6", "1/3", "2/6", "4/6"]),
    q!(Category::Math, Difficulty::Hard, "What is the value of e rounded to two decimal places?", 0, ["2,72", "2,71", "3,14", "1,61"]),
    q!(Category::Math, Difficulty::Hard, "How many faces does an icosahedron have?", 1, ["12", "20", "24", "30"]),
    q!(Category::Math, Difficulty::Hard, "What is 40% of 250?", 2, ["60", "80", "100", "120"]),
    q!(Category::Math, Difficulty::Hard, "If the hypotenuse of a right triangle measures 13 and one leg measures 5, how long is the other leg?", 3, ["10", "8", "14", "12"]),
    q!(Category::Math, Difficulty::Hard, "How much is the cube root of 27?", 1, ["9", "3", "6", "8"]),
    q!(Category::Math, Difficulty::Hard, "What is the general term of the series 3, 6, 12, 24, ...?", 1, ["3n", "3 x 2^(n-1)", "n + 3", "n^2"]),
    q!(Category::Math, Difficulty::Hard, "How much is 1/3 + 1/6?", 2, ["1/9", "2/9", "1/2", "3/6"]),
    q!(Category::Math, Difficulty::Hard, "What is the range of the sample 2, 5, 9, 12, 20?", 0, ["18", "12", "20", "10"]),
    q!(Category::Math, Difficulty::Hard, "How much is 15% of 15?", 1, ["1,5", "2,25", "3", "2,5"]),
    q!(Category::Math, Difficulty::Hard, "What is the solution of the equation 2(x - 3) = 10?", 3, ["5", "6", "7", "8"]),
    q!(Category::Math, Difficulty::Hard, "How many degrees does a radian measure approximately?", 2, ["45", "90", "57,3", "30"]),
    q!(Category::Math, Difficulty::Hard, "What is the distance between the points (0, 0) and (3, 4)?", 1, ["4", "5", "7", "6"]),
    q!(Category::Math, Difficulty::Hard, "How much is 3^3 + 2^3?", 0, ["35", "29", "33", "27"]),
    q!(Category::Math, Difficulty::Hard, "What is the probability of rolling a 6 on a die?", 1, ["1/2", "1/6", "1/3", "5/6"]),
    q!(Category::Math, Difficulty::Hard, "How much is the weighted mean of 2 (weight 1) and 8 (weight 3)?", 2, ["5", "6", "6,5", "7"]),
    q!(Category::Math, Difficulty::Hard, "What is the largest 3-digit number?", 3, ["999", "998", "900", "990"]),
    q!(Category::Math, Difficulty::Hard, "How much is 0,1 + 0,2 + 0,3?", 1, ["0,5", "0,6", "0,4", "1"]),
    q!(Category::Math, Difficulty::Hard, "What is the multiplicative inverse of 4?", 2, ["-4", "0,4", "1/4", "4/1"]),
    q!(Category::Math, Difficulty::Hard, "How many permutations does the word ABC have?", 0, ["6", "3", "9", "12"]),
    q!(Category::Math, Difficulty::Hard, "What is the square of 1,5?", 1, ["2", "2,25", "3", "2,5"]),
    q!(Category::Math, Difficulty::Hard, "How much is 10 - 3 x 2 + 4?", 3, ["10", "14", "6", "8"]),
    q!(Category::Math, Difficulty::Hard, "What is the solution of x/2 + 3 = 7?", 1, ["6", "8", "4", "10"]),
    // ================= History =================
    // -- Easy --
    q!(Category::History, Difficulty::Easy, "In what year did Christopher Columbus arrive in America?", 1, ["1500", "1492", "1498", "1485"]),
    q!(Category::History, Difficulty::Easy, "Which civilization built the pyramids of Egypt?", 2, ["The Roman", "The Greek", "The Egyptian", "The Mayan"]),
    q!(Category::History, Difficulty::Easy, "Who painted the Mona Lisa?", 1, ["Michelangelo", "Leonardo da Vinci", "Pablo Picasso", "Vincent van Gogh"]),
    q!(Category::History, Difficulty::Easy, "What symbols did the Romans use to write numbers?", 0, ["Roman numerals", "Arabic numerals", "Hieroglyphics", "Cuneiform"]),
    q!(Category::History, Difficulty::Easy, "In which city is the Eiffel Tower?", 2, ["London", "Rome", "Paris", "Madrid"]),
    q!(Category::History, Difficulty::Easy, "Who discovered America in 1492?", 1, ["Magellan", "Christopher Columbus", "Elcano", "Pizarro"]),
    q!(Category::History, Difficulty::Easy, "What famous amphitheater is in Rome?", 1, ["The Parthenon", "The Colosseum", "The Aqueduct", "The Pantheon"]),
    q!(Category::History, Difficulty::Easy, "What is the writing of ancient Egypt called?", 1, ["Cuneiform", "Hieroglyphics", "Runic", "Braille"]),
    q!(Category::History, Difficulty::Easy, "Who was the first emperor of Rome?", 1, ["Julius Caesar", "Augustus", "Nero", "Trajan"]),
    q!(Category::History, Difficulty::Easy, "Which people built Machu Picchu?", 2, ["The Aztecs", "The Mayans", "The Incas", "The Olmecs"]),
    // -- Medium --
    q!(Category::History, Difficulty::Medium, "In what year did World War II begin?", 1, ["1936", "1939", "1945", "1933"]),
    q!(Category::History, Difficulty::Medium, "Which empire built the Colosseum of Rome?", 2, ["The Greek", "The Persian", "The Roman", "The Ottoman"]),
    q!(Category::History, Difficulty::Medium, "Who was the first president of the United States?", 1, ["Abraham Lincoln", "George Washington", "Thomas Jefferson", "Benjamin Franklin"]),
    q!(Category::History, Difficulty::Medium, "In what year did World War II end?", 0, ["1945", "1939", "1942", "1950"]),
    q!(Category::History, Difficulty::Medium, "Which expedition completed the first voyage around the world?", 0, ["Magellan and Elcano", "Columbus", "Vasco da Gama", "Marco Polo"]),
    q!(Category::History, Difficulty::Medium, "In which century did Isabella the Catholic reign?", 2, ["XII", "XIV", "XV", "XVI"]),
    q!(Category::History, Difficulty::Medium, "Which civilization inhabited present-day Mexico before the arrival of the Spanish?", 1, ["The Mayans", "The Aztecs", "The Incas", "The Chibchas"]),
    q!(Category::History, Difficulty::Medium, "Who wrote the Iliad?", 1, ["Socrates", "Homer", "Virgil", "Plato"]),
    q!(Category::History, Difficulty::Medium, "Which empire fell in 1453 with the fall of Constantinople?", 0, ["The Byzantine", "The Roman", "The Persian", "The Egyptian"]),
    q!(Category::History, Difficulty::Medium, "Which Carthaginian general crossed the Alps with elephants?", 0, ["Hannibal", "Scipio", "Julius Caesar", "Attila"]),
    // -- Hard --
    q!(Category::History, Difficulty::Hard, "In what year did the Berlin Wall fall?", 2, ["1991", "1985", "1989", "1993"]),
    q!(Category::History, Difficulty::Hard, "Which battle ended Napoleon's empire?", 2, ["Bailén", "Trafalgar", "Waterloo", "Lepanto"]),
    q!(Category::History, Difficulty::Hard, "Which treaty ended the Hundred Years' War?", 2, ["The Treaty of Versailles", "The Treaty of Tordesillas", "The Treaty of Troyes", "The Treaty of Utrecht"]),
    q!(Category::History, Difficulty::Hard, "In what year did the French Revolution begin?", 0, ["1789", "1804", "1776", "1812"]),
    q!(Category::History, Difficulty::Hard, "Which emperor divided the Roman Empire in two?", 1, ["Constantine", "Theodosius", "Nero", "Hadrian"]),
    q!(Category::History, Difficulty::Hard, "Who was the first president of the Spanish Second Republic?", 1, ["Manuel Azaña", "Niceto Alcalá-Zamora", "Primo de Rivera", "Franco"]),
    q!(Category::History, Difficulty::Hard, "Which Spanish king was nicknamed 'the Prudent'?", 1, ["Charles I", "Philip II", "Philip III", "Charles II"]),
    q!(Category::History, Difficulty::Hard, "In what year did humans reach the Moon?", 1, ["1965", "1969", "1972", "1959"]),
    q!(Category::History, Difficulty::Hard, "Which geographical feature separated Hispania from Gaul?", 1, ["The Alps", "The Pyrenees", "The Ebro", "The Duero"]),
    q!(Category::History, Difficulty::Hard, "Who was the first woman to win a Nobel Prize?", 0, ["Marie Curie", "Irène Joliot-Curie", "Rosalind Franklin", "Ada Lovelace"]),
    // -- Easy (mass batch) --
    q!(Category::History, Difficulty::Easy, "What is the name of the city where the pharaohs of Egypt lived?", 1, ["Athens", "Memphis", "Rome", "Babylon"]),
    q!(Category::History, Difficulty::Easy, "Who was the first man to step on the Moon?", 2, ["Buzz Aldrin", "Yuri Gagarin", "Neil Armstrong", "Michael Collins"]),
    q!(Category::History, Difficulty::Easy, "Which war lasted 100 years according to its popular name?", 1, ["World War I", "The Hundred Years' War", "The Cold War", "The Trojan War"]),
    q!(Category::History, Difficulty::Easy, "In which country was paper invented?", 2, ["Egypt", "India", "China", "Greece"]),
    q!(Category::History, Difficulty::Easy, "What is the name of the ship in which Columbus arrived in America?", 0, ["The Santa María", "The Pinta", "The Niña", "The Victoria"]),
    q!(Category::History, Difficulty::Easy, "Which civilization created the 365-day calendar?", 2, ["The Greek", "The Roman", "The Egyptian", "The Celtic"]),
    q!(Category::History, Difficulty::Easy, "Who was the most famous Viking leader?", 1, ["Ragnar", "Leif Erikson", "Rollo", "Erik the Red"]),
    q!(Category::History, Difficulty::Easy, "In which country is the Great Wall located?", 2, ["Japan", "Mongolia", "China", "Korea"]),
    q!(Category::History, Difficulty::Easy, "Which Roman emperor built a famous amphitheater?", 1, ["Augustus", "Vespasian", "Caligula", "Nero"]),
    q!(Category::History, Difficulty::Easy, "What is the name of the famous Arthurian king of the sword Excalibur?", 2, ["Merlin", "Lancelot", "Arthur", "Gawain"]),
    q!(Category::History, Difficulty::Easy, "Which people built Stonehenge?", 1, ["The Romans", "The Celts", "The Egyptians", "The Greeks"]),
    q!(Category::History, Difficulty::Easy, "Who was famous for her resistance against the Romans in Britain?", 2, ["Cleopatra", "Joan of Arc", "Boudica", "Zenobia"]),
    q!(Category::History, Difficulty::Easy, "Which famous explorer reached the Indies by rounding Africa?", 0, ["Vasco da Gama", "Magellan", "Columbus", "Pizarro"]),
    q!(Category::History, Difficulty::Easy, "In which city was the Roman Empire founded?", 1, ["Athens", "Rome", "Carthage", "Constantinople"]),
    q!(Category::History, Difficulty::Easy, "What did the Egyptians write on the walls of the temples?", 2, ["Runes", "Alphabet", "Hieroglyphics", "Cuneiform"]),
    q!(Category::History, Difficulty::Easy, "Who painted the Sistine Chapel?", 3, ["Raphael", "Da Vinci", "Titian", "Michelangelo"]),
    q!(Category::History, Difficulty::Easy, "Which country won the first soccer World Cup in 1930?", 1, ["Brazil", "Uruguay", "Argentina", "Italy"]),
    q!(Category::History, Difficulty::Easy, "What is the name of the famous leaning tower in Italy?", 0, ["Leaning Tower of Pisa", "Eiffel Tower", "Big Ben", "Colosseum"]),
    q!(Category::History, Difficulty::Easy, "Which Spanish queen sponsored Columbus's voyage?", 2, ["Isabella of England", "Mary Tudor", "Isabella the Catholic", "Joanna the Mad"]),
    q!(Category::History, Difficulty::Easy, "Who was the leader of Nazi Germany?", 1, ["Mussolini", "Hitler", "Franco", "Stalin"]),
    q!(Category::History, Difficulty::Easy, "What did Gutenberg invent in the 15th century?", 1, ["The compass", "The printing press", "The telescope", "Gunpowder"]),
    q!(Category::History, Difficulty::Easy, "On which continent is Egypt?", 0, ["Africa", "Asia", "Europe", "America"]),
    q!(Category::History, Difficulty::Easy, "Which famous Roman city was buried by Vesuvius?", 2, ["Rome", "Naples", "Pompeii", "Herculaneum"]),
    q!(Category::History, Difficulty::Easy, "Who was the leader of the Cuban Revolution?", 1, ["Che Guevara", "Fidel Castro", "Perón", "Allende"]),
    q!(Category::History, Difficulty::Easy, "Which Egyptian monument is a great sphinx?", 1, ["The Temple of Karnak", "The Great Sphinx of Giza", "The obelisk", "The Pantheon"]),
    q!(Category::History, Difficulty::Easy, "In what year was the US Declaration of Independence signed?", 3, ["1800", "1792", "1770", "1776"]),
    q!(Category::History, Difficulty::Easy, "What is the first writing system of Mesopotamia called?", 2, ["Hieroglyphic", "Phoenician alphabet", "Cuneiform", "Runes"]),
    q!(Category::History, Difficulty::Easy, "Which animal did knights use to fight in the Middle Ages?", 1, ["The bull", "The horse", "The elephant", "The camel"]),
    q!(Category::History, Difficulty::Easy, "Who was the last king of France before the Revolution?", 2, ["Napoleon", "Louis XVI", "Charles IX", "Henry IV"]),
    q!(Category::History, Difficulty::Easy, "Which famous naval battle did Spain win against the Turks in 1571?", 0, ["Lepanto", "Trafalgar", "Invincible Armada", "Salamis"]),
    q!(Category::History, Difficulty::Easy, "Which civilization used zero in mathematics?", 1, ["The Romans", "The Mayans", "The Vikings", "The Celts"]),
    q!(Category::History, Difficulty::Easy, "Who founded the Mongol Empire?", 2, ["Kublai Khan", "Tamerlane", "Genghis Khan", "Attila"]),
    q!(Category::History, Difficulty::Easy, "In which country was the first subway in the world built?", 3, ["Paris", "New York", "Madrid", "London"]),
    q!(Category::History, Difficulty::Easy, "Which famous navigator sailed around the world by ship?", 1, ["Columbus", "Magellan", "Vasco da Gama", "Amerigo Vespucci"]),
    q!(Category::History, Difficulty::Easy, "What name does the famous wall of China receive?", 2, ["Hadrian's Wall", "Berlin Wall", "Great Wall", "Wailing Wall"]),
    q!(Category::History, Difficulty::Easy, "Who was the first famous empress of China?", 1, ["Wu Zetian", "Cixi", "Sissi", "Isabella II"]),
    q!(Category::History, Difficulty::Easy, "Which people inhabited the Iberian Peninsula before the Romans?", 2, ["The Vikings", "The Celts", "The Iberians", "The Persians"]),
    q!(Category::History, Difficulty::Easy, "What famous statue is in the port of New York?", 1, ["The David", "The Venus", "The Statue of Liberty", "The Moses"]),
    q!(Category::History, Difficulty::Easy, "In what year did World War I begin?", 3, ["1918", "1912", "1916", "1914"]),
    q!(Category::History, Difficulty::Easy, "Which Spanish king was nicknamed 'the Bewitched'?", 0, ["Charles II", "Philip II", "Charles I", "Philip IV"]),
    // -- Medium (mass batch) --
    q!(Category::History, Difficulty::Medium, "In what year did Constantinople fall into Ottoman hands?", 2, ["1400", "1492", "1453", "1519"]),
    q!(Category::History, Difficulty::Medium, "Which treaty divided the New World between Spain and Portugal?", 1, ["The Treaty of Versailles", "The Treaty of Tordesillas", "The Treaty of Utrecht", "The Treaty of Paris"]),
    q!(Category::History, Difficulty::Medium, "Who was the last pharaoh of Egypt?", 2, ["Tutankhamun", "Ramses II", "Cleopatra", "Nefertiti"]),
    q!(Category::History, Difficulty::Medium, "Which emperor built the Colosseum?", 0, ["Vespasian", "Julius Caesar", "Hadrian", "Constantine"]),
    q!(Category::History, Difficulty::Medium, "In what year did the Industrial Revolution begin?", 1, ["1600", "1760", "1850", "1900"]),
    q!(Category::History, Difficulty::Medium, "Which country launched the first artificial satellite, the Sputnik?", 1, ["USA", "The USSR", "China", "Japan"]),
    q!(Category::History, Difficulty::Medium, "Which English king signed the Magna Carta in 1215?", 2, ["Richard I", "Henry III", "John Lackland", "Edward I"]),
    q!(Category::History, Difficulty::Medium, "Which civilization invented the wheel more than 5,000 years ago?", 3, ["The Egyptians", "The Greeks", "The Romans", "The Sumerians"]),
    q!(Category::History, Difficulty::Medium, "Who was the first chancellor of unified Germany?", 1, ["Hindenburg", "Bismarck", "Hitler", "Adenauer"]),
    q!(Category::History, Difficulty::Medium, "Which explorer discovered the strait that bears his name in southern America?", 2, ["Columbus", "Elcano", "Magellan", "Pizarro"]),
    q!(Category::History, Difficulty::Medium, "In what year was the Peace of Westphalia signed?", 0, ["1648", "1713", "1815", "1618"]),
    q!(Category::History, Difficulty::Medium, "Which female pharaoh ruled Egypt as a woman?", 1, ["Nefertiti", "Hatshepsut", "Cleopatra", "Isis"]),
    q!(Category::History, Difficulty::Medium, "Which city was the capital of the Aztec Empire?", 2, ["Cuzco", "Chichén Itzá", "Tenochtitlan", "Tikal"]),
    q!(Category::History, Difficulty::Medium, "Who wrote 'The Prince'?", 1, ["Rousseau", "Machiavelli", "Voltaire", "Montesquieu"]),
    q!(Category::History, Difficulty::Medium, "Which naval battle of 1805 did Nelson win?", 0, ["Trafalgar", "Lepanto", "Jutland", "Salamis"]),
    q!(Category::History, Difficulty::Medium, "In what year was the First Spanish Republic proclaimed?", 2, ["1868", "1875", "1873", "1898"]),
    q!(Category::History, Difficulty::Medium, "Which empire had its capital in Cuzco?", 1, ["The Aztec", "The Inca", "The Maya", "The Olmec"]),
    q!(Category::History, Difficulty::Medium, "Which river crosses Rome?", 2, ["The Po", "The Arno", "The Tiber", "The Tagus"]),
    q!(Category::History, Difficulty::Medium, "Who was the first emperor of China?", 1, ["Confucius", "Qin Shi Huang", "Mao", "Sun Tzu"]),
    q!(Category::History, Difficulty::Medium, "Which famous battle of 1066 changed the fate of England?", 2, ["Agincourt", "Crécy", "Hastings", "Bosworth"]),
    q!(Category::History, Difficulty::Medium, "In what year did man reach the Moon?", 3, ["1965", "1972", "1959", "1969"]),
    q!(Category::History, Difficulty::Medium, "Which Indian leader fought for independence without violence?", 1, ["Nehru", "Gandhi", "Bose", "Tilak"]),
    q!(Category::History, Difficulty::Medium, "Which civilization sculpted the colossal stone heads?", 2, ["The Aztecs", "The Mayans", "The Olmecs", "The Incas"]),
    q!(Category::History, Difficulty::Medium, "Which French king built the palace of Versailles?", 0, ["Louis XIV", "Louis XVI", "Napoleon", "Francis I"]),
    q!(Category::History, Difficulty::Medium, "In what year did the 13 US colonies become independent?", 1, ["1770", "1776", "1789", "1800"]),
    q!(Category::History, Difficulty::Medium, "Which famous nurse worked in the hospitals of the Crimean War?", 1, ["Marie Curie", "Florence Nightingale", "Rosalind Franklin", "Anne Boleyn"]),
    q!(Category::History, Difficulty::Medium, "Which empire had Constantinople as its capital?", 0, ["The Byzantine", "The Roman", "The Persian", "The Ottoman"]),
    q!(Category::History, Difficulty::Medium, "Who conquered the Inca Empire?", 1, ["Cortés", "Pizarro", "Balboa", "Orellana"]),
    q!(Category::History, Difficulty::Medium, "Which treaty ended the Spanish War of Succession?", 2, ["The Treaty of Tordesillas", "The Treaty of Versailles", "The Treaty of Utrecht", "The Treaty of Vienna"]),
    q!(Category::History, Difficulty::Medium, "In what year was the UN founded?", 3, ["1919", "1940", "1950", "1945"]),
    q!(Category::History, Difficulty::Medium, "Which Egyptian leader built the Aswan Dam?", 1, ["Farouk", "Nasser", "Sadat", "Mubarak"]),
    q!(Category::History, Difficulty::Medium, "Which civilization lived in what is now Peru?", 2, ["Aztecs", "Mayans", "Incas", "Toltecs"]),
    q!(Category::History, Difficulty::Medium, "Which queen of England reigned 63 years in the 19th century?", 1, ["Elizabeth I", "Victoria", "Anne", "Elizabeth II"]),
    q!(Category::History, Difficulty::Medium, "Which barbarian people sacked Rome in the year 410?", 2, ["The Huns", "The Vandals", "The Visigoths", "The Ostrogoths"]),
    q!(Category::History, Difficulty::Medium, "In what year was the Suez Canal built?", 3, ["1820", "1900", "1850", "1869"]),
    q!(Category::History, Difficulty::Medium, "Who was the leader of Mexico's independence?", 1, ["Bolívar", "Hidalgo", "San Martín", "Iturbide"]),
    q!(Category::History, Difficulty::Medium, "Which Greek philosopher was the teacher of Alexander the Great?", 2, ["Socrates", "Plato", "Aristotle", "Heraclitus"]),
    q!(Category::History, Difficulty::Medium, "Which disease killed millions in Europe in the Middle Ages?", 1, ["The flu", "The Black Death", "Cholera", "Smallpox"]),
    q!(Category::History, Difficulty::Medium, "Which famous battle of 1815 definitively defeated Napoleon?", 2, ["Austerlitz", "Moscow", "Waterloo", "Bailén"]),
    q!(Category::History, Difficulty::Medium, "In what year was America discovered?", 3, ["1500", "1485", "1498", "1492"]),
    // -- Hard (mass batch) --
    q!(Category::History, Difficulty::Hard, "Which Byzantine emperor reconquered Rome in the 6th century?", 1, ["Constantine", "Justinian", "Heraclius", "Theodosius"]),
    q!(Category::History, Difficulty::Hard, "In what year was the Council of Trent first held?", 2, ["1517", "1530", "1545", "1563"]),
    q!(Category::History, Difficulty::Hard, "Which treaty of 1815 reorganized Europe after Napoleon?", 1, ["The Congress of Vienna", "The Treaty of Versailles", "The Treaty of Utrecht", "The Treaty of Berlin"]),
    q!(Category::History, Difficulty::Hard, "Which pharaoh built the Great Pyramid of Giza?", 0, ["Khufu", "Khafre", "Menkaure", "Tutankhamun"]),
    q!(Category::History, Difficulty::Hard, "Which Carthaginian general won the Battle of Cannae?", 1, ["Scipio", "Hannibal", "Hamilcar", "Hasdrubal"]),
    q!(Category::History, Difficulty::Hard, "In what year was the Treaty of Tordesillas signed?", 2, ["1492", "1500", "1494", "1488"]),
    q!(Category::History, Difficulty::Hard, "Which queen of Egypt allied with Mark Antony?", 3, ["Nefertiti", "Hatshepsut", "Isis", "Cleopatra"]),
    q!(Category::History, Difficulty::Hard, "Which Roman emperor legalized Christianity?", 1, ["Diocletian", "Constantine", "Julian", "Nero"]),
    q!(Category::History, Difficulty::Hard, "Which battle of 732 stopped the Muslim expansion in Europe?", 2, ["Lepanto", "Poitiers", "Tours", "Covadonga"]),
    q!(Category::History, Difficulty::Hard, "Which famous route connected Europe with Asia through the Mongols?", 1, ["The Incense Route", "The Silk Road", "The Silver Route", "The Amber Route"]),
    q!(Category::History, Difficulty::Hard, "In what year did the October Russian Revolution take place?", 2, ["1905", "1914", "1917", "1923"]),
    q!(Category::History, Difficulty::Hard, "Which archaeologist discovered the tomb of Tutankhamun?", 1, ["Champollion", "Howard Carter", "Schliemann", "Evans"]),
    q!(Category::History, Difficulty::Hard, "Which Roman emperor divided the empire in two in 395?", 0, ["Theodosius", "Constantine", "Marcus Aurelius", "Diocletian"]),
    q!(Category::History, Difficulty::Hard, "Which war pitted Castile against Portugal in the 14th century?", 2, ["The War of the Communities", "The War of the Two Pedros", "The War of Succession", "The War of Granada"]),
    q!(Category::History, Difficulty::Hard, "Who was the first president of the Weimar Republic?", 1, ["Hindenburg", "Ebert", "Bismarck", "Stresemann"]),
    q!(Category::History, Difficulty::Hard, "In what year was Germany unified under the Empire of William I?", 2, ["1848", "1866", "1871", "1918"]),
    q!(Category::History, Difficulty::Hard, "Which Portuguese explorer was the first to round the Cape of Good Hope?", 1, ["Vasco da Gama", "Bartolomeu Dias", "Magellan", "Cabral"]),
    q!(Category::History, Difficulty::Hard, "Which city was destroyed by the eruption of Vesuvius in the year 79?", 2, ["Naples", "Capri", "Pompeii", "Rome"]),
    q!(Category::History, Difficulty::Hard, "Which Spanish king signed the Nueva Planta Decrees?", 1, ["Charles II", "Philip V", "Philip IV", "Charles III"]),
    q!(Category::History, Difficulty::Hard, "In what year did Brazil become independent from Portugal?", 2, ["1808", "1815", "1822", "1831"]),
    q!(Category::History, Difficulty::Hard, "Which Japanese emperor reigned during World War II?", 1, ["Meiji", "Hirohito", "Taisho", "Akihito"]),
    q!(Category::History, Difficulty::Hard, "Which civilization created the city of Teotihuacan?", 2, ["The Aztecs", "The Olmecs", "The Teotihuacans", "The Zapotecs"]),
    q!(Category::History, Difficulty::Hard, "Which treaty of 1919 ended World War I?", 1, ["The Treaty of Brest-Litovsk", "The Treaty of Versailles", "The Treaty of Trianon", "The Treaty of Saint-Germain"]),
    q!(Category::History, Difficulty::Hard, "Which king of Spain was overthrown in the Revolution of 1868?", 2, ["Ferdinand VII", "Charles IV", "Isabella II", "Amadeus I"]),
    q!(Category::History, Difficulty::Hard, "Who was the strategist of the Spanish guerrilla war against Napoleon?", 1, ["El Empecinado", "Espoz y Mina", "Viriat", "Don Pelayo"]),
    q!(Category::History, Difficulty::Hard, "In what year was Julius Caesar assassinated?", 2, ["31 BC", "27 BC", "44 BC", "54 BC"]),
    q!(Category::History, Difficulty::Hard, "Which medieval city was the center of the Islamic world and of learning?", 1, ["Cairo", "Baghdad", "Córdoba", "Damascus"]),
    q!(Category::History, Difficulty::Hard, "Which queen governed England during the Spanish Armada?", 2, ["Mary Stuart", "Victoria", "Elizabeth I", "Anne"]),
    q!(Category::History, Difficulty::Hard, "Which famous navigator discovered Australia for the Europeans?", 1, ["Cook", "Vespucci", "Drake", "Tasman"]),
    q!(Category::History, Difficulty::Hard, "In what year was the railway between Liverpool and Manchester opened?", 2, ["1800", "1825", "1830", "1848"]),
    q!(Category::History, Difficulty::Hard, "Which Roman general conquered Gaul?", 1, ["Pompey", "Julius Caesar", "Crassus", "Scipio"]),
    q!(Category::History, Difficulty::Hard, "Which empire extended from the Balkans to the Indus?", 2, ["The Persian", "The Assyrian", "The Macedonian", "The Seleucid"]),
    q!(Category::History, Difficulty::Hard, "Who was the last Bourbon king of Spain in the 19th century?", 1, ["Ferdinand VII", "Alfonso XIII", "Charles IV", "Alfonso XII"]),
    q!(Category::History, Difficulty::Hard, "In what year was the city of Rome founded according to legend?", 2, ["1000 BC", "900 BC", "753 BC", "500 BC"]),
    q!(Category::History, Difficulty::Hard, "Which king of Spain was nicknamed 'the Desired'?", 1, ["Charles III", "Ferdinand VII", "Isabella II", "Alfonso XII"]),
    q!(Category::History, Difficulty::Hard, "Which battle of 1808 was Napoleon's first defeat in the open field?", 2, ["Austerlitz", "Trafalgar", "Bailén", "Waterloo"]),
];
