//! Part 2 of the English bank: Computing and Geography.
use super::super::questions::{q, Category, Difficulty, Question};

pub static QUESTIONS_EN_2: &[Question] = &[
    // ================= History (end of section) =================
    q!(Category::History, Difficulty::Hard, "Which English scientist formulated the laws of gravitation in the 17th century?", 1, ["Darwin", "Newton", "Kepler", "Galileo"]),
    q!(Category::History, Difficulty::Hard, "Which empire controlled the silk trade in antiquity?", 2, ["The Roman", "The Persian", "The Chinese", "The Egyptian"]),
    q!(Category::History, Difficulty::Hard, "In what year was the Second Spanish Republic proclaimed?", 1, ["1930", "1931", "1936", "1939"]),
    q!(Category::History, Difficulty::Hard, "Which treaty ended the US War of Independence?", 2, ["The Treaty of Yorktown", "The Treaty of Paris of 1783", "The Treaty of Versailles", "The Treaty of London"]),
    // ================= Computer Science =================
    // -- Easy --
    q!(Category::Cs, Difficulty::Easy, "What does CPU stand for?", 0, ["Central Processing Unit", "Main Calculation Unit", "User Processor", "Single Program Center"]),
    q!(Category::Cs, Difficulty::Easy, "How many bits are in a byte?", 1, ["16", "8", "4", "32"]),
    q!(Category::Cs, Difficulty::Easy, "Which of these is an operating system?", 2, ["Keyboard", "Mouse", "Windows", "Screen"]),
    q!(Category::Cs, Difficulty::Easy, "What do we use to type on the computer?", 1, ["The mouse", "The keyboard", "The screen", "The printer"]),
    q!(Category::Cs, Difficulty::Easy, "Where are files stored permanently?", 1, ["In the RAM", "On the hard drive", "In the processor", "In the fan"]),
    q!(Category::Cs, Difficulty::Easy, "What device is used to print documents?", 1, ["The scanner", "The printer", "The monitor", "The router"]),
    q!(Category::Cs, Difficulty::Easy, "What is the computer screen called?", 0, ["Monitor", "Keyboard", "Mouse", "Speaker"]),
    q!(Category::Cs, Difficulty::Easy, "Which network connects computers around the world?", 1, ["Intranet", "Internet", "Bluetooth", "Email"]),
    q!(Category::Cs, Difficulty::Easy, "What program do we use to browse the internet?", 1, ["Processor", "Browser", "Antivirus", "System"]),
    q!(Category::Cs, Difficulty::Easy, "What is a computer normally turned on with?", 0, ["Power button", "Speaker", "Mouse", "Monitor"]),
    // -- Medium --
    q!(Category::Cs, Difficulty::Medium, "What language is used to create web pages?", 2, ["Python", "SQL", "HTML", "C++"]),
    q!(Category::Cs, Difficulty::Medium, "What is RAM?", 0, ["Random access memory", "External hard drive", "Graphics card", "Network cable"]),
    q!(Category::Cs, Difficulty::Medium, "Which device stores data in the long term?", 0, ["The hard drive", "RAM", "The processor", "The fan"]),
    q!(Category::Cs, Difficulty::Medium, "What does USB stand for?", 0, ["Universal Serial Bus", "Basic System Unit", "Ultra Binary System", "Basic Software Union"]),
    q!(Category::Cs, Difficulty::Medium, "What language is this game programmed in?", 2, ["Python", "Java", "Rust", "C#"]),
    q!(Category::Cs, Difficulty::Medium, "What extension does a plain text document have?", 1, [".jpg", ".txt", ".mp3", ".exe"]),
    q!(Category::Cs, Difficulty::Medium, "What does an antivirus do?", 1, ["Speeds up the computer", "Protects against harmful programs", "Creates documents", "Connects to the internet"]),
    q!(Category::Cs, Difficulty::Medium, "What does WWW stand for?", 0, ["World Wide Web", "Windows World Web", "Web World Wide", "Wide World Windows"]),
    q!(Category::Cs, Difficulty::Medium, "What is the smallest unit of digital information?", 0, ["The bit", "The byte", "The megabyte", "The file"]),
    q!(Category::Cs, Difficulty::Medium, "Which network is wireless?", 1, ["Ethernet", "Wi-Fi", "Fiber optics", "USB"]),
    // -- Hard --
    q!(Category::Cs, Difficulty::Hard, "What protocol is used to send emails?", 2, ["FTP", "HTTP", "SMTP", "SSH"]),
    q!(Category::Cs, Difficulty::Hard, "What does 'bug' mean in computing?", 0, ["An error in the program", "A serious virus", "A performance improvement", "A type of network"]),
    q!(Category::Cs, Difficulty::Hard, "Which number base does a computer use internally?", 1, ["Decimal", "Binary", "Hexadecimal", "Octal"]),
    q!(Category::Cs, Difficulty::Hard, "What does AI stand for?", 0, ["Artificial intelligence", "Automatic interface", "Advanced computing", "Open internet"]),
    q!(Category::Cs, Difficulty::Hard, "Which of these is a compiled language?", 2, ["Python", "JavaScript", "C++", "PHP"]),
    q!(Category::Cs, Difficulty::Hard, "What does HTML stand for?", 0, ["HyperText Markup Language", "High Tech Modern Language", "Home Tool Markup Language", "Hyperlink Text Machine Language"]),
    q!(Category::Cs, Difficulty::Hard, "What is 'software'?", 0, ["The programs", "The cables", "The keyboard", "The screen"]),
    q!(Category::Cs, Difficulty::Hard, "Which port is used to connect the mouse and keyboard?", 1, ["HDMI", "USB", "VGA", "Ethernet"]),
    q!(Category::Cs, Difficulty::Hard, "Which command lists files in Linux?", 1, ["dir", "ls", "list", "show"]),
    q!(Category::Cs, Difficulty::Hard, "What does DNS stand for?", 0, ["Domain Name System", "Digital Network Server", "Data Name Service", "Dynamic Name System"]),
    // -- Easy (mass batch) --
    q!(Category::Cs, Difficulty::Easy, "Which key deletes the character to the left of the cursor?", 1, ["Delete", "Backspace", "Enter", "Shift"]),
    q!(Category::Cs, Difficulty::Easy, "What is the recycle bin icon on the desktop called?", 0, ["Recycle bin", "Folder", "Shortcut", "Window"]),
    q!(Category::Cs, Difficulty::Easy, "What program is used to write letters and documents?", 1, ["Calculator", "Word processor", "Browser", "Game"]),
    q!(Category::Cs, Difficulty::Easy, "Which symbol is used for email?", 2, ["#", "&", "@", "$"]),
    q!(Category::Cs, Difficulty::Easy, "What is the mouse pointer on the screen called?", 1, ["Arrow", "Cursor", "Icon", "Button"]),
    q!(Category::Cs, Difficulty::Easy, "What device is used to hear the computer's sound?", 2, ["Monitor", "Keyboard", "Speakers", "Scanner"]),
    q!(Category::Cs, Difficulty::Easy, "Which key do you use to skip to a new line when typing?", 1, ["Space", "Enter", "Tab", "Esc"]),
    q!(Category::Cs, Difficulty::Easy, "Where are the camera photos stored on the computer?", 1, ["On the monitor", "On the hard drive", "On the keyboard", "On the mouse"]),
    q!(Category::Cs, Difficulty::Easy, "What program is used to watch movies and videos?", 1, ["Processor", "Video player", "Antivirus", "Calculator"]),
    q!(Category::Cs, Difficulty::Easy, "What is used to connect the computer to the internet by cable?", 0, ["Ethernet cable", "Speaker cable", "HDMI cable", "USB cable"]),
    q!(Category::Cs, Difficulty::Easy, "What is the machine that prints tickets in shops called?", 1, ["Photocopier", "Printer", "Scanner", "Plotter"]),
    q!(Category::Cs, Difficulty::Easy, "What indicates that a program is minimized?", 1, ["X", "Icon in the taskbar", "Menu", "Folder"]),
    q!(Category::Cs, Difficulty::Easy, "Which key is used to type uppercase letters?", 1, ["Ctrl", "Shift", "Alt", "Esc"]),
    q!(Category::Cs, Difficulty::Easy, "What is the program that protects the computer from viruses called?", 1, ["Browser", "Antivirus", "Operating system", "Game"]),
    q!(Category::Cs, Difficulty::Easy, "What device is used to make copies of paper documents?", 1, ["Printer", "Scanner", "Photocopier", "Fax"]),
    q!(Category::Cs, Difficulty::Easy, "What is the part of the computer shown on the screen when you open a program called?", 2, ["Icon", "Bar", "Window", "Cursor"]),
    q!(Category::Cs, Difficulty::Easy, "Which key deletes the character where the cursor is?", 2, ["Backspace", "Enter", "Delete", "Tab"]),
    q!(Category::Cs, Difficulty::Easy, "What is needed to play an online multiplayer game?", 1, ["A printer", "Internet", "A scanner", "A speaker"]),
    q!(Category::Cs, Difficulty::Easy, "What is the small picture that represents a program called?", 1, ["Window", "Icon", "Cursor", "Background"]),
    q!(Category::Cs, Difficulty::Easy, "Which part of the computer shows the images?", 1, ["Keyboard", "Monitor", "Mouse", "Tower"]),
    q!(Category::Cs, Difficulty::Easy, "Which key is used to cancel or close a window?", 1, ["Enter", "Esc", "Space", "Tab"]),
    q!(Category::Cs, Difficulty::Easy, "What is the device that moves the arrow across the screen called?", 1, ["Keyboard", "Mouse", "Speaker", "Microphone"]),
    q!(Category::Cs, Difficulty::Easy, "What program is used to listen to music on the computer?", 1, ["Browser", "Music player", "Processor", "Antivirus"]),
    q!(Category::Cs, Difficulty::Easy, "Where do you save your school homework on the computer?", 1, ["In the backpack", "In a folder", "In the window", "In the cursor"]),
    q!(Category::Cs, Difficulty::Easy, "Which key is pressed to confirm an action?", 1, ["Esc", "Enter", "Shift", "Ctrl"]),
    q!(Category::Cs, Difficulty::Easy, "What is email called?", 1, ["e-fax", "e-mail", "e-phone", "e-web"]),
    q!(Category::Cs, Difficulty::Easy, "What device is used to make video calls?", 1, ["Scanner", "Webcam", "Printer", "Plotter"]),
    q!(Category::Cs, Difficulty::Easy, "What is the touch screen of a tablet called?", 1, ["Touch mouse", "Touch screen", "Touch keyboard", "Touch printer"]),
    q!(Category::Cs, Difficulty::Easy, "What is used to raise the volume of the speakers?", 1, ["The keyboard", "The volume wheel", "The mouse", "The printer"]),
    q!(Category::Cs, Difficulty::Easy, "Which key is used to make a space?", 1, ["Enter", "Space", "Shift", "Tab"]),
    q!(Category::Cs, Difficulty::Easy, "What is the drawing program on the computer called?", 1, ["Processor", "Image editor", "Browser", "Antivirus"]),
    q!(Category::Cs, Difficulty::Easy, "What device is used to talk over the internet with your voice?", 1, ["Speaker", "Microphone", "Monitor", "Mouse"]),
    q!(Category::Cs, Difficulty::Easy, "Where do Windows notifications appear?", 1, ["On the desktop", "In the taskbar", "In the recycle bin", "On the background"]),
    q!(Category::Cs, Difficulty::Easy, "What is needed to turn on the computer?", 1, ["A screen", "Electricity", "A keyboard", "A mouse"]),
    q!(Category::Cs, Difficulty::Easy, "What is the game played over the internet against other people called?", 1, ["Single-player game", "Online game", "Board game", "Physical game"]),
    q!(Category::Cs, Difficulty::Easy, "Which key is used to put a period in the text?", 1, ["Space", "Period", "Shift", "Esc"]),
    q!(Category::Cs, Difficulty::Easy, "What is the part of the computer where the clock is shown called?", 1, ["Desktop", "Taskbar", "Recycle bin", "Menu"]),
    q!(Category::Cs, Difficulty::Easy, "What program is used to make presentations?", 1, ["Calculator", "Presentations", "Browser", "Antivirus"]),
    q!(Category::Cs, Difficulty::Easy, "Which key is used to type the @ sign?", 1, ["The @ key", "The # key", "The $ key", "The & key"]),
    q!(Category::Cs, Difficulty::Easy, "What is the device that detects finger movement on a laptop called?", 1, ["Mouse", "Touchpad", "Keyboard", "Screen"]),
    // -- Medium (mass batch) --
    q!(Category::Cs, Difficulty::Medium, "What language is used to create dynamic web pages?", 1, ["SQL", "JavaScript", "Assembly", "COBOL"]),
    q!(Category::Cs, Difficulty::Medium, "What does the 'copy' command do?", 1, ["Moves the file", "Duplicates the file", "Deletes the file", "Prints the file"]),
    q!(Category::Cs, Difficulty::Medium, "What is a compressed ZIP file?", 1, ["An encrypted file", "A file with less size", "An image file", "A sound file"]),
    q!(Category::Cs, Difficulty::Medium, "What is the cloud in computing?", 1, ["A virus", "Storage on the internet", "A cable", "A screen"]),
    q!(Category::Cs, Difficulty::Medium, "What does the Ctrl+C shortcut do?", 1, ["Cuts", "Copies", "Pastes", "Deletes"]),
    q!(Category::Cs, Difficulty::Medium, "What does the Ctrl+V shortcut do?", 1, ["Copies", "Cuts", "Pastes", "Undoes"]),
    q!(Category::Cs, Difficulty::Medium, "What is a browser?", 1, ["A game", "A program to view the web", "An antivirus", "A printer"]),
    q!(Category::Cs, Difficulty::Medium, "What extension does an image have?", 1, [".txt", ".jpg", ".doc", ".mp3"]),
    q!(Category::Cs, Difficulty::Medium, "What is a computer virus?", 1, ["A useful program", "A harmful program", "Hardware", "A game"]),
    q!(Category::Cs, Difficulty::Medium, "What does the Ctrl+Z shortcut do?", 1, ["Saves", "Undoes", "Copies", "Prints"]),
    q!(Category::Cs, Difficulty::Medium, "What is ROM memory?", 1, ["Temporary memory", "Read-only memory", "Write memory", "Hard drive"]),
    q!(Category::Cs, Difficulty::Medium, "What is a router?", 1, ["A printer", "A device that distributes the internet", "A keyboard", "A speaker"]),
    q!(Category::Cs, Difficulty::Medium, "What is an operating system?", 1, ["A drawing program", "The program that manages the computer", "A virus", "A web page"]),
    q!(Category::Cs, Difficulty::Medium, "What does double-clicking on an icon do?", 1, ["Selects", "Opens the program", "Deletes", "Renames"]),
    q!(Category::Cs, Difficulty::Medium, "What is an attachment?", 1, ["A virus", "A file sent with an email", "A folder", "A link"]),
    q!(Category::Cs, Difficulty::Medium, "What is a secure password?", 1, ["Your name", "A mix of letters, numbers and symbols", "Only numbers", "Only letters"]),
    q!(Category::Cs, Difficulty::Medium, "What is a search engine?", 1, ["A game", "A program that searches the internet", "A printer", "An antivirus"]),
    q!(Category::Cs, Difficulty::Medium, "What does the F5 key do in the browser?", 1, ["Closes", "Reloads the page", "Prints", "Saves"]),
    q!(Category::Cs, Difficulty::Medium, "What is a link?", 1, ["A cable", "A connection to another page", "A file", "An icon"]),
    q!(Category::Cs, Difficulty::Medium, "What is cache memory?", 1, ["A slow memory", "A fast access memory", "A hard drive", "A printer"]),
    q!(Category::Cs, Difficulty::Medium, "What is a firewall?", 1, ["A game", "A firewall that protects the network", "A monitor", "A keyboard"]),
    q!(Category::Cs, Difficulty::Medium, "What is a database?", 1, ["A music file", "A set of organized data", "A drawing program", "A virus"]),
    q!(Category::Cs, Difficulty::Medium, "What does the Ctrl+S shortcut do?", 1, ["Copies", "Saves the file", "Pastes", "Deletes"]),
    q!(Category::Cs, Difficulty::Medium, "What is a LAN?", 1, ["A worldwide network", "A local network", "A wireless network", "A cable network"]),
    q!(Category::Cs, Difficulty::Medium, "What is a PDF file?", 1, ["A video file", "A document format", "A sound file", "A program"]),
    q!(Category::Cs, Difficulty::Medium, "What is phishing?", 1, ["A game", "A trick to steal data", "An antivirus", "A browser"]),
    q!(Category::Cs, Difficulty::Medium, "What is a browser tab?", 1, ["A small window", "An open page in the bar", "A button", "An icon"]),
    q!(Category::Cs, Difficulty::Medium, "What is a byte?", 1, ["A bit", "8 bits", "16 bits", "A file"]),
    q!(Category::Cs, Difficulty::Medium, "What is an executable file?", 1, ["A document", "A program ready to run", "An image", "A sound"]),
    q!(Category::Cs, Difficulty::Medium, "What is the speed of a processor?", 1, ["Gigabytes", "Gigahertz", "Megabytes", "Pixels"]),
    q!(Category::Cs, Difficulty::Medium, "What is a spreadsheet?", 1, ["A text document", "A program with cells for numbers", "A game", "A browser"]),
    q!(Category::Cs, Difficulty::Medium, "What is the browser history?", 1, ["Viruses", "Visited pages", "Downloads", "Favorites"]),
    q!(Category::Cs, Difficulty::Medium, "What is a bookmark or favorite?", 1, ["A virus", "A saved page", "A file", "An icon"]),
    q!(Category::Cs, Difficulty::Medium, "What is a 3D printer?", 1, ["A normal printer", "It creates objects in 3 dimensions", "A scanner", "A photocopier"]),
    q!(Category::Cs, Difficulty::Medium, "What is Bluetooth?", 1, ["A cable", "A short wireless connection", "A virus", "A program"]),
    q!(Category::Cs, Difficulty::Medium, "What is a compressed folder?", 1, ["An empty folder", "A file that groups and compresses", "An icon", "A shortcut"]),
    q!(Category::Cs, Difficulty::Medium, "What is a hashtag?", 1, ["A label with #", "An email", "A file", "A web page"]),
    q!(Category::Cs, Difficulty::Medium, "What is an algorithm?", 1, ["A virus", "A sequence of steps to solve something", "A browser", "A file"]),
    q!(Category::Cs, Difficulty::Medium, "What is the blue screen of death?", 1, ["A wallpaper", "A serious Windows error", "A screen saver", "A game"]),
    q!(Category::Cs, Difficulty::Medium, "What is a keyboard shortcut?", 1, ["A key", "A combination of keys for an action", "An icon", "A virus"]),
    // -- Hard (mass batch) --
    q!(Category::Cs, Difficulty::Hard, "Which algorithm sorts an array by comparing pairs?", 1, ["Binary search", "Bubble", "Hash", "Recursion"]),
    q!(Category::Cs, Difficulty::Hard, "What is an IP address?", 1, ["An email", "The address of a device on the network", "A file", "A virus"]),
    q!(Category::Cs, Difficulty::Hard, "What is object-oriented programming?", 1, ["A virus", "A paradigm with classes and objects", "A language", "An algorithm"]),
    q!(Category::Cs, Difficulty::Hard, "What is a compiler?", 1, ["An editor", "It translates code to machine language", "A browser", "A printer"]),
    q!(Category::Cs, Difficulty::Hard, "What is a variable in programming?", 1, ["A file", "A memory space with a value", "A button", "A window"]),
    q!(Category::Cs, Difficulty::Hard, "What is recursion?", 1, ["An infinite loop", "A function that calls itself", "An error", "A virus"]),
    q!(Category::Cs, Difficulty::Hard, "Which protocol does HTTPS use?", 1, ["FTP", "HTTP over TLS", "SMTP", "SSH"]),
    q!(Category::Cs, Difficulty::Hard, "What is a for loop?", 1, ["An error", "A structure that repeats code", "A variable", "A file"]),
    q!(Category::Cs, Difficulty::Hard, "What is Big Data?", 1, ["A game", "Analysis of large volumes of data", "A virus", "A cable"]),
    q!(Category::Cs, Difficulty::Hard, "What is cybersecurity?", 1, ["An antivirus", "The protection of systems and data", "A browser", "A network"]),
    q!(Category::Cs, Difficulty::Hard, "What language is used to query databases?", 1, ["Python", "SQL", "HTML", "CSS"]),
    q!(Category::Cs, Difficulty::Hard, "What is an embedded system?", 1, ["A virus", "A system inside another device", "A language", "A file"]),
    q!(Category::Cs, Difficulty::Hard, "What is cloud computing?", 1, ["A game", "Cloud computing", "A virus", "A cable"]),
    q!(Category::Cs, Difficulty::Hard, "What is a DDoS attack?", 1, ["A virus", "Saturation of a server", "An error", "A language"]),
    q!(Category::Cs, Difficulty::Hard, "What is artificial intelligence?", 1, ["A robot", "Systems that simulate intelligence", "A game", "A cable"]),
    q!(Category::Cs, Difficulty::Hard, "What is an API?", 1, ["A virus", "An interface to connect programs", "A file", "An icon"]),
    q!(Category::Cs, Difficulty::Hard, "What is encryption?", 1, ["A file", "Encoding information to protect it", "A browser", "A virus"]),
    q!(Category::Cs, Difficulty::Hard, "What is a blockchain?", 1, ["A game", "A decentralized chain of blocks", "A cable", "A language"]),
    q!(Category::Cs, Difficulty::Hard, "What is an interpreter?", 1, ["A compiler", "It executes code line by line", "An editor", "A printer"]),
    q!(Category::Cs, Difficulty::Hard, "What is a script?", 1, ["A virus", "A small program", "An image file", "A sound"]),
    q!(Category::Cs, Difficulty::Hard, "What is machine learning?", 1, ["A game", "Automatic learning", "A virus", "A cable"]),
    q!(Category::Cs, Difficulty::Hard, "What is virtual memory?", 1, ["A virus", "Memory that uses part of the disk", "A file", "A folder"]),
    q!(Category::Cs, Difficulty::Hard, "What is a microprocessor?", 1, ["A speaker", "The brain of the computer", "A monitor", "A keyboard"]),
    q!(Category::Cs, Difficulty::Hard, "What is an artificial neural network?", 1, ["A virus", "A learning model", "A cable", "A game"]),
    q!(Category::Cs, Difficulty::Hard, "What is the hexadecimal system?", 1, ["Base 2", "Base 16", "Base 10", "Base 8"]),
    q!(Category::Cs, Difficulty::Hard, "What is a 404 error?", 1, ["A virus", "Page not found", "A file", "An icon"]),
    q!(Category::Cs, Difficulty::Hard, "What is the latency of a network?", 1, ["The download speed", "The delay in transmission", "The upload", "The bandwidth"]),
    q!(Category::Cs, Difficulty::Hard, "What is open source?", 1, ["A virus", "Software with visible code", "A file", "A game"]),
    q!(Category::Cs, Difficulty::Hard, "What is a kernel?", 1, ["A game", "The core of the operating system", "A file", "An icon"]),
    q!(Category::Cs, Difficulty::Hard, "What is debugging?", 1, ["A virus", "Finding and fixing errors", "A language", "A network"]),
    q!(Category::Cs, Difficulty::Hard, "What is an array?", 1, ["A virus", "A data structure", "A file", "An icon"]),
    q!(Category::Cs, Difficulty::Hard, "What is a hash function?", 1, ["A virus", "It converts data into a fixed value", "A file", "A language"]),
    q!(Category::Cs, Difficulty::Hard, "What is a server?", 1, ["A virus", "A computer that provides services", "A monitor", "A keyboard"]),
    q!(Category::Cs, Difficulty::Hard, "What is a client in computing?", 1, ["A virus", "A program that requests services", "A file", "A folder"]),
    q!(Category::Cs, Difficulty::Hard, "What is cache storage?", 1, ["A virus", "Saving data for fast access", "A file", "A cable"]),
    q!(Category::Cs, Difficulty::Hard, "What is a proxy?", 1, ["A virus", "A network intermediary", "A file", "An icon"]),
    q!(Category::Cs, Difficulty::Hard, "What is virtualization?", 1, ["A game", "Creating virtual versions of resources", "A virus", "A cable"]),
    q!(Category::Cs, Difficulty::Hard, "What is a low-level language?", 1, ["HTML", "Assembly", "Python", "JavaScript"]),
    q!(Category::Cs, Difficulty::Hard, "What is a computer vulnerability?", 1, ["A virus", "A security flaw", "A file", "A game"]),
    q!(Category::Cs, Difficulty::Hard, "What is a patch?", 1, ["A virus", "An update that fixes flaws", "A file", "A cable"]),
    // ================= Geography =================
    // -- Easy --
    q!(Category::Geography, Difficulty::Easy, "What is the capital of France?", 1, ["London", "Paris", "Rome", "Madrid"]),
    q!(Category::Geography, Difficulty::Easy, "Which continent is Spain in?", 2, ["Africa", "Asia", "Europe", "America"]),
    q!(Category::Geography, Difficulty::Easy, "Which planet do we live on?", 2, ["Mars", "Venus", "The Earth", "Jupiter"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Spain?", 2, ["Barcelona", "Seville", "Madrid", "Valencia"]),
    q!(Category::Geography, Difficulty::Easy, "Which ocean is west of Spain?", 1, ["The Mediterranean", "The Atlantic", "The Pacific", "The Indian"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Portugal?", 1, ["Oporto", "Lisbon", "Fátima", "Coimbra"]),
    q!(Category::Geography, Difficulty::Easy, "Which country is shaped like a boot?", 1, ["Greece", "Italy", "Portugal", "Croatia"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Italy?", 1, ["Milan", "Rome", "Naples", "Florence"]),
    q!(Category::Geography, Difficulty::Easy, "What is the largest continent?", 1, ["Africa", "Asia", "America", "Europe"]),
    q!(Category::Geography, Difficulty::Easy, "Which sea bathes the east coast of Spain?", 1, ["The Atlantic", "The Mediterranean", "The Cantabrian", "The Baltic"]),
    // -- Medium --
    q!(Category::Geography, Difficulty::Medium, "What is the largest country in the world?", 1, ["China", "Russia", "Canada", "United States"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Australia?", 1, ["Sydney", "Canberra", "Melbourne", "Perth"]),
    q!(Category::Geography, Difficulty::Medium, "Which ocean bathes the west coast of Spain?", 0, ["The Atlantic", "The Pacific", "The Indian", "The Arctic"]),
    q!(Category::Geography, Difficulty::Medium, "Which of these rivers is in Spain?", 2, ["The Nile", "The Amazon", "The Ebro", "The Ganges"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Argentina?", 1, ["Santiago", "Buenos Aires", "Montevideo", "Lima"]),
    q!(Category::Geography, Difficulty::Medium, "Which desert is in the north of Africa?", 1, ["The Gobi", "The Sahara", "The Kalahari", "The Atacama"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Japan?", 2, ["Beijing", "Seoul", "Tokyo", "Bangkok"]),
    q!(Category::Geography, Difficulty::Medium, "Which country has the most inhabitants in the world?", 1, ["China", "India", "United States", "Brazil"]),
    q!(Category::Geography, Difficulty::Medium, "What is the smallest country in the world?", 1, ["Monaco", "Vatican City", "San Marino", "Malta"]),
    q!(Category::Geography, Difficulty::Medium, "Which mountain range separates Spain from France?", 1, ["The Alps", "The Pyrenees", "Sierra Nevada", "The Atlas"]),
    // -- Hard --
    q!(Category::Geography, Difficulty::Hard, "Which strait separates Spain from Morocco?", 0, ["The Strait of Gibraltar", "The Strait of Messina", "The Bering Strait", "The Strait of Hormuz"]),
    q!(Category::Geography, Difficulty::Hard, "What is the highest mountain in the world?", 2, ["Kilimanjaro", "Mont Blanc", "Everest", "Aconcagua"]),
    q!(Category::Geography, Difficulty::Hard, "Which country is shaped like a boot?", 1, ["Greece", "Italy", "Portugal", "Croatia"]),
    q!(Category::Geography, Difficulty::Hard, "What is the highest point of mainland Spain?", 1, ["Teide", "Mulhacén", "Aneto", "Naranjo"]),
    q!(Category::Geography, Difficulty::Hard, "Which river flows through London?", 1, ["The Seine", "The Thames", "The Rhine", "The Danube"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of New Zealand?", 1, ["Auckland", "Wellington", "Christchurch", "Hamilton"]),
    q!(Category::Geography, Difficulty::Hard, "Which strait separates Asia from America?", 1, ["The Strait of Gibraltar", "The Bering Strait", "The Strait of Magellan", "The Suez Canal"]),
    q!(Category::Geography, Difficulty::Hard, "What is the driest desert in the world?", 2, ["The Sahara", "The Gobi", "The Atacama", "The Arabian"]),
    q!(Category::Geography, Difficulty::Hard, "In which country is most of the Amazon River?", 2, ["Peru", "Colombia", "Brazil", "Venezuela"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of Egypt?", 1, ["Alexandria", "Cairo", "Luxor", "Aswan"]),
    // -- Easy (mass batch) --
    q!(Category::Geography, Difficulty::Easy, "What is the capital of England?", 2, ["Manchester", "Liverpool", "London", "Oxford"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Germany?", 1, ["Munich", "Berlin", "Hamburg", "Frankfurt"]),
    q!(Category::Geography, Difficulty::Easy, "Which country is north of Spain?", 1, ["Portugal", "France", "Morocco", "Andorra"]),
    q!(Category::Geography, Difficulty::Easy, "What is the largest ocean in the world?", 1, ["The Atlantic", "The Pacific", "The Indian", "The Arctic"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Mexico?", 1, ["Guadalajara", "Mexico City", "Monterrey", "Cancún"]),
    q!(Category::Geography, Difficulty::Easy, "Which continent is Brazil in?", 1, ["Africa", "South America", "Asia", "Europe"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Russia?", 1, ["Saint Petersburg", "Moscow", "Kyiv", "Warsaw"]),
    q!(Category::Geography, Difficulty::Easy, "Which country is shaped like a star and is north of Spain?", 1, ["Portugal", "France", "Morocco", "Italy"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of China?", 1, ["Shanghai", "Beijing", "Hong Kong", "Guangzhou"]),
    q!(Category::Geography, Difficulty::Easy, "Which river flows through Madrid?", 1, ["The Ebro", "The Manzanares", "The Tagus", "The Guadalquivir"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Greece?", 1, ["Thessaloniki", "Athens", "Sparta", "Crete"]),
    q!(Category::Geography, Difficulty::Easy, "Which sea separates Spain from Africa?", 1, ["The Cantabrian", "The Mediterranean", "The Atlantic", "The Baltic"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Turkey?", 1, ["Istanbul", "Ankara", "Izmir", "Bursa"]),
    q!(Category::Geography, Difficulty::Easy, "In which country are the pyramids of Giza?", 1, ["Mexico", "Egypt", "Peru", "Sudan"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Canada?", 1, ["Toronto", "Ottawa", "Montreal", "Vancouver"]),
    q!(Category::Geography, Difficulty::Easy, "Which continent has the most countries?", 1, ["Europe", "Africa", "Asia", "America"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of India?", 1, ["Bombay", "New Delhi", "Calcutta", "Bangalore"]),
    q!(Category::Geography, Difficulty::Easy, "Which country is the most populated in Europe?", 1, ["Germany", "Russia", "France", "United Kingdom"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Brazil?", 1, ["Rio de Janeiro", "Brasília", "São Paulo", "Salvador"]),
    q!(Category::Geography, Difficulty::Easy, "Which river flows through Paris?", 1, ["The Rhône", "The Seine", "The Loire", "The Garonne"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Sweden?", 1, ["Gothenburg", "Stockholm", "Malmö", "Uppsala"]),
    q!(Category::Geography, Difficulty::Easy, "Which continent is Australia in?", 1, ["Asia", "Oceania", "Africa", "Europe"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Norway?", 1, ["Bergen", "Oslo", "Trondheim", "Tromsø"]),
    q!(Category::Geography, Difficulty::Easy, "Which country borders Spain to the south?", 1, ["France", "Morocco", "Portugal", "Italy"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Ireland?", 1, ["Cork", "Dublin", "Galway", "Belfast"]),
    q!(Category::Geography, Difficulty::Easy, "Which ocean is east of America?", 1, ["The Pacific", "The Atlantic", "The Indian", "The Arctic"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Argentina?", 1, ["Rosario", "Buenos Aires", "Córdoba", "Mendoza"]),
    q!(Category::Geography, Difficulty::Easy, "Which country is famous for its tulips and windmills?", 1, ["Belgium", "Netherlands", "Denmark", "Switzerland"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Poland?", 1, ["Kraków", "Warsaw", "Gdańsk", "Łódź"]),
    q!(Category::Geography, Difficulty::Easy, "In which country is the Eiffel Tower?", 1, ["Italy", "France", "Spain", "Belgium"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Peru?", 1, ["Cusco", "Lima", "Arequipa", "Trujillo"]),
    q!(Category::Geography, Difficulty::Easy, "Which country is shaped like a boot?", 1, ["Spain", "Italy", "Portugal", "Greece"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Austria?", 1, ["Salzburg", "Vienna", "Innsbruck", "Graz"]),
    q!(Category::Geography, Difficulty::Easy, "Which sea is north of Spain?", 1, ["The Mediterranean", "The Cantabrian", "The Atlantic", "The Baltic"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Chile?", 1, ["Valparaíso", "Santiago", "Concepción", "Antofagasta"]),
    q!(Category::Geography, Difficulty::Easy, "Which continent is the Sahara Desert in?", 1, ["Asia", "Africa", "America", "Australia"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Switzerland?", 1, ["Zurich", "Geneva", "Bern", "Basel"]),
    q!(Category::Geography, Difficulty::Easy, "Which country has the largest population in the world?", 1, ["China", "India", "USA", "Indonesia"]),
    q!(Category::Geography, Difficulty::Easy, "What is the capital of Denmark?", 1, ["Aarhus", "Odense", "Copenhagen", "Aalborg"]),
    q!(Category::Geography, Difficulty::Easy, "Which river is the longest in the world?", 1, ["The Nile", "The Amazon", "The Yangtze", "The Mississippi"]),
    // -- Medium (mass batch) --
    q!(Category::Geography, Difficulty::Medium, "Which river has the most water flow in the world?", 1, ["The Nile", "The Amazon", "The Congo", "The Yangtze"]),
    q!(Category::Geography, Difficulty::Medium, "Which country has the largest area in Europe?", 1, ["Germany", "France", "Russia", "Ukraine"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Morocco?", 1, ["Casablanca", "Rabat", "Marrakesh", "Tangier"]),
    q!(Category::Geography, Difficulty::Medium, "Which strait separates Europe from Africa?", 1, ["The Bering", "The Gibraltar", "The Messina", "The Hormuz"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Colombia?", 1, ["Medellín", "Bogotá", "Cali", "Cartagena"]),
    q!(Category::Geography, Difficulty::Medium, "Which country in Africa is the most populated?", 1, ["Egypt", "Nigeria", "Ethiopia", "South Africa"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Ukraine?", 1, ["Lviv", "Kyiv", "Kharkiv", "Odesa"]),
    q!(Category::Geography, Difficulty::Medium, "Which mountain range is the longest in the world?", 1, ["The Alps", "The Andes", "The Himalayas", "The Rockies"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Venezuela?", 1, ["Maracaibo", "Caracas", "Valencia", "Barquisimeto"]),
    q!(Category::Geography, Difficulty::Medium, "Which desert is in the southwest of South America?", 1, ["The Sahara", "The Atacama", "The Gobi", "The Kalahari"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of South Korea?", 1, ["Busan", "Seoul", "Incheon", "Daegu"]),
    q!(Category::Geography, Difficulty::Medium, "Which country is the largest oil producer in the Middle East?", 1, ["Iran", "Saudi Arabia", "Iraq", "Kuwait"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Algeria?", 1, ["Oran", "Algiers", "Constantine", "Tlemcen"]),
    q!(Category::Geography, Difficulty::Medium, "Which river separates Spain from Portugal in its final stretch?", 1, ["The Ebro", "The Guadiana", "The Tagus", "The Miño"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of the Philippines?", 1, ["Cebu", "Manila", "Davao", "Quezon City"]),
    q!(Category::Geography, Difficulty::Medium, "Which sea is the saltiest in the world?", 1, ["The Mediterranean", "The Dead Sea", "The Baltic", "The Black"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Thailand?", 1, ["Chiang Mai", "Bangkok", "Pattaya", "Phuket"]),
    q!(Category::Geography, Difficulty::Medium, "Which country has the largest island in the world, Greenland?", 1, ["Canada", "Denmark", "Norway", "Iceland"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Ecuador?", 1, ["Guayaquil", "Quito", "Cuenca", "Manta"]),
    q!(Category::Geography, Difficulty::Medium, "Which ocean bathes the west coast of South America?", 1, ["The Atlantic", "The Pacific", "The Indian", "The Arctic"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Iran?", 1, ["Tehran", "Isfahan", "Shiraz", "Tabriz"]),
    q!(Category::Geography, Difficulty::Medium, "Which country in Europe has the most castles?", 1, ["France", "Spain", "Germany", "Italy"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Pakistan?", 1, ["Karachi", "Islamabad", "Lahore", "Peshawar"]),
    q!(Category::Geography, Difficulty::Medium, "Which lake is the largest in the world?", 1, ["Lake Victoria", "The Caspian Sea", "Lake Superior", "Lake Titicaca"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Bulgaria?", 1, ["Plovdiv", "Sofia", "Varna", "Burgas"]),
    q!(Category::Geography, Difficulty::Medium, "Which country is between France and Spain?", 1, ["Portugal", "Andorra", "Monaco", "Luxembourg"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Serbia?", 1, ["Novi Sad", "Belgrade", "Niš", "Kragujevac"]),
    q!(Category::Geography, Difficulty::Medium, "Which country has the most active volcanoes?", 1, ["Japan", "Indonesia", "Italy", "Mexico"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Romania?", 1, ["Cluj", "Bucharest", "Brașov", "Timișoara"]),
    q!(Category::Geography, Difficulty::Medium, "Which river rises in the Alps and flows into the Black Sea?", 1, ["The Rhine", "The Danube", "The Po", "The Elbe"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Nigeria?", 1, ["Lagos", "Abuja", "Kano", "Ibadan"]),
    q!(Category::Geography, Difficulty::Medium, "Which archipelago belongs to Spain in the Atlantic?", 1, ["The Balearic Islands", "The Canary Islands", "The Azores", "The Cíes"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Vietnam?", 1, ["Ho Chi Minh City", "Hanoi", "Da Nang", "Haiphong"]),
    q!(Category::Geography, Difficulty::Medium, "Which country has the largest economy in Africa?", 1, ["Egypt", "Nigeria", "South Africa", "Algeria"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Hungary?", 1, ["Debrecen", "Budapest", "Szeged", "Pécs"]),
    q!(Category::Geography, Difficulty::Medium, "Which strait separates England from France?", 1, ["The Strait of Gibraltar", "The English Channel", "The Bering Strait", "The Strait of Messina"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Cuba?", 1, ["Santiago", "Havana", "Varadero", "Cienfuegos"]),
    q!(Category::Geography, Difficulty::Medium, "Which country in South America has no coast?", 1, ["Ecuador", "Bolivia", "Paraguay", "Uruguay"]),
    q!(Category::Geography, Difficulty::Medium, "What is the capital of Finland?", 1, ["Tampere", "Helsinki", "Turku", "Oulu"]),
    q!(Category::Geography, Difficulty::Medium, "Which country has the largest Muslim population in the world?", 1, ["Egypt", "Indonesia", "Pakistan", "Turkey"]),
    // -- Hard (mass batch) --
    q!(Category::Geography, Difficulty::Hard, "What is the deepest point of the ocean?", 1, ["The Tonga Trench", "The Mariana Trench", "The Java Trench", "The Puerto Rico Trench"]),
    q!(Category::Geography, Difficulty::Hard, "Which country has the most time zones?", 1, ["Russia", "France", "USA", "China"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of Kazakhstan?", 1, ["Almaty", "Astana", "Shymkent", "Karaganda"]),
    q!(Category::Geography, Difficulty::Hard, "Which river flows into the Aral Sea?", 1, ["The Volga", "The Amu Darya", "The Ural", "The Don"]),
    q!(Category::Geography, Difficulty::Hard, "What is the highest point in America?", 1, ["Everest", "Aconcagua", "McKinley", "Ojos del Salado"]),
    q!(Category::Geography, Difficulty::Hard, "Which country is the largest exporter of coffee?", 1, ["Colombia", "Brazil", "Ethiopia", "Vietnam"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of Uzbekistan?", 1, ["Samarkand", "Tashkent", "Bukhara", "Khiva"]),
    q!(Category::Geography, Difficulty::Hard, "Which strait separates Russia from Alaska?", 1, ["The Strait of Gibraltar", "The Bering Strait", "The Strait of Magellan", "The Drake Passage"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of Angola?", 1, ["Luanda", "Benguela", "Huambo", "Lubango"]),
    q!(Category::Geography, Difficulty::Hard, "Which country has the most lakes?", 1, ["Finland", "Canada", "Russia", "Sweden"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of Myanmar (Burma)?", 1, ["Mandalay", "Naypyidaw", "Rangoon", "Bagan"]),
    q!(Category::Geography, Difficulty::Hard, "Which desert is the largest in the world?", 1, ["The Sahara", "Antarctica", "The Gobi", "The Arabian"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of Ethiopia?", 1, ["Gondar", "Addis Ababa", "Dire Dawa", "Mekele"]),
    q!(Category::Geography, Difficulty::Hard, "Which country has the longest coastline?", 1, ["Australia", "Canada", "Russia", "Norway"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of Cambodia?", 1, ["Siem Reap", "Phnom Penh", "Battambang", "Kampot"]),
    q!(Category::Geography, Difficulty::Hard, "Which canal connects the Mediterranean with the Red Sea?", 1, ["The Panama Canal", "The Suez Canal", "The Kiel Canal", "The Corinth Canal"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of Senegal?", 1, ["Dakar", "Saint-Louis", "Thiès", "Touba"]),
    q!(Category::Geography, Difficulty::Hard, "Which country has the most land borders?", 1, ["Russia", "China", "Brazil", "USA"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of Mongolia?", 1, ["Erdenet", "Ulaanbaatar", "Darkhan", "Choibalsan"]),
    q!(Category::Geography, Difficulty::Hard, "Which archipelago is the largest in the world?", 1, ["The Philippines", "Indonesia", "Japan", "The Maldives"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of Tunisia?", 1, ["Sfax", "Tunis", "Sousse", "Bizerte"]),
    q!(Category::Geography, Difficulty::Hard, "Which country occupies most of the Scandinavian Peninsula?", 1, ["Norway", "Sweden", "Finland", "Denmark"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of Nepal?", 1, ["Pokhara", "Kathmandu", "Lumbini", "Patan"]),
    q!(Category::Geography, Difficulty::Hard, "Which sea is between Italy and the Balkans?", 1, ["The Tyrrhenian", "The Adriatic", "The Ionian", "The Aegean"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of Paraguay?", 1, ["Ciudad del Este", "Asunción", "Encarnación", "Luque"]),
    q!(Category::Geography, Difficulty::Hard, "Which country has the highest volcano in the world?", 1, ["Japan", "Ecuador", "Italy", "Indonesia"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of Azerbaijan?", 1, ["Ganja", "Baku", "Sumqayit", "Nakhchivan"]),
    q!(Category::Geography, Difficulty::Hard, "Which river is the longest in Europe?", 1, ["The Danube", "The Volga", "The Rhine", "The Ural"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of Uruguay?", 1, ["Punta del Este", "Montevideo", "Salto", "Paysandú"]),
    q!(Category::Geography, Difficulty::Hard, "Which country has the largest GDP in Africa?", 1, ["Egypt", "Nigeria", "South Africa", "Morocco"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of Croatia?", 1, ["Split", "Zagreb", "Dubrovnik", "Rijeka"]),
    q!(Category::Geography, Difficulty::Hard, "Which desert is north of China and Mongolia?", 1, ["The Sahara", "The Gobi", "The Taklamakan", "The Arabian"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of Jordan?", 1, ["Petra", "Amman", "Aqaba", "Zarqa"]),
    q!(Category::Geography, Difficulty::Hard, "Which country is the largest rice producer in the world?", 1, ["India", "China", "Indonesia", "Bangladesh"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of Belize?", 1, ["Belize City", "Belmopan", "San Ignacio", "Orange Walk"]),
    q!(Category::Geography, Difficulty::Hard, "Which strait is between Asia and Africa?", 1, ["The Strait of Gibraltar", "The Bab el-Mandeb", "The Strait of Hormuz", "The Strait of Malacca"]),
];
