//! Part 3 of the English bank: Science and Art.
use super::super::questions::{q, Category, Difficulty, Question};

pub static QUESTIONS_EN_3: &[Question] = &[
    q!(Category::Geography, Difficulty::Hard, "What is the capital of Iceland?", 1, ["Akureyri", "Reykjavik", "Keflavík", "Hafnarfjörður"]),
    q!(Category::Geography, Difficulty::Hard, "Which European country has the most volcanoes?", 1, ["Spain", "Italy", "Greece", "France"]),
    q!(Category::Geography, Difficulty::Hard, "What is the capital of Zimbabwe?", 1, ["Bulawayo", "Harare", "Gweru", "Mutare"]),
    q!(Category::Geography, Difficulty::Hard, "Which canal crosses Central America?", 1, ["The Suez Canal", "The Panama Canal", "The Corinth Canal", "The Kiel Canal"]),
    // ================= Science =================
    // -- Easy --
    q!(Category::Science, Difficulty::Easy, "How many planets are in the solar system?", 1, ["7", "8", "9", "10"]),
    q!(Category::Science, Difficulty::Easy, "Which gas do we need to breathe to live?", 2, ["Nitrogen", "Carbon dioxide", "Oxygen", "Helium"]),
    q!(Category::Science, Difficulty::Easy, "Which is the planet closest to the Sun?", 2, ["Venus", "Mars", "Mercury", "The Earth"]),
    q!(Category::Science, Difficulty::Easy, "Which part of the plant absorbs water from the soil?", 1, ["The leaf", "The root", "The flower", "The stem"]),
    q!(Category::Science, Difficulty::Easy, "How many legs does an insect have?", 1, ["4", "6", "8", "10"]),
    q!(Category::Science, Difficulty::Easy, "Which animal gives milk?", 1, ["The hen", "The cow", "The fish", "The lizard"]),
    q!(Category::Science, Difficulty::Easy, "What color is oxygenated blood?", 2, ["Blue", "Green", "Red", "Yellow"]),
    q!(Category::Science, Difficulty::Easy, "What do plants need to do photosynthesis?", 0, ["Sunlight", "Darkness", "Wind", "Snow"]),
    q!(Category::Science, Difficulty::Easy, "How many teeth does an adult have approximately?", 2, ["20", "28", "32", "36"]),
    q!(Category::Science, Difficulty::Easy, "Which organ do we use to think?", 1, ["The heart", "The brain", "The lung", "The liver"]),
    // -- Medium --
    q!(Category::Science, Difficulty::Medium, "Which organ pumps blood through the body?", 0, ["The heart", "The lung", "The liver", "The kidney"]),
    q!(Category::Science, Difficulty::Medium, "Which is the largest animal in the world?", 0, ["The blue whale", "The elephant", "The giraffe", "The great white shark"]),
    q!(Category::Science, Difficulty::Medium, "Which force keeps us stuck to the ground?", 0, ["Gravity", "Magnetism", "Friction", "Inertia"]),
    q!(Category::Science, Difficulty::Medium, "Which planet is famous for its rings?", 1, ["Mars", "Saturn", "Neptune", "Uranus"]),
    q!(Category::Science, Difficulty::Medium, "Which part of the eye controls the amount of light?", 1, ["The pupil", "The iris", "The lens", "The cornea"]),
    q!(Category::Science, Difficulty::Medium, "Which is the longest bone in the human body?", 1, ["The humerus", "The femur", "The tibia", "The spine"]),
    q!(Category::Science, Difficulty::Medium, "Which gas does photosynthesis produce?", 1, ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"]),
    q!(Category::Science, Difficulty::Medium, "Which animal lays eggs and is not a bird?", 1, ["The dog", "The turtle", "The dolphin", "The bat"]),
    q!(Category::Science, Difficulty::Medium, "What is the change of liquid water to gas called?", 1, ["Condensation", "Evaporation", "Solidification", "Filtration"]),
    q!(Category::Science, Difficulty::Medium, "Which is the largest organ of the human body?", 2, ["The liver", "The brain", "The skin", "The lungs"]),
    // -- Hard --
    q!(Category::Science, Difficulty::Hard, "What is the chemical formula of water?", 0, ["H2O", "CO2", "O2", "NaCl"]),
    q!(Category::Science, Difficulty::Hard, "Which particle has a negative charge?", 0, ["The electron", "The proton", "The neutron", "The atom"]),
    q!(Category::Science, Difficulty::Hard, "Which is the largest planet in the solar system?", 1, ["Mars", "Jupiter", "Neptune", "Venus"]),
    q!(Category::Science, Difficulty::Hard, "Which unit measures force?", 1, ["The joule", "The newton", "The watt", "The ampere"]),
    q!(Category::Science, Difficulty::Hard, "What kind of energy does a moving object have?", 1, ["Potential", "Kinetic", "Thermal", "Chemical"]),
    q!(Category::Science, Difficulty::Hard, "Where is the DNA of the cell found?", 1, ["In the cytoplasm", "In the nucleus", "In the membrane", "In the wall"]),
    q!(Category::Science, Difficulty::Hard, "What is the approximate speed of light?", 0, ["300,000 km/s", "150,000 km/s", "3,000 km/s", "1,000,000 km/s"]),
    q!(Category::Science, Difficulty::Hard, "Which scientist formulated the theory of relativity?", 1, ["Newton", "Einstein", "Bohr", "Planck"]),
    q!(Category::Science, Difficulty::Hard, "How many bones does an adult human have?", 1, ["106", "206", "306", "156"]),
    q!(Category::Science, Difficulty::Hard, "Which gas is the most abundant in the atmosphere?", 1, ["Oxygen", "Nitrogen", "Carbon dioxide", "Argon"]),
    // -- Easy (massive batch) --
    q!(Category::Science, Difficulty::Easy, "Which animal is the fastest in the world?", 2, ["The lion", "The horse", "The cheetah", "The zebra"]),
    q!(Category::Science, Difficulty::Easy, "Which part of the body do you use to breathe?", 1, ["The heart", "The lungs", "The stomach", "The liver"]),
    q!(Category::Science, Difficulty::Easy, "How many seasons does the year have?", 2, ["2", "3", "4", "6"]),
    q!(Category::Science, Difficulty::Easy, "Which animal changes color to camouflage itself?", 1, ["The fish", "The chameleon", "The snake", "The parrot"]),
    q!(Category::Science, Difficulty::Easy, "Which part of the body pumps blood?", 0, ["The heart", "The brain", "The lungs", "The kidneys"]),
    q!(Category::Science, Difficulty::Easy, "Which gas do plants breathe?", 1, ["Oxygen", "Carbon dioxide", "Nitrogen", "Helium"]),
    q!(Category::Science, Difficulty::Easy, "How many eyes does a common spider have?", 1, ["2", "8", "4", "6"]),
    q!(Category::Science, Difficulty::Easy, "Which planet is known as the red planet?", 1, ["Venus", "Mars", "Jupiter", "Mercury"]),
    q!(Category::Science, Difficulty::Easy, "Which organ helps you digest food?", 1, ["The lung", "The stomach", "The heart", "The brain"]),
    q!(Category::Science, Difficulty::Easy, "Which animal is the largest on land?", 1, ["The giraffe", "The elephant", "The rhinoceros", "The hippopotamus"]),
    q!(Category::Science, Difficulty::Easy, "What do plants need to grow besides water?", 1, ["Snow", "Sunlight", "Wind", "Darkness"]),
    q!(Category::Science, Difficulty::Easy, "How many legs does a cat have?", 2, ["2", "6", "4", "8"]),
    q!(Category::Science, Difficulty::Easy, "Which star is closest to the Earth?", 1, ["The Moon", "The Sun", "Sirius", "Polaris"]),
    q!(Category::Science, Difficulty::Easy, "Which animal sleeps standing up?", 1, ["The dog", "The horse", "The cat", "The rabbit"]),
    q!(Category::Science, Difficulty::Easy, "Which sense does the tongue use?", 1, ["Smell", "Taste", "Hearing", "Sight"]),
    q!(Category::Science, Difficulty::Easy, "Which part of the body lets you smell?", 1, ["The eyes", "The nose", "The ears", "The mouth"]),
    q!(Category::Science, Difficulty::Easy, "How many wings does a bee have?", 1, ["1", "2", "4", "6"]),
    q!(Category::Science, Difficulty::Easy, "Which animal lives in the water and breathes through gills?", 1, ["The dolphin", "The fish", "The whale", "The seal"]),
    q!(Category::Science, Difficulty::Easy, "Which organ produces urine?", 1, ["The stomach", "The kidney", "The heart", "The lung"]),
    q!(Category::Science, Difficulty::Easy, "Which planet is the closest to the Earth?", 1, ["Mars", "Venus", "Jupiter", "Mercury"]),
    q!(Category::Science, Difficulty::Easy, "Which animal is known as man's best friend?", 1, ["The cat", "The dog", "The horse", "The parrot"]),
    q!(Category::Science, Difficulty::Easy, "How many fingers does a human hand have?", 3, ["4", "6", "3", "5"]),
    q!(Category::Science, Difficulty::Easy, "Which part of the flower produces the seeds?", 1, ["The petal", "The pistil", "The leaf", "The stem"]),
    q!(Category::Science, Difficulty::Easy, "Which animal is the king of the jungle according to tradition?", 1, ["The tiger", "The lion", "The bear", "The wolf"]),
    q!(Category::Science, Difficulty::Easy, "Which gas makes bubbles rise in a soft drink?", 1, ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"]),
    q!(Category::Science, Difficulty::Easy, "How many legs does a spider have?", 2, ["6", "10", "8", "4"]),
    q!(Category::Science, Difficulty::Easy, "Which animal lays eggs and lives in the water?", 1, ["The dog", "The frog", "The cat", "The pig"]),
    q!(Category::Science, Difficulty::Easy, "Which part of the body do you use to see?", 1, ["The nose", "The eyes", "The ears", "The tongue"]),
    q!(Category::Science, Difficulty::Easy, "Which season comes after winter?", 1, ["Autumn", "Spring", "Summer", "None"]),
    q!(Category::Science, Difficulty::Easy, "Which animal produces honey?", 1, ["The wasp", "The bee", "The fly", "The mosquito"]),
    q!(Category::Science, Difficulty::Easy, "Which part of the plant becomes the fruit?", 1, ["The leaf", "The flower", "The root", "The stem"]),
    q!(Category::Science, Difficulty::Easy, "How many hearts does an octopus have?", 2, ["1", "2", "3", "4"]),
    q!(Category::Science, Difficulty::Easy, "Which organ filters the blood?", 1, ["The heart", "The kidney", "The lung", "The stomach"]),
    q!(Category::Science, Difficulty::Easy, "Which planet has life according to scientists?", 1, ["Mars", "The Earth", "Venus", "Jupiter"]),
    q!(Category::Science, Difficulty::Easy, "Which animal has a hump?", 1, ["The elephant", "The camel", "The llama", "The bison"]),
    q!(Category::Science, Difficulty::Easy, "What do living beings need to live?", 1, ["Darkness", "Water", "Ice", "Fire"]),
    q!(Category::Science, Difficulty::Easy, "Which part of the body beats with each heartbeat?", 1, ["The brain", "The heart", "The lung", "The liver"]),
    q!(Category::Science, Difficulty::Easy, "How many planets have rings?", 1, ["Only Saturn", "Jupiter, Saturn, Uranus and Neptune", "Only Jupiter", "None"]),
    q!(Category::Science, Difficulty::Easy, "Which animal is the tallest in the world?", 1, ["The elephant", "The giraffe", "The camel", "The ostrich"]),
    q!(Category::Science, Difficulty::Easy, "Which part of the cell controls everything?", 1, ["The membrane", "The nucleus", "The cytoplasm", "The wall"]),
    // -- Medium (massive batch) --
    q!(Category::Science, Difficulty::Medium, "Which bones protect the brain?", 1, ["The ribs", "The skull", "The spine", "The pelvis"]),
    q!(Category::Science, Difficulty::Medium, "Which animal is the most venomous in the world?", 1, ["The cobra", "The sea wasp jellyfish", "The black widow spider", "The dart frog"]),
    q!(Category::Science, Difficulty::Medium, "How many liters of blood does an adult have?", 1, ["1-2", "5-6", "10-12", "15-20"]),
    q!(Category::Science, Difficulty::Medium, "What type of rock forms when magma cools?", 1, ["Sedimentary", "Igneous", "Metamorphic", "Limestone"]),
    q!(Category::Science, Difficulty::Medium, "Which organ produces insulin?", 1, ["The liver", "The pancreas", "The kidney", "The spleen"]),
    q!(Category::Science, Difficulty::Medium, "Which planet has the longest day in the solar system?", 1, ["Mars", "Venus", "Jupiter", "Mercury"]),
    q!(Category::Science, Difficulty::Medium, "How many pairs of chromosomes does a human being have?", 1, ["22", "23", "24", "46"]),
    q!(Category::Science, Difficulty::Medium, "Which force makes things fall to the ground?", 1, ["Magnetism", "Gravity", "Electricity", "Pressure"]),
    q!(Category::Science, Difficulty::Medium, "Which gas is used to inflate balloons and flies?", 1, ["Oxygen", "Helium", "Nitrogen", "Neon"]),
    q!(Category::Science, Difficulty::Medium, "How many chambers does the human heart have?", 2, ["2", "3", "4", "6"]),
    q!(Category::Science, Difficulty::Medium, "Which animal can regenerate its tail?", 1, ["The dog", "The lizard", "The turtle", "The crocodile"]),
    q!(Category::Science, Difficulty::Medium, "What type of energy does a plant use to live?", 1, ["Electrical", "Solar", "Nuclear", "Wind"]),
    q!(Category::Science, Difficulty::Medium, "Which layer of the Earth is at the center?", 1, ["The crust", "The core", "The mantle", "The atmosphere"]),
    q!(Category::Science, Difficulty::Medium, "How many bones does a baby's body have?", 1, ["206", "300", "150", "100"]),
    q!(Category::Science, Difficulty::Medium, "Which instrument measures temperature?", 1, ["The barometer", "The thermometer", "The hygrometer", "The speedometer"]),
    q!(Category::Science, Difficulty::Medium, "Which animal is the longest-lived on the planet?", 1, ["The giant tortoise", "The whale", "The Greenland shark", "The elephant"]),
    q!(Category::Science, Difficulty::Medium, "Which planet has the highest atmospheric pressure?", 1, ["Mars", "Venus", "Jupiter", "Saturn"]),
    q!(Category::Science, Difficulty::Medium, "What is an ecosystem?", 1, ["An animal", "A set of living beings and their environment", "A climate", "A plant"]),
    q!(Category::Science, Difficulty::Medium, "Which vitamin does the skin produce with the sun?", 1, ["Vitamin A", "Vitamin D", "Vitamin C", "Vitamin B12"]),
    q!(Category::Science, Difficulty::Medium, "What type of animal is the whale?", 1, ["A fish", "A mammal", "A reptile", "An amphibian"]),
    q!(Category::Science, Difficulty::Medium, "Which metal is liquid at room temperature?", 1, ["Lead", "Mercury", "Copper", "Silver"]),
    q!(Category::Science, Difficulty::Medium, "How many vertebrae does the human spine have?", 1, ["20", "33", "40", "50"]),
    q!(Category::Science, Difficulty::Medium, "Which planet has the shortest day?", 1, ["The Earth", "Jupiter", "Venus", "Mars"]),
    q!(Category::Science, Difficulty::Medium, "Which process turns wine into vinegar?", 1, ["Photosynthesis", "Fermentation", "Evaporation", "Oxidation"]),
    q!(Category::Science, Difficulty::Medium, "Which gland controls growth?", 1, ["The pancreas", "The pituitary", "The liver", "The thyroid"]),
    q!(Category::Science, Difficulty::Medium, "What is DNA?", 1, ["A protein", "Genetic material", "A sugar", "A fat"]),
    q!(Category::Science, Difficulty::Medium, "Which animal is an amphibian?", 1, ["The snake", "The frog", "The crocodile", "The penguin"]),
    q!(Category::Science, Difficulty::Medium, "Which unit measures electric current?", 1, ["The watt", "The ampere", "The volt", "The ohm"]),
    q!(Category::Science, Difficulty::Medium, "Which planet is farthest from the Sun?", 1, ["Uranus", "Neptune", "Saturn", "Pluto"]),
    q!(Category::Science, Difficulty::Medium, "Which part of the eye focuses the image?", 1, ["The pupil", "The lens", "The iris", "The retina"]),
    q!(Category::Science, Difficulty::Medium, "How many baby teeth does a child have?", 1, ["20", "28", "32", "24"]),
    q!(Category::Science, Difficulty::Medium, "Which gas does human respiration produce?", 1, ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"]),
    q!(Category::Science, Difficulty::Medium, "Which animal is a flying mammal?", 1, ["The eagle", "The bat", "The butterfly", "The hummingbird"]),
    q!(Category::Science, Difficulty::Medium, "What is photosynthesis?", 1, ["Breathing", "Producing food with light", "Sleeping", "Running"]),
    q!(Category::Science, Difficulty::Medium, "Which mineral forms the shells of mollusks?", 1, ["Iron", "Calcium carbonate", "Salt", "Quartz"]),
    q!(Category::Science, Difficulty::Medium, "Which is the heaviest organ of the human body?", 1, ["The brain", "The liver", "The heart", "The lungs"]),
    q!(Category::Science, Difficulty::Medium, "What type of energy does the wind have?", 1, ["Thermal", "Wind", "Nuclear", "Chemical"]),
    q!(Category::Science, Difficulty::Medium, "Which animal has the largest brain in proportion?", 1, ["The elephant", "The dolphin", "The human being", "The whale"]),
    q!(Category::Science, Difficulty::Medium, "What is a fossil?", 1, ["A rock", "Remains of ancient living beings", "A mineral", "A volcano"]),
    q!(Category::Science, Difficulty::Medium, "How many legs does a crab have?", 1, ["6", "8", "10", "12"]),
    // -- Hard (massive batch) --
    q!(Category::Science, Difficulty::Hard, "Which is the most abundant element in the universe?", 1, ["Oxygen", "Hydrogen", "Carbon", "Helium"]),
    q!(Category::Science, Difficulty::Hard, "Which theory explains the origin of the universe?", 1, ["Evolution", "The Big Bang", "Continental drift", "Relativity"]),
    q!(Category::Science, Difficulty::Hard, "What is the atomic number of carbon?", 1, ["12", "6", "14", "8"]),
    q!(Category::Science, Difficulty::Hard, "Which particle is in the nucleus and is positive?", 1, ["The electron", "The proton", "The neutron", "The photon"]),
    q!(Category::Science, Difficulty::Hard, "Which scientist proposed natural selection?", 1, ["Lamarck", "Darwin", "Mendel", "Wallace"]),
    q!(Category::Science, Difficulty::Hard, "What is the speed of sound in air?", 1, ["340 km/h", "340 m/s", "1,000 m/s", "3,000 km/h"]),
    q!(Category::Science, Difficulty::Hard, "Which organ produces bile?", 1, ["The pancreas", "The liver", "The stomach", "The spleen"]),
    q!(Category::Science, Difficulty::Hard, "Which type of radiation has the most energy?", 1, ["Infrared", "Gamma", "Ultraviolet", "Microwaves"]),
    q!(Category::Science, Difficulty::Hard, "Which scale measures earthquakes?", 1, ["The Beaufort scale", "The Richter scale", "The Celsius scale", "The Kelvin scale"]),
    q!(Category::Science, Difficulty::Hard, "What is a black hole?", 1, ["A star", "A region of extreme gravity", "A planet", "A nebula"]),
    q!(Category::Science, Difficulty::Hard, "How many elements does the natural periodic table have?", 1, ["92", "118", "100", "120"]),
    q!(Category::Science, Difficulty::Hard, "Which noble gas is the most abundant in the air?", 1, ["Helium", "Argon", "Neon", "Krypton"]),
    q!(Category::Science, Difficulty::Hard, "Which scientist discovered penicillin?", 1, ["Pasteur", "Fleming", "Koch", "Jenner"]),
    q!(Category::Science, Difficulty::Hard, "Which unit measures pressure?", 1, ["The watt", "The pascal", "The joule", "The newton"]),
    q!(Category::Science, Difficulty::Hard, "Which process do cells divide to reproduce?", 1, ["Photosynthesis", "Mitosis", "Respiration", "Digestion"]),
    q!(Category::Science, Difficulty::Hard, "Which is the coldest planet in the solar system?", 1, ["Neptune", "Uranus", "Pluto", "Mars"]),
    q!(Category::Science, Difficulty::Hard, "Which metal is the best conductor of electricity?", 1, ["Copper", "Silver", "Gold", "Iron"]),
    q!(Category::Science, Difficulty::Hard, "Which enzyme digests proteins in the stomach?", 1, ["Amylase", "Pepsin", "Lipase", "Insulin"]),
    q!(Category::Science, Difficulty::Hard, "Which star is the closest to the Sun?", 1, ["Sirius", "Proxima Centauri", "Alpha Centauri A", "Betelgeuse"]),
    q!(Category::Science, Difficulty::Hard, "Which type of cell has no nucleus?", 1, ["The eukaryotic cell", "The prokaryotic cell", "The plant cell", "The animal cell"]),
    q!(Category::Science, Difficulty::Hard, "What is the formula of carbon dioxide?", 1, ["CO", "CO2", "C2O", "CO3"]),
    q!(Category::Science, Difficulty::Hard, "Which hormone regulates blood sugar?", 1, ["Adrenaline", "Insulin", "Thyroxine", "Melatonin"]),
    q!(Category::Science, Difficulty::Hard, "Which phenomenon causes the tides?", 1, ["The wind", "The Moon and the Sun", "The seabed", "The currents"]),
    q!(Category::Science, Difficulty::Hard, "How many liters of water does the human body have?", 1, ["10", "42", "75", "20"]),
    q!(Category::Science, Difficulty::Hard, "Which scientist discovered natural radioactivity?", 1, ["Curie", "Becquerel", "Röntgen", "Rutherford"]),
    q!(Category::Science, Difficulty::Hard, "What is entropy?", 1, ["A force", "A measure of disorder", "An element", "A planet"]),
    q!(Category::Science, Difficulty::Hard, "Which layer of the atmosphere has the ozone layer?", 1, ["The troposphere", "The stratosphere", "The mesosphere", "The ionosphere"]),
    q!(Category::Science, Difficulty::Hard, "Which animal has the most powerful venom in the world?", 1, ["The king cobra", "The golden poison dart frog", "The funnel-web spider", "The scorpion"]),
    q!(Category::Science, Difficulty::Hard, "Which unit measures the energy in food?", 1, ["The watt", "The calorie", "The joule", "The ampere"]),
    q!(Category::Science, Difficulty::Hard, "Which planet has the strongest magnetic field?", 1, ["The Earth", "Jupiter", "Saturn", "Mars"]),
    q!(Category::Science, Difficulty::Hard, "Which scientist formulated the laws of motion?", 1, ["Einstein", "Newton", "Galileo", "Kepler"]),
    q!(Category::Science, Difficulty::Hard, "What is a quark?", 1, ["A star", "A fundamental particle", "An atom", "A planet"]),
    q!(Category::Science, Difficulty::Hard, "How many pairs of cranial nerves are there?", 1, ["10", "12", "14", "16"]),
    q!(Category::Science, Difficulty::Hard, "What type of wave is light?", 1, ["Mechanical", "Electromagnetic", "Sound", "Gravitational"]),
    q!(Category::Science, Difficulty::Hard, "Which mineral is the hardest in nature?", 1, ["Quartz", "Diamond", "Ruby", "Corundum"]),
    q!(Category::Science, Difficulty::Hard, "Which process produces energy in the Sun?", 1, ["Combustion", "Nuclear fusion", "Nuclear fission", "Oxidation"]),
    q!(Category::Science, Difficulty::Hard, "Which scientist proposed heliocentrism?", 1, ["Ptolemy", "Copernicus", "Aristotle", "Tycho Brahe"]),
    q!(Category::Science, Difficulty::Hard, "What is the theory of evolution?", 1, ["A physical law", "The change of species over time", "A religion", "An experiment"]),
    q!(Category::Science, Difficulty::Hard, "How many stars does the solar system have?", 1, ["Thousands", "One", "Two", "Eight"]),
    q!(Category::Science, Difficulty::Hard, "Which particle carries the electromagnetic force?", 1, ["The gluon", "The photon", "The W boson", "The graviton"]),
    // ================= Art =================
    // -- Easy --
    q!(Category::Art, Difficulty::Easy, "How many colors does the rainbow have?", 2, ["5", "6", "7", "8"]),
    q!(Category::Art, Difficulty::Easy, "Who painted Guernica?", 0, ["Pablo Picasso", "Salvador Dalí", "Francisco de Goya", "Diego Velázquez"]),
    q!(Category::Art, Difficulty::Easy, "Which instrument has black and white keys?", 0, ["The piano", "The guitar", "The violin", "The flute"]),
    q!(Category::Art, Difficulty::Easy, "What color results from mixing blue and yellow?", 1, ["Red", "Green", "Purple", "Orange"]),
    q!(Category::Art, Difficulty::Easy, "What is a person who sculpts called?", 1, ["Painter", "Sculptor", "Musician", "Architect"]),
    q!(Category::Art, Difficulty::Easy, "Which instrument has six strings?", 1, ["The violin", "The guitar", "The piano", "The trumpet"]),
    q!(Category::Art, Difficulty::Easy, "Who painted 'La noche estrellada'?", 1, ["Pablo Picasso", "Vincent van Gogh", "Salvador Dalí", "Claude Monet"]),
    q!(Category::Art, Difficulty::Easy, "Which dance is typical of Andalusia?", 0, ["Flamenco", "La sardana", "La jota", "El pasodoble"]),
    q!(Category::Art, Difficulty::Easy, "How many strings does a violin have?", 1, ["2", "4", "6", "8"]),
    q!(Category::Art, Difficulty::Easy, "Which material was used to sculpt Michelangelo's David?", 1, ["Wood", "Marble", "Bronze", "Clay"]),
    // -- Medium --
    q!(Category::Art, Difficulty::Medium, "Who wrote Don Quijote de la Mancha?", 0, ["Miguel de Cervantes", "Lope de Vega", "Federico García Lorca", "Garcilaso de la Vega"]),
    q!(Category::Art, Difficulty::Medium, "Which painter is famous for his sunflowers?", 1, ["Monet", "Vincent van Gogh", "Renoir", "Cézanne"]),
    q!(Category::Art, Difficulty::Medium, "Which architectural style characterizes the Sagrada Familia?", 0, ["Modernism", "Gothic", "Baroque", "Neoclassical"]),
    q!(Category::Art, Difficulty::Medium, "Which instrument is a percussion instrument?", 1, ["The flute", "The drum", "The violin", "The guitar"]),
    q!(Category::Art, Difficulty::Medium, "Who painted 'Las Meninas'?", 1, ["Francisco de Goya", "Diego Velázquez", "El Greco", "Zurbarán"]),
    q!(Category::Art, Difficulty::Medium, "How many complete symphonies did Beethoven write?", 1, ["5", "9", "12", "7"]),
    q!(Category::Art, Difficulty::Medium, "Which poet wrote 'Romancero gitano'?", 1, ["Antonio Machado", "Federico García Lorca", "Juan Ramón Jiménez", "Quevedo"]),
    q!(Category::Art, Difficulty::Medium, "Which wind instrument is made of metal?", 1, ["The flute", "The trumpet", "The clarinet", "The oboe"]),
    q!(Category::Art, Difficulty::Medium, "Who composed 'Las cuatro estaciones'?", 0, ["Antonio Vivaldi", "Mozart", "Bach", "Haendel"]),
    q!(Category::Art, Difficulty::Medium, "What color is obtained by mixing red and white?", 1, ["Brown", "Pink", "Orange", "Gray"]),
    // -- Hard --
    q!(Category::Art, Difficulty::Hard, "Which painter is famous for his melting clocks?", 0, ["Salvador Dalí", "Pablo Picasso", "Claude Monet", "Edvard Munch"]),
    q!(Category::Art, Difficulty::Hard, "Who composed the Ninth Symphony?", 0, ["Beethoven", "Mozart", "Bach", "Chopin"]),
    q!(Category::Art, Difficulty::Hard, "Which artistic movement includes Vincent van Gogh?", 0, ["Post-impressionism", "Cubism", "Surrealism", "Impressionism"]),
    q!(Category::Art, Difficulty::Hard, "Which Renaissance painter painted the Sistine Chapel?", 1, ["Leonardo da Vinci", "Michelangelo", "Raphael", "Titian"]),
    q!(Category::Art, Difficulty::Hard, "Which architect designed the Sagrada Familia?", 0, ["Antoni Gaudí", "Calatrava", "Mies van der Rohe", "Le Corbusier"]),
    q!(Category::Art, Difficulty::Hard, "Which writer wrote 'La Regenta'?", 1, ["Benito Pérez Galdós", "Leopoldo Alas 'Clarín'", "Emilia Pardo Bazán", "Unamuno"]),
    q!(Category::Art, Difficulty::Hard, "Which painter was nicknamed 'El Greco'?", 0, ["Domenikos Theotokopoulos", "El Bosco", "Francisco de Goya", "Velázquez"]),
    q!(Category::Art, Difficulty::Hard, "Which opera did Bizet compose?", 0, ["Carmen", "La Traviata", "Aída", "Tosca"]),
    q!(Category::Art, Difficulty::Hard, "Which artistic movement did Picasso lead with the 'Guernica'?", 1, ["Surrealism", "Cubism", "Impressionism", "Expressionism"]),
    q!(Category::Art, Difficulty::Hard, "Who wrote 'La casa de Bernarda Alba'?", 0, ["Federico García Lorca", "Valle-Inclán", "Jacinto Benavente", "Alejandro Casona"]),
    // -- Easy (massive batch) --
    q!(Category::Art, Difficulty::Easy, "Which artist draws comics?", 1, ["The sculptor", "The cartoonist", "The musician", "The dancer"]),
    q!(Category::Art, Difficulty::Easy, "What color results from mixing red and blue?", 1, ["Green", "Purple", "Orange", "Brown"]),
    q!(Category::Art, Difficulty::Easy, "Who painted the famous painting of the Mona Lisa?", 1, ["Michelangelo", "Leonardo da Vinci", "Picasso", "Dalí"]),
    q!(Category::Art, Difficulty::Easy, "Which instrument is played by blowing?", 1, ["The guitar", "The flute", "The piano", "The drum"]),
    q!(Category::Art, Difficulty::Easy, "What is a poem?", 1, ["A painting", "A written work with verses", "A song", "A sculpture"]),
    q!(Category::Art, Difficulty::Easy, "Which string instrument has 12 strings in pairs?", 1, ["The Spanish guitar", "The lute", "The bandurria", "The ukulele"]),
    q!(Category::Art, Difficulty::Easy, "What color results from mixing red and yellow?", 1, ["Green", "Orange", "Purple", "Blue"]),
    q!(Category::Art, Difficulty::Easy, "Who painted 'La Gioconda'?", 1, ["Velázquez", "Leonardo da Vinci", "Goya", "Picasso"]),
    q!(Category::Art, Difficulty::Easy, "Which instrument is played with a drumstick?", 1, ["The violin", "The drum", "The flute", "The piano"]),
    q!(Category::Art, Difficulty::Easy, "What is a portrait?", 1, ["A landscape", "A drawing of a person", "A song", "A building"]),
    q!(Category::Art, Difficulty::Easy, "Which Spanish painter painted 'Los fusilamientos del 3 de mayo'?", 1, ["Velázquez", "Goya", "Picasso", "El Greco"]),
    q!(Category::Art, Difficulty::Easy, "Which instrument has 88 keys?", 1, ["The organ", "The piano", "The accordion", "The harmonica"]),
    q!(Category::Art, Difficulty::Easy, "What is the lighter shade of red?", 1, ["Blue", "Pink", "Orange", "Purple"]),
    q!(Category::Art, Difficulty::Easy, "Who sculpted 'El pensador'?", 1, ["Michelangelo", "Rodin", "Dalí", "Gaudí"]),
    q!(Category::Art, Difficulty::Easy, "What is a sculpture?", 1, ["A painting", "A three-dimensional work", "A song", "A poem"]),
    q!(Category::Art, Difficulty::Easy, "Which dance is danced in pairs and is very popular in Argentina?", 1, ["Flamenco", "The tango", "Salsa", "The waltz"]),
    q!(Category::Art, Difficulty::Easy, "How many strings does a ukulele have?", 1, ["6", "4", "8", "2"]),
    q!(Category::Art, Difficulty::Easy, "What color is the sky on a clear day?", 1, ["Gray", "Blue", "Green", "Yellow"]),
    q!(Category::Art, Difficulty::Easy, "Who painted 'El grito'?", 1, ["Van Gogh", "Munch", "Dalí", "Klimt"]),
    q!(Category::Art, Difficulty::Easy, "Which instrument is played with a bow?", 1, ["The guitar", "The violin", "The trumpet", "The saxophone"]),
    q!(Category::Art, Difficulty::Easy, "What is a tale?", 1, ["A poem", "A short story", "A painting", "A song"]),
    q!(Category::Art, Difficulty::Easy, "Which dance is typical of Catalonia?", 1, ["La jota", "La sardana", "Flamenco", "La muñeira"]),
    q!(Category::Art, Difficulty::Easy, "What color comes from mixing all colors?", 1, ["White", "Black", "Gray", "Brown"]),
    q!(Category::Art, Difficulty::Easy, "Who wrote 'Platero y yo'?", 1, ["Unamuno", "Juan Ramón Jiménez", "García Lorca", "Cervantes"]),
    q!(Category::Art, Difficulty::Easy, "Which is the largest instrument of the orchestra?", 1, ["The violin", "The double bass", "The flute", "The clarinet"]),
    q!(Category::Art, Difficulty::Easy, "What is a mural?", 1, ["A song", "A large painting on a wall", "A poem", "A sculpture"]),
    q!(Category::Art, Difficulty::Easy, "Which painter is famous for his soft clocks?", 1, ["Picasso", "Dalí", "Miró", "Kandinsky"]),
    q!(Category::Art, Difficulty::Easy, "How many notes does a musical scale have?", 2, ["5", "6", "7", "8"]),
    q!(Category::Art, Difficulty::Easy, "Who wrote 'La Celestina'?", 1, ["Quevedo", "Fernando de Rojas", "Cervantes", "Lope de Vega"]),
    q!(Category::Art, Difficulty::Easy, "Which instrument has a bellows?", 1, ["The guitar", "The accordion", "The violin", "The drum set"]),
    q!(Category::Art, Difficulty::Easy, "What color is grass?", 1, ["Blue", "Green", "Yellow", "Red"]),
    q!(Category::Art, Difficulty::Easy, "Who painted the 'Guernica'?", 1, ["Dalí", "Picasso", "Miró", "Gris"]),
    q!(Category::Art, Difficulty::Easy, "What is an opera?", 1, ["A poem", "A sung theater play", "A sculpture", "A novel"]),
    q!(Category::Art, Difficulty::Easy, "Which percussion instrument is played with the hands?", 1, ["The piano", "The drum", "The maracas", "The flute"]),
    q!(Category::Art, Difficulty::Easy, "Who wrote 'La ratita presumida'?", 1, ["An anonymous author", "Charles Perrault", "The Brothers Grimm", "Andersen"]),
    q!(Category::Art, Difficulty::Easy, "What is a sonnet?", 1, ["A painting", "A poem of 14 verses", "A song", "A dance"]),
    q!(Category::Art, Difficulty::Easy, "What color results from mixing white and black?", 1, ["Brown", "Gray", "Pink", "Beige"]),
    q!(Category::Art, Difficulty::Easy, "Who painted the famous sunflowers?", 1, ["Monet", "Van Gogh", "Cézanne", "Gauguin"]),
    q!(Category::Art, Difficulty::Easy, "Which dance is typical of Asturias and Galicia?", 1, ["La jota", "La muñeira", "La sardana", "El chotis"]),
    q!(Category::Art, Difficulty::Easy, "How many strings does a double bass have?", 1, ["2", "4", "6", "8"]),
    // -- Medium (massive batch) --
    q!(Category::Art, Difficulty::Medium, "Who wrote 'Cien años de soledad'?", 1, ["Pablo Neruda", "Gabriel García Márquez", "Jorge Luis Borges", "Julio Cortázar"]),
    q!(Category::Art, Difficulty::Medium, "Which painter founded Cubism with Picasso?", 1, ["Matisse", "Georges Braque", "Mondrian", "Duchamp"]),
    q!(Category::Art, Difficulty::Medium, "Which work did Cervantes write as the first modern novel?", 1, ["La Galatea", "El Quijote", "Novelas ejemplares", "Persiles"]),
    q!(Category::Art, Difficulty::Medium, "Which composer wrote 'El Mesías'?", 1, ["Bach", "Haendel", "Vivaldi", "Mozart"]),
    q!(Category::Art, Difficulty::Medium, "Which Spanish artist is famous for his iron sculptures?", 1, ["Miró", "Chillida", "Dalí", "Tapies"]),
    q!(Category::Art, Difficulty::Medium, "Which female writer wrote 'Los pazos de Ulloa'?", 1, ["Pardo Bazán", "Galdós", "Clarín", "Valera"]),
    q!(Category::Art, Difficulty::Medium, "Which artistic movement does Munch's 'El grito' belong to?", 1, ["Cubism", "Expressionism", "Impressionism", "Surrealism"]),
    q!(Category::Art, Difficulty::Medium, "Which instrument is a woodwind instrument?", 1, ["The trumpet", "The clarinet", "The trombone", "The tuba"]),
    q!(Category::Art, Difficulty::Medium, "Who painted 'La persistencia de la memoria'?", 1, ["Picasso", "Dalí", "Miró", "Magritte"]),
    q!(Category::Art, Difficulty::Medium, "Which poet wrote 'Campos de Castilla'?", 1, ["García Lorca", "Antonio Machado", "Juan Ramón Jiménez", "Quevedo"]),
    q!(Category::Art, Difficulty::Medium, "Which opera did Mozart write in Italian?", 1, ["Carmen", "Las bodas de Fígaro", "Aída", "Tosca"]),
    q!(Category::Art, Difficulty::Medium, "Which Dutch painter is famous for his self-portraits?", 1, ["Vermeer", "Rembrandt", "Brueghel", "Bosch"]),
    q!(Category::Art, Difficulty::Medium, "Which writer wrote 'Fortunata y Jacinta'?", 1, ["Clarín", "Galdós", "Valle-Inclán", "Blasco Ibáñez"]),
    q!(Category::Art, Difficulty::Medium, "Which architectural style has pointed arches?", 1, ["Romanesque", "Gothic", "Renaissance", "Baroque"]),
    q!(Category::Art, Difficulty::Medium, "Which Impressionist painter painted 'Impresión, sol naciente'?", 1, ["Renoir", "Claude Monet", "Degas", "Pissarro"]),
    q!(Category::Art, Difficulty::Medium, "Which writer wrote 'Niebla'?", 1, ["Ortega y Gasset", "Unamuno", "Azorín", "Baroja"]),
    q!(Category::Art, Difficulty::Medium, "Which composer is known as 'the father of the symphony'?", 1, ["Mozart", "Haydn", "Bach", "Beethoven"]),
    q!(Category::Art, Difficulty::Medium, "Which Mexican painter is famous for her self-portraits?", 1, ["Rita Hayworth", "Frida Kahlo", "Leonora Carrington", "María Izquierdo"]),
    q!(Category::Art, Difficulty::Medium, "Which play did Lope de Vega write about a commander?", 1, ["El burlador", "Fuenteovejuna", "La dama boba", "Peribáñez"]),
    q!(Category::Art, Difficulty::Medium, "Which instrument is a brass instrument?", 1, ["The oboe", "The trombone", "The bassoon", "The flute"]),
    q!(Category::Art, Difficulty::Medium, "Which writer wrote 'La Colmena'?", 1, ["Cela", "Delibes", "Goytisolo", "Marsé"]),
    q!(Category::Art, Difficulty::Medium, "Which architect designed the City of Arts of Valencia?", 1, ["Gaudí", "Calatrava", "Moneo", "Bofill"]),
    q!(Category::Art, Difficulty::Medium, "Which Flemish painter painted 'El jardín de las delicias'?", 1, ["Brueghel", "El Bosco", "Rubens", "Van Eyck"]),
    q!(Category::Art, Difficulty::Medium, "Which composer wrote 'La consagración de la primavera'?", 1, ["Debussy", "Stravinski", "Ravel", "Satie"]),
    q!(Category::Art, Difficulty::Medium, "Which writer wrote 'La verdad sobre el caso Savolta'?", 1, ["Mendoza", "Vázquez Montalbán", "Muñoz Molina", "Cercas"]),
    q!(Category::Art, Difficulty::Medium, "What is watercolor?", 1, ["A sculpture", "A water-based painting", "A poem", "A dance"]),
    q!(Category::Art, Difficulty::Medium, "Which Italian painter painted 'El nacimiento de Venus'?", 1, ["Michelangelo", "Botticelli", "Raphael", "Titian"]),
    q!(Category::Art, Difficulty::Medium, "Which writer wrote 'Luces de Bohemia'?", 1, ["Unamuno", "Valle-Inclán", "Baroja", "Azorín"]),
    q!(Category::Art, Difficulty::Medium, "Which musician is known as 'the king of rock'?", 1, ["John Lennon", "Elvis Presley", "Michael Jackson", "Bob Dylan"]),
    q!(Category::Art, Difficulty::Medium, "Which instrument has pedals?", 1, ["The guitar", "The organ", "The violin", "The flute"]),
    q!(Category::Art, Difficulty::Medium, "Which poet wrote 'La voz a ti debida'?", 1, ["Aleixandre", "Salinas", "Guillén", "Cernuda"]),
    q!(Category::Art, Difficulty::Medium, "Which Spanish painter painted the 'Cristo de Velázquez'?", 1, ["Goya", "Velázquez", "El Greco", "Zurbarán"]),
    q!(Category::Art, Difficulty::Medium, "What is the Baroque?", 1, ["A dance", "An artistic style of the 17th century", "An instrument", "A poem"]),
    q!(Category::Art, Difficulty::Medium, "Which writer wrote 'La familia de Pascual Duarte'?", 1, ["Cela", "Delibes", "Laforet", "Aldecoa"]),
    q!(Category::Art, Difficulty::Medium, "Which composer wrote the 'Misa en si menor'?", 1, ["Mozart", "Bach", "Haendel", "Beethoven"]),
    q!(Category::Art, Difficulty::Medium, "Which Greek sculptor created the Venus de Milo?", 1, ["Phidias", "Praxiteles", "Alexandros of Antioch", "Myron"]),
    q!(Category::Art, Difficulty::Medium, "Which female writer wrote 'Nada'?", 1, ["Carmen Martín Gaite", "Carmen Laforet", "Ana María Matute", "Rosa Montero"]),
    q!(Category::Art, Difficulty::Medium, "Which French painter is the father of Impressionism?", 1, ["Cézanne", "Monet", "Degas", "Manet"]),
    q!(Category::Art, Difficulty::Medium, "What is a ballet?", 1, ["A painting", "A classical dance", "A poem", "An opera"]),
    q!(Category::Art, Difficulty::Medium, "Which instrument has a curved tube with a funnel?", 1, ["The clarinet", "The saxophone", "The flute", "The oboe"]),
    // -- Hard (massive batch) --
    q!(Category::Art, Difficulty::Hard, "Who painted the triptych 'El jardín de las delicias'?", 1, ["Rubens", "El Bosco", "Durero", "Cranach"]),
    q!(Category::Art, Difficulty::Hard, "Which writer coined the term 'esperpento'?", 1, ["Unamuno", "Valle-Inclán", "Ortega", "Baroja"]),
    q!(Category::Art, Difficulty::Hard, "Which Puccini opera is set in Japan?", 1, ["La Bohème", "Madama Butterfly", "Tosca", "Turandot"]),
    q!(Category::Art, Difficulty::Hard, "Which Russian painter founded abstract art?", 1, ["Malevich", "Kandinsky", "Chagall", "Repin"]),
    q!(Category::Art, Difficulty::Hard, "Which writer wrote 'Rayuela'?", 1, ["Borges", "Cortázar", "García Márquez", "Vargas Llosa"]),
    q!(Category::Art, Difficulty::Hard, "Which architect designed the tower of the Sagrada Familia?", 1, ["Calatrava", "Gaudí", "Domènech", "Puig"]),
    q!(Category::Art, Difficulty::Hard, "Which painter was Velázquez's teacher?", 1, ["El Greco", "Pacheco", "Zurbarán", "Murillo"]),
    q!(Category::Art, Difficulty::Hard, "Which composer wrote 'El anillo del nibelungo'?", 1, ["Mozart", "Wagner", "Brahms", "Schubert"]),
    q!(Category::Art, Difficulty::Hard, "Which writer wrote 'La Regenta'?", 1, ["Galdós", "Clarín", "Pardo Bazán", "Valera"]),
    q!(Category::Art, Difficulty::Hard, "Which Spanish painter painted 'El entierro del conde de Orgaz'?", 1, ["Velázquez", "El Greco", "Goya", "Ribera"]),
    q!(Category::Art, Difficulty::Hard, "Which Shakespeare play is set in Denmark?", 1, ["Othello", "Hamlet", "Macbeth", "Romeo and Juliet"]),
    q!(Category::Art, Difficulty::Hard, "Which pop artist painted soup cans?", 1, ["Lichtenstein", "Warhol", "Hockney", "Basquiat"]),
    q!(Category::Art, Difficulty::Hard, "Which writer wrote 'La saga/fuga de J.B.'?", 1, ["Torrente Ballester", "Cela", "Delibes", "Sánchez Ferlosio"]),
    q!(Category::Art, Difficulty::Hard, "Which composer wrote 'Cuadros de una exposición'?", 1, ["Chaikovski", "Músorgski", "Rajmáninov", "Prokófiev"]),
    q!(Category::Art, Difficulty::Hard, "Which painter was nicknamed 'El Divino'?", 1, ["Leonardo", "Raphael", "Michelangelo", "Titian"]),
    q!(Category::Art, Difficulty::Hard, "Which poet wrote 'Poeta en Nueva York'?", 1, ["Machado", "García Lorca", "Alberti", "Hernández"]),
    q!(Category::Art, Difficulty::Hard, "Which sculptor made the bronze 'David'?", 1, ["Michelangelo", "Donatello", "Verrocchio", "Ghiberti"]),
    q!(Category::Art, Difficulty::Hard, "Which Italian painter painted the 'Escuela de Atenas'?", 1, ["Leonardo", "Raphael", "Michelangelo", "Botticelli"]),
    q!(Category::Art, Difficulty::Hard, "Which writer wrote 'El Jarama'?", 1, ["Delibes", "Sánchez Ferlosio", "Cela", "Goytisolo"]),
    q!(Category::Art, Difficulty::Hard, "Which musician composed 'Las variaciones Goldberg'?", 1, ["Mozart", "Bach", "Beethoven", "Chopin"]),
    q!(Category::Art, Difficulty::Hard, "Which French painter founded Cubism?", 1, ["Cézanne", "Braque", "Matisse", "Derain"]),
    q!(Category::Art, Difficulty::Hard, "Who wrote 'Memoria de mis putas tristes'?", 1, ["Allende", "García Márquez", "Vargas Llosa", "Fuentes"]),
    q!(Category::Art, Difficulty::Hard, "Which composer wrote the 'Sinfonía Fantástica'?", 1, ["Berlioz", "Liszt", "Schumann", "Mendelssohn"]),
    q!(Category::Art, Difficulty::Hard, "Which Dutch painter painted 'La lechera'?", 1, ["Rembrandt", "Vermeer", "Hals", "Steen"]),
    q!(Category::Art, Difficulty::Hard, "Which playwright wrote 'Bodas de sangre'?", 1, ["Valle-Inclán", "García Lorca", "Benavente", "Casona"]),
    q!(Category::Art, Difficulty::Hard, "Which architect designed the Guggenheim in Bilbao?", 1, ["Moneo", "Gehry", "Hadid", "Rogers"]),
    q!(Category::Art, Difficulty::Hard, "Which writer wrote 'La invención de Morel'?", 1, ["Cortázar", "Borges", "Bioy Casares", "Mujica"]),
    q!(Category::Art, Difficulty::Hard, "Which composer wrote the unfinished 'Requiem'?", 1, ["Bach", "Mozart", "Haydn", "Schubert"]),
    q!(Category::Art, Difficulty::Hard, "Which English painter painted 'El carro de heno'?", 1, ["Turner", "Constable", "Gainsborough", "Hogarth"]),
    q!(Category::Art, Difficulty::Hard, "Which poet wrote 'Hojas de hierba'?", 1, ["Poe", "Whitman", "Dickinson", "Frost"]),
    q!(Category::Art, Difficulty::Hard, "Which Norwegian painter is the author of 'El grito'?", 1, ["Klimt", "Munch", "Schiele", "Kollwitz"]),
    q!(Category::Art, Difficulty::Hard, "Which writer wrote 'Los santos inocentes'?", 1, ["Delibes", "Cela", "Laforet", "Grosso"]),
    q!(Category::Art, Difficulty::Hard, "Which composer wrote 'El lago de los cisnes'?", 1, ["Músorgski", "Chaikovski", "Rimski-Kórsakov", "Borodín"]),
    q!(Category::Art, Difficulty::Hard, "Which painter is the author of the 'Autorretrato' with bandaged ear?", 1, ["Gauguin", "Van Gogh", "Cézanne", "Toulouse-Lautrec"]),
    q!(Category::Art, Difficulty::Hard, "Which architects built the Alhambra?", 1, ["The Catholic Monarchs", "The Nasrids", "The Umayyads", "The Almohads"]),
    q!(Category::Art, Difficulty::Hard, "Which writer wrote 'Tiempo de silencio'?", 1, ["Luis Martín-Santos", "Benet", "Goytisolo", "Marsé"]),
];