//! Partie 1 du banc français : Mathématiques et Histoire.
use super::super::questions::{q, Category, Difficulty, Question};

pub static QUESTIONS_FR_1: &[Question] = &[
    // ================= Mathématiques =================
    // -- Facile --
    q!(Category::Math, Difficulty::Easy, "Combien font 7 x 8 ?", 1, ["54", "56", "63", "48"]),
    q!(Category::Math, Difficulty::Easy, "Quel est le résultat de 15 + 27 ?", 0, ["42", "43", "41", "45"]),
    q!(Category::Math, Difficulty::Easy, "Combien de côtés a un hexagone ?", 1, ["5", "6", "7", "8"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 100 / 4 ?", 2, ["20", "30", "25", "35"]),
    q!(Category::Math, Difficulty::Easy, "Quel est le double de 9 ?", 1, ["16", "18", "17", "19"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 12 x 3 ?", 3, ["32", "34", "38", "36"]),
    q!(Category::Math, Difficulty::Easy, "Combien de minutes y a-t-il dans une heure ?", 0, ["60", "100", "30", "45"]),
    q!(Category::Math, Difficulty::Easy, "Quel nombre poursuit la série 2, 4, 6, ... ?", 1, ["7", "8", "9", "10"]),
    q!(Category::Math, Difficulty::Easy, "Combien de sommets a un cube ?", 2, ["6", "12", "8", "4"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 3 + 4 x 2 ?", 1, ["14", "11", "10", "12"]),
    // -- Moyenne --
    q!(Category::Math, Difficulty::Medium, "Si 3x = 21, combien vaut x ?", 0, ["7", "6", "8", "9"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 25 % de 200 ?", 2, ["40", "60", "50", "25"]),
    q!(Category::Math, Difficulty::Medium, "Quelle est l'aire d'un triangle de base 10 et de hauteur 6 ?", 1, ["60", "30", "15", "45"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 2 élevé à la puissance 5 ?", 2, ["25", "16", "32", "64"]),
    q!(Category::Math, Difficulty::Medium, "Quel est le périmètre d'un carré de côté 7 ?", 1, ["49", "28", "14", "21"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 5/6 de 36 ?", 0, ["30", "25", "35", "31"]),
    q!(Category::Math, Difficulty::Medium, "Lequel de ces nombres est premier ?", 2, ["15", "21", "17", "27"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 9 x 9 ?", 1, ["72", "81", "89", "63"]),
    q!(Category::Math, Difficulty::Medium, "Quel est 10 % de 350 ?", 0, ["35", "30", "45", "3,5"]),
    q!(Category::Math, Difficulty::Medium, "Un triangle a des angles de 60° et 70°. Combien mesure le troisième ?", 0, ["50", "60", "40", "70"]),
    // -- Difficile --
    q!(Category::Math, Difficulty::Hard, "Quelles sont les solutions de x^2 - 9 = 0 ?", 1, ["9 seulement", "3 et -3", "3 seulement", "3 et 9"]),
    q!(Category::Math, Difficulty::Hard, "Si 2x + 5 = 17, combien vaut x ?", 0, ["6", "5", "7", "4"]),
    q!(Category::Math, Difficulty::Hard, "Quelle est la valeur de pi arrondie à deux décimales ?", 2, ["3,16", "3,12", "3,14", "3,18"]),
    q!(Category::Math, Difficulty::Hard, "Combien fait la racine carrée de 144 ?", 3, ["11", "14", "13", "12"]),
    q!(Category::Math, Difficulty::Hard, "Combien de degrés font les angles d'un triangle ?", 1, ["360", "180", "90", "270"]),
    q!(Category::Math, Difficulty::Hard, "Combien font 15 % de 80 ?", 0, ["12", "8", "15", "10"]),
    q!(Category::Math, Difficulty::Hard, "Quel nombre poursuit la série 1, 1, 2, 3, 5, 8, ... ?", 1, ["12", "13", "11", "21"]),
    q!(Category::Math, Difficulty::Hard, "Quelle est l'aire d'un cercle de rayon 3 (π ≈ 3,14) ?", 0, ["28,26", "18,84", "9,42", "31,4"]),
    q!(Category::Math, Difficulty::Hard, "Combien font (-3) x (-4) ?", 1, ["-12", "12", "7", "-7"]),
    q!(Category::Math, Difficulty::Hard, "Quelle fraction est équivalente à 1/2 ?", 1, ["2/5", "3/6", "1/4", "5/8"]),
    // -- Facile (grande série) --
    q!(Category::Math, Difficulty::Easy, "Combien font 6 x 9 ?", 3, ["48", "52", "56", "54"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 20 + 15 ?", 2, ["30", "40", "35", "25"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 50 - 17 ?", 1, ["43", "33", "37", "27"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 8 x 7 ?", 0, ["56", "64", "54", "48"]),
    q!(Category::Math, Difficulty::Easy, "Combien de dizaines a le nombre 80 ?", 0, ["8", "80", "10", "4"]),
    q!(Category::Math, Difficulty::Easy, "Combien de côtés a un carré ?", 2, ["3", "5", "4", "6"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 9 + 9 + 9 ?", 1, ["26", "27", "28", "30"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 100 - 100 ?", 1, ["100", "0", "10", "1"]),
    q!(Category::Math, Difficulty::Easy, "Quel est le nombre qui suit 99 ?", 0, ["100", "98", "90", "110"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 3 x 3 ?", 0, ["9", "6", "12", "8"]),
    q!(Category::Math, Difficulty::Easy, "Combien de doigts as-tu sur les deux mains ?", 3, ["8", "9", "11", "10"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 40 / 8 ?", 2, ["6", "4", "5", "7"]),
    q!(Category::Math, Difficulty::Easy, "Quel nombre est le plus grand : 345 ou 354 ?", 1, ["345", "354", "Égaux", "On ne sait pas"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 7 + 8 ?", 2, ["14", "16", "15", "17"]),
    q!(Category::Math, Difficulty::Easy, "Combien d'heures y a-t-il dans un jour ?", 1, ["12", "24", "48", "60"]),
    q!(Category::Math, Difficulty::Easy, "Combien de jours a une semaine ?", 2, ["5", "6", "7", "8"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 5 x 5 ?", 1, ["15", "25", "35", "45"]),
    q!(Category::Math, Difficulty::Easy, "Quelle est la moitié de 30 ?", 3, ["10", "20", "25", "15"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 11 + 11 ?", 2, ["20", "21", "22", "23"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 6 x 4 ?", 0, ["24", "28", "22", "26"]),
    q!(Category::Math, Difficulty::Easy, "Quel nombre est le plus petit : 12 ou 21 ?", 0, ["12", "21", "Égaux", "Aucun"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 30 / 3 ?", 3, ["5", "15", "20", "10"]),
    q!(Category::Math, Difficulty::Easy, "Combien de mois a une année ?", 3, ["10", "11", "13", "12"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 2 + 2 x 3 ?", 0, ["8", "12", "10", "7"]),
    q!(Category::Math, Difficulty::Easy, "Quelle est la moitié de 100 ?", 2, ["25", "60", "50", "75"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 14 - 6 ?", 3, ["6", "7", "9", "8"]),
    q!(Category::Math, Difficulty::Easy, "Combien de côtés a un pentagone ?", 0, ["5", "6", "4", "7"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 3 x 7 ?", 2, ["24", "20", "21", "27"]),
    q!(Category::Math, Difficulty::Easy, "Quel est le double de 15 ?", 1, ["25", "30", "35", "20"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 90 / 10 ?", 0, ["9", "8", "10", "11"]),
    q!(Category::Math, Difficulty::Easy, "Combien de minutes y a-t-il dans un quart d'heure ?", 2, ["30", "20", "15", "45"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 25 + 25 ?", 3, ["40", "45", "60", "50"]),
    q!(Category::Math, Difficulty::Easy, "Quel nombre vient avant 50 ?", 2, ["51", "40", "49", "48"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 10 x 10 ?", 1, ["20", "100", "50", "200"]),
    q!(Category::Math, Difficulty::Easy, "Combien de centimètres a un mètre ?", 3, ["10", "50", "1000", "100"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 6 + 6 + 6 ?", 0, ["18", "16", "20", "12"]),
    q!(Category::Math, Difficulty::Easy, "Quelle est la moitié de 46 ?", 2, ["20", "26", "23", "33"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 4 x 9 ?", 1, ["40", "36", "32", "44"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 75 - 25 ?", 0, ["50", "40", "60", "25"]),
    q!(Category::Math, Difficulty::Easy, "Quel nombre est pair : 7 ou 8 ?", 1, ["7", "8", "Les deux", "Aucun"]),
    // -- Moyenne (grande série) --
    q!(Category::Math, Difficulty::Medium, "Combien font 20 % de 150 ?", 1, ["20", "30", "40", "25"]),
    q!(Category::Math, Difficulty::Medium, "Quelle est l'aire d'un rectangle de 8 x 5 ?", 2, ["26", "13", "40", "80"]),
    q!(Category::Math, Difficulty::Medium, "Si 4x - 8 = 0, combien vaut x ?", 0, ["2", "4", "8", "-2"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 7 au carré ?", 2, ["42", "56", "49", "63"]),
    q!(Category::Math, Difficulty::Medium, "Quel est le plus petit commun multiple de 4 et 6 ?", 1, ["12", "24", "6", "48"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 3/4 + 1/4 ?", 0, ["1", "3/8", "4/8", "2"]),
    q!(Category::Math, Difficulty::Medium, "Combien de degrés mesure un angle droit ?", 1, ["45", "90", "180", "360"]),
    q!(Category::Math, Difficulty::Medium, "Quel est le périmètre d'un triangle équilatéral de côté 6 ?", 2, ["12", "20", "18", "24"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 1,5 x 2 ?", 1, ["2,5", "3", "3,5", "4"]),
    q!(Category::Math, Difficulty::Medium, "Quel est 50 % de 78 ?", 2, ["38", "19,5", "39", "78"]),
    q!(Category::Math, Difficulty::Medium, "Si x + 7 = 15, combien vaut x ?", 0, ["8", "7", "9", "6"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 2^6 (2 puissance 6) ?", 3, ["32", "48", "36", "64"]),
    q!(Category::Math, Difficulty::Medium, "Quelle est l'aire d'un carré de côté 9 ?", 2, ["36", "72", "81", "18"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 5/8 de 64 ?", 1, ["32", "40", "36", "48"]),
    q!(Category::Math, Difficulty::Medium, "Lequel de ces nombres n'est pas un multiple de 3 ?", 2, ["18", "27", "25", "36"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 0,25 exprimé en fraction ?", 0, ["1/4", "1/2", "2/5", "3/4"]),
    q!(Category::Math, Difficulty::Medium, "Quel est le plus grand commun diviseur de 12 et 18 ?", 1, ["3", "6", "9", "2"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 3 x 4 + 2 ?", 2, ["18", "10", "14", "20"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 15 % de 200 ?", 3, ["20", "25", "35", "30"]),
    q!(Category::Math, Difficulty::Medium, "Quel nombre fait 5^3 ?", 1, ["15", "125", "25", "75"]),
    q!(Category::Math, Difficulty::Medium, "Quelle est la médiane de 3, 5, 7, 9, 11 ?", 0, ["7", "5", "9", "6"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 2/3 de 90 ?", 2, ["30", "45", "60", "75"]),
    q!(Category::Math, Difficulty::Medium, "Combien de degrés mesure un angle plat ?", 1, ["90", "180", "270", "360"]),
    q!(Category::Math, Difficulty::Medium, "Quel est le périmètre d'un rectangle de 10 x 4 ?", 0, ["28", "40", "14", "80"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 7/10 + 3/10 ?", 1, ["10/20", "1", "2/10", "0,7"]),
    q!(Category::Math, Difficulty::Medium, "Si 2x = 34, combien vaut x ?", 3, ["16", "18", "12", "17"]),
    q!(Category::Math, Difficulty::Medium, "Quel est 30 % de 120 ?", 2, ["30", "24", "36", "40"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 8 x 0,5 ?", 0, ["4", "8", "2", "16"]),
    q!(Category::Math, Difficulty::Medium, "Quelle fraction est la plus grande : 3/4 ou 2/3 ?", 0, ["3/4", "2/3", "Égales", "Impossible à savoir"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 10^4 ?", 2, ["400", "1.000", "10.000", "100.000"]),
    q!(Category::Math, Difficulty::Medium, "Quel est le volume d'un cube d'arête 3 ?", 3, ["9", "18", "12", "27"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 12,5 + 7,5 ?", 1, ["19", "20", "21", "18"]),
    q!(Category::Math, Difficulty::Medium, "Quel est le nombre suivant de la série 5, 10, 20, 40, ... ?", 0, ["80", "60", "70", "100"]),
    q!(Category::Math, Difficulty::Medium, "Combien de degrés font les angles d'un carré ?", 3, ["180", "270", "90", "360"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 6/2 x 3 ?", 1, ["6", "9", "12", "18"]),
    q!(Category::Math, Difficulty::Medium, "Quel est 75 % de 80 ?", 2, ["40", "50", "60", "70"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 2 x 3 x 4 ?", 1, ["20", "24", "28", "32"]),
    q!(Category::Math, Difficulty::Medium, "Quel est le plus petit nombre premier ?", 2, ["0", "1", "2", "3"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 100 / 0,5 ?", 3, ["50", "100", "500", "200"]),
    q!(Category::Math, Difficulty::Medium, "Quelle est l'aire d'un triangle de base 12 et de hauteur 5 ?", 2, ["60", "17", "30", "15"]),
    // -- Difficile (grande série) --
    q!(Category::Math, Difficulty::Hard, "Combien fait la racine carrée de 225 ?", 1, ["12", "15", "25", "18"]),
    q!(Category::Math, Difficulty::Hard, "Si x^2 = 81, quelles sont les solutions ?", 2, ["9 seulement", "-9 seulement", "9 et -9", "9 et 3"]),
    q!(Category::Math, Difficulty::Hard, "Combien font 12 % de 250 ?", 0, ["30", "25", "35", "40"]),
    q!(Category::Math, Difficulty::Hard, "Quelle est la pente de la droite y = 3x + 2 ?", 1, ["2", "3", "5", "-3"]),
    q!(Category::Math, Difficulty::Hard, "Combien fait log10(1000) ?", 2, ["1", "2", "3", "10"]),
    q!(Category::Math, Difficulty::Hard, "Quelle est l'aire d'un cercle de rayon 5 (π ≈ 3,14) ?", 3, ["31,4", "62,8", "157", "78,5"]),
    q!(Category::Math, Difficulty::Hard, "Combien font 7 ! (factorielle de 7) ?", 1, ["720", "5040", "40320", "2520"]),
    q!(Category::Math, Difficulty::Hard, "Quel est le sinus de 30 degrés ?", 2, ["1", "√3/2", "1/2", "√2/2"]),
    q!(Category::Math, Difficulty::Hard, "Si 3x + 6 = 2x + 10, combien vaut x ?", 0, ["4", "6", "2", "-4"]),
    q!(Category::Math, Difficulty::Hard, "Combien de combinaisons de 2 éléments y a-t-il parmi 5 ?", 1, ["5", "10", "20", "15"]),
    q!(Category::Math, Difficulty::Hard, "Quel est le volume d'une sphère de rayon 3 (π ≈ 3,14) ?", 1, ["37,68", "113,04", "28,26", "75,36"]),
    q!(Category::Math, Difficulty::Hard, "Quel est le résultat de 2^10 ?", 2, ["512", "2048", "1024", "256"]),
    q!(Category::Math, Difficulty::Hard, "Quelle est la somme des 100 premiers nombres entiers naturels ?", 1, ["5000", "5050", "5100", "5150"]),
    q!(Category::Math, Difficulty::Hard, "Combien font 0,2 x 0,5 ?", 0, ["0,1", "0,7", "1", "0,25"]),
    q!(Category::Math, Difficulty::Hard, "Quelle est la dérivée de x^3 ?", 1, ["x^2", "3x^2", "3x", "x^4/4"]),
    q!(Category::Math, Difficulty::Hard, "Combien font (-2)^3 ?", 2, ["8", "6", "-8", "-6"]),
    q!(Category::Math, Difficulty::Hard, "Quelle est la moyenne de 4, 8, 12 et 16 ?", 3, ["8", "12", "9", "10"]),
    q!(Category::Math, Difficulty::Hard, "Combien font 5/6 - 1/2 ?", 1, ["1/6", "1/3", "2/6", "4/6"]),
    q!(Category::Math, Difficulty::Hard, "Quelle est la valeur de e arrondie à deux décimales ?", 0, ["2,72", "2,71", "3,14", "1,61"]),
    q!(Category::Math, Difficulty::Hard, "Combien de faces a un icosaèdre ?", 1, ["12", "20", "24", "30"]),
    q!(Category::Math, Difficulty::Hard, "Quel est 40 % de 250 ?", 2, ["60", "80", "100", "120"]),
    q!(Category::Math, Difficulty::Hard, "Si l'hypoténuse d'un triangle rectangle mesure 13 et un côté 5, combien mesure l'autre côté ?", 3, ["10", "8", "14", "12"]),
    q!(Category::Math, Difficulty::Hard, "Combien fait la racine cubique de 27 ?", 1, ["9", "3", "6", "8"]),
    q!(Category::Math, Difficulty::Hard, "Quel est le terme général de la série 3, 6, 12, 24, ... ?", 1, ["3n", "3 x 2^(n-1)", "n + 3", "n^2"]),
    q!(Category::Math, Difficulty::Hard, "Combien font 1/3 + 1/6 ?", 2, ["1/9", "2/9", "1/2", "3/6"]),
    q!(Category::Math, Difficulty::Hard, "Quelle est l'étendue de l'échantillon 2, 5, 9, 12, 20 ?", 0, ["18", "12", "20", "10"]),
    q!(Category::Math, Difficulty::Hard, "Combien font 15 % de 15 ?", 1, ["1,5", "2,25", "3", "2,5"]),
    q!(Category::Math, Difficulty::Hard, "Quelle est la solution de l'équation 2(x - 3) = 10 ?", 3, ["5", "6", "7", "8"]),
    q!(Category::Math, Difficulty::Hard, "Combien de degrés mesure un radian environ ?", 2, ["45", "90", "57,3", "30"]),
    q!(Category::Math, Difficulty::Hard, "Quelle est la distance entre les points (0, 0) et (3, 4) ?", 1, ["4", "5", "7", "6"]),
    q!(Category::Math, Difficulty::Hard, "Combien font 3^3 + 2^3 ?", 0, ["35", "29", "33", "27"]),
    q!(Category::Math, Difficulty::Hard, "Quelle est la probabilité d'obtenir un 6 avec un dé ?", 1, ["1/2", "1/6", "1/3", "5/6"]),
    q!(Category::Math, Difficulty::Hard, "Combien fait la moyenne pondérée de 2 (poids 1) et 8 (poids 3) ?", 2, ["5", "6", "6,5", "7"]),
    q!(Category::Math, Difficulty::Hard, "Quel est le plus grand nombre à 3 chiffres ?", 3, ["999", "998", "900", "990"]),
    q!(Category::Math, Difficulty::Hard, "Combien font 0,1 + 0,2 + 0,3 ?", 1, ["0,5", "0,6", "0,4", "1"]),
    q!(Category::Math, Difficulty::Hard, "Quel est l'inverse multiplicatif de 4 ?", 2, ["-4", "0,4", "1/4", "4/1"]),
    q!(Category::Math, Difficulty::Hard, "Combien de permutations a le mot ABC ?", 0, ["6", "3", "9", "12"]),
    q!(Category::Math, Difficulty::Hard, "Quel est le carré de 1,5 ?", 1, ["2", "2,25", "3", "2,5"]),
    q!(Category::Math, Difficulty::Hard, "Combien font 10 - 3 x 2 + 4 ?", 3, ["10", "14", "6", "8"]),
    q!(Category::Math, Difficulty::Hard, "Quelle est la solution de x/2 + 3 = 7 ?", 1, ["6", "8", "4", "10"]),
    // ================= Histoire =================
    // -- Facile --
    q!(Category::History, Difficulty::Easy, "En quelle année Christophe Colomb a-t-il atteint l'Amérique ?", 1, ["1500", "1492", "1498", "1485"]),
    q!(Category::History, Difficulty::Easy, "Quelle civilisation a construit les pyramides d'Égypte ?", 2, ["La romaine", "La grecque", "L'égyptienne", "La maya"]),
    q!(Category::History, Difficulty::Easy, "Qui a peint la Joconde ?", 1, ["Michel-Ange", "Leonardo da Vinci", "Pablo Picasso", "Vincent van Gogh"]),
    q!(Category::History, Difficulty::Easy, "Quels symboles utilisaient les Romains pour écrire les nombres ?", 0, ["Les chiffres romains", "Les chiffres arabes", "Les hiéroglyphes", "Le cunéiforme"]),
    q!(Category::History, Difficulty::Easy, "Dans quelle ville se trouve la tour Eiffel ?", 2, ["Londres", "Rome", "Paris", "Madrid"]),
    q!(Category::History, Difficulty::Easy, "Qui a découvert l'Amérique en 1492 ?", 1, ["Magellan", "Christophe Colomb", "Elcano", "Pizarre"]),
    q!(Category::History, Difficulty::Easy, "Quel amphithéâtre célèbre se trouve à Rome ?", 1, ["Le Parthénon", "Le Colisée", "L'aqueduc", "Le Panthéon"]),
    q!(Category::History, Difficulty::Easy, "Comment s'appelle l'écriture de l'Égypte antique ?", 1, ["Le cunéiforme", "Les hiéroglyphes", "Les runes", "Le braille"]),
    q!(Category::History, Difficulty::Easy, "Qui fut le premier empereur de Rome ?", 1, ["Jules César", "Auguste", "Néron", "Trajan"]),
    q!(Category::History, Difficulty::Easy, "Quel peuple a construit le Machu Picchu ?", 2, ["Les Aztèques", "Les Mayas", "Les Incas", "Les Olmèques"]),
    // -- Moyenne --
    q!(Category::History, Difficulty::Medium, "En quelle année a commencé la Seconde Guerre mondiale ?", 1, ["1936", "1939", "1945", "1933"]),
    q!(Category::History, Difficulty::Medium, "Quel empire a construit le Colisée de Rome ?", 2, ["L'empire grec", "L'empire perse", "L'empire romain", "L'Empire ottoman"]),
    q!(Category::History, Difficulty::Medium, "Qui fut le premier président des États-Unis ?", 1, ["Abraham Lincoln", "George Washington", "Thomas Jefferson", "Benjamin Franklin"]),
    q!(Category::History, Difficulty::Medium, "En quelle année a pris fin la Seconde Guerre mondiale ?", 0, ["1945", "1939", "1942", "1950"]),
    q!(Category::History, Difficulty::Medium, "Quelle expédition a fait le premier tour du monde ?", 0, ["Magellan et Elcano", "Colomb", "Vasco de Gama", "Marco Polo"]),
    q!(Category::History, Difficulty::Medium, "En quel siècle a régné Isabelle la Catholique ?", 2, ["XII", "XIV", "XV", "XVI"]),
    q!(Category::History, Difficulty::Medium, "Quelle civilisation habitait le Mexique actuel avant l'arrivée des Espagnols ?", 1, ["Les Mayas", "Les Aztèques", "Les Incas", "Les Chibchas"]),
    q!(Category::History, Difficulty::Medium, "Qui a écrit l'Iliade ?", 1, ["Socrate", "Homère", "Virgile", "Platon"]),
    q!(Category::History, Difficulty::Medium, "Quel empire est tombé en 1453 avec la prise de Constantinople ?", 0, ["L'Empire byzantin", "L'Empire romain", "L'Empire perse", "L'Égypte"]),
    q!(Category::History, Difficulty::Medium, "Quel général carthaginois a traversé les Alpes avec des éléphants ?", 0, ["Hannibal", "Scipion", "Jules César", "Attila"]),
    // -- Difficile --
    q!(Category::History, Difficulty::Hard, "En quelle année le Mur de Berlin est-il tombé ?", 2, ["1991", "1985", "1989", "1993"]),
    q!(Category::History, Difficulty::Hard, "Quelle bataille a mis fin à l'empire de Napoléon ?", 2, ["Bailén", "Trafalgar", "Waterloo", "Lépante"]),
    q!(Category::History, Difficulty::Hard, "Quel traité a mis fin à la guerre de Cent Ans ?", 2, ["Celui de Versailles", "Celui de Tordesillas", "Celui de Troyes", "Celui d'Utrecht"]),
    q!(Category::History, Difficulty::Hard, "En quelle année a commencé la Révolution française ?", 0, ["1789", "1804", "1776", "1812"]),
    q!(Category::History, Difficulty::Hard, "Quel empereur a divisé l'Empire romain en deux ?", 1, ["Constantin", "Théodose", "Néron", "Hadrien"]),
    q!(Category::History, Difficulty::Hard, "Qui fut le premier président de la Seconde République espagnole ?", 1, ["Manuel Azaña", "Niceto Alcalá-Zamora", "Primo de Rivera", "Franco"]),
    q!(Category::History, Difficulty::Hard, "Quel roi espagnol était surnommé « le Prudent » ?", 1, ["Charles Quint", "Philippe II", "Philippe III", "Charles II"]),
    q!(Category::History, Difficulty::Hard, "En quelle année l'être humain a-t-il atteint la Lune ?", 1, ["1965", "1969", "1972", "1959"]),
    q!(Category::History, Difficulty::Hard, "Quel accident géographique séparait l'Hispanie de la Gaule ?", 1, ["Les Alpes", "Les Pyrénées", "L'Èbre", "Le Douro"]),
    q!(Category::History, Difficulty::Hard, "Qui fut la première femme à remporter un prix Nobel ?", 0, ["Marie Curie", "Irène Joliot-Curie", "Rosalind Franklin", "Ada Lovelace"]),
    // -- Facile (grande série) --
    q!(Category::History, Difficulty::Easy, "Comment s'appelle la ville où vivaient les pharaons d'Égypte ?", 1, ["Athènes", "Memphis", "Rome", "Babylone"]),
    q!(Category::History, Difficulty::Easy, "Qui fut le premier homme à marcher sur la Lune ?", 2, ["Buzz Aldrin", "Yuri Gagarin", "Neil Armstrong", "Michael Collins"]),
    q!(Category::History, Difficulty::Easy, "Quelle guerre a duré 100 ans selon son nom populaire ?", 1, ["La Première Guerre mondiale", "La guerre de Cent Ans", "La guerre froide", "La guerre de Troie"]),
    q!(Category::History, Difficulty::Easy, "Dans quel pays le papier a-t-il été inventé ?", 2, ["L'Égypte", "L'Inde", "La Chine", "La Grèce"]),
    q!(Category::History, Difficulty::Easy, "Comment s'appelle le navire sur lequel Colomb a atteint l'Amérique ?", 0, ["La Santa María", "La Pinta", "La Niña", "La Victoria"]),
    q!(Category::History, Difficulty::Easy, "Quelle civilisation a créé le calendrier de 365 jours ?", 2, ["La grecque", "La romaine", "L'égyptienne", "La celte"]),
    q!(Category::History, Difficulty::Easy, "Qui était le plus célèbre chef des Vikings ?", 1, ["Ragnar", "Leif Erikson", "Rollon", "Erik le Rouge"]),
    q!(Category::History, Difficulty::Easy, "Dans quel pays se trouve la Grande Muraille ?", 2, ["Le Japon", "La Mongolie", "La Chine", "La Corée"]),
    q!(Category::History, Difficulty::Easy, "Quel empereur romain a construit un célèbre amphithéâtre ?", 1, ["Auguste", "Vespasien", "Caligula", "Néron"]),
    q!(Category::History, Difficulty::Easy, "Comment s'appelle le célèbre roi arthurien de l'épée Excalibur ?", 2, ["Merlin", "Lancelot", "Arthur", "Gauvain"]),
    q!(Category::History, Difficulty::Easy, "Quel peuple a construit Stonehenge ?", 1, ["Les Romains", "Les Celtes", "Les Égyptiens", "Les Grecs"]),
    q!(Category::History, Difficulty::Easy, "Qui fut célèbre pour sa résistance contre les Romains en Bretagne ?", 2, ["Cléopâtre", "Jeanne d'Arc", "Boudicca", "Zénobie"]),
    q!(Category::History, Difficulty::Easy, "Quel célèbre explorateur a atteint les Indes en contournant l'Afrique ?", 0, ["Vasco de Gama", "Magellan", "Colomb", "Pizarre"]),
    q!(Category::History, Difficulty::Easy, "Dans quelle ville l'Empire romain a-t-il été fondé ?", 1, ["Athènes", "Rome", "Carthage", "Constantinople"]),
    q!(Category::History, Difficulty::Easy, "Qu'écrivaient les Égyptiens sur les murs des temples ?", 2, ["Des runes", "L'alphabet", "Des hiéroglyphes", "Le cunéiforme"]),
    q!(Category::History, Difficulty::Easy, "Qui a peint la chapelle Sixtine ?", 3, ["Raphaël", "De Vinci", "Le Titien", "Michel-Ange"]),
    q!(Category::History, Difficulty::Easy, "Quel pays a remporté la première Coupe du monde de football en 1930 ?", 1, ["Le Brésil", "L'Uruguay", "L'Argentine", "L'Italie"]),
    q!(Category::History, Difficulty::Easy, "Comment s'appelle la célèbre tour penchée d'Italie ?", 0, ["La tour de Pise", "La tour Eiffel", "Big Ben", "Le Colisée"]),
    q!(Category::History, Difficulty::Easy, "Quelle reine espagnole a financé le voyage de Colomb ?", 2, ["Élisabeth d'Angleterre", "Marie Tudor", "Isabelle la Catholique", "Jeanne la Folle"]),
    q!(Category::History, Difficulty::Easy, "Qui fut le chef de l'Allemagne nazie ?", 1, ["Mussolini", "Hitler", "Franco", "Staline"]),
    q!(Category::History, Difficulty::Easy, "Qu'a inventé Gutenberg au XVe siècle ?", 1, ["La boussole", "L'imprimerie", "Le télescope", "La poudre à canon"]),
    q!(Category::History, Difficulty::Easy, "Sur quel continent se trouve l'Égypte ?", 0, ["L'Afrique", "L'Asie", "L'Europe", "L'Amérique"]),
    q!(Category::History, Difficulty::Easy, "Quelle célèbre ville romaine a été ensevelie par le Vésuve ?", 2, ["Rome", "Naples", "Pompéi", "Herculanum"]),
    q!(Category::History, Difficulty::Easy, "Qui fut le leader de la révolution cubaine ?", 1, ["Che Guevara", "Fidel Castro", "Perón", "Allende"]),
    q!(Category::History, Difficulty::Easy, "Quel monument égyptien est une grande sphinx ?", 1, ["Le temple de Karnak", "Le Grand Sphinx de Gizeh", "L'obélisque", "Le Panthéon"]),
    q!(Category::History, Difficulty::Easy, "En quelle année la Déclaration d'indépendance des États-Unis a-t-elle été signée ?", 3, ["1800", "1792", "1770", "1776"]),
    q!(Category::History, Difficulty::Easy, "Comment s'appelle le premier système d'écriture de Mésopotamie ?", 2, ["Les hiéroglyphes", "L'alphabet phénicien", "Le cunéiforme", "Les runes"]),
    q!(Category::History, Difficulty::Easy, "Quel animal utilisaient les chevaliers au Moyen Âge pour se battre ?", 1, ["Le taureau", "Le cheval", "L'éléphant", "Le chameau"]),
    q!(Category::History, Difficulty::Easy, "Qui fut le dernier roi de France avant la Révolution ?", 2, ["Napoléon", "Louis XVI", "Charles IX", "Henri IV"]),
    q!(Category::History, Difficulty::Easy, "Quelle célèbre bataille navale l'Espagne a-t-elle gagnée contre les Turcs en 1571 ?", 0, ["Lépante", "Trafalgar", "L'Invincible Armada", "Salamine"]),
    q!(Category::History, Difficulty::Easy, "Quelle civilisation utilisait le zéro en mathématiques ?", 1, ["Les Romains", "Les Mayas", "Les Vikings", "Les Celtes"]),
    q!(Category::History, Difficulty::Easy, "Qui a fondé l'Empire mongol ?", 2, ["Kubilai Khan", "Tamerlan", "Gengis Khan", "Attila"]),
    q!(Category::History, Difficulty::Easy, "Dans quel pays le premier métro du monde a-t-il été construit ?", 3, ["Paris", "New York", "Madrid", "Londres"]),
    q!(Category::History, Difficulty::Easy, "Quel célèbre navigateur a fait le tour du monde en bateau ?", 1, ["Colomb", "Magellan", "Vasco de Gama", "Amerigo Vespucci"]),
    q!(Category::History, Difficulty::Easy, "Quel nom porte le célèbre mur de Chine ?", 2, ["Le mur d'Hadrien", "Le mur de Berlin", "La Grande Muraille", "Le mur des Lamentations"]),
    q!(Category::History, Difficulty::Easy, "Qui fut la première impératrice célèbre de Chine ?", 1, ["Wu Zetian", "Cixi", "Sissi", "Élisabeth II"]),
    q!(Category::History, Difficulty::Easy, "Quel peuple habitait la péninsule Ibérique avant les Romains ?", 2, ["Les Vikings", "Les Celtes", "Les Ibères", "Les Perses"]),
    q!(Category::History, Difficulty::Easy, "Quelle célèbre statue se trouve dans le port de New York ?", 1, ["Le David", "La Vénus", "La statue de la Liberté", "Le Moïse"]),
    q!(Category::History, Difficulty::Easy, "En quelle année a commencé la Première Guerre mondiale ?", 3, ["1918", "1912", "1916", "1914"]),
    q!(Category::History, Difficulty::Easy, "Quel roi espagnol était surnommé « l'Ensorcelé » ?", 0, ["Charles II", "Philippe II", "Charles Quint", "Philippe IV"]),
    // -- Moyenne (grande série) --
    q!(Category::History, Difficulty::Medium, "En quelle année Constantinople est-elle tombée aux mains des Ottomans ?", 2, ["1400", "1492", "1453", "1519"]),
    q!(Category::History, Difficulty::Medium, "Quel traité a divisé le Nouveau Monde entre l'Espagne et le Portugal ?", 1, ["Celui de Versailles", "Celui de Tordesillas", "Celui d'Utrecht", "Celui de Paris"]),
    q!(Category::History, Difficulty::Medium, "Qui fut le dernier pharaon d'Égypte ?", 2, ["Toutânkhamon", "Ramsès II", "Cléopâtre", "Néfertiti"]),
    q!(Category::History, Difficulty::Medium, "Quel empereur a construit le Colisée ?", 0, ["Vespasien", "Jules César", "Hadrien", "Constantin"]),
    q!(Category::History, Difficulty::Medium, "En quelle année a commencé la Révolution industrielle ?", 1, ["1600", "1760", "1850", "1900"]),
    q!(Category::History, Difficulty::Medium, "Quel pays a lancé le premier satellite artificiel, le Spoutnik ?", 1, ["Les États-Unis", "L'URSS", "La Chine", "Le Japon"]),
    q!(Category::History, Difficulty::Medium, "Quel roi d'Angleterre a signé la Magna Carta en 1215 ?", 2, ["Richard Ier", "Henri III", "Jean sans Terre", "Édouard Ier"]),
    q!(Category::History, Difficulty::Medium, "Quelle civilisation a inventé la roue il y a plus de 5 000 ans ?", 3, ["Les Égyptiens", "Les Grecs", "Les Romains", "Les Sumériens"]),
    q!(Category::History, Difficulty::Medium, "Qui fut le premier chancelier de l'Allemagne unifiée ?", 1, ["Hindenburg", "Bismarck", "Hitler", "Adenauer"]),
    q!(Category::History, Difficulty::Medium, "Quel explorateur a découvert le détroit qui porte son nom dans le sud de l'Amérique ?", 2, ["Colomb", "Elcano", "Magellan", "Pizarre"]),
    q!(Category::History, Difficulty::Medium, "En quelle année la paix de Westphalie a-t-elle été signée ?", 0, ["1648", "1713", "1815", "1618"]),
    q!(Category::History, Difficulty::Medium, "Quelle pharaonne a gouverné l'Égypte en tant que femme ?", 1, ["Néfertiti", "Hatchepsout", "Cléopâtre", "Isis"]),
    q!(Category::History, Difficulty::Medium, "Quelle ville était la capitale de l'Empire aztèque ?", 2, ["Cuzco", "Chichén Itzá", "Tenochtitlan", "Tikal"]),
    q!(Category::History, Difficulty::Medium, "Qui a écrit « Le Prince » ?", 1, ["Rousseau", "Machiavel", "Voltaire", "Montesquieu"]),
    q!(Category::History, Difficulty::Medium, "Quelle bataille navale de 1805 Nelson a-t-il gagnée ?", 0, ["Trafalgar", "Lépante", "Jutland", "Salamine"]),
    q!(Category::History, Difficulty::Medium, "En quelle année la Première République espagnole a-t-elle été proclamée ?", 2, ["1868", "1875", "1873", "1898"]),
    q!(Category::History, Difficulty::Medium, "Quel empire avait sa capitale à Cuzco ?", 1, ["L'empire aztèque", "L'empire inca", "L'empire maya", "L'empire olmèque"]),
    q!(Category::History, Difficulty::Medium, "Quel fleuve traverse Rome ?", 2, ["Le Pô", "L'Arno", "Le Tibre", "Le Tage"]),
    q!(Category::History, Difficulty::Medium, "Qui fut le premier empereur de Chine ?", 1, ["Confucius", "Qin Shi Huang", "Mao", "Sun Tzu"]),
    q!(Category::History, Difficulty::Medium, "Quelle célèbre bataille de 1066 a changé le destin de l'Angleterre ?", 2, ["Azincourt", "Crécy", "Hastings", "Bosworth"]),
    q!(Category::History, Difficulty::Medium, "En quelle année l'homme a-t-il atteint la Lune ?", 3, ["1965", "1972", "1959", "1969"]),
    q!(Category::History, Difficulty::Medium, "Quel leader indien a lutté pour l'indépendance sans violence ?", 1, ["Nehru", "Gandhi", "Bose", "Tilak"]),
    q!(Category::History, Difficulty::Medium, "Quelle civilisation a sculpté les têtes colossales en pierre ?", 2, ["Les Aztèques", "Les Mayas", "Les Olmèques", "Les Incas"]),
    q!(Category::History, Difficulty::Medium, "Quel roi de France a construit le palais de Versailles ?", 0, ["Louis XIV", "Louis XVI", "Napoléon", "François Ier"]),
    q!(Category::History, Difficulty::Medium, "En quelle année les 13 colonies des États-Unis sont-elles devenues indépendantes ?", 1, ["1770", "1776", "1789", "1800"]),
    q!(Category::History, Difficulty::Medium, "Quelle célèbre docteure a travaillé dans les hôpitaux de la guerre de Crimée ?", 1, ["Marie Curie", "Florence Nightingale", "Rosalind Franklin", "Anne Boleyn"]),
    q!(Category::History, Difficulty::Medium, "Quel empire avait Constantinople pour capitale ?", 0, ["L'Empire byzantin", "L'Empire romain", "L'Empire perse", "L'Empire ottoman"]),
    q!(Category::History, Difficulty::Medium, "Qui a conquis l'Empire inca ?", 1, ["Cortés", "Pizarre", "Balboa", "Orellana"]),
    q!(Category::History, Difficulty::Medium, "Quel traité a mis fin à la guerre de Succession d'Espagne ?", 2, ["Celui de Tordesillas", "Celui de Versailles", "Celui d'Utrecht", "Celui de Vienne"]),
    q!(Category::History, Difficulty::Medium, "En quelle année l'ONU a-t-elle été fondée ?", 3, ["1919", "1940", "1950", "1945"]),
    q!(Category::History, Difficulty::Medium, "Quel dirigeant égyptien a construit le barrage d'Assouan ?", 1, ["Faruk", "Nasser", "Sadat", "Mubarak"]),
    q!(Category::History, Difficulty::Medium, "Quelle civilisation vivait dans ce qui est aujourd'hui le Pérou ?", 2, ["Les Aztèques", "Les Mayas", "Les Incas", "Les Toltèques"]),
    q!(Category::History, Difficulty::Medium, "Quelle reine d'Angleterre a régné 63 ans au XIXe siècle ?", 1, ["Élisabeth Ire", "Victoria", "Anne", "Élisabeth II"]),
    q!(Category::History, Difficulty::Medium, "Quel peuple barbare a pillé Rome en l'an 410 ?", 2, ["Les Huns", "Les Vandales", "Les Wisigoths", "Les Ostrogoths"]),
    q!(Category::History, Difficulty::Medium, "En quelle année le canal de Suez a-t-il été construit ?", 3, ["1820", "1900", "1850", "1869"]),
    q!(Category::History, Difficulty::Medium, "Qui fut le leader de l'indépendance du Mexique ?", 1, ["Bolívar", "Hidalgo", "San Martín", "Iturbide"]),
    q!(Category::History, Difficulty::Medium, "Quel philosophe grec fut le maître d'Alexandre le Grand ?", 2, ["Socrate", "Platon", "Aristote", "Héraclite"]),
    q!(Category::History, Difficulty::Medium, "Quelle maladie a tué des millions de personnes en Europe au Moyen Âge ?", 1, ["La grippe", "La peste noire", "Le choléra", "La variole"]),
    q!(Category::History, Difficulty::Medium, "Quelle célèbre bataille de 1815 a définitivement vaincu Napoléon ?", 2, ["Austerlitz", "Moscou", "Waterloo", "Bailén"]),
    q!(Category::History, Difficulty::Medium, "En quelle année l'Amérique a-t-elle été découverte ?", 3, ["1500", "1485", "1498", "1492"]),
    // -- Difficile (grande série) --
    q!(Category::History, Difficulty::Hard, "Quel empereur byzantin a reconquis Rome au VIe siècle ?", 1, ["Constantin", "Justinien", "Héraclius", "Théodose"]),
    q!(Category::History, Difficulty::Hard, "En quelle année le concile de Trente a-t-il été célébré pour la première fois ?", 2, ["1517", "1530", "1545", "1563"]),
    q!(Category::History, Difficulty::Hard, "Quel traité de 1815 a réorganisé l'Europe après Napoléon ?", 1, ["Celui de Vienne", "Celui de Versailles", "Celui d'Utrecht", "Celui de Berlin"]),
    q!(Category::History, Difficulty::Hard, "Quel pharaon a construit la grande pyramide de Gizeh ?", 0, ["Khéops", "Khéphren", "Mykérinos", "Toutânkhamon"]),
    q!(Category::History, Difficulty::Hard, "Quel général carthaginois a gagné la bataille de Cannes ?", 1, ["Scipion", "Hannibal", "Hamilcar", "Hasdrubal"]),
    q!(Category::History, Difficulty::Hard, "En quelle année le traité de Tordesillas a-t-il été signé ?", 2, ["1492", "1500", "1494", "1488"]),
    q!(Category::History, Difficulty::Hard, "Quelle reine d'Égypte s'est alliée avec Marc Antoine ?", 3, ["Néfertiti", "Hatchepsout", "Isis", "Cléopâtre"]),
    q!(Category::History, Difficulty::Hard, "Quel empereur romain a légalisé le christianisme ?", 1, ["Dioclétien", "Constantin", "Julien", "Néron"]),
    q!(Category::History, Difficulty::Hard, "Quelle bataille de 732 a arrêté l'expansion musulmane en Europe ?", 2, ["Lépante", "Poitiers", "Tours", "Covadonga"]),
    q!(Category::History, Difficulty::Hard, "Quelle célèbre route reliait l'Europe à l'Asie à travers les Mongols ?", 1, ["La route de l'encens", "La route de la Soie", "La route de l'argent", "La route de l'ambre"]),
    q!(Category::History, Difficulty::Hard, "En quelle année la Révolution russe d'octobre a-t-elle eu lieu ?", 2, ["1905", "1914", "1917", "1923"]),
    q!(Category::History, Difficulty::Hard, "Quel archéologue a découvert la tombe de Toutânkhamon ?", 1, ["Champollion", "Howard Carter", "Schliemann", "Evans"]),
    q!(Category::History, Difficulty::Hard, "Quel empereur romain a divisé l'empire en deux en 395 ?", 0, ["Théodose", "Constantin", "Marc Aurèle", "Dioclétien"]),
    q!(Category::History, Difficulty::Hard, "Quelle guerre a opposé la Castille et le Portugal au XIVe siècle ?", 2, ["Celle des Comunidades", "Celle des Deux Pierre", "Celle de Succession", "Celle de Grenade"]),
    q!(Category::History, Difficulty::Hard, "Qui fut le premier président de la république de Weimar ?", 1, ["Hindenburg", "Ebert", "Bismarck", "Stresemann"]),
    q!(Category::History, Difficulty::Hard, "En quelle année l'Allemagne s'est-elle unifiée sous l'empire de Guillaume Ier ?", 2, ["1848", "1866", "1871", "1918"]),
    q!(Category::History, Difficulty::Hard, "Quel explorateur portugais fut le premier à doubler le cap de Bonne-Espérance ?", 1, ["Vasco de Gama", "Bartolomeu Dias", "Magellan", "Cabral"]),
    q!(Category::History, Difficulty::Hard, "Quelle ville a été détruite par l'éruption du Vésuve en l'an 79 ?", 2, ["Naples", "Capri", "Pompéi", "Rome"]),
    q!(Category::History, Difficulty::Hard, "Quel roi d'Espagne a signé les décrets de Nueva Planta ?", 1, ["Charles II", "Philippe V", "Philippe IV", "Charles III"]),
    q!(Category::History, Difficulty::Hard, "En quelle année le Brésil est-il devenu indépendant du Portugal ?", 2, ["1808", "1815", "1822", "1831"]),
    q!(Category::History, Difficulty::Hard, "Quel empereur japonais a régné pendant la Seconde Guerre mondiale ?", 1, ["Meiji", "Hirohito", "Taishō", "Akihito"]),
    q!(Category::History, Difficulty::Hard, "Quelle civilisation a créé la ville de Teotihuacán ?", 2, ["Les Aztèques", "Les Olmèques", "Les Teotihuacans", "Les Zapotèques"]),
    q!(Category::History, Difficulty::Hard, "Quel traité de 1919 a mis fin à la Première Guerre mondiale ?", 1, ["Celui de Brest-Litovsk", "Celui de Versailles", "Celui de Trianon", "Celui de Saint-Germain"]),
    q!(Category::History, Difficulty::Hard, "Quel roi d'Espagne a été renversé lors de la révolution de 1868 ?", 2, ["Ferdinand VII", "Charles IV", "Isabelle II", "Amédée Ier"]),
    q!(Category::History, Difficulty::Hard, "Qui fut le stratège de la guérilla espagnole contre Napoléon ?", 1, ["El Empecinado", "Espoz y Mina", "Viriat", "Don Pelayo"]),
    q!(Category::History, Difficulty::Hard, "En quelle année Jules César a-t-il été assassiné ?", 2, ["31 av. J.-C.", "27 av. J.-C.", "44 av. J.-C.", "54 av. J.-C."]),
    q!(Category::History, Difficulty::Hard, "Quelle ville médiévale était le centre du monde islamique et du savoir ?", 1, ["Le Caire", "Bagdad", "Cordoue", "Damas"]),
    q!(Category::History, Difficulty::Hard, "Quelle reine gouvernait l'Angleterre pendant l'Invincible Armada ?", 2, ["Marie Stuart", "Victoria", "Élisabeth Ire", "Anne"]),
    q!(Category::History, Difficulty::Hard, "Quel célèbre navigateur a découvert l'Australie pour les Européens ?", 1, ["Cook", "Vespucci", "Drake", "Tasman"]),
    q!(Category::History, Difficulty::Hard, "En quelle année le chemin de fer entre Liverpool et Manchester a-t-il été inauguré ?", 2, ["1800", "1825", "1830", "1848"]),
    q!(Category::History, Difficulty::Hard, "Quel général romain a conquis la Gaule ?", 1, ["Pompée", "Jules César", "Crassus", "Scipion"]),
    q!(Category::History, Difficulty::Hard, "Quel empire s'étendait des Balkans jusqu'à l'Indus ?", 2, ["L'Empire perse", "L'Empire assyrien", "L'Empire macédonien", "L'Empire séleucide"]),
    q!(Category::History, Difficulty::Hard, "Qui fut le dernier roi Bourbon d'Espagne au XIXe siècle ?", 1, ["Ferdinand VII", "Alphonse XIII", "Charles IV", "Alphonse XII"]),
    q!(Category::History, Difficulty::Hard, "En quelle année la ville de Rome a-t-elle été fondée selon la légende ?", 2, ["1000 av. J.-C.", "900 av. J.-C.", "753 av. J.-C.", "500 av. J.-C."]),
    q!(Category::History, Difficulty::Hard, "Quel roi d'Espagne était surnommé « le Désiré » ?", 1, ["Charles III", "Ferdinand VII", "Isabelle II", "Alphonse XII"]),
    q!(Category::History, Difficulty::Hard, "Quelle bataille de 1808 fut la première défaite en rase campagne de Napoléon ?", 2, ["Austerlitz", "Trafalgar", "Bailén", "Waterloo"]),
];