//! Partie 2 du banc français : Informatique et Géographie.
use super::super::questions::{q, Category, Difficulty, Question};

pub static QUESTIONS_FR_2: &[Question] = &[
    // ================= Histoire (fin de la partie 1) =================
    q!(Category::History, Difficulty::Hard, "Quel scientifique anglais a formulé les lois de la gravitation au XVIIe siècle ?", 1, ["Darwin", "Newton", "Kepler", "Galileo"]),
    q!(Category::History, Difficulty::Hard, "Quel empire contrôlait le commerce de la soie dans l'Antiquité ?", 2, ["Le romain", "Le perse", "Le chinois", "L'égyptien"]),
    q!(Category::History, Difficulty::Hard, "En quelle année fut proclamée la Deuxième République espagnole ?", 1, ["1930", "1931", "1936", "1939"]),
    q!(Category::History, Difficulty::Hard, "Quel traité a mis fin à la guerre d'indépendance des États-Unis ?", 2, ["Celui de Yorktown", "Celui de Paris de 1783", "Celui de Versailles", "Celui de Londres"]),
    // ================= Informatique =================
    // -- Facile --
    q!(Category::Cs, Difficulty::Easy, "Que signifie CPU ?", 0, ["Unité centrale de traitement", "Unité de calcul principale", "Processeur d'utilisateur", "Centre de programmes unique"]),
    q!(Category::Cs, Difficulty::Easy, "Combien de bits compte un octet ?", 1, ["16", "8", "4", "32"]),
    q!(Category::Cs, Difficulty::Easy, "Lequel de ceux-ci est un système d'exploitation ?", 2, ["Clavier", "Souris", "Windows", "Écran"]),
    q!(Category::Cs, Difficulty::Easy, "Avec quoi écrivons-nous sur l'ordinateur ?", 1, ["La souris", "Le clavier", "L'écran", "L'imprimante"]),
    q!(Category::Cs, Difficulty::Easy, "Où les fichiers sont-ils conservés de manière permanente ?", 1, ["Dans la RAM", "Sur le disque dur", "Dans le processeur", "Dans le ventilateur"]),
    q!(Category::Cs, Difficulty::Easy, "Quel appareil sert à imprimer des documents ?", 1, ["Le scanner", "L'imprimante", "Le moniteur", "Le routeur"]),
    q!(Category::Cs, Difficulty::Easy, "Comment s'appelle l'écran de l'ordinateur ?", 0, ["Moniteur", "Clavier", "Souris", "Haut-parleur"]),
    q!(Category::Cs, Difficulty::Easy, "Quel réseau connecte les ordinateurs du monde entier ?", 1, ["Intranet", "Internet", "Bluetooth", "Courriel"]),
    q!(Category::Cs, Difficulty::Easy, "Quel programme utilisons-nous pour naviguer sur internet ?", 1, ["Processeur", "Navigateur", "Antivirus", "Système"]),
    q!(Category::Cs, Difficulty::Easy, "Avec quoi allume-t-on normalement un ordinateur ?", 0, ["Bouton d'allumage", "Haut-parleur", "Souris", "Moniteur"]),
    // -- Moyenne --
    q!(Category::Cs, Difficulty::Medium, "Quel langage sert à créer des pages web ?", 2, ["Python", "SQL", "HTML", "C++"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce que la RAM ?", 0, ["Mémoire à accès aléatoire", "Disque dur externe", "Carte graphique", "Câble réseau"]),
    q!(Category::Cs, Difficulty::Medium, "Quel dispositif conserve les données à long terme ?", 0, ["Le disque dur", "La RAM", "Le processeur", "Le ventilateur"]),
    q!(Category::Cs, Difficulty::Medium, "Que signifie USB ?", 0, ["Universal Serial Bus", "Unité de système de base", "Ultra Système Binaire", "Union de logiciels de base"]),
    q!(Category::Cs, Difficulty::Medium, "Dans quel langage ce jeu est-il programmé ?", 2, ["Python", "Java", "Rust", "C#"]),
    q!(Category::Cs, Difficulty::Medium, "Quelle extension a un document texte simple ?", 1, [".jpg", ".txt", ".mp3", ".exe"]),
    q!(Category::Cs, Difficulty::Medium, "Que fait l'antivirus ?", 1, ["Accélère l'ordinateur", "Protège contre les programmes nuisibles", "Crée des documents", "Connecte à internet"]),
    q!(Category::Cs, Difficulty::Medium, "Que signifie WWW ?", 0, ["World Wide Web", "Windows World Web", "Web World Wide", "Wide World Windows"]),
    q!(Category::Cs, Difficulty::Medium, "Quelle est la plus petite unité d'information numérique ?", 0, ["Le bit", "L'octet", "Le mégaoctet", "Le fichier"]),
    q!(Category::Cs, Difficulty::Medium, "Quel réseau est sans fil ?", 1, ["Ethernet", "Wi-Fi", "Fibre optique", "USB"]),
    // -- Difficile --
    q!(Category::Cs, Difficulty::Hard, "Quel protocole sert à envoyer des courriels ?", 2, ["FTP", "HTTP", "SMTP", "SSH"]),
    q!(Category::Cs, Difficulty::Hard, "Que signifie « bug » en informatique ?", 0, ["Une erreur dans le programme", "Un virus grave", "Une amélioration des performances", "Un type de réseau"]),
    q!(Category::Cs, Difficulty::Hard, "Quelle base numérique un ordinateur utilise-t-il en interne ?", 1, ["Décimale", "Binaire", "Hexadécimale", "Octale"]),
    q!(Category::Cs, Difficulty::Hard, "Que signifie IA ?", 0, ["Intelligence artificielle", "Interface automatique", "Informatique avancée", "Internet ouvert"]),
    q!(Category::Cs, Difficulty::Hard, "Lequel de ces langages est compilé ?", 2, ["Python", "JavaScript", "C++", "PHP"]),
    q!(Category::Cs, Difficulty::Hard, "Que signifie HTML ?", 0, ["HyperText Markup Language", "High Tech Modern Language", "Home Tool Markup Language", "Hyperlink Text Machine Language"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce que le « logiciel » (software) ?", 0, ["Les programmes", "Les câbles", "Le clavier", "L'écran"]),
    q!(Category::Cs, Difficulty::Hard, "Quel port sert à connecter la souris et le clavier ?", 1, ["HDMI", "USB", "VGA", "Ethernet"]),
    q!(Category::Cs, Difficulty::Hard, "Quelle commande liste les fichiers sous Linux ?", 1, ["dir", "ls", "list", "show"]),
    q!(Category::Cs, Difficulty::Hard, "Que signifie DNS ?", 0, ["Domain Name System", "Digital Network Server", "Data Name Service", "Dynamic Name System"]),
    // -- Facile (grande série) --
    q!(Category::Cs, Difficulty::Easy, "Quelle touche efface le caractère à gauche du curseur ?", 1, ["Suppr", "Retour arrière", "Entrée", "Maj"]),
    q!(Category::Cs, Difficulty::Easy, "Comment s'appelle l'icône de la corbeille du bureau ?", 0, ["Corbeille de recyclage", "Dossier", "Raccourci", "Fenêtre"]),
    q!(Category::Cs, Difficulty::Easy, "Quel programme sert à écrire des lettres et des documents ?", 1, ["Calculatrice", "Traitement de texte", "Navigateur", "Jeu"]),
    q!(Category::Cs, Difficulty::Easy, "Quel symbole est utilisé pour le courriel ?", 2, ["#", "&", "@", "$"]),
    q!(Category::Cs, Difficulty::Easy, "Comment s'appelle le pointeur de la souris à l'écran ?", 1, ["Flèche", "Curseur", "Icône", "Bouton"]),
    q!(Category::Cs, Difficulty::Easy, "Quel appareil sert à écouter le son de l'ordinateur ?", 2, ["Moniteur", "Clavier", "Haut-parleurs", "Scanner"]),
    q!(Category::Cs, Difficulty::Easy, "Quelle touche utilises-tu pour passer à la ligne en écrivant ?", 1, ["Espace", "Entrée", "Tab", "Échap"]),
    q!(Category::Cs, Difficulty::Easy, "Où sont conservées les photos de l'appareil photo sur l'ordinateur ?", 1, ["Sur le moniteur", "Sur le disque dur", "Sur le clavier", "Sur la souris"]),
    q!(Category::Cs, Difficulty::Easy, "Quel programme sert à regarder des films et des vidéos ?", 1, ["Processeur", "Lecteur vidéo", "Antivirus", "Calculatrice"]),
    q!(Category::Cs, Difficulty::Easy, "Quoi utiliser pour connecter l'ordinateur à internet par câble ?", 0, ["Câble Ethernet", "Câble de haut-parleur", "Câble HDMI", "Câble USB"]),
    q!(Category::Cs, Difficulty::Easy, "Comment s'appelle la machine qui imprime les tickets dans les magasins ?", 1, ["Photocopieuse", "Imprimante", "Scanner", "Traceur"]),
    q!(Category::Cs, Difficulty::Easy, "Quel symbole indique qu'un programme est réduit ?", 1, ["X", "Icône dans la barre des tâches", "Menu", "Dossier"]),
    q!(Category::Cs, Difficulty::Easy, "Quelle touche sert à écrire en majuscules ?", 1, ["Ctrl", "Maj", "Alt", "Échap"]),
    q!(Category::Cs, Difficulty::Easy, "Comment s'appelle le programme qui protège l'ordinateur contre les virus ?", 1, ["Navigateur", "Antivirus", "Système d'exploitation", "Jeu"]),
    q!(Category::Cs, Difficulty::Easy, "Quel appareil sert à faire des copies de documents papier ?", 1, ["Imprimante", "Scanner", "Photocopieuse", "Fax"]),
    q!(Category::Cs, Difficulty::Easy, "Comment s'appelle la partie de l'ordinateur qui apparaît à l'écran quand on ouvre un programme ?", 2, ["Icône", "Barre", "Fenêtre", "Curseur"]),
    q!(Category::Cs, Difficulty::Easy, "Quelle touche efface le caractère à l'endroit du curseur ?", 2, ["Retour arrière", "Entrée", "Suppr", "Tab"]),
    q!(Category::Cs, Difficulty::Easy, "Que faut-il pour jouer à un jeu multijoueur en ligne ?", 1, ["Une imprimante", "Internet", "Un scanner", "Un haut-parleur"]),
    q!(Category::Cs, Difficulty::Easy, "Comment s'appelle le petit dessin qui représente un programme ?", 1, ["Fenêtre", "Icône", "Curseur", "Fond"]),
    q!(Category::Cs, Difficulty::Easy, "Quelle partie de l'ordinateur affiche les images ?", 1, ["Clavier", "Moniteur", "Souris", "Boîtier"]),
    q!(Category::Cs, Difficulty::Easy, "Quelle touche sert à annuler ou fermer une fenêtre ?", 1, ["Entrée", "Échap", "Espace", "Tab"]),
    q!(Category::Cs, Difficulty::Easy, "Comment s'appelle l'appareil qui déplace la flèche à l'écran ?", 1, ["Clavier", "Souris", "Haut-parleur", "Microphone"]),
    q!(Category::Cs, Difficulty::Easy, "Quel programme sert à écouter de la musique sur l'ordinateur ?", 1, ["Navigateur", "Lecteur de musique", "Processeur", "Antivirus"]),
    q!(Category::Cs, Difficulty::Easy, "Où ranges-tu les devoirs de l'école sur l'ordinateur ?", 1, ["Dans le sac", "Dans un dossier", "Dans la fenêtre", "Sur le curseur"]),
    q!(Category::Cs, Difficulty::Easy, "Quelle touche appuie-t-on pour confirmer une action ?", 1, ["Échap", "Entrée", "Maj", "Ctrl"]),
    q!(Category::Cs, Difficulty::Easy, "Comment s'appelle le courrier électronique ?", 1, ["e-fax", "e-mail", "e-phone", "e-web"]),
    q!(Category::Cs, Difficulty::Easy, "Quel appareil sert à faire des visioconférences ?", 1, ["Scanner", "Webcam", "Imprimante", "Traceur"]),
    q!(Category::Cs, Difficulty::Easy, "Comment s'appelle l'écran tactile d'une tablette ?", 1, ["Souris tactile", "Écran tactile", "Clavier tactile", "Imprimante tactile"]),
    q!(Category::Cs, Difficulty::Easy, "Quoi utiliser pour monter le volume des haut-parleurs ?", 1, ["Le clavier", "La molette du volume", "La souris", "L'imprimante"]),
    q!(Category::Cs, Difficulty::Easy, "Quelle touche sert à faire une espace ?", 1, ["Entrée", "Espace", "Maj", "Tab"]),
    q!(Category::Cs, Difficulty::Easy, "Comment s'appelle le programme de dessin de l'ordinateur ?", 1, ["Processeur", "Éditeur d'images", "Navigateur", "Antivirus"]),
    q!(Category::Cs, Difficulty::Easy, "Quel appareil sert à parler sur internet avec la voix ?", 1, ["Haut-parleur", "Microphone", "Moniteur", "Souris"]),
    q!(Category::Cs, Difficulty::Easy, "Où apparaissent les notifications de Windows ?", 1, ["Sur le bureau", "Dans la barre des tâches", "Dans la corbeille", "Sur le fond"]),
    q!(Category::Cs, Difficulty::Easy, "Que faut-il pour allumer l'ordinateur ?", 1, ["Un écran", "De l'électricité", "Un clavier", "Une souris"]),
    q!(Category::Cs, Difficulty::Easy, "Comment s'appelle le jeu qui se joue sur internet contre d'autres personnes ?", 1, ["Jeu solo", "Jeu en ligne", "Jeu de société", "Jeu physique"]),
    q!(Category::Cs, Difficulty::Easy, "Quelle touche sert à mettre un point dans le texte ?", 1, ["Espace", "Point", "Maj", "Échap"]),
    q!(Category::Cs, Difficulty::Easy, "Comment s'appelle la partie de l'ordinateur où l'on voit l'horloge ?", 1, ["Bureau", "Barre des tâches", "Corbeille", "Menu"]),
    q!(Category::Cs, Difficulty::Easy, "Quel programme sert à faire des présentations ?", 1, ["Calculatrice", "Présentations", "Navigateur", "Antivirus"]),
    q!(Category::Cs, Difficulty::Easy, "Quelle touche sert à écrire l'arobase @ ?", 1, ["La touche @", "La touche #", "La touche $", "La touche &"]),
    q!(Category::Cs, Difficulty::Easy, "Comment s'appelle le dispositif qui détecte le mouvement du doigt sur un portable ?", 1, ["Souris", "Pavé tactile", "Clavier", "Écran"]),
    // -- Moyenne (grande série) --
    q!(Category::Cs, Difficulty::Medium, "Quel langage sert à créer des pages web dynamiques ?", 1, ["SQL", "JavaScript", "Assembleur", "COBOL"]),
    q!(Category::Cs, Difficulty::Medium, "Que fait la commande « copier » ?", 1, ["Déplace le fichier", "Duplique le fichier", "Supprime le fichier", "Imprime le fichier"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'un fichier compressé ZIP ?", 1, ["Un fichier chiffré", "Un fichier de taille réduite", "Un fichier image", "Un fichier sonore"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce que le cloud en informatique ?", 1, ["Un virus", "Du stockage sur internet", "Un câble", "Un écran"]),
    q!(Category::Cs, Difficulty::Medium, "Que fait le raccourci Ctrl+C ?", 1, ["Coupe", "Copie", "Colle", "Supprime"]),
    q!(Category::Cs, Difficulty::Medium, "Que fait le raccourci Ctrl+V ?", 1, ["Copie", "Coupe", "Colle", "Annule"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'un navigateur ?", 1, ["Un jeu", "Un programme pour consulter le web", "Un antivirus", "Une imprimante"]),
    q!(Category::Cs, Difficulty::Medium, "Quelle extension a une image ?", 1, [".txt", ".jpg", ".doc", ".mp3"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'un virus informatique ?", 1, ["Un programme utile", "Un programme nuisible", "Un matériel", "Un jeu"]),
    q!(Category::Cs, Difficulty::Medium, "Que fait le raccourci Ctrl+Z ?", 1, ["Enregistre", "Annule", "Copie", "Imprime"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce que la mémoire ROM ?", 1, ["Mémoire temporaire", "Mémoire en lecture seule", "Mémoire en écriture", "Disque dur"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'un routeur ?", 1, ["Une imprimante", "Un appareil qui distribue internet", "Un clavier", "Un haut-parleur"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'un système d'exploitation ?", 1, ["Un programme de dessin", "Le programme qui gère l'ordinateur", "Un virus", "Un site web"]),
    q!(Category::Cs, Difficulty::Medium, "Que fait un double-clic sur une icône ?", 1, ["Sélectionne", "Ouvre le programme", "Supprime", "Renomme"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'un fichier joint ?", 1, ["Un virus", "Un fichier envoyé avec un courriel", "Un dossier", "Un lien"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'un mot de passe sûr ?", 1, ["Ton nom", "Un mélange de lettres, de chiffres et de symboles", "Que des chiffres", "Que des lettres"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'un moteur de recherche ?", 1, ["Un jeu", "Un programme qui cherche sur internet", "Une imprimante", "Un antivirus"]),
    q!(Category::Cs, Difficulty::Medium, "Que fait la touche F5 dans le navigateur ?", 1, ["Ferme", "Recharge la page", "Imprime", "Enregistre"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'un lien ?", 1, ["Un câble", "Une connexion vers une autre page", "Un fichier", "Une icône"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce que la mémoire cache ?", 1, ["Une mémoire lente", "Une mémoire rapide d'accès", "Un disque dur", "Une imprimante"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'un pare-feu (firewall) ?", 1, ["Un jeu", "Un coupe-feu qui protège le réseau", "Un moniteur", "Un clavier"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'une base de données ?", 1, ["Un fichier de musique", "Un ensemble de données organisées", "Un programme de dessin", "Un virus"]),
    q!(Category::Cs, Difficulty::Medium, "Que fait le raccourci Ctrl+S ?", 1, ["Copie", "Enregistre le fichier", "Colle", "Supprime"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'un réseau LAN ?", 1, ["Un réseau mondial", "Un réseau local", "Un réseau sans fil", "Un réseau de câbles"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'un fichier PDF ?", 1, ["Un fichier vidéo", "Un format de document", "Un fichier sonore", "Un programme"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce que le phishing ?", 1, ["Un jeu", "Une arnaque pour voler des données", "Un antivirus", "Un navigateur"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'un onglet de navigateur ?", 1, ["Une petite fenêtre", "Une page ouverte dans la barre", "Un bouton", "Une icône"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'un octet ?", 1, ["Un bit", "8 bits", "16 bits", "Un fichier"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'un fichier exécutable ?", 1, ["Un document", "Un programme prêt à être exécuté", "Une image", "Un son"]),
    q!(Category::Cs, Difficulty::Medium, "Quelle est la vitesse d'un processeur ?", 1, ["Les gigaoctets", "Les gigahertz", "Les mégaoctets", "Les pixels"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'un tableur ?", 1, ["Un document texte", "Un programme avec des cellules pour les nombres", "Un jeu", "Un navigateur"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce que l'historique du navigateur ?", 1, ["Les virus", "Les pages visitées", "Les téléchargements", "Les favoris"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'un marque-page ou favori ?", 1, ["Un virus", "Une page enregistrée", "Un fichier", "Une icône"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'une imprimante 3D ?", 1, ["Une imprimante normale", "Crée des objets en 3 dimensions", "Un scanner", "Une photocopieuse"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce que le Bluetooth ?", 1, ["Un câble", "Une connexion sans fil de courte portée", "Un virus", "Un programme"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'un dossier compressé ?", 1, ["Un dossier vide", "Un fichier qui regroupe et compresse", "Une icône", "Un raccourci"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'un hashtag ?", 1, ["Une étiquette avec #", "Un courriel", "Un fichier", "Un site web"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'un algorithme ?", 1, ["Un virus", "Une suite d'étapes pour résoudre quelque chose", "Un navigateur", "Un fichier"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce que l'écran bleu de la mort ?", 1, ["Un fond d'écran", "Une erreur grave de Windows", "Un économiseur", "Un jeu"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'un raccourci clavier ?", 1, ["Une touche", "Une combinaison de touches pour une action", "Une icône", "Un virus"]),
    // -- Difficile (grande série) --
    q!(Category::Cs, Difficulty::Hard, "Quel algorithme trie un tableau en comparant les paires ?", 1, ["Recherche binaire", "Tri à bulles", "Hash", "Récursion"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce qu'une adresse IP ?", 1, ["Un courriel", "L'adresse d'un appareil sur le réseau", "Un fichier", "Un virus"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce que la programmation orientée objet ?", 1, ["Un virus", "Un paradigme avec des classes et des objets", "Un langage", "Un algorithme"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce qu'un compilateur ?", 1, ["Un éditeur", "Traduit le code en langage machine", "Un navigateur", "Une imprimante"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce qu'une variable en programmation ?", 1, ["Un fichier", "Un espace mémoire avec une valeur", "Un bouton", "Une fenêtre"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce que la récursion ?", 1, ["Une boucle infinie", "Une fonction qui s'appelle elle-même", "Une erreur", "Un virus"]),
    q!(Category::Cs, Difficulty::Hard, "Quel protocole utilise HTTPS ?", 1, ["FTP", "HTTP sur TLS", "SMTP", "SSH"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce qu'une boucle for ?", 1, ["Une erreur", "Une structure qui répète du code", "Une variable", "Un fichier"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce que le Big Data ?", 1, ["Un jeu", "L'analyse de grands volumes de données", "Un virus", "Un câble"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce que la cybersécurité ?", 1, ["Un antivirus", "La protection des systèmes et des données", "Un navigateur", "Un réseau"]),
    q!(Category::Cs, Difficulty::Hard, "Quel langage sert à interroger les bases de données ?", 1, ["Python", "SQL", "HTML", "CSS"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce qu'un système embarqué ?", 1, ["Un virus", "Un système dans un autre appareil", "Un langage", "Un fichier"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce que le cloud computing ?", 1, ["Un jeu", "L'informatique en nuage", "Un virus", "Un câble"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce qu'une attaque DDoS ?", 1, ["Un virus", "La saturation d'un serveur", "Une erreur", "Un langage"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce que l'intelligence artificielle ?", 1, ["Un robot", "Des systèmes qui simulent l'intelligence", "Un jeu", "Un câble"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce qu'une API ?", 1, ["Un virus", "Une interface pour connecter des programmes", "Un fichier", "Une icône"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce que le chiffrement ?", 1, ["Un fichier", "Coder l'information pour la protéger", "Un navigateur", "Un virus"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce qu'une blockchain ?", 1, ["Un jeu", "Une chaîne de blocs décentralisée", "Un câble", "Un langage"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce qu'un interpréteur ?", 1, ["Un compilateur", "Exécute le code ligne par ligne", "Un éditeur", "Une imprimante"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce qu'un script ?", 1, ["Un virus", "Un programme de petite taille", "Un fichier image", "Un son"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce que le machine learning ?", 1, ["Un jeu", "L'apprentissage automatique", "Un virus", "Un câble"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce que la mémoire virtuelle ?", 1, ["Un virus", "Une mémoire qui utilise une partie du disque", "Un fichier", "Un dossier"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce qu'un microprocesseur ?", 1, ["Un haut-parleur", "Le cerveau de l'ordinateur", "Un moniteur", "Un clavier"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce qu'un réseau de neurones artificiels ?", 1, ["Un virus", "Un modèle d'apprentissage", "Un câble", "Un jeu"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce que le système hexadécimal ?", 1, ["Base 2", "Base 16", "Base 10", "Base 8"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce qu'une erreur 404 ?", 1, ["Un virus", "Page introuvable", "Un fichier", "Une icône"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce que la latence d'un réseau ?", 1, ["La vitesse de téléchargement", "Le retard dans la transmission", "L'envoi", "La largeur"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce que le logiciel libre (open source) ?", 1, ["Un virus", "Un logiciel au code visible", "Un fichier", "Un jeu"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce qu'un noyau (kernel) ?", 1, ["Un jeu", "Le cœur du système d'exploitation", "Un fichier", "Une icône"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce que le débogage (debugging) ?", 1, ["Un virus", "Trouver et corriger les erreurs", "Un langage", "Un réseau"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce qu'un tableau (array) ?", 1, ["Un virus", "Une structure de données", "Un fichier", "Une icône"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce qu'une fonction de hachage ?", 1, ["Un virus", "Convertit des données en une valeur fixe", "Un fichier", "Un langage"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce qu'un serveur ?", 1, ["Un virus", "Un ordinateur qui fournit des services", "Un moniteur", "Un clavier"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce qu'un client en informatique ?", 1, ["Un virus", "Un programme qui demande des services", "Un fichier", "Un dossier"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce que le stockage en cache ?", 1, ["Un virus", "Garder des données pour un accès rapide", "Un fichier", "Un câble"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce qu'un proxy ?", 1, ["Un virus", "Un intermédiaire de réseau", "Un fichier", "Une icône"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce que la virtualisation ?", 1, ["Un jeu", "Créer des versions virtuelles de ressources", "Un virus", "Un câble"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce qu'un langage de bas niveau ?", 1, ["HTML", "Assembleur", "Python", "JavaScript"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce qu'une vulnérabilité informatique ?", 1, ["Un virus", "Une faille de sécurité", "Un fichier", "Un jeu"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce qu'un patch ou correctif ?", 1, ["Un virus", "Une mise à jour qui corrige des défauts", "Un fichier", "Un câble"]),
    // ================= Géographie =================
    // -- Facile --
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de la France ?", 1, ["Londres", "Paris", "Rome", "Madrid"]),
    q!(Category::Geography, Difficulty::Easy, "Sur quel continent se trouve l'Espagne ?", 2, ["Afrique", "Asie", "Europe", "Amérique"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la planète sur laquelle nous vivons ?", 2, ["Mars", "Vénus", "La Terre", "Jupiter"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de l'Espagne ?", 2, ["Barcelone", "Séville", "Madrid", "Valence"]),
    q!(Category::Geography, Difficulty::Easy, "Quel océan se trouve à l'ouest de l'Espagne ?", 1, ["La Méditerranée", "L'Atlantique", "Le Pacifique", "L'Indien"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale du Portugal ?", 1, ["Porto", "Lisbonne", "Fátima", "Coimbra"]),
    q!(Category::Geography, Difficulty::Easy, "Quel pays a la forme d'une botte ?", 1, ["Grèce", "Italie", "Portugal", "Croatie"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de l'Italie ?", 1, ["Milan", "Rome", "Naples", "Florence"]),
    q!(Category::Geography, Difficulty::Easy, "Quel est le plus grand continent ?", 1, ["Afrique", "Asie", "Amérique", "Europe"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle mer baigne la côte est de l'Espagne ?", 1, ["L'Atlantique", "La Méditerranée", "La Cantabrique", "La Baltique"]),
    // -- Moyenne --
    q!(Category::Geography, Difficulty::Medium, "Quel est le plus grand pays du monde ?", 1, ["Chine", "Russie", "Canada", "États-Unis"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de l'Australie ?", 1, ["Sydney", "Canberra", "Melbourne", "Perth"]),
    q!(Category::Geography, Difficulty::Medium, "Quel océan baigne la côte ouest de l'Espagne ?", 0, ["L'Atlantique", "Le Pacifique", "L'Indien", "L'Arctique"]),
    q!(Category::Geography, Difficulty::Medium, "Lequel de ces fleuves se trouve en Espagne ?", 2, ["Le Nil", "L'Amazone", "L'Èbre", "Le Gange"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de l'Argentine ?", 1, ["Santiago", "Buenos Aires", "Montevideo", "Lima"]),
    q!(Category::Geography, Difficulty::Medium, "Quel désert se trouve au nord de l'Afrique ?", 1, ["Le Gobi", "Le Sahara", "Le Kalahari", "L'Atacama"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale du Japon ?", 2, ["Pékin", "Séoul", "Tokyo", "Bangkok"]),
    q!(Category::Geography, Difficulty::Medium, "Quel pays compte le plus d'habitants au monde ?", 1, ["Chine", "Inde", "États-Unis", "Brésil"]),
    q!(Category::Geography, Difficulty::Medium, "Quel est le plus petit pays du monde ?", 1, ["Monaco", "Le Vatican", "Saint-Marin", "Malte"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle chaîne de montagnes sépare l'Espagne de la France ?", 1, ["Les Alpes", "Les Pyrénées", "Sierra Nevada", "L'Atlas"]),
    // -- Difficile --
    q!(Category::Geography, Difficulty::Hard, "Quel détroit sépare l'Espagne du Maroc ?", 0, ["Celui de Gibraltar", "Celui de Messine", "Celui de Béring", "Celui d'Ormuz"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la plus haute montagne du monde ?", 2, ["Le Kilimandjaro", "Le mont Blanc", "L'Everest", "L'Aconcagua"]),
    q!(Category::Geography, Difficulty::Hard, "Quel pays a la forme d'une botte ?", 1, ["Grèce", "Italie", "Portugal", "Croatie"]),
    q!(Category::Geography, Difficulty::Hard, "Quel est le point le plus haut de l'Espagne péninsulaire ?", 1, ["Le Teide", "Le Mulhacén", "L'Aneto", "Le Naranjo"]),
    q!(Category::Geography, Difficulty::Hard, "Quel fleuve traverse Londres ?", 1, ["La Seine", "La Tamise", "Le Rhin", "Le Danube"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale de la Nouvelle-Zélande ?", 1, ["Auckland", "Wellington", "Christchurch", "Hamilton"]),
    q!(Category::Geography, Difficulty::Hard, "Quel détroit sépare l'Asie de l'Amérique ?", 1, ["Celui de Gibraltar", "Celui de Béring", "Celui de Magellan", "Le canal de Suez"]),
    q!(Category::Geography, Difficulty::Hard, "Quel est le désert le plus sec du monde ?", 2, ["Le Sahara", "Le Gobi", "Celui d'Atacama", "Celui d'Arabie"]),
    q!(Category::Geography, Difficulty::Hard, "Dans quel pays se trouve la majeure partie du fleuve Amazone ?", 2, ["Pérou", "Colombie", "Brésil", "Venezuela"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale de l'Égypte ?", 1, ["Alexandrie", "Le Caire", "Louxor", "Assouan"]),
    // -- Facile (grande série) --
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de l'Angleterre ?", 2, ["Manchester", "Liverpool", "Londres", "Oxford"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de l'Allemagne ?", 1, ["Munich", "Berlin", "Hambourg", "Francfort"]),
    q!(Category::Geography, Difficulty::Easy, "Quel pays se trouve au nord de l'Espagne ?", 1, ["Portugal", "France", "Maroc", "Andorre"]),
    q!(Category::Geography, Difficulty::Easy, "Quel est le plus grand océan du monde ?", 1, ["L'Atlantique", "Le Pacifique", "L'Indien", "L'Arctique"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale du Mexique ?", 1, ["Guadalajara", "Mexico", "Monterrey", "Cancún"]),
    q!(Category::Geography, Difficulty::Easy, "Sur quel continent se trouve le Brésil ?", 1, ["Afrique", "Amérique du Sud", "Asie", "Europe"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de la Russie ?", 1, ["Saint-Pétersbourg", "Moscou", "Kiev", "Varsovie"]),
    q!(Category::Geography, Difficulty::Easy, "Quel pays a la forme d'une étoile et se trouve au nord de l'Espagne ?", 1, ["Portugal", "France", "Maroc", "Italie"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de la Chine ?", 1, ["Shanghai", "Pékin", "Hong Kong", "Canton"]),
    q!(Category::Geography, Difficulty::Easy, "Quel fleuve traverse Madrid ?", 1, ["L'Èbre", "Le Manzanares", "Le Tage", "Le Guadalquivir"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de la Grèce ?", 1, ["Salonique", "Athènes", "Sparte", "Crète"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle mer sépare l'Espagne de l'Afrique ?", 1, ["La Cantabrique", "La Méditerranée", "L'Atlantique", "La Baltique"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de la Turquie ?", 1, ["Istanbul", "Ankara", "Izmir", "Bursa"]),
    q!(Category::Geography, Difficulty::Easy, "Dans quel pays se trouvent les pyramides de Gizeh ?", 1, ["Mexique", "Égypte", "Pérou", "Soudan"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale du Canada ?", 1, ["Toronto", "Ottawa", "Montréal", "Vancouver"]),
    q!(Category::Geography, Difficulty::Easy, "Quel continent compte le plus de pays ?", 1, ["Europe", "Afrique", "Asie", "Amérique"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de l'Inde ?", 1, ["Bombay", "New Delhi", "Calcutta", "Bangalore"]),
    q!(Category::Geography, Difficulty::Easy, "Quel pays est le plus peuplé d'Europe ?", 1, ["Allemagne", "Russie", "France", "Royaume-Uni"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale du Brésil ?", 1, ["Rio de Janeiro", "Brasilia", "São Paulo", "Salvador"]),
    q!(Category::Geography, Difficulty::Easy, "Quel fleuve traverse Paris ?", 1, ["Le Rhône", "La Seine", "La Loire", "La Garonne"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de la Suède ?", 1, ["Göteborg", "Stockholm", "Malmö", "Uppsala"]),
    q!(Category::Geography, Difficulty::Easy, "Sur quel continent se trouve l'Australie ?", 1, ["Asie", "Océanie", "Afrique", "Europe"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de la Norvège ?", 1, ["Bergen", "Oslo", "Trondheim", "Tromsø"]),
    q!(Category::Geography, Difficulty::Easy, "Quel pays est limitrophe de l'Espagne au sud ?", 1, ["France", "Maroc", "Portugal", "Italie"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de l'Irlande ?", 1, ["Cork", "Dublin", "Galway", "Belfast"]),
    q!(Category::Geography, Difficulty::Easy, "Quel océan se trouve à l'est de l'Amérique ?", 1, ["Le Pacifique", "L'Atlantique", "L'Indien", "L'Arctique"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de l'Argentine ?", 1, ["Rosario", "Buenos Aires", "Cordoue", "Mendoza"]),
    q!(Category::Geography, Difficulty::Easy, "Quel pays est célèbre pour ses tulipes et ses moulins ?", 1, ["Belgique", "Hollande", "Danemark", "Suisse"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de la Pologne ?", 1, ["Cracovie", "Varsovie", "Gdańsk", "Lodz"]),
    q!(Category::Geography, Difficulty::Easy, "Dans quel pays se trouve la tour Eiffel ?", 1, ["Italie", "France", "Espagne", "Belgique"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale du Pérou ?", 1, ["Cusco", "Lima", "Arequipa", "Trujillo"]),
    q!(Category::Geography, Difficulty::Easy, "Quel pays a la forme d'une botte ?", 1, ["Espagne", "Italie", "Portugal", "Grèce"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de l'Autriche ?", 1, ["Salzbourg", "Vienne", "Innsbruck", "Graz"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle mer se trouve au nord de l'Espagne ?", 1, ["La Méditerranée", "La Cantabrique", "L'Atlantique", "La Baltique"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale du Chili ?", 1, ["Valparaíso", "Santiago", "Concepción", "Antofagasta"]),
    q!(Category::Geography, Difficulty::Easy, "Sur quel continent se trouve le désert du Sahara ?", 1, ["Asie", "Afrique", "Amérique", "Australie"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de la Suisse ?", 1, ["Zurich", "Genève", "Berne", "Bâle"]),
    q!(Category::Geography, Difficulty::Easy, "Quel pays a la plus grande population du monde ?", 1, ["Chine", "Inde", "États-Unis", "Indonésie"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale du Danemark ?", 1, ["Aarhus", "Odense", "Copenhague", "Aalborg"]),
    q!(Category::Geography, Difficulty::Easy, "Quel est le fleuve le plus long du monde ?", 1, ["Le Nil", "L'Amazone", "Le Yangtsé", "Le Mississippi"]),
    // -- Moyenne (grande série) --
    q!(Category::Geography, Difficulty::Medium, "Quel est le fleuve le plus puissant du monde ?", 1, ["Le Nil", "L'Amazone", "Le Congo", "Le Yangtsé"]),
    q!(Category::Geography, Difficulty::Medium, "Quel pays a la plus grande superficie d'Europe ?", 1, ["Allemagne", "France", "Russie", "Ukraine"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale du Maroc ?", 1, ["Casablanca", "Rabat", "Marrakech", "Tanger"]),
    q!(Category::Geography, Difficulty::Medium, "Quel détroit sépare l'Europe de l'Afrique ?", 1, ["Celui de Béring", "Celui de Gibraltar", "Celui de Messine", "Celui d'Ormuz"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de la Colombie ?", 1, ["Medellín", "Bogota", "Cali", "Cartagène"]),
    q!(Category::Geography, Difficulty::Medium, "Quel pays d'Afrique est le plus peuplé ?", 1, ["Égypte", "Nigeria", "Éthiopie", "Afrique du Sud"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de l'Ukraine ?", 1, ["Lviv", "Kiev", "Kharkiv", "Odessa"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la plus longue chaîne de montagnes du monde ?", 1, ["Les Alpes", "Les Andes", "L'Himalaya", "Les Rocheuses"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale du Venezuela ?", 1, ["Maracaibo", "Caracas", "Valencia", "Barquisimeto"]),
    q!(Category::Geography, Difficulty::Medium, "Quel désert se trouve dans le sud-ouest de l'Amérique du Sud ?", 1, ["Le Sahara", "L'Atacama", "Le Gobi", "Le Kalahari"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de la Corée du Sud ?", 1, ["Busan", "Séoul", "Incheon", "Daegu"]),
    q!(Category::Geography, Difficulty::Medium, "Quel pays est le plus grand producteur de pétrole du Moyen-Orient ?", 1, ["Iran", "Arabie saoudite", "Irak", "Koweït"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de l'Algérie ?", 1, ["Oran", "Alger", "Constantine", "Tlemcen"]),
    q!(Category::Geography, Difficulty::Medium, "Quel fleuve sépare l'Espagne du Portugal dans son tronçon final ?", 1, ["L'Èbre", "Le Guadiana", "Le Tage", "Le Miño"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale des Philippines ?", 1, ["Cebu", "Manille", "Davao", "Quezon City"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle mer est la plus salée du monde ?", 1, ["La Méditerranée", "La mer Morte", "La Baltique", "La mer Noire"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de la Thaïlande ?", 1, ["Chiang Mai", "Bangkok", "Pattaya", "Phuket"]),
    q!(Category::Geography, Difficulty::Medium, "Quel pays possède la plus grande île du monde, le Groenland ?", 1, ["Canada", "Danemark", "Norvège", "Islande"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de l'Équateur ?", 1, ["Guayaquil", "Quito", "Cuenca", "Manta"]),
    q!(Category::Geography, Difficulty::Medium, "Quel océan baigne la côte ouest de l'Amérique du Sud ?", 1, ["L'Atlantique", "Le Pacifique", "L'Indien", "L'Arctique"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de l'Iran ?", 1, ["Téhéran", "Ispahan", "Chiraz", "Tabriz"]),
    q!(Category::Geography, Difficulty::Medium, "Quel pays d'Europe possède le plus de châteaux ?", 1, ["France", "Espagne", "Allemagne", "Italie"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale du Pakistan ?", 1, ["Karachi", "Islamabad", "Lahore", "Peshawar"]),
    q!(Category::Geography, Difficulty::Medium, "Quel est le plus grand lac du monde ?", 1, ["Le Victoria", "La mer Caspienne", "Le Supérieur", "Le Titicaca"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de la Bulgarie ?", 1, ["Plovdiv", "Sofia", "Varna", "Bourgas"]),
    q!(Category::Geography, Difficulty::Medium, "Quel pays se trouve entre la France et l'Espagne ?", 1, ["Portugal", "Andorre", "Monaco", "Luxembourg"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de la Serbie ?", 1, ["Novi Sad", "Belgrade", "Niš", "Kragujevac"]),
    q!(Category::Geography, Difficulty::Medium, "Quel pays compte le plus de volcans actifs ?", 1, ["Japon", "Indonésie", "Italie", "Mexique"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de la Roumanie ?", 1, ["Cluj", "Bucarest", "Brașov", "Timișoara"]),
    q!(Category::Geography, Difficulty::Medium, "Quel fleuve naît dans les Alpes et se jette dans la mer Noire ?", 1, ["Le Rhin", "Le Danube", "Le Pô", "L'Elbe"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale du Nigeria ?", 1, ["Lagos", "Abuja", "Kano", "Ibadan"]),
    q!(Category::Geography, Difficulty::Medium, "Quel archipel appartient à l'Espagne dans l'Atlantique ?", 1, ["Les îles Baléares", "Les îles Canaries", "Les Açores", "Les Cíes"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale du Vietnam ?", 1, ["Ho Chi Minh-Ville", "Hanoï", "Da Nang", "Haiphong"]),
    q!(Category::Geography, Difficulty::Medium, "Quel pays a la plus grande économie d'Afrique ?", 1, ["Égypte", "Nigeria", "Afrique du Sud", "Algérie"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de la Hongrie ?", 1, ["Debrecen", "Budapest", "Szeged", "Pécs"]),
    q!(Category::Geography, Difficulty::Medium, "Quel détroit sépare l'Angleterre de la France ?", 1, ["Celui de Gibraltar", "La Manche", "Celui de Béring", "Celui de Messine"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de Cuba ?", 1, ["Santiago", "La Havane", "Varadero", "Cienfuegos"]),
    q!(Category::Geography, Difficulty::Medium, "Quel pays d'Amérique du Sud n'a pas de littoral ?", 1, ["Équateur", "Bolivie", "Paraguay", "Uruguay"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de la Finlande ?", 1, ["Tampere", "Helsinki", "Turku", "Oulu"]),
    q!(Category::Geography, Difficulty::Medium, "Quel pays compte la plus grande population musulmane du monde ?", 1, ["Égypte", "Indonésie", "Pakistan", "Turquie"]),
    // -- Difficile (grande série) --
    q!(Category::Geography, Difficulty::Hard, "Quel est le point le plus profond de l'océan ?", 1, ["La fosse des Tonga", "La fosse des Mariannes", "La fosse de Java", "La fosse de Porto Rico"]),
    q!(Category::Geography, Difficulty::Hard, "Quel pays compte le plus de fuseaux horaires ?", 1, ["Russie", "France", "États-Unis", "Chine"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale du Kazakhstan ?", 1, ["Almaty", "Astana", "Chimkent", "Karaganda"]),
    q!(Category::Geography, Difficulty::Hard, "Quel fleuve se jette dans la mer d'Aral ?", 1, ["La Volga", "L'Amou-Daria", "L'Oural", "Le Don"]),
    q!(Category::Geography, Difficulty::Hard, "Quel est le point le plus haut d'Amérique ?", 1, ["L'Everest", "L'Aconcagua", "Le McKinley", "L'Ojos del Salado"]),
    q!(Category::Geography, Difficulty::Hard, "Quel pays est le plus grand exportateur de café ?", 1, ["Colombie", "Brésil", "Éthiopie", "Vietnam"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale de l'Ouzbékistan ?", 1, ["Samarcande", "Tachkent", "Boukhara", "Khiva"]),
    q!(Category::Geography, Difficulty::Hard, "Quel détroit sépare la Russie de l'Alaska ?", 1, ["Celui de Gibraltar", "Celui de Béring", "Celui de Magellan", "Celui de Drake"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale de l'Angola ?", 1, ["Luanda", "Benguela", "Huambo", "Lubango"]),
    q!(Category::Geography, Difficulty::Hard, "Quel pays possède le plus grand nombre de lacs ?", 1, ["Finlande", "Canada", "Russie", "Suède"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale du Myanmar (Birmanie) ?", 1, ["Mandalay", "Naypyidaw", "Rangoun", "Bagan"]),
    q!(Category::Geography, Difficulty::Hard, "Quel est le plus grand désert du monde ?", 1, ["Le Sahara", "L'Antarctique", "Le Gobi", "Celui d'Arabie"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale de l'Éthiopie ?", 1, ["Gondar", "Addis-Abeba", "Dire Dawa", "Mekele"]),
    q!(Category::Geography, Difficulty::Hard, "Quel pays possède le plus long littoral ?", 1, ["Australie", "Canada", "Russie", "Norvège"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale du Cambodge ?", 1, ["Siem Reap", "Phnom Penh", "Battambang", "Kampot"]),
    q!(Category::Geography, Difficulty::Hard, "Quel canal relie la Méditerranée à la mer Rouge ?", 1, ["Le canal de Panama", "Le canal de Suez", "Le canal de Kiel", "Le canal de Corinthe"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale du Sénégal ?", 1, ["Dakar", "Saint-Louis", "Thiès", "Touba"]),
    q!(Category::Geography, Difficulty::Hard, "Quel pays a le plus de frontières terrestres ?", 1, ["Russie", "Chine", "Brésil", "États-Unis"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale de la Mongolie ?", 1, ["Erdenet", "Oulan-Bator", "Darkhan", "Choibalsan"]),
    q!(Category::Geography, Difficulty::Hard, "Quel est le plus grand archipel du monde ?", 1, ["Les Philippines", "L'Indonésie", "Le Japon", "Les Maldives"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale de la Tunisie ?", 1, ["Sfax", "Tunis", "Sousse", "Bizerte"]),
    q!(Category::Geography, Difficulty::Hard, "Quel pays occupe la plus grande partie de la péninsule scandinave ?", 1, ["Norvège", "Suède", "Finlande", "Danemark"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale du Népal ?", 1, ["Pokhara", "Katmandou", "Lumbini", "Patan"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle mer se trouve entre l'Italie et les Balkans ?", 1, ["La mer Tyrrhénienne", "L'Adriatique", "La mer Ionienne", "La mer Égée"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale du Paraguay ?", 1, ["Ciudad del Este", "Asuncion", "Encarnación", "Luque"]),
    q!(Category::Geography, Difficulty::Hard, "Quel pays possède le plus haut volcan du monde ?", 1, ["Japon", "Équateur", "Italie", "Indonésie"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale de l'Azerbaïdjan ?", 1, ["Gandja", "Bakou", "Sumqayit", "Nakhitchevan"]),
    q!(Category::Geography, Difficulty::Hard, "Quel est le plus long fleuve d'Europe ?", 1, ["Le Danube", "La Volga", "Le Rhin", "L'Oural"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale de l'Uruguay ?", 1, ["Punta del Este", "Montevideo", "Salto", "Paysandú"]),
    q!(Category::Geography, Difficulty::Hard, "Quel pays a le plus grand PIB d'Afrique ?", 1, ["Égypte", "Nigeria", "Afrique du Sud", "Maroc"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale de la Croatie ?", 1, ["Split", "Zagreb", "Dubrovnik", "Rijeka"]),
    q!(Category::Geography, Difficulty::Hard, "Quel désert se trouve au nord de la Chine et de la Mongolie ?", 1, ["Le Sahara", "Le Gobi", "Le Taklamakan", "Celui d'Arabie"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale de la Jordanie ?", 1, ["Pétra", "Amman", "Aqaba", "Zarqa"]),
    q!(Category::Geography, Difficulty::Hard, "Quel pays est le plus grand producteur de riz au monde ?", 1, ["Inde", "Chine", "Indonésie", "Bangladesh"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale du Belize ?", 1, ["Belize City", "Belmopan", "San Ignacio", "Orange Walk"]),
    q!(Category::Geography, Difficulty::Hard, "Quel détroit se trouve entre l'Asie et l'Afrique ?", 1, ["Celui de Gibraltar", "Celui de Bab el-Mandeb", "Celui d'Ormuz", "Celui de Malacca"]),
];
