//! Partie 3 du banc français : Sciences et Art.
use super::super::questions::{q, Category, Difficulty, Question};

pub static QUESTIONS_FR_3: &[Question] = &[
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale de l'Islande ?", 1, ["Akureyri", "Reykjavik", "Keflavík", "Hafnarfjörður"]),
    q!(Category::Geography, Difficulty::Hard, "Quel pays d'Europe a le plus de volcans ?", 1, ["Espagne", "Italie", "Grèce", "France"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale du Zimbabwe ?", 1, ["Bulawayo", "Harare", "Gweru", "Mutare"]),
    q!(Category::Geography, Difficulty::Hard, "Quel canal traverse l'Amérique centrale ?", 1, ["Celui de Suez", "Celui de Panama", "Celui de Corinthe", "Celui de Kiel"]),
    q!(Category::Science, Difficulty::Easy, "Combien de planètes compte le système solaire ?", 1, ["7", "8", "9", "10"]),
    q!(Category::Science, Difficulty::Easy, "Quel gaz avons-nous besoin de respirer pour vivre ?", 2, ["L'azote", "Le dioxyde de carbone", "L'oxygène", "L'hélium"]),
    q!(Category::Science, Difficulty::Easy, "Quelle est la planète la plus proche du Soleil ?", 2, ["Vénus", "Mars", "Mercure", "La Terre"]),
    q!(Category::Science, Difficulty::Easy, "Quelle partie de la plante absorbe l'eau du sol ?", 1, ["La feuille", "La racine", "La fleur", "La tige"]),
    q!(Category::Science, Difficulty::Easy, "Combien de pattes a un insecte ?", 1, ["4", "6", "8", "10"]),
    q!(Category::Science, Difficulty::Easy, "Quel animal donne du lait ?", 1, ["La poule", "La vache", "Le poisson", "Le lézard"]),
    q!(Category::Science, Difficulty::Easy, "De quelle couleur est le sang oxygéné ?", 2, ["Bleu", "Vert", "Rouge", "Jaune"]),
    q!(Category::Science, Difficulty::Easy, "De quoi les plantes ont-elles besoin pour faire la photosynthèse ?", 0, ["La lumière du soleil", "L'obscurité", "Le vent", "La neige"]),
    q!(Category::Science, Difficulty::Easy, "Combien de dents a un adulte environ ?", 2, ["20", "28", "32", "36"]),
    q!(Category::Science, Difficulty::Easy, "Quel organe utilisons-nous pour penser ?", 1, ["Le cœur", "Le cerveau", "Le poumon", "Le foie"]),
    q!(Category::Science, Difficulty::Medium, "Quel organe pompe le sang dans le corps ?", 0, ["Le cœur", "Le poumon", "Le foie", "Le rein"]),
    q!(Category::Science, Difficulty::Medium, "Quel est le plus grand animal du monde ?", 0, ["La baleine bleue", "L'éléphant", "La girafe", "Le grand requin blanc"]),
    q!(Category::Science, Difficulty::Medium, "Quelle force nous maintient collés au sol ?", 0, ["La gravité", "Le magnétisme", "Le frottement", "L'inertie"]),
    q!(Category::Science, Difficulty::Medium, "Quelle planète est célèbre pour ses anneaux ?", 1, ["Mars", "Saturne", "Neptune", "Uranus"]),
    q!(Category::Science, Difficulty::Medium, "Quelle partie de l'œil contrôle la quantité de lumière ?", 1, ["La pupille", "L'iris", "Le cristallin", "La cornée"]),
    q!(Category::Science, Difficulty::Medium, "Quel est l'os le plus long du corps humain ?", 1, ["L'humérus", "Le fémur", "Le tibia", "La colonne"]),
    q!(Category::Science, Difficulty::Medium, "Quel gaz la photosynthèse produit-elle ?", 1, ["Le dioxyde de carbone", "L'oxygène", "L'azote", "L'hydrogène"]),
    q!(Category::Science, Difficulty::Medium, "Quel animal pond des œufs et n'est pas un oiseau ?", 1, ["Le chien", "La tortue", "Le dauphin", "La chauve-souris"]),
    q!(Category::Science, Difficulty::Medium, "Comment s'appelle le passage de l'eau liquide au gaz ?", 1, ["La condensation", "L'évaporation", "La solidification", "La filtration"]),
    q!(Category::Science, Difficulty::Medium, "Quel est le plus grand organe du corps humain ?", 2, ["Le foie", "Le cerveau", "La peau", "Les poumons"]),
    q!(Category::Science, Difficulty::Hard, "Quelle est la formule chimique de l'eau ?", 0, ["H2O", "CO2", "O2", "NaCl"]),
    q!(Category::Science, Difficulty::Hard, "Quelle particule a une charge négative ?", 0, ["L'électron", "Le proton", "Le neutron", "L'atome"]),
    q!(Category::Science, Difficulty::Hard, "Quelle est la plus grande planète du système solaire ?", 1, ["Mars", "Jupiter", "Neptune", "Vénus"]),
    q!(Category::Science, Difficulty::Hard, "Quelle unité mesure la force ?", 1, ["Le joule", "Le newton", "Le watt", "L'ampère"]),
    q!(Category::Science, Difficulty::Hard, "Quel type d'énergie possède un objet en mouvement ?", 1, ["Potentielle", "Cinétique", "Thermique", "Chimique"]),
    q!(Category::Science, Difficulty::Hard, "Où se trouve l'ADN de la cellule ?", 1, ["Dans le cytoplasme", "Dans le noyau", "Dans la membrane", "Dans la paroi"]),
    q!(Category::Science, Difficulty::Hard, "Quelle est la vitesse approximative de la lumière ?", 0, ["300.000 km/s", "150.000 km/s", "3.000 km/s", "1.000.000 km/s"]),
    q!(Category::Science, Difficulty::Hard, "Quel scientifique a formulé la théorie de la relativité ?", 1, ["Newton", "Einstein", "Bohr", "Planck"]),
    q!(Category::Science, Difficulty::Hard, "Combien d'os a un adulte humain ?", 1, ["106", "206", "306", "156"]),
    q!(Category::Science, Difficulty::Hard, "Quel gaz est le plus abondant dans l'atmosphère ?", 1, ["L'oxygène", "L'azote", "Le dioxyde de carbone", "L'argon"]),
    q!(Category::Science, Difficulty::Easy, "Quel est l'animal le plus rapide du monde ?", 2, ["Le lion", "Le cheval", "Le guépard", "Le zèbre"]),
    q!(Category::Science, Difficulty::Easy, "Quelle partie du corps utilises-tu pour respirer ?", 1, ["Le cœur", "Les poumons", "L'estomac", "Le foie"]),
    q!(Category::Science, Difficulty::Easy, "Combien de saisons compte l'année ?", 2, ["2", "3", "4", "6"]),
    q!(Category::Science, Difficulty::Easy, "Quel animal change de couleur pour se camoufler ?", 1, ["Le poisson", "Le caméléon", "Le serpent", "Le perroquet"]),
    q!(Category::Science, Difficulty::Easy, "Quelle partie du corps pompe le sang ?", 0, ["Le cœur", "Le cerveau", "Les poumons", "Les reins"]),
    q!(Category::Science, Difficulty::Easy, "Quel gaz respirent les plantes ?", 1, ["L'oxygène", "Le dioxyde de carbone", "L'azote", "L'hélium"]),
    q!(Category::Science, Difficulty::Easy, "Combien d'yeux a une araignée commune ?", 1, ["2", "8", "4", "6"]),
    q!(Category::Science, Difficulty::Easy, "Quelle planète est connue comme la planète rouge ?", 1, ["Vénus", "Mars", "Jupiter", "Mercure"]),
    q!(Category::Science, Difficulty::Easy, "Quel organe t'aide à digérer les aliments ?", 1, ["Le poumon", "L'estomac", "Le cœur", "Le cerveau"]),
    q!(Category::Science, Difficulty::Easy, "Quel est le plus grand animal de la terre ferme ?", 1, ["La girafe", "L'éléphant", "Le rhinocéros", "L'hippopotame"]),
    q!(Category::Science, Difficulty::Easy, "De quoi les plantes ont-elles besoin pour pousser en plus de l'eau ?", 1, ["La neige", "La lumière du soleil", "Le vent", "L'obscurité"]),
    q!(Category::Science, Difficulty::Easy, "Combien de pattes a un chat ?", 2, ["2", "6", "4", "8"]),
    q!(Category::Science, Difficulty::Easy, "Quelle étoile est la plus proche de la Terre ?", 1, ["La Lune", "Le Soleil", "Sirius", "Polaris"]),
    q!(Category::Science, Difficulty::Easy, "Quel animal dort debout ?", 1, ["Le chien", "Le cheval", "Le chat", "Le lapin"]),
    q!(Category::Science, Difficulty::Easy, "Quel sens utilise la langue ?", 1, ["L'odorat", "Le goût", "L'ouïe", "La vue"]),
    q!(Category::Science, Difficulty::Easy, "Quelle partie du corps te permet de sentir les odeurs ?", 1, ["Les yeux", "Le nez", "Les oreilles", "La bouche"]),
    q!(Category::Science, Difficulty::Easy, "Combien d'ailes a une abeille ?", 1, ["1", "2", "4", "6"]),
    q!(Category::Science, Difficulty::Easy, "Quel animal vit dans l'eau et respire par des branchies ?", 1, ["Le dauphin", "Le poisson", "La baleine", "Le phoque"]),
    q!(Category::Science, Difficulty::Easy, "Quel organe produit l'urine ?", 1, ["L'estomac", "Le rein", "Le cœur", "Le poumon"]),
    q!(Category::Science, Difficulty::Easy, "Quelle planète est la plus proche de la Terre ?", 1, ["Mars", "Vénus", "Jupiter", "Mercure"]),
    q!(Category::Science, Difficulty::Easy, "Quel animal est connu comme le meilleur ami de l'homme ?", 1, ["Le chat", "Le chien", "Le cheval", "Le perroquet"]),
    q!(Category::Science, Difficulty::Easy, "Combien de doigts a une main humaine ?", 3, ["4", "6", "3", "5"]),
    q!(Category::Science, Difficulty::Easy, "Quelle partie de la fleur produit les graines ?", 1, ["Le pétale", "Le pistil", "La feuille", "La tige"]),
    q!(Category::Science, Difficulty::Easy, "Quel animal est le roi de la jungle selon la tradition ?", 1, ["Le tigre", "Le lion", "L'ours", "Le loup"]),
    q!(Category::Science, Difficulty::Easy, "Quel gaz fait monter les bulles dans une boisson gazeuse ?", 1, ["L'oxygène", "Le dioxyde de carbone", "L'azote", "L'hydrogène"]),
    q!(Category::Science, Difficulty::Easy, "Combien de pattes a une araignée ?", 2, ["6", "10", "8", "4"]),
    q!(Category::Science, Difficulty::Easy, "Quel animal pond des œufs et vit dans l'eau ?", 1, ["Le chien", "La grenouille", "Le chat", "Le cochon"]),
    q!(Category::Science, Difficulty::Easy, "Quelle partie du corps utilises-tu pour voir ?", 1, ["Le nez", "Les yeux", "Les oreilles", "La langue"]),
    q!(Category::Science, Difficulty::Easy, "Quelle saison vient après l'hiver ?", 1, ["L'automne", "Le printemps", "L'été", "Aucune"]),
    q!(Category::Science, Difficulty::Easy, "Quel animal produit le miel ?", 1, ["La guêpe", "L'abeille", "La mouche", "Le moustique"]),
    q!(Category::Science, Difficulty::Easy, "Quelle partie de la plante se transforme en fruit ?", 1, ["La feuille", "La fleur", "La racine", "La tige"]),
    q!(Category::Science, Difficulty::Easy, "Combien de cœurs a un poulpe ?", 2, ["1", "2", "3", "4"]),
    q!(Category::Science, Difficulty::Easy, "Quel organe filtre le sang ?", 1, ["Le cœur", "Le rein", "Le poumon", "L'estomac"]),
    q!(Category::Science, Difficulty::Easy, "Quelle planète abrite la vie selon les scientifiques ?", 1, ["Mars", "La Terre", "Vénus", "Jupiter"]),
    q!(Category::Science, Difficulty::Easy, "Quel animal a la bosse ?", 1, ["L'éléphant", "Le chameau", "Le lama", "Le bison"]),
    q!(Category::Science, Difficulty::Easy, "De quoi les êtres vivants ont-ils besoin pour vivre ?", 1, ["L'obscurité", "L'eau", "La glace", "Le feu"]),
    q!(Category::Science, Difficulty::Easy, "Quelle partie du corps bat à chaque battement ?", 1, ["Le cerveau", "Le cœur", "Le poumon", "Le foie"]),
    q!(Category::Science, Difficulty::Easy, "Combien de planètes ont des anneaux ?", 1, ["Seulement Saturne", "Jupiter, Saturne, Uranus et Neptune", "Seulement Jupiter", "Aucune"]),
    q!(Category::Science, Difficulty::Easy, "Quel est l'animal le plus grand du monde ?", 1, ["L'éléphant", "La girafe", "Le chameau", "L'autruche"]),
    q!(Category::Science, Difficulty::Easy, "Quelle partie de la cellule contrôle tout ?", 1, ["La membrane", "Le noyau", "Le cytoplasme", "La paroi"]),
    q!(Category::Science, Difficulty::Medium, "Quels os protègent le cerveau ?", 1, ["Les côtes", "Le crâne", "La colonne", "Le bassin"]),
    q!(Category::Science, Difficulty::Medium, "Quel est l'animal le plus venimeux du monde ?", 1, ["Le cobra", "La méduse guêpe de mer", "L'araignée veuve noire", "La grenouille dard"]),
    q!(Category::Science, Difficulty::Medium, "Combien de litres de sang a un adulte ?", 1, ["1-2", "5-6", "10-12", "15-20"]),
    q!(Category::Science, Difficulty::Medium, "Quel type de roche se forme lorsque le magma refroidit ?", 1, ["Sédimentaire", "Igneuse", "Métamorphique", "Calcaire"]),
    q!(Category::Science, Difficulty::Medium, "Quel organe produit l'insuline ?", 1, ["Le foie", "Le pancréas", "Le rein", "La rate"]),
    q!(Category::Science, Difficulty::Medium, "Quelle planète a le jour le plus long du système solaire ?", 1, ["Mars", "Vénus", "Jupiter", "Mercure"]),
    q!(Category::Science, Difficulty::Medium, "Combien de paires de chromosomes a un être humain ?", 1, ["22", "23", "24", "46"]),
    q!(Category::Science, Difficulty::Medium, "Quelle force fait tomber les objets au sol ?", 1, ["Le magnétisme", "La gravité", "L'électricité", "La pression"]),
    q!(Category::Science, Difficulty::Medium, "Quel gaz est utilisé pour gonfler les ballons et s'envole ?", 1, ["L'oxygène", "L'hélium", "L'azote", "Le néon"]),
    q!(Category::Science, Difficulty::Medium, "Combien de cavités a le cœur humain ?", 2, ["2", "3", "4", "6"]),
    q!(Category::Science, Difficulty::Medium, "Quel animal peut régénérer sa queue ?", 1, ["Le chien", "Le lézard", "La tortue", "Le crocodile"]),
    q!(Category::Science, Difficulty::Medium, "Quel type d'énergie une plante utilise-t-elle pour vivre ?", 1, ["Électrique", "Solaire", "Nucléaire", "Éolienne"]),
    q!(Category::Science, Difficulty::Medium, "Quelle couche de la Terre est au centre ?", 1, ["La croûte", "Le noyau", "Le manteau", "L'atmosphère"]),
    q!(Category::Science, Difficulty::Medium, "Combien d'os a le corps d'un bébé ?", 1, ["206", "300", "150", "100"]),
    q!(Category::Science, Difficulty::Medium, "Quel instrument mesure la température ?", 1, ["Le baromètre", "Le thermomètre", "L'hygromètre", "Le compteur de vitesse"]),
    q!(Category::Science, Difficulty::Medium, "Quel est l'animal le plus vieux de la planète ?", 1, ["La tortue géante", "La baleine", "Le requin du Groenland", "L'éléphant"]),
    q!(Category::Science, Difficulty::Medium, "Quelle planète a la plus forte pression atmosphérique ?", 1, ["Mars", "Vénus", "Jupiter", "Saturne"]),
    q!(Category::Science, Difficulty::Medium, "Qu'est-ce qu'un écosystème ?", 1, ["Un animal", "Un ensemble d'êtres vivants et de leur milieu", "Un climat", "Une plante"]),
    q!(Category::Science, Difficulty::Medium, "Quelle vitamine la peau produit-elle avec le soleil ?", 1, ["Vitamine A", "Vitamine D", "Vitamine C", "Vitamine B12"]),
    q!(Category::Science, Difficulty::Medium, "Quel type d'animal est la baleine ?", 1, ["Un poisson", "Un mammifère", "Un reptile", "Un amphibien"]),
    q!(Category::Science, Difficulty::Medium, "Quel métal est liquide à température ambiante ?", 1, ["Le plomb", "Le mercure", "Le cuivre", "L'argent"]),
    q!(Category::Science, Difficulty::Medium, "Combien de vertèbres a la colonne humaine ?", 1, ["20", "33", "40", "50"]),
    q!(Category::Science, Difficulty::Medium, "Quelle planète a le jour le plus court ?", 1, ["La Terre", "Jupiter", "Vénus", "Mars"]),
    q!(Category::Science, Difficulty::Medium, "Quel processus transforme le vin en vinaigre ?", 1, ["La photosynthèse", "La fermentation", "L'évaporation", "L'oxydation"]),
    q!(Category::Science, Difficulty::Medium, "Quelle glande contrôle la croissance ?", 1, ["Le pancréas", "L'hypophyse", "Le foie", "La thyroïde"]),
    q!(Category::Science, Difficulty::Medium, "Qu'est-ce que l'ADN ?", 1, ["Une protéine", "Le matériel génétique", "Un sucre", "Une graisse"]),
    q!(Category::Science, Difficulty::Medium, "Quel animal est un amphibien ?", 1, ["Le serpent", "La grenouille", "Le crocodile", "Le pingouin"]),
    q!(Category::Science, Difficulty::Medium, "Quelle unité mesure le courant électrique ?", 1, ["Le watt", "L'ampère", "Le volt", "L'ohm"]),
    q!(Category::Science, Difficulty::Medium, "Quelle planète est la plus éloignée du Soleil ?", 1, ["Uranus", "Neptune", "Saturne", "Pluton"]),
    q!(Category::Science, Difficulty::Medium, "Quelle partie de l'œil fait la mise au point de l'image ?", 1, ["La pupille", "Le cristallin", "L'iris", "La rétine"]),
    q!(Category::Science, Difficulty::Medium, "Combien de dents de lait a un enfant ?", 1, ["20", "28", "32", "24"]),
    q!(Category::Science, Difficulty::Medium, "Quel gaz produit la respiration humaine ?", 1, ["L'oxygène", "Le dioxyde de carbone", "L'azote", "L'hydrogène"]),
    q!(Category::Science, Difficulty::Medium, "Quel animal est un mammifère qui vole ?", 1, ["L'aigle", "La chauve-souris", "Le papillon", "Le colibri"]),
    q!(Category::Science, Difficulty::Medium, "Qu'est-ce que la photosynthèse ?", 1, ["Respirer", "Produire de la nourriture grâce à la lumière", "Dormir", "Courir"]),
    q!(Category::Science, Difficulty::Medium, "Quel minéral forme les coquilles des mollusques ?", 1, ["Le fer", "Le carbonate de calcium", "Le sel", "Le quartz"]),
    q!(Category::Science, Difficulty::Medium, "Quel est l'organe le plus lourd du corps humain ?", 1, ["Le cerveau", "Le foie", "Le cœur", "Les poumons"]),
    q!(Category::Science, Difficulty::Medium, "Quel type d'énergie possède le vent ?", 1, ["Thermique", "Éolienne", "Nucléaire", "Chimique"]),
    q!(Category::Science, Difficulty::Medium, "Quel animal a le plus gros cerveau proportionnellement ?", 1, ["L'éléphant", "Le dauphin", "L'être humain", "La baleine"]),
    q!(Category::Science, Difficulty::Medium, "Qu'est-ce qu'un fossile ?", 1, ["Une roche", "Des restes d'êtres vivants anciens", "Un minéral", "Un volcan"]),
    q!(Category::Science, Difficulty::Medium, "Combien de pattes a un crabe ?", 1, ["6", "8", "10", "12"]),
    q!(Category::Science, Difficulty::Hard, "Quel est l'élément le plus abondant de l'univers ?", 1, ["L'oxygène", "L'hydrogène", "Le carbone", "L'hélium"]),
    q!(Category::Science, Difficulty::Hard, "Quelle théorie explique l'origine de l'univers ?", 1, ["L'évolution", "Le Big Bang", "La dérive des continents", "La relativité"]),
    q!(Category::Science, Difficulty::Hard, "Quel est le numéro atomique du carbone ?", 1, ["12", "6", "14", "8"]),
    q!(Category::Science, Difficulty::Hard, "Quelle particule est dans le noyau et est positive ?", 1, ["L'électron", "Le proton", "Le neutron", "Le photon"]),
    q!(Category::Science, Difficulty::Hard, "Quel scientifique a proposé la sélection naturelle ?", 1, ["Lamarck", "Darwin", "Mendel", "Wallace"]),
    q!(Category::Science, Difficulty::Hard, "Quelle est la vitesse du son dans l'air ?", 1, ["340 km/h", "340 m/s", "1.000 m/s", "3.000 km/h"]),
    q!(Category::Science, Difficulty::Hard, "Quel organe produit la bile ?", 1, ["Le pancréas", "Le foie", "L'estomac", "La rate"]),
    q!(Category::Science, Difficulty::Hard, "Quel type de rayonnement a le plus d'énergie ?", 1, ["Les infrarouges", "Le gamma", "Les ultraviolets", "Les micro-ondes"]),
    q!(Category::Science, Difficulty::Hard, "Quelle est l'échelle qui mesure les tremblements de terre ?", 1, ["Celle de Beaufort", "Celle de Richter", "Celle de Celsius", "Celle de Kelvin"]),
    q!(Category::Science, Difficulty::Hard, "Qu'est-ce qu'un trou noir ?", 1, ["Une étoile", "Une région de gravité extrême", "Une planète", "Une nébuleuse"]),
    q!(Category::Science, Difficulty::Hard, "Combien d'éléments compte le tableau périodique naturel ?", 1, ["92", "118", "100", "120"]),
    q!(Category::Science, Difficulty::Hard, "Quel gaz noble est le plus abondant dans l'air ?", 1, ["L'hélium", "L'argon", "Le néon", "Le krypton"]),
    q!(Category::Science, Difficulty::Hard, "Quel scientifique a découvert la pénicilline ?", 1, ["Pasteur", "Fleming", "Koch", "Jenner"]),
    q!(Category::Science, Difficulty::Hard, "Quelle unité mesure la pression ?", 1, ["Le watt", "Le pascal", "Le joule", "Le newton"]),
    q!(Category::Science, Difficulty::Hard, "Quel processus les cellules utilisent-elles pour se reproduire ?", 1, ["La photosynthèse", "La mitose", "La respiration", "La digestion"]),
    q!(Category::Science, Difficulty::Hard, "Quelle est la planète la plus froide du système solaire ?", 1, ["Neptune", "Uranus", "Pluton", "Mars"]),
    q!(Category::Science, Difficulty::Hard, "Quel métal est le meilleur conducteur d'électricité ?", 1, ["Le cuivre", "L'argent", "L'or", "Le fer"]),
    q!(Category::Science, Difficulty::Hard, "Quelle enzyme digère les protéines dans l'estomac ?", 1, ["L'amylase", "La pepsine", "La lipase", "L'insuline"]),
    q!(Category::Science, Difficulty::Hard, "Quelle étoile est la plus proche du Soleil ?", 1, ["Sirius", "Proxima du Centaure", "Alpha du Centaure A", "Bételgeuse"]),
    q!(Category::Science, Difficulty::Hard, "Quel type de cellule n'a pas de noyau ?", 1, ["L'eucaryote", "La procaryote", "La végétale", "L'animale"]),
    q!(Category::Science, Difficulty::Hard, "Quelle est la formule du dioxyde de carbone ?", 1, ["CO", "CO2", "C2O", "CO3"]),
    q!(Category::Science, Difficulty::Hard, "Quelle hormone régule le sucre dans le sang ?", 1, ["L'adrénaline", "L'insuline", "La thyroxine", "La mélatonine"]),
    q!(Category::Science, Difficulty::Hard, "Quel phénomène provoque les marées ?", 1, ["Le vent", "La Lune et le Soleil", "Le fond marin", "Les courants"]),
    q!(Category::Science, Difficulty::Hard, "Combien de litres d'eau contient le corps humain ?", 1, ["10", "42", "75", "20"]),
    q!(Category::Science, Difficulty::Hard, "Quel scientifique a découvert la radioactivité naturelle ?", 1, ["Curie", "Becquerel", "Röntgen", "Rutherford"]),
    q!(Category::Science, Difficulty::Hard, "Qu'est-ce que l'entropie ?", 1, ["Une force", "Une mesure du désordre", "Un élément", "Une planète"]),
    q!(Category::Science, Difficulty::Hard, "Quelle couche de l'atmosphère contient la couche d'ozone ?", 1, ["La troposphère", "La stratosphère", "La mésosphère", "L'ionosphère"]),
    q!(Category::Science, Difficulty::Hard, "Quel animal a le venin le plus puissant du monde ?", 1, ["Le cobra royal", "La grenouille dard dorée", "L'araignée à toile", "Le scorpion"]),
    q!(Category::Science, Difficulty::Hard, "Quelle unité mesure l'énergie des aliments ?", 1, ["Le watt", "La calorie", "Le joule", "L'ampère"]),
    q!(Category::Science, Difficulty::Hard, "Quelle planète a le champ magnétique le plus fort ?", 1, ["La Terre", "Jupiter", "Saturne", "Mars"]),
    q!(Category::Science, Difficulty::Hard, "Quel scientifique a formulé les lois du mouvement ?", 1, ["Einstein", "Newton", "Galilée", "Kepler"]),
    q!(Category::Science, Difficulty::Hard, "Qu'est-ce qu'un quark ?", 1, ["Une étoile", "Une particule fondamentale", "Un atome", "Une planète"]),
    q!(Category::Science, Difficulty::Hard, "Combien de paires de nerfs crâniens y a-t-il ?", 1, ["10", "12", "14", "16"]),
    q!(Category::Science, Difficulty::Hard, "Quel type d'onde est la lumière ?", 1, ["Mécanique", "Électromagnétique", "Sonore", "Gravitationnelle"]),
    q!(Category::Science, Difficulty::Hard, "Quel est le minéral le plus dur de la nature ?", 1, ["Le quartz", "Le diamant", "Le rubis", "Le corindon"]),
    q!(Category::Science, Difficulty::Hard, "Quel processus produit de l'énergie dans le Soleil ?", 1, ["La combustion", "La fusion nucléaire", "La fission nucléaire", "L'oxydation"]),
    q!(Category::Science, Difficulty::Hard, "Quel scientifique a proposé l'héliocentrisme ?", 1, ["Ptolémée", "Copernic", "Aristote", "Tycho Brahe"]),
    q!(Category::Science, Difficulty::Hard, "Qu'est-ce que la théorie de l'évolution ?", 1, ["Une loi physique", "Le changement des espèces au fil du temps", "Une religion", "Une expérience"]),
    q!(Category::Science, Difficulty::Hard, "Combien d'étoiles compte le système solaire ?", 1, ["Des milliers", "Une", "Deux", "Huit"]),
    q!(Category::Science, Difficulty::Hard, "Quelle particule transporte la force électromagnétique ?", 1, ["Le gluon", "Le photon", "Le boson W", "Le graviton"]),
    q!(Category::Art, Difficulty::Easy, "Combien de couleurs a l'arc-en-ciel ?", 2, ["5", "6", "7", "8"]),
    q!(Category::Art, Difficulty::Easy, "Qui a peint le Guernica ?", 0, ["Pablo Picasso", "Salvador Dalí", "Francisco de Goya", "Diego Velázquez"]),
    q!(Category::Art, Difficulty::Easy, "Quel instrument a des touches blanches et noires ?", 0, ["Le piano", "La guitare", "Le violon", "La flûte"]),
    q!(Category::Art, Difficulty::Easy, "Quelle couleur résulte du mélange du bleu et du jaune ?", 1, ["Rouge", "Vert", "Violet", "Orange"]),
    q!(Category::Art, Difficulty::Easy, "Comment s'appelle la personne qui sculpte ?", 1, ["Peintre", "Sculpteur", "Musicien", "Architecte"]),
    q!(Category::Art, Difficulty::Easy, "Quel instrument a six cordes ?", 1, ["Le violon", "La guitare", "Le piano", "La trompette"]),
    q!(Category::Art, Difficulty::Easy, "Qui a peint « La Nuit étoilée » ?", 1, ["Pablo Picasso", "Vincent van Gogh", "Salvador Dalí", "Claude Monet"]),
    q!(Category::Art, Difficulty::Easy, "Quelle danse est typique de l'Andalousie ?", 0, ["Le flamenco", "La sardane", "La jota", "Le paso doble"]),
    q!(Category::Art, Difficulty::Easy, "Combien de cordes a un violon ?", 1, ["2", "4", "6", "8"]),
    q!(Category::Art, Difficulty::Easy, "Quel matériau a été utilisé pour sculpter le David de Michel-Ange ?", 1, ["Le bois", "Le marbre", "Le bronze", "L'argile"]),
    q!(Category::Art, Difficulty::Medium, "Qui a écrit Don Quichotte de la Manche ?", 0, ["Miguel de Cervantes", "Lope de Vega", "Federico García Lorca", "Garcilaso de la Vega"]),
    q!(Category::Art, Difficulty::Medium, "Quel peintre est célèbre pour ses tournesols ?", 1, ["Monet", "Vincent van Gogh", "Renoir", "Cézanne"]),
    q!(Category::Art, Difficulty::Medium, "Quel style architectural caractérise la Sagrada Família ?", 0, ["Le modernisme", "Le gothique", "Le baroque", "Le néoclassique"]),
    q!(Category::Art, Difficulty::Medium, "Quel instrument est un instrument à percussion ?", 1, ["La flûte", "Le tambour", "Le violon", "La guitare"]),
    q!(Category::Art, Difficulty::Medium, "Qui a peint « Les Ménines » ?", 1, ["Francisco de Goya", "Diego Velázquez", "El Greco", "Zurbarán"]),
    q!(Category::Art, Difficulty::Medium, "Combien de symphonies complètes Beethoven a-t-il écrites ?", 1, ["5", "9", "12", "7"]),
    q!(Category::Art, Difficulty::Medium, "Quel poète a écrit « Romancero gitano » ?", 1, ["Antonio Machado", "Federico García Lorca", "Juan Ramón Jiménez", "Quevedo"]),
    q!(Category::Art, Difficulty::Medium, "Quel instrument à vent est fait de métal ?", 1, ["La flûte", "La trompette", "La clarinette", "Le hautbois"]),
    q!(Category::Art, Difficulty::Medium, "Qui a composé « Les Quatre Saisons » ?", 0, ["Antonio Vivaldi", "Mozart", "Bach", "Haendel"]),
    q!(Category::Art, Difficulty::Medium, "Quelle couleur obtient-on en mélangeant le rouge et le blanc ?", 1, ["Marron", "Rose", "Orange", "Gris"]),
    q!(Category::Art, Difficulty::Hard, "Quel peintre est célèbre pour ses montres fondues ?", 0, ["Salvador Dalí", "Pablo Picasso", "Claude Monet", "Edvard Munch"]),
    q!(Category::Art, Difficulty::Hard, "Qui a composé la Neuvième Symphonie ?", 0, ["Beethoven", "Mozart", "Bach", "Chopin"]),
    q!(Category::Art, Difficulty::Hard, "Quel mouvement artistique inclut Vincent van Gogh ?", 0, ["Le postimpressionnisme", "Le cubisme", "Le surréalisme", "L'impressionnisme"]),
    q!(Category::Art, Difficulty::Hard, "Quel peintre de la Renaissance a peint la chapelle Sixtine ?", 1, ["Léonard de Vinci", "Michel-Ange", "Raphaël", "Titien"]),
    q!(Category::Art, Difficulty::Hard, "Quel architecte a conçu la Sagrada Família ?", 0, ["Antoni Gaudí", "Calatrava", "Mies van der Rohe", "Le Corbusier"]),
    q!(Category::Art, Difficulty::Hard, "Quel écrivain a écrit « La Regenta » ?", 1, ["Benito Pérez Galdós", "Leopoldo Alas « Clarín »", "Emilia Pardo Bazán", "Unamuno"]),
    q!(Category::Art, Difficulty::Hard, "Quel peintre était surnommé « El Greco » ?", 0, ["Domenikos Theotokopoulos", "Jérôme Bosch", "Francisco de Goya", "Velázquez"]),
    q!(Category::Art, Difficulty::Hard, "Quelle opéra Bizet a-t-il composée ?", 0, ["Carmen", "La Traviata", "Aïda", "Tosca"]),
    q!(Category::Art, Difficulty::Hard, "Quel mouvement artistique Picasso a-t-il mené avec le « Guernica » ?", 1, ["Le surréalisme", "Le cubisme", "L'impressionnisme", "L'expressionnisme"]),
    q!(Category::Art, Difficulty::Hard, "Qui a écrit « La casa de Bernarda Alba » ?", 0, ["Federico García Lorca", "Valle-Inclán", "Jacinto Benavente", "Alejandro Casona"]),
    q!(Category::Art, Difficulty::Easy, "Quel artiste dessine des bandes dessinées ?", 1, ["Le sculpteur", "Le dessinateur", "Le musicien", "Le danseur"]),
    q!(Category::Art, Difficulty::Easy, "Quelle couleur est le résultat du mélange du rouge et du bleu ?", 1, ["Vert", "Violet", "Orange", "Marron"]),
    q!(Category::Art, Difficulty::Easy, "Qui a peint le célèbre tableau de la Joconde ?", 1, ["Michel-Ange", "Léonard de Vinci", "Picasso", "Dalí"]),
    q!(Category::Art, Difficulty::Easy, "Quel instrument se joue en soufflant ?", 1, ["La guitare", "La flûte", "Le piano", "Le tambour"]),
    q!(Category::Art, Difficulty::Easy, "Qu'est-ce qu'un poème ?", 1, ["Une peinture", "Une œuvre écrite en vers", "Une chanson", "Une sculpture"]),
    q!(Category::Art, Difficulty::Easy, "Quel instrument à cordes a 12 cordes en paires ?", 1, ["La guitare espagnole", "Le luth", "La bandurria", "L'ukulélé"]),
    q!(Category::Art, Difficulty::Easy, "Quelle couleur résulte du mélange du rouge et du jaune ?", 1, ["Vert", "Orange", "Violet", "Bleu"]),
    q!(Category::Art, Difficulty::Easy, "Qui a peint « La Gioconda » ?", 1, ["Velázquez", "Léonard de Vinci", "Goya", "Picasso"]),
    q!(Category::Art, Difficulty::Easy, "Quel instrument se joue avec une baguette ?", 1, ["Le violon", "Le tambour", "La flûte", "Le piano"]),
    q!(Category::Art, Difficulty::Easy, "Qu'est-ce qu'un portrait ?", 1, ["Un paysage", "Un dessin d'une personne", "Une chanson", "Un bâtiment"]),
    q!(Category::Art, Difficulty::Easy, "Quel peintre espagnol a peint « Les Fusillades du 3 mai » ?", 1, ["Velázquez", "Goya", "Picasso", "El Greco"]),
    q!(Category::Art, Difficulty::Easy, "Quel instrument a 88 touches ?", 1, ["L'orgue", "Le piano", "L'accordéon", "L'harmonica"]),
    q!(Category::Art, Difficulty::Easy, "Quelle couleur est plus claire que le rouge ?", 1, ["Le bleu", "Le rose", "L'orange", "Le violet"]),
    q!(Category::Art, Difficulty::Easy, "Qui a sculpté « Le Penseur » ?", 1, ["Michel-Ange", "Rodin", "Dalí", "Gaudí"]),
    q!(Category::Art, Difficulty::Easy, "Qu'est-ce qu'une sculpture ?", 1, ["Une peinture", "Une œuvre en trois dimensions", "Une chanson", "Un poème"]),
    q!(Category::Art, Difficulty::Easy, "Quelle danse se danse en couple et est très populaire en Argentine ?", 1, ["Le flamenco", "Le tango", "La salsa", "La valse"]),
    q!(Category::Art, Difficulty::Easy, "Combien de cordes a un ukulélé ?", 1, ["6", "4", "8", "2"]),
    q!(Category::Art, Difficulty::Easy, "Quelle couleur a le ciel un jour dégagé ?", 1, ["Gris", "Bleu", "Vert", "Jaune"]),
    q!(Category::Art, Difficulty::Easy, "Qui a peint « Le Cri » ?", 1, ["Van Gogh", "Munch", "Dalí", "Klimt"]),
    q!(Category::Art, Difficulty::Easy, "Quel instrument se joue avec un archet ?", 1, ["La guitare", "Le violon", "La trompette", "Le saxophone"]),
    q!(Category::Art, Difficulty::Easy, "Qu'est-ce qu'un conte ?", 1, ["Un poème", "Un récit court", "Une peinture", "Une chanson"]),
    q!(Category::Art, Difficulty::Easy, "Quelle danse est typique de la Catalogne ?", 1, ["La jota", "La sardane", "Le flamenco", "La muñeira"]),
    q!(Category::Art, Difficulty::Easy, "Quelle couleur résulte du mélange de toutes les couleurs ?", 1, ["Le blanc", "Le noir", "Le gris", "Le marron"]),
    q!(Category::Art, Difficulty::Easy, "Qui a écrit « Platero y yo » ?", 1, ["Unamuno", "Juan Ramón Jiménez", "García Lorca", "Cervantes"]),
    q!(Category::Art, Difficulty::Easy, "Quel est le plus grand instrument de l'orchestre ?", 1, ["Le violon", "La contrebasse", "La flûte", "La clarinette"]),
    q!(Category::Art, Difficulty::Easy, "Qu'est-ce qu'une fresque murale ?", 1, ["Une chanson", "Une grande peinture sur un mur", "Un poème", "Une sculpture"]),
    q!(Category::Art, Difficulty::Easy, "Quel peintre est célèbre pour ses montres molles ?", 1, ["Picasso", "Dalí", "Miró", "Kandinsky"]),
    q!(Category::Art, Difficulty::Easy, "Combien de notes a une gamme musicale ?", 2, ["5", "6", "7", "8"]),
    q!(Category::Art, Difficulty::Easy, "Qui a écrit « La Celestina » ?", 1, ["Quevedo", "Fernando de Rojas", "Cervantes", "Lope de Vega"]),
    q!(Category::Art, Difficulty::Easy, "Quel instrument a un soufflet ?", 1, ["La guitare", "L'accordéon", "Le violon", "La batterie"]),
    q!(Category::Art, Difficulty::Easy, "Quelle couleur a l'herbe ?", 1, ["Bleu", "Vert", "Jaune", "Rouge"]),
    q!(Category::Art, Difficulty::Easy, "Qui a peint le « Guernica » ?", 1, ["Dalí", "Picasso", "Miró", "Gris"]),
    q!(Category::Art, Difficulty::Easy, "Qu'est-ce qu'un opéra ?", 1, ["Un poème", "Une pièce de théâtre chantée", "Une sculpture", "Un roman"]),
    q!(Category::Art, Difficulty::Easy, "Quel instrument de percussion se joue avec les mains ?", 1, ["Le piano", "Le tambour", "Les maracas", "La flûte"]),
    q!(Category::Art, Difficulty::Easy, "Qui a écrit « La Petite Souris coquette » ?", 1, ["Un auteur anonyme", "Charles Perrault", "Les frères Grimm", "Andersen"]),
    q!(Category::Art, Difficulty::Easy, "Qu'est-ce qu'un sonnet ?", 1, ["Un tableau", "Un poème de 14 vers", "Une chanson", "Une danse"]),
    q!(Category::Art, Difficulty::Easy, "Quelle couleur est le résultat du mélange du blanc et du noir ?", 1, ["Le marron", "Le gris", "Le rose", "Le beige"]),
    q!(Category::Art, Difficulty::Easy, "Qui a peint les célèbres tournesols ?", 1, ["Monet", "Van Gogh", "Cézanne", "Gauguin"]),
    q!(Category::Art, Difficulty::Easy, "Quelle danse est typique des Asturies et de la Galice ?", 1, ["La jota", "La muñeira", "La sardane", "Le chotis"]),
    q!(Category::Art, Difficulty::Easy, "Combien de cordes a une contrebasse ?", 1, ["2", "4", "6", "8"]),
    q!(Category::Art, Difficulty::Medium, "Qui a écrit « Cent ans de solitude » ?", 1, ["Pablo Neruda", "Gabriel García Márquez", "Jorge Luis Borges", "Julio Cortázar"]),
    q!(Category::Art, Difficulty::Medium, "Quel peintre a fondé le cubisme avec Picasso ?", 1, ["Matisse", "Georges Braque", "Mondrian", "Duchamp"]),
    q!(Category::Art, Difficulty::Medium, "Quelle œuvre Cervantes a-t-il écrite comme premier roman moderne ?", 1, ["La Galatée", "Le Quichotte", "Nouvelles exemplaires", "Persilès"]),
    q!(Category::Art, Difficulty::Medium, "Quel compositeur a écrit « Le Messie » ?", 1, ["Bach", "Haendel", "Vivaldi", "Mozart"]),
    q!(Category::Art, Difficulty::Medium, "Quel artiste espagnol est célèbre pour ses sculptures en fer ?", 1, ["Miró", "Chillida", "Dalí", "Tàpies"]),
    q!(Category::Art, Difficulty::Medium, "Quelle écrivaine a écrit « Los pazos de Ulloa » ?", 1, ["Pardo Bazán", "Galdós", "Clarín", "Valera"]),
    q!(Category::Art, Difficulty::Medium, "Quel mouvement artistique est celui du « Cri » de Munch ?", 1, ["Le cubisme", "L'expressionnisme", "L'impressionnisme", "Le surréalisme"]),
    q!(Category::Art, Difficulty::Medium, "Quel instrument est un bois ?", 1, ["La trompette", "La clarinette", "Le trombone", "Le tuba"]),
    q!(Category::Art, Difficulty::Medium, "Qui a peint « La Persistance de la mémoire » ?", 1, ["Picasso", "Dalí", "Miró", "Magritte"]),
    q!(Category::Art, Difficulty::Medium, "Quel poète a écrit « Campos de Castilla » ?", 1, ["García Lorca", "Antonio Machado", "Juan Ramón Jiménez", "Quevedo"]),
    q!(Category::Art, Difficulty::Medium, "Quelle opéra Mozart a-t-il écrite en italien ?", 1, ["Carmen", "Les Noces de Figaro", "Aïda", "Tosca"]),
    q!(Category::Art, Difficulty::Medium, "Quel peintre néerlandais est célèbre pour ses autoportraits ?", 1, ["Vermeer", "Rembrandt", "Brueghel", "Bosch"]),
    q!(Category::Art, Difficulty::Medium, "Quel écrivain a écrit « Fortunata y Jacinta » ?", 1, ["Clarín", "Galdós", "Valle-Inclán", "Blasco Ibáñez"]),
    q!(Category::Art, Difficulty::Medium, "Quel style architectural ont les arcs brisés ?", 1, ["Le roman", "Le gothique", "Le renaissance", "Le baroque"]),
    q!(Category::Art, Difficulty::Medium, "Quel peintre impressionniste a peint « Impression, soleil levant » ?", 1, ["Renoir", "Claude Monet", "Degas", "Pissarro"]),
    q!(Category::Art, Difficulty::Medium, "Quel écrivain a écrit « Niebla » ?", 1, ["Ortega y Gasset", "Unamuno", "Azorín", "Baroja"]),
    q!(Category::Art, Difficulty::Medium, "Quel compositeur est connu comme « le père de la symphonie » ?", 1, ["Mozart", "Haydn", "Bach", "Beethoven"]),
    q!(Category::Art, Difficulty::Medium, "Quelle peintre mexicaine est célèbre pour ses autoportraits ?", 1, ["Rita Hayworth", "Frida Kahlo", "Leonora Carrington", "María Izquierdo"]),
    q!(Category::Art, Difficulty::Medium, "Quelle pièce de théâtre Lope de Vega a-t-il écrite sur un commandeur ?", 1, ["El burlador", "Fuenteovejuna", "La dama boba", "Peribáñez"]),
    q!(Category::Art, Difficulty::Medium, "Quel instrument est un cuivre ?", 1, ["Le hautbois", "Le trombone", "Le basson", "La flûte"]),
    q!(Category::Art, Difficulty::Medium, "Quel écrivain a écrit « La Colmena » ?", 1, ["Cela", "Delibes", "Goytisolo", "Marsé"]),
    q!(Category::Art, Difficulty::Medium, "Quel architecte a conçu la Cité des Arts de Valence ?", 1, ["Gaudí", "Calatrava", "Moneo", "Bofill"]),
    q!(Category::Art, Difficulty::Medium, "Quel peintre flamand a peint « Le Jardin des délices » ?", 1, ["Brueghel", "Jérôme Bosch", "Rubens", "Van Eyck"]),
    q!(Category::Art, Difficulty::Medium, "Quel compositeur a écrit « Le Sacre du printemps » ?", 1, ["Debussy", "Stravinski", "Ravel", "Satie"]),
    q!(Category::Art, Difficulty::Medium, "Quel écrivain a écrit « La vérité sur le cas Savolta » ?", 1, ["Mendoza", "Vázquez Montalbán", "Muñoz Molina", "Cercas"]),
    q!(Category::Art, Difficulty::Medium, "Qu'est-ce que l'aquarelle ?", 1, ["Une sculpture", "Une peinture à l'eau", "Un poème", "Une danse"]),
    q!(Category::Art, Difficulty::Medium, "Quel peintre italien a peint « La Naissance de Vénus » ?", 1, ["Michel-Ange", "Botticelli", "Raphaël", "Titien"]),
    q!(Category::Art, Difficulty::Medium, "Quel écrivain a écrit « Luces de Bohemia » ?", 1, ["Unamuno", "Valle-Inclán", "Baroja", "Azorín"]),
    q!(Category::Art, Difficulty::Medium, "Quel musicien est connu comme « le roi du rock » ?", 1, ["John Lennon", "Elvis Presley", "Michael Jackson", "Bob Dylan"]),
    q!(Category::Art, Difficulty::Medium, "Quel instrument a des pédales ?", 1, ["La guitare", "L'orgue", "Le violon", "La flûte"]),
    q!(Category::Art, Difficulty::Medium, "Quel poète a écrit « La voz a ti debida » ?", 1, ["Aleixandre", "Salinas", "Guillén", "Cernuda"]),
    q!(Category::Art, Difficulty::Medium, "Quel peintre espagnol a peint le « Christ de Velázquez » ?", 1, ["Goya", "Velázquez", "El Greco", "Zurbarán"]),
    q!(Category::Art, Difficulty::Medium, "Qu'est-ce que le baroque ?", 1, ["Une danse", "Un style artistique du XVIIe siècle", "Un instrument", "Un poème"]),
    q!(Category::Art, Difficulty::Medium, "Quel écrivain a écrit « La famille de Pascual Duarte » ?", 1, ["Cela", "Delibes", "Laforet", "Aldecoa"]),
    q!(Category::Art, Difficulty::Medium, "Quel compositeur a écrit la « Messe en si mineur » ?", 1, ["Mozart", "Bach", "Haendel", "Beethoven"]),
    q!(Category::Art, Difficulty::Medium, "Quel sculpteur grec a créé la Vénus de Milo ?", 1, ["Phidias", "Praxitèle", "Alexandre d'Antioche", "Myron"]),
    q!(Category::Art, Difficulty::Medium, "Quelle écrivaine a écrit « Nada » ?", 1, ["Carmen Martín Gaite", "Carmen Laforet", "Ana María Matute", "Rosa Montero"]),
    q!(Category::Art, Difficulty::Medium, "Quel peintre français est le père de l'impressionnisme ?", 1, ["Cézanne", "Monet", "Degas", "Manet"]),
    q!(Category::Art, Difficulty::Medium, "Qu'est-ce qu'un ballet ?", 1, ["Un tableau", "Une danse classique", "Un poème", "Un opéra"]),
    q!(Category::Art, Difficulty::Medium, "Quel instrument a un tube courbé et un pavillon ?", 1, ["La clarinette", "Le saxophone", "La flûte", "Le hautbois"]),
    q!(Category::Art, Difficulty::Hard, "Qui a peint le triptyque « Le Jardin des délices » ?", 1, ["Rubens", "Jérôme Bosch", "Dürer", "Cranach"]),
    q!(Category::Art, Difficulty::Hard, "Quel écrivain a inventé le terme « esperpento » ?", 1, ["Unamuno", "Valle-Inclán", "Ortega", "Baroja"]),
    q!(Category::Art, Difficulty::Hard, "Quelle opéra de Puccini se déroule au Japon ?", 1, ["La Bohème", "Madama Butterfly", "Tosca", "Turandot"]),
    q!(Category::Art, Difficulty::Hard, "Quel peintre russe a fondé l'art abstrait ?", 1, ["Malevitch", "Kandinsky", "Chagall", "Répine"]),
    q!(Category::Art, Difficulty::Hard, "Quel écrivain a écrit « Rayuela » ?", 1, ["Borges", "Cortázar", "García Márquez", "Vargas Llosa"]),
    q!(Category::Art, Difficulty::Hard, "Quel architecte a conçu la tour de la Sagrada Família ?", 1, ["Calatrava", "Gaudí", "Domènech", "Puig"]),
    q!(Category::Art, Difficulty::Hard, "Quel peintre a été le maître de Velázquez ?", 1, ["El Greco", "Pacheco", "Zurbarán", "Murillo"]),
    q!(Category::Art, Difficulty::Hard, "Quel compositeur a écrit « L'Anneau du Nibelung » ?", 1, ["Mozart", "Wagner", "Brahms", "Schubert"]),
    q!(Category::Art, Difficulty::Hard, "Quel écrivain a écrit « La Regenta » ?", 1, ["Galdós", "Clarín", "Pardo Bazán", "Valera"]),
    q!(Category::Art, Difficulty::Hard, "Quel peintre espagnol a peint « L'Enterrement du comte d'Orgaz » ?", 1, ["Velázquez", "El Greco", "Goya", "Ribera"]),
    q!(Category::Art, Difficulty::Hard, "Quelle œuvre de Shakespeare se déroule au Danemark ?", 1, ["Othello", "Hamlet", "Macbeth", "Roméo et Juliette"]),
    q!(Category::Art, Difficulty::Hard, "Quel artiste pop a peint des boîtes de soupe ?", 1, ["Lichtenstein", "Warhol", "Hockney", "Basquiat"]),
    q!(Category::Art, Difficulty::Hard, "Quel écrivain a écrit « La saga/fuga de J.B. » ?", 1, ["Torrente Ballester", "Cela", "Delibes", "Sánchez Ferlosio"]),
    q!(Category::Art, Difficulty::Hard, "Quel compositeur a écrit « Tableaux d'une exposition » ?", 1, ["Tchaïkovski", "Moussorgski", "Rachmaninov", "Prokofiev"]),
    q!(Category::Art, Difficulty::Hard, "Quel peintre était surnommé « Le Divin » ?", 1, ["Léonard", "Raphaël", "Michel-Ange", "Titien"]),
    q!(Category::Art, Difficulty::Hard, "Quel poète a écrit « Poeta en Nueva York » ?", 1, ["Machado", "García Lorca", "Alberti", "Hernández"]),
    q!(Category::Art, Difficulty::Hard, "Quel sculpteur a réalisé le « David » de bronze ?", 1, ["Michel-Ange", "Donatello", "Verrocchio", "Ghiberti"]),
    q!(Category::Art, Difficulty::Hard, "Quel peintre italien a peint « L'École d'Athènes » ?", 1, ["Léonard", "Raphaël", "Michel-Ange", "Botticelli"]),
    q!(Category::Art, Difficulty::Hard, "Quel écrivain a écrit « El Jarama » ?", 1, ["Delibes", "Sánchez Ferlosio", "Cela", "Goytisolo"]),
    q!(Category::Art, Difficulty::Hard, "Quel musicien a composé « Les Variations Goldberg » ?", 1, ["Mozart", "Bach", "Beethoven", "Chopin"]),
    q!(Category::Art, Difficulty::Hard, "Quel peintre français a fondé le cubisme ?", 1, ["Cézanne", "Braque", "Matisse", "Derain"]),
    q!(Category::Art, Difficulty::Hard, "Qui a écrit « Mémoire de mes putains tristes » ?", 1, ["Allende", "García Márquez", "Vargas Llosa", "Fuentes"]),
    q!(Category::Art, Difficulty::Hard, "Quel compositeur a écrit la « Symphonie fantastique » ?", 1, ["Berlioz", "Liszt", "Schumann", "Mendelssohn"]),
    q!(Category::Art, Difficulty::Hard, "Quel peintre néerlandais a peint « La Laitière » ?", 1, ["Rembrandt", "Vermeer", "Hals", "Steen"]),
    q!(Category::Art, Difficulty::Hard, "Quel dramaturge a écrit « Noces de sang » ?", 1, ["Valle-Inclán", "García Lorca", "Benavente", "Casona"]),
    q!(Category::Art, Difficulty::Hard, "Quel architecte a conçu le Guggenheim de Bilbao ?", 1, ["Moneo", "Gehry", "Hadid", "Rogers"]),
    q!(Category::Art, Difficulty::Hard, "Quel écrivain a écrit « L'Invention de Morel » ?", 1, ["Cortázar", "Borges", "Bioy Casares", "Mujica"]),
    q!(Category::Art, Difficulty::Hard, "Quel compositeur a écrit le « Requiem » inachevé ?", 1, ["Bach", "Mozart", "Haydn", "Schubert"]),
    q!(Category::Art, Difficulty::Hard, "Quel peintre anglais a peint « La Charette de foin » ?", 1, ["Turner", "Constable", "Gainsborough", "Hogarth"]),
    q!(Category::Art, Difficulty::Hard, "Quel poète a écrit « Feuilles d'herbe » ?", 1, ["Poe", "Whitman", "Dickinson", "Frost"]),
    q!(Category::Art, Difficulty::Hard, "Quel peintre norvégien est l'auteur du « Cri » ?", 1, ["Klimt", "Munch", "Schiele", "Kollwitz"]),
    q!(Category::Art, Difficulty::Hard, "Quel écrivain a écrit « Los santos inocentes » ?", 1, ["Delibes", "Cela", "Laforet", "Grosso"]),
    q!(Category::Art, Difficulty::Hard, "Quel compositeur a écrit « Le Lac des cygnes » ?", 1, ["Moussorgski", "Tchaïkovski", "Rimski-Korsakov", "Borodine"]),
    q!(Category::Art, Difficulty::Hard, "Quel peintre est l'auteur de l'« Autoportrait » à l'oreille bandée ?", 1, ["Gauguin", "Van Gogh", "Cézanne", "Toulouse-Lautrec"]),
    q!(Category::Art, Difficulty::Hard, "Quel architecte a construit l'Alhambra ?", 1, ["Les Rois catholiques", "Les nasrides", "Les Omeyyades", "Les Almohades"]),
    q!(Category::Art, Difficulty::Hard, "Quel écrivain a écrit « Tiempo de silencio » ?", 1, ["Luis Martín-Santos", "Benet", "Goytisolo", "Marsé"]),
];
