//! Partie 5 du banc français : questions ouvertes.
use super::super::questions::{q_open, Category, Difficulty, Question};

pub static QUESTIONS_FR_5: &[Question] = &[
    // -- Art --
    q_open!(Category::Art, Difficulty::Hard, "Qui a composé la Neuvième Symphonie ?", "Beethoven"),
    // -- Tabou --
    q_open!(Category::Taboo, Difficulty::Easy, "Animal de ferme qui pond des œufs. Qu'est-ce que c'est ?", "poule"),
    q_open!(Category::Taboo, Difficulty::Medium, "Instrument avec des touches qui sert à faire des calculs. Qu'est-ce que c'est ?", "calculatrice"),
    // -- Mathématiques --
    q_open!(Category::Math, Difficulty::Easy, "Combien font 7 + 8 ?", "15"),
    q_open!(Category::Math, Difficulty::Easy, "Combien font 9 x 9 ?", "81"),
    q_open!(Category::Math, Difficulty::Easy, "Combien de côtés a un carré ?", "4"),
    q_open!(Category::Math, Difficulty::Easy, "Quelle est la moitié de 50 ?", "25"),
    q_open!(Category::Math, Difficulty::Easy, "Combien font 100 - 35 ?", "65"),
    q_open!(Category::Math, Difficulty::Easy, "Combien de minutes a une heure ?", "60"),
    q_open!(Category::Math, Difficulty::Easy, "Combien font 12 x 4 ?", "48"),
    q_open!(Category::Math, Difficulty::Easy, "Combien de jours a une année normale ?", "365"),
    q_open!(Category::Math, Difficulty::Easy, "Combien font 3 x 9 ?", "27"),
    q_open!(Category::Math, Difficulty::Easy, "Combien de mois a une année ?", "12"),
    q_open!(Category::Math, Difficulty::Medium, "Combien font 50 % de 90 ?", "45"),
    q_open!(Category::Math, Difficulty::Medium, "Combien font 2 puissance 10 ?", "1024"),
    q_open!(Category::Math, Difficulty::Medium, "Combien de degrés mesure un angle droit ?", "90"),
    q_open!(Category::Math, Difficulty::Medium, "Quelle est la racine carrée de 81 ?", "9"),
    q_open!(Category::Math, Difficulty::Medium, "Combien font 5/6 de 60 ?", "50"),
    q_open!(Category::Math, Difficulty::Medium, "Combien font 25 % de 400 ?", "100"),
    q_open!(Category::Math, Difficulty::Medium, "Quel est le périmètre d'un carré de côté 8 ?", "32"),
    q_open!(Category::Math, Difficulty::Medium, "Combien font 0,5 x 10 ?", "5"),
    q_open!(Category::Math, Difficulty::Medium, "Combien de côtés a un octogone ?", "8"),
    q_open!(Category::Math, Difficulty::Medium, "Combien font 13 x 3 ?", "39"),
    q_open!(Category::Math, Difficulty::Hard, "Quelle est la solution de x + 5 = 20 ?", "15"),
    q_open!(Category::Math, Difficulty::Hard, "Combien font 3 puissance 4 ?", "81"),
    q_open!(Category::Math, Difficulty::Hard, "Combien de degrés font les angles d'un carré ?", "360"),
    q_open!(Category::Math, Difficulty::Hard, "Combien font la racine carrée de 169 ?", "13"),
    q_open!(Category::Math, Difficulty::Hard, "Quel est le plus petit nombre premier ?", "2"),
    q_open!(Category::Math, Difficulty::Hard, "Combien font 10 % de 350 ?", "35"),
    q_open!(Category::Math, Difficulty::Hard, "Combien font 2 x 2 x 2 x 2 x 2 ?", "32"),
    q_open!(Category::Math, Difficulty::Hard, "Quelle est la valeur de pi avec deux décimales ?", "3,14"),
    q_open!(Category::Math, Difficulty::Hard, "Combien font 100 divisé par 8 ?", "12,5"),
    q_open!(Category::Math, Difficulty::Hard, "Combien de faces a un cube ?", "6"),
    // -- Histoire --
    q_open!(Category::History, Difficulty::Easy, "En quelle année l'homme a-t-il marché sur la Lune ?", "1969"),
    q_open!(Category::History, Difficulty::Easy, "Qui a peint la Joconde ?", "Léonard de Vinci"),
    q_open!(Category::History, Difficulty::Easy, "Dans quelle ville se trouve le Colisée ?", "Rome"),
    q_open!(Category::History, Difficulty::Easy, "Comment s'appelle l'écriture de l'Égypte ancienne ?", "Hiéroglyphes"),
    q_open!(Category::History, Difficulty::Easy, "Quel peuple a construit les pyramides ?", "Égyptiens"),
    q_open!(Category::History, Difficulty::Easy, "Qui a été le premier homme à marcher sur la Lune ?", "Neil Armstrong"),
    q_open!(Category::History, Difficulty::Easy, "Quel empereur romain a été assassiné aux ides de mars ?", "Jules César"),
    q_open!(Category::History, Difficulty::Easy, "En quelle année s'est terminée la Première Guerre mondiale ?", "1918"),
    q_open!(Category::History, Difficulty::Easy, "Quel célèbre navire a fait naufrage en 1912 ?", "Titanic"),
    q_open!(Category::History, Difficulty::Easy, "Qui a été le roi de France surnommé « le Roi Soleil » ?", "Louis XIV"),
    q_open!(Category::History, Difficulty::Medium, "En quelle année l'Amérique a-t-elle été découverte ?", "1492"),
    q_open!(Category::History, Difficulty::Medium, "Qui a écrit l'Iliade ?", "Homère"),
    q_open!(Category::History, Difficulty::Medium, "Quel empereur a divisé l'Empire romain ?", "Théodose"),
    q_open!(Category::History, Difficulty::Medium, "En quelle année Constantinople est-elle tombée ?", "1453"),
    q_open!(Category::History, Difficulty::Medium, "Qui a été le premier président des États-Unis ?", "George Washington"),
    q_open!(Category::History, Difficulty::Medium, "Quel traité a divisé le monde entre l'Espagne et le Portugal ?", "Tordesillas"),
    q_open!(Category::History, Difficulty::Medium, "Qui a été le pharaon de la grande pyramide ?", "Khéops"),
    q_open!(Category::History, Difficulty::Medium, "En quelle année s'est terminée la Seconde Guerre mondiale ?", "1945"),
    q_open!(Category::History, Difficulty::Medium, "Quelle civilisation a construit le Machu Picchu ?", "Incas"),
    q_open!(Category::History, Difficulty::Medium, "Qui a été le dirigeant le plus connu de la Révolution française ?", "Robespierre"),
    q_open!(Category::History, Difficulty::Hard, "Quelle bataille a vaincu Napoléon en 1815 ?", "Waterloo"),
    q_open!(Category::History, Difficulty::Hard, "En quelle année a été signé le Traité de Tordesillas ?", "1494"),
    q_open!(Category::History, Difficulty::Hard, "Qui a été le premier empereur de Chine ?", "Qin Shi Huang"),
    q_open!(Category::History, Difficulty::Hard, "Quel roi anglais a signé la Magna Carta ?", "Jean sans Terre"),
    q_open!(Category::History, Difficulty::Hard, "En quelle année a commencé la Révolution française ?", "1789"),
    q_open!(Category::History, Difficulty::Hard, "Quel scientifique a formulé les lois de la gravitation ?", "Newton"),
    q_open!(Category::History, Difficulty::Hard, "Quelle ville a été la capitale de l'Empire aztèque ?", "Tenochtitlan"),
    q_open!(Category::History, Difficulty::Hard, "Qui a été le dernier roi de la maison de Bourbon en Espagne en 1931 ?", "Alphonse XIII"),
    q_open!(Category::History, Difficulty::Hard, "En quelle année a été fondée l'ONU ?", "1945"),
    q_open!(Category::History, Difficulty::Hard, "Quel explorateur a découvert le détroit au sud de l'Amérique ?", "Magellan"),
    // -- Informatique --
    q_open!(Category::Cs, Difficulty::Easy, "Combien d'octets compte un kilooctet ?", "1024"),
    q_open!(Category::Cs, Difficulty::Easy, "Comment s'appelle le symbole du courrier électronique ?", "Arobase"),
    q_open!(Category::Cs, Difficulty::Easy, "Quel système d'exploitation a créé Microsoft ?", "Windows"),
    q_open!(Category::Cs, Difficulty::Easy, "Comment s'appelle l'écran de l'ordinateur ?", "Moniteur"),
    q_open!(Category::Cs, Difficulty::Easy, "Quel appareil sert à imprimer ?", "Imprimante"),
    q_open!(Category::Cs, Difficulty::Easy, "Comment s'appelle le programme pour consulter les pages web ?", "Navigateur"),
    q_open!(Category::Cs, Difficulty::Easy, "Quel réseau connecte les ordinateurs du monde entier ?", "Internet"),
    q_open!(Category::Cs, Difficulty::Easy, "Combien de touches a un clavier standard environ ?", "104"),
    q_open!(Category::Cs, Difficulty::Easy, "Quoi utilise-t-on pour déplacer le curseur ?", "Souris"),
    q_open!(Category::Cs, Difficulty::Easy, "Comment s'appelle le courrier électronique en anglais ?", "Email"),
    q_open!(Category::Cs, Difficulty::Medium, "Quel langage est utilisé pour les pages web ?", "HTML"),
    q_open!(Category::Cs, Difficulty::Medium, "Que fait Ctrl+C ?", "Copier"),
    q_open!(Category::Cs, Difficulty::Medium, "Que fait Ctrl+V ?", "Coller"),
    q_open!(Category::Cs, Difficulty::Medium, "Quelle unité est plus petite, le bit ou l'octet ?", "Bit"),
    q_open!(Category::Cs, Difficulty::Medium, "Que signifie WWW ?", "World Wide Web"),
    q_open!(Category::Cs, Difficulty::Medium, "Comment s'appelle le programme qui protège des virus ?", "Antivirus"),
    q_open!(Category::Cs, Difficulty::Medium, "Quel réseau est sans fil ?", "Wi-Fi"),
    q_open!(Category::Cs, Difficulty::Medium, "Que signifie USB ?", "Universal Serial Bus"),
    q_open!(Category::Cs, Difficulty::Medium, "Quelle extension a un document de texte simple ?", "TXT"),
    q_open!(Category::Cs, Difficulty::Medium, "Quelle touche efface le caractère à gauche ?", "Retour arrière"),
    q_open!(Category::Cs, Difficulty::Hard, "Que signifie CPU ?", "Unité centrale de traitement"),
    q_open!(Category::Cs, Difficulty::Hard, "Quelle base numérique utilise l'ordinateur ?", "Binaire"),
    q_open!(Category::Cs, Difficulty::Hard, "Que signifie IA ?", "Intelligence artificielle"),
    q_open!(Category::Cs, Difficulty::Hard, "Qu'est-ce qu'un bug ?", "Erreur"),
    q_open!(Category::Cs, Difficulty::Hard, "Que signifie HTTP ?", "HyperText Transfer Protocol"),
    q_open!(Category::Cs, Difficulty::Hard, "Quel langage a Cargo comme gestionnaire ?", "Rust"),
    q_open!(Category::Cs, Difficulty::Hard, "Quelle commande liste les fichiers sous Linux ?", "LS"),
    q_open!(Category::Cs, Difficulty::Hard, "Que signifie DNS ?", "Domain Name System"),
    q_open!(Category::Cs, Difficulty::Hard, "Qu'est-ce que le logiciel ?", "Programmes"),
    q_open!(Category::Cs, Difficulty::Hard, "Quel système d'exploitation utilise le noyau Linux ?", "Linux"),
    // -- Géographie --
    q_open!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de l'Espagne ?", "Madrid"),
    q_open!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de l'Italie ?", "Rome"),
    q_open!(Category::Geography, Difficulty::Easy, "Sur quel continent se trouve l'Égypte ?", "Afrique"),
    q_open!(Category::Geography, Difficulty::Easy, "Quelle est la capitale du Portugal ?", "Lisbonne"),
    q_open!(Category::Geography, Difficulty::Easy, "Quel pays a la forme d'une botte ?", "Italie"),
    q_open!(Category::Geography, Difficulty::Easy, "Quel est le plus grand océan ?", "Pacifique"),
    q_open!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de l'Allemagne ?", "Berlin"),
    q_open!(Category::Geography, Difficulty::Easy, "Quel fleuve traverse Paris ?", "Seine"),
    q_open!(Category::Geography, Difficulty::Easy, "Quelle est la capitale du Japon ?", "Tokyo"),
    q_open!(Category::Geography, Difficulty::Easy, "Quelle mer baigne la côte est de l'Espagne ?", "Méditerranée"),
    q_open!(Category::Geography, Difficulty::Medium, "Quelle est la plus haute montagne du monde ?", "Everest"),
    q_open!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de l'Australie ?", "Canberra"),
    q_open!(Category::Geography, Difficulty::Medium, "Quel désert se trouve au nord de l'Afrique ?", "Sahara"),
    q_open!(Category::Geography, Difficulty::Medium, "Quelle est la capitale du Canada ?", "Ottawa"),
    q_open!(Category::Geography, Difficulty::Medium, "Quelle chaîne de montagnes sépare l'Espagne de la France ?", "Pyrénées"),
    q_open!(Category::Geography, Difficulty::Medium, "Quel est le plus long fleuve du monde ?", "Nil"),
    q_open!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de l'Argentine ?", "Buenos Aires"),
    q_open!(Category::Geography, Difficulty::Medium, "Quel pays est le plus grand d'Europe ?", "Russie"),
    q_open!(Category::Geography, Difficulty::Medium, "Quelle est la capitale du Brésil ?", "Brasilia"),
    q_open!(Category::Geography, Difficulty::Medium, "Quelle mer se trouve au nord de l'Espagne ?", "Cantabrique"),
    q_open!(Category::Geography, Difficulty::Hard, "Quel est le point le plus profond de l'océan ?", "Fosse des Mariannes"),
    q_open!(Category::Geography, Difficulty::Hard, "Quelle est la capitale de la Nouvelle-Zélande ?", "Wellington"),
    q_open!(Category::Geography, Difficulty::Hard, "Quel détroit sépare l'Asie de l'Amérique ?", "Béring"),
    q_open!(Category::Geography, Difficulty::Hard, "Quel est le désert le plus sec du monde ?", "Atacama"),
    q_open!(Category::Geography, Difficulty::Hard, "Quelle est la capitale de la Turquie ?", "Ankara"),
    q_open!(Category::Geography, Difficulty::Hard, "Quel pays a le plus d'habitants au monde ?", "Inde"),
    q_open!(Category::Geography, Difficulty::Hard, "Quelle est la capitale de la Suisse ?", "Berne"),
    q_open!(Category::Geography, Difficulty::Hard, "Quel canal relie la Méditerranée à la mer Rouge ?", "Suez"),
    q_open!(Category::Geography, Difficulty::Hard, "Quel est le plus grand lac du monde ?", "Caspienne"),
    q_open!(Category::Geography, Difficulty::Hard, "Quelle est la capitale de l'Islande ?", "Reykjavik"),
    // -- Sciences --
    q_open!(Category::Science, Difficulty::Easy, "Quelle planète est connue comme la planète rouge ?", "Mars"),
    q_open!(Category::Science, Difficulty::Easy, "Quel gaz faut-il pour respirer ?", "Oxygène"),
    q_open!(Category::Science, Difficulty::Easy, "Combien de pattes a une araignée ?", "8"),
    q_open!(Category::Science, Difficulty::Easy, "Quel animal est le plus grand du monde ?", "Baleine"),
    q_open!(Category::Science, Difficulty::Easy, "Combien de saisons a une année ?", "4"),
    q_open!(Category::Science, Difficulty::Easy, "Quel organe pompe le sang ?", "Cœur"),
    q_open!(Category::Science, Difficulty::Easy, "Quelle planète est la plus proche du Soleil ?", "Mercure"),
    q_open!(Category::Science, Difficulty::Easy, "Combien de jours a une semaine ?", "7"),
    q_open!(Category::Science, Difficulty::Easy, "Quel animal produit le miel ?", "Abeille"),
    q_open!(Category::Science, Difficulty::Easy, "Combien de doigts as-tu au total ?", "20"),
    q_open!(Category::Science, Difficulty::Medium, "Quel est l'os le plus long du corps ?", "Fémur"),
    q_open!(Category::Science, Difficulty::Medium, "Quelle force nous maintient au sol ?", "Gravité"),
    q_open!(Category::Science, Difficulty::Medium, "Combien de planètes y a-t-il dans le système solaire ?", "8"),
    q_open!(Category::Science, Difficulty::Medium, "Quel gaz produit la photosynthèse ?", "Oxygène"),
    q_open!(Category::Science, Difficulty::Medium, "Quel est le plus grand organe du corps ?", "Peau"),
    q_open!(Category::Science, Difficulty::Medium, "Quelle planète a des anneaux célèbres ?", "Saturne"),
    q_open!(Category::Science, Difficulty::Medium, "Combien d'os a un adulte ?", "206"),
    q_open!(Category::Science, Difficulty::Medium, "Quel animal peut changer de couleur ?", "Caméléon"),
    q_open!(Category::Science, Difficulty::Medium, "Quelle vitamine produit le soleil ?", "Vitamine D"),
    q_open!(Category::Science, Difficulty::Medium, "Combien de litres de sang a une personne ?", "5"),
    q_open!(Category::Science, Difficulty::Hard, "Quelle est la formule chimique du sel ?", "NaCl"),
    q_open!(Category::Science, Difficulty::Hard, "Quelle particule a une charge négative ?", "Électron"),
    q_open!(Category::Science, Difficulty::Hard, "Quelle unité mesure la force ?", "Newton"),
    q_open!(Category::Science, Difficulty::Hard, "Quel scientifique a découvert la pénicilline ?", "Fleming"),
    q_open!(Category::Science, Difficulty::Hard, "Quelle est la vitesse de la lumière en km/s ?", "300000"),
    q_open!(Category::Science, Difficulty::Hard, "Quelle théorie explique l'origine de l'univers ?", "Big Bang"),
    q_open!(Category::Science, Difficulty::Hard, "Quelle planète est la plus grande ?", "Jupiter"),
    q_open!(Category::Science, Difficulty::Hard, "Quel est l'élément le plus abondant de l'univers ?", "Hydrogène"),
    q_open!(Category::Science, Difficulty::Hard, "Quelle échelle mesure les séismes ?", "Richter"),
    q_open!(Category::Science, Difficulty::Hard, "Quel gaz est le plus abondant de l'air ?", "Azote"),
    // -- Art --
    q_open!(Category::Art, Difficulty::Easy, "Combien de cordes a une guitare ?", "6"),
    q_open!(Category::Art, Difficulty::Easy, "Qui a peint le Guernica ?", "Picasso"),
    q_open!(Category::Art, Difficulty::Easy, "Quelle couleur obtient-on en mélangeant le bleu et le jaune ?", "Vert"),
    q_open!(Category::Art, Difficulty::Easy, "Combien de notes a la gamme musicale ?", "7"),
    q_open!(Category::Art, Difficulty::Easy, "Qui a sculpté le David ?", "Michel-Ange"),
    q_open!(Category::Art, Difficulty::Easy, "Quel instrument a 88 touches ?", "Piano"),
    q_open!(Category::Art, Difficulty::Easy, "Qui a peint « La Nuit étoilée » ?", "Van Gogh"),
    q_open!(Category::Art, Difficulty::Easy, "Quelle couleur résulte du mélange du rouge et du blanc ?", "Rose"),
    q_open!(Category::Art, Difficulty::Easy, "Combien de cordes a un violon ?", "4"),
    q_open!(Category::Art, Difficulty::Easy, "Quelle danse est typique de l'Andalousie ?", "Flamenco"),
    q_open!(Category::Art, Difficulty::Medium, "Qui a écrit Don Quichotte ?", "Cervantes"),
    q_open!(Category::Art, Difficulty::Medium, "Quel peintre a peint les tournesols ?", "Van Gogh"),
    q_open!(Category::Art, Difficulty::Medium, "Combien de symphonies complètes a écrites Beethoven ?", "9"),
    q_open!(Category::Art, Difficulty::Medium, "Qui a peint « Les Ménines » ?", "Velázquez"),
    q_open!(Category::Art, Difficulty::Medium, "Quel instrument est à percussion ?", "Tambour"),
    q_open!(Category::Art, Difficulty::Medium, "Qui a composé « Les Quatre Saisons » ?", "Vivaldi"),
    q_open!(Category::Art, Difficulty::Medium, "Quel poète a écrit « Romancero gitan » ?", "Lorca"),
    q_open!(Category::Art, Difficulty::Medium, "Quelle couleur obtient-on avec le rouge et le jaune ?", "Orange"),
    q_open!(Category::Art, Difficulty::Medium, "Qui a conçu la Sagrada Família ?", "Gaudí"),
    q_open!(Category::Art, Difficulty::Medium, "Quel écrivain a écrit « Cent ans de solitude » ?", "García Márquez"),
    q_open!(Category::Art, Difficulty::Hard, "Quel peintre est célèbre pour ses montres fondantes ?", "Dalí"),
    q_open!(Category::Art, Difficulty::Hard, "Qui a composé la Neuvième Symphonie ?", "Beethoven"),
    q_open!(Category::Art, Difficulty::Hard, "Quel écrivain a écrit « La Regenta » ?", "Clarín"),
    q_open!(Category::Art, Difficulty::Hard, "Quel architecte a conçu le Guggenheim de Bilbao ?", "Gehry"),
    q_open!(Category::Art, Difficulty::Hard, "Quel peintre a peint la Chapelle Sixtine ?", "Michel-Ange"),
    q_open!(Category::Art, Difficulty::Hard, "Quel opéra a composé Bizet ?", "Carmen"),
    q_open!(Category::Art, Difficulty::Hard, "Qui a écrit « La Maison de Bernarda Alba » ?", "Lorca"),
    q_open!(Category::Art, Difficulty::Hard, "Quel mouvement artistique Picasso a-t-il mené avec le Guernica ?", "Cubisme"),
    q_open!(Category::Art, Difficulty::Hard, "Quel compositeur a écrit « Le Lac des cygnes » ?", "Tchaïkovski"),
    q_open!(Category::Art, Difficulty::Hard, "Quel poète a écrit « Feuilles d'herbe » ?", "Whitman"),
    // -- Tabou --
    q_open!(Category::Taboo, Difficulty::Easy, "Animal qui pond des œufs et qui fait « cocorico ». Qu'est-ce que c'est ?", "poule"),
    q_open!(Category::Taboo, Difficulty::Easy, "Il a 8 pattes et tisse des toiles. Qu'est-ce que c'est ?", "araignée"),
    q_open!(Category::Taboo, Difficulty::Easy, "Elle sert à écrire et à effacer sur le tableau. Qu'est-ce que c'est ?", "craie"),
    q_open!(Category::Taboo, Difficulty::Easy, "Il est jaune et les singes le mangent. Qu'est-ce que c'est ?", "banane"),
    q_open!(Category::Taboo, Difficulty::Easy, "Il a des aiguilles et indique l'heure. Qu'est-ce que c'est ?", "horloge"),
    q_open!(Category::Taboo, Difficulty::Easy, "Tu l'utilises pour lacer tes chaussures. Qu'est-ce que c'est ?", "lacet"),
    q_open!(Category::Taboo, Difficulty::Easy, "C'est un lieu où l'on prête des livres. Qu'est-ce que c'est ?", "bibliothèque"),
    q_open!(Category::Taboo, Difficulty::Easy, "Il sert à te regarder et à voir ton reflet. Qu'est-ce que c'est ?", "miroir"),
    q_open!(Category::Taboo, Difficulty::Easy, "Il est rond et rebondit. Qu'est-ce que c'est ?", "ballon"),
    q_open!(Category::Taboo, Difficulty::Easy, "Il donne de la lumière la nuit et fonctionne avec des piles. Qu'est-ce que c'est ?", "lampe de poche"),
    q_open!(Category::Taboo, Difficulty::Medium, "Il sert à mesurer la fièvre. Qu'est-ce que c'est ?", "thermomètre"),
    q_open!(Category::Taboo, Difficulty::Medium, "Il conserve la nourriture et la garde au froid. Qu'est-ce que c'est ?", "réfrigérateur"),
    q_open!(Category::Taboo, Difficulty::Medium, "Les pompiers l'utilisent pour éteindre le feu. Qu'est-ce que c'est ?", "tuyau"),
    q_open!(Category::Taboo, Difficulty::Medium, "Il se pend au mur et montre le jour et le mois. Qu'est-ce que c'est ?", "calendrier"),
    q_open!(Category::Taboo, Difficulty::Medium, "Il sonne le matin pour te réveiller. Qu'est-ce que c'est ?", "réveil"),
    q_open!(Category::Taboo, Difficulty::Medium, "Elle se plante dans la terre et une plante en naît. Qu'est-ce que c'est ?", "graine"),
    q_open!(Category::Taboo, Difficulty::Medium, "Tu l'ouvres pour entrer ou sortir d'une pièce. Qu'est-ce que c'est ?", "porte"),
    q_open!(Category::Taboo, Difficulty::Medium, "Il sert à pêcher dans la rivière. Qu'est-ce que c'est ?", "canne à pêche"),
    q_open!(Category::Taboo, Difficulty::Medium, "C'est un moyen de transport à deux roues. Qu'est-ce que c'est ?", "bicyclette"),
    q_open!(Category::Taboo, Difficulty::Medium, "Il sert à te sécher après le bain. Qu'est-ce que c'est ?", "serviette"),
    q_open!(Category::Taboo, Difficulty::Hard, "Instrument que les marins utilisaient pour voir de loin. Qu'est-ce que c'est ?", "longue-vue"),
    q_open!(Category::Taboo, Difficulty::Hard, "Il sert à couper le papier en ligne droite. Qu'est-ce que c'est ?", "ciseaux"),
    q_open!(Category::Taboo, Difficulty::Hard, "Il a une trompe et il est très lourd. Qu'est-ce que c'est ?", "éléphant"),
    q_open!(Category::Taboo, Difficulty::Hard, "Il se met sur la tête pour te protéger. Qu'est-ce que c'est ?", "casque"),
    q_open!(Category::Taboo, Difficulty::Hard, "Il sert à ouvrir les boîtes de conserve. Qu'est-ce que c'est ?", "ouvre-boîte"),
    q_open!(Category::Taboo, Difficulty::Hard, "C'est le lieu où l'on soigne les malades. Qu'est-ce que c'est ?", "hôpital"),
    q_open!(Category::Taboo, Difficulty::Hard, "Il sert à voir les étoiles la nuit. Qu'est-ce que c'est ?", "télescope"),
    q_open!(Category::Taboo, Difficulty::Hard, "Il donne de la lumière la nuit avec des piles. Qu'est-ce que c'est ?", "lampe de poche"),
];
