//! Partie 6 du banc français : lots supplémentaires de nouvelles questions.
use super::super::questions::{q, q_open, Category, Difficulty, Question};

pub static QUESTIONS_FR_6: &[Question] = &[
    q_open!(Category::Taboo, Difficulty::Hard, "C'est un appareil qui aspire la poussière. Qu'est-ce que c'est ?", "aspirateur"),
    q_open!(Category::Taboo, Difficulty::Hard, "Instrument pour mesurer les angles. Qu'est-ce que c'est ?", "rapporteur"),
    // ================= Tanda extra : 231 nouvelles questions =================
    // -- Mathématiques (fermées) --
    q!(Category::Math, Difficulty::Easy, "Combien font 9 + 6 ?", 2, ["13", "14", "15", "16"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 48 ÷ 6 ?", 3, ["6", "7", "9", "8"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 5 x 6 ?", 0, ["30", "36", "25", "35"]),
    q!(Category::Math, Difficulty::Easy, "Combien d'arêtes a un cube ?", 1, ["8", "12", "10", "16"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 27 + 33 ?", 2, ["50", "55", "60", "65"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 100 ÷ 25 ?", 0, ["4", "5", "25", "40"]),
    q!(Category::Math, Difficulty::Easy, "Lequel de ces nombres est impair ?", 1, ["42", "43", "44", "46"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 13 - 5 ?", 1, ["6", "8", "7", "9"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 40 % de 250 ?", 2, ["50", "75", "100", "125"]),
    q!(Category::Math, Difficulty::Medium, "Si 5x + 10 = 35, combien vaut x ?", 0, ["5", "4", "6", "3"]),
    q!(Category::Math, Difficulty::Medium, "Quel est le volume d'un cube d'arête 4 ?", 3, ["16", "24", "48", "64"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 2/5 + 1/10 ?", 1, ["3/5", "1/2", "2/10", "3/10"]),
    q!(Category::Math, Difficulty::Medium, "Quelle est la moyenne de 4, 8, 12 et 16 ?", 2, ["8", "9", "10", "12"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 3 élevé à la puissance 4 ?", 0, ["81", "64", "27", "243"]),
    q!(Category::Math, Difficulty::Medium, "Quel nombre suit dans la série 1, 4, 9, 16, ... ?", 1, ["20", "25", "24", "36"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 7 x 12 ?", 3, ["72", "77", "81", "84"]),
    q!(Category::Math, Difficulty::Hard, "Quelle est la dérivée de x² ?", 2, ["x", "2", "2x", "x²"]),
    q!(Category::Math, Difficulty::Hard, "Quelle est la racine carrée de 289 ?", 1, ["16", "17", "19", "23"]),
    q!(Category::Math, Difficulty::Hard, "Si log₂(8) = 3, combien font log₂(32) ?", 3, ["2", "3", "4", "5"]),
    q!(Category::Math, Difficulty::Hard, "Quelle est la probabilité de tirer un 6 en lançant un dé ?", 0, ["1/6", "1/5", "1/2", "1/3"]),
    q!(Category::Math, Difficulty::Hard, "Combien font les angles internes d'un pentagone ?", 1, ["360°", "540°", "720°", "180°"]),
    q!(Category::Math, Difficulty::Hard, "Si f(x) = 2x + 3 et f(a) = 11, combien vaut a ?", 2, ["3", "5", "4", "7"]),
    q!(Category::Math, Difficulty::Hard, "Combien font (a + b)² ?", 0, ["a² + 2ab + b²", "a² + b²", "2a + 2b", "a² + ab + b²"]),
    q!(Category::Math, Difficulty::Hard, "Combien font 7 % de 300 ?", 1, ["22", "21", "25", "30"]),
    // -- Mathématiques (ouvertes) --
    q_open!(Category::Math, Difficulty::Easy, "Combien font 4 + 4 x 4 ?", "20"),
    q_open!(Category::Math, Difficulty::Easy, "Combien de secondes a une minute ?", "60"),
    q_open!(Category::Math, Difficulty::Easy, "Combien font 6 x 6 ?", "36"),
    q_open!(Category::Math, Difficulty::Medium, "Combien font 25 % de 80 ?", "20"),
    q_open!(Category::Math, Difficulty::Medium, "Quelle est la racine carrée de 64 ?", "8"),
    q_open!(Category::Math, Difficulty::Medium, "Combien font 1/3 + 1/3 ?", "2/3"),
    q_open!(Category::Math, Difficulty::Hard, "Combien font 5 factoriel (5!) ?", "120"),
    q_open!(Category::Math, Difficulty::Hard, "Quelle est la somme des 10 premiers nombres ?", "55"),
    q_open!(Category::Math, Difficulty::Hard, "Combien de degrés a un angle plat ?", "180"),
    // -- Histoire (fermées) --
    q!(Category::History, Difficulty::Easy, "Qui a été le premier président des États-Unis ?", 2, ["Lincoln", "Jefferson", "Washington", "Adams"]),
    q!(Category::History, Difficulty::Easy, "En quelle année Colomb a-t-il atteint l'Amérique ?", 0, ["1492", "1498", "1500", "1453"]),
    q!(Category::History, Difficulty::Easy, "Quelle civilisation a construit les pyramides de Gizeh ?", 1, ["Romains", "Égyptiens", "Grecs", "Mayas"]),
    q!(Category::History, Difficulty::Easy, "Qui fut empereur de France en 1810 ?", 2, ["Louis XVI", "Charles Quint", "Napoléon", "Henri VIII"]),
    q!(Category::History, Difficulty::Easy, "Quelle ville romaine fut ensevelie par le Vésuve en 79 ap. J.-C. ?", 0, ["Pompéi", "Rome", "Athènes", "Carthage"]),
    q!(Category::History, Difficulty::Easy, "Quel mur séparait Berlin-Est et Berlin-Ouest ?", 1, ["Mur d'Hadrien", "Mur de Berlin", "Grande Muraille", "Mur des Lamentations"]),
    q!(Category::History, Difficulty::Easy, "En quel siècle s'est terminée la Seconde Guerre mondiale ?", 3, ["XIXe", "XVIIIe", "XXIe", "XXe"]),
    q!(Category::History, Difficulty::Easy, "Qui a écrit l'Iliade et l'Odyssée ?", 0, ["Homère", "Virgile", "Sophocle", "Platon"]),
    q!(Category::History, Difficulty::Medium, "En quelle année est tombé le Mur de Berlin ?", 1, ["1985", "1989", "1991", "1979"]),
    q!(Category::History, Difficulty::Medium, "Quelle reine britannique a régné de 1837 à 1901 ?", 2, ["Élisabeth Ire", "Anne", "Victoria", "Élisabeth II"]),
    q!(Category::History, Difficulty::Medium, "Quel traité a mis fin à la Première Guerre mondiale ?", 0, ["Versailles", "Vienne", "Genève", "Paris"]),
    q!(Category::History, Difficulty::Medium, "Qui a été le chef de la Révolution cubaine de 1959 ?", 3, ["Che Guevara", "Batista", "José Martí", "Fidel Castro"]),
    q!(Category::History, Difficulty::Medium, "Quel empire a conquis Constantinople en 1453 ?", 1, ["Romain", "Ottoman", "Mongol", "Perse"]),
    q!(Category::History, Difficulty::Medium, "En quelle année a commencé la Révolution française ?", 0, ["1789", "1799", "1776", "1812"]),
    q!(Category::History, Difficulty::Medium, "Quel explorateur a dirigé le premier tour du monde ?", 2, ["Colomb", "Vasco de Gama", "Magellan", "Cortés"]),
    q!(Category::History, Difficulty::Medium, "En quelle année a été inauguré le canal de Suez ?", 3, ["1848", "1857", "1865", "1869"]),
    q!(Category::History, Difficulty::Hard, "Quel empereur romain a établi la tétrarchie ?", 0, ["Dioclétien", "Constantin", "Théodose", "Auguste"]),
    q!(Category::History, Difficulty::Hard, "Quelle civilisation a conquis la Grèce en 146 av. J.-C. ?", 2, ["Perse", "Égypte", "Rome", "Macédoine"]),
    q!(Category::History, Difficulty::Hard, "Quel roi d'Espagne a lancé l'Invincible Armada ?", 1, ["Charles Ier", "Philippe II", "Philippe III", "Charles II"]),
    q!(Category::History, Difficulty::Hard, "En quelle année a été proclamée la Deuxième République espagnole ?", 3, ["1923", "1929", "1936", "1931"]),
    q!(Category::History, Difficulty::Hard, "Quel traité a mis fin à la guerre de Trente Ans ?", 0, ["Westphalie", "Utrecht", "Vienne", "Paris"]),
    q!(Category::History, Difficulty::Hard, "Qui a été le premier homme à marcher sur la Lune ?", 1, ["Aldrin", "Armstrong", "Gagarine", "Shepard"]),
    q!(Category::History, Difficulty::Hard, "Quel peuple a pillé Rome en l'an 410 ?", 2, ["Vandales", "Huns", "Wisigoths", "Francs"]),
    q!(Category::History, Difficulty::Hard, "En quelle année a eu lieu la bataille de Covadonga ?", 3, ["711", "732", "778", "722"]),
    // -- Histoire (ouvertes) --
    q_open!(Category::History, Difficulty::Easy, "Qui fut président des États-Unis pendant la Seconde Guerre mondiale ?", "Roosevelt"),
    q_open!(Category::History, Difficulty::Easy, "En quelle année s'est terminée la Première Guerre mondiale ?", "1918"),
    q_open!(Category::History, Difficulty::Easy, "Qui a été vaincu à la bataille de Waterloo ?", "Napoléon"),
    q_open!(Category::History, Difficulty::Medium, "En quelle année a été signée la Déclaration d'indépendance des États-Unis ?", "1776"),
    q_open!(Category::History, Difficulty::Medium, "Qui fut la dernière reine de l'Égypte antique ?", "Cléopâtre"),
    q_open!(Category::History, Difficulty::Medium, "Qui fut le premier empereur de Rome ?", "Auguste"),
    q_open!(Category::History, Difficulty::Hard, "En quelle année a été construit le Mur de Berlin ?", "1961"),
    q_open!(Category::History, Difficulty::Hard, "Quelle civilisation a inventé l'écriture cunéiforme ?", "Sumérie"),
    q_open!(Category::History, Difficulty::Hard, "Quelle guerre a opposé l'OTAN et le pacte de Varsovie sans combats directs ?", "Guerre froide"),
    // -- Informatique (fermées) --
    q!(Category::Cs, Difficulty::Easy, "Que signifie CPU ?", 0, ["Unité centrale de traitement", "Centre de programmes uniques", "Ordinateur personnel unique", "Unité de calcul principale"]),
    q!(Category::Cs, Difficulty::Easy, "Quel dispositif déplace le curseur à l'écran ?", 1, ["Clavier", "Souris", "Moniteur", "Imprimante"]),
    q!(Category::Cs, Difficulty::Easy, "Combien de bits a un octet ?", 2, ["4", "16", "8", "32"]),
    q!(Category::Cs, Difficulty::Easy, "Quel système d'exploitation appartient à Microsoft ?", 0, ["Windows", "Linux", "Android", "macOS"]),
    q!(Category::Cs, Difficulty::Easy, "Quelle extension ont les documents Word ?", 1, [".pdf", ".docx", ".txt", ".jpg"]),
    q!(Category::Cs, Difficulty::Easy, "Quelle touche efface le caractère à gauche du curseur ?", 3, ["Suppr", "Entrée", "Maj", "Retour arrière"]),
    q!(Category::Cs, Difficulty::Easy, "Quel programme utilise-t-on pour naviguer sur Internet ?", 0, ["Navigateur", "Processeur", "Antivirus", "Compresseur"]),
    q!(Category::Cs, Difficulty::Easy, "Quel dispositif affiche l'image de l'ordinateur ?", 2, ["Souris", "Clavier", "Moniteur", "Imprimante"]),
    q!(Category::Cs, Difficulty::Medium, "Que signifie HTML ?", 0, ["HyperText Markup Language", "High Tech Modern Language", "Home Tool Markup Language", "Hyperlink Transfer Markup"]),
    q!(Category::Cs, Difficulty::Medium, "Combien d'octets a un kibioctet (KiB) ?", 1, ["1000", "1024", "512", "2048"]),
    q!(Category::Cs, Difficulty::Medium, "Quel langage de programmation utilise le moteur Bevy ?", 2, ["Python", "Java", "Rust", "C#"]),
    q!(Category::Cs, Difficulty::Medium, "Quel protocole une page web utilise-t-elle dans le navigateur ?", 3, ["FTP", "SMTP", "TCP", "HTTP"]),
    q!(Category::Cs, Difficulty::Medium, "Que signifie RAM ?", 0, ["Mémoire à accès aléatoire", "Mémoire de démarrage rapide", "Mémoire en lecture seule", "Registre d'applications mobiles"]),
    q!(Category::Cs, Difficulty::Medium, "Quelle extension ont les fichiers sources de Rust ?", 1, [".rust", ".rs", ".r", ".rsrc"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'un algorithme ?", 2, ["Une erreur de code", "Un type de virus", "Une suite d'étapes pour résoudre un problème", "Un type de donnée"]),
    q!(Category::Cs, Difficulty::Medium, "Que fait la commande cd dans le terminal ?", 0, ["Changer de répertoire", "Copier des données", "Compresser des données", "Compiler des données"]),
    q!(Category::Cs, Difficulty::Hard, "Quelle complexité temporelle a la recherche dichotomique ?", 1, ["O(n)", "O(log n)", "O(n²)", "O(1)"]),
    q!(Category::Cs, Difficulty::Hard, "Quelle structure de données fonctionne en LIFO ?", 0, ["Pile", "File", "Liste", "Arbre"]),
    q!(Category::Cs, Difficulty::Hard, "Quel compilateur Rust utilise-t-il par défaut ?", 2, ["gcc", "clang", "rustc", "llvm"]),
    q!(Category::Cs, Difficulty::Hard, "Quel port HTTPS utilise-t-il par défaut ?", 3, ["80", "8080", "21", "443"]),
    q!(Category::Cs, Difficulty::Hard, "Quelle structure de données fonctionne en FIFO ?", 1, ["Pile", "File", "Arbre", "Graphe"]),
    q!(Category::Cs, Difficulty::Hard, "Que signifie OOP en programmation ?", 0, ["Object-Oriented Programming", "Operating Output Protocol", "Open Order Path", "Object Ordering Process"]),
    q!(Category::Cs, Difficulty::Hard, "Quelle mémoire perd son contenu lorsqu'on éteint l'ordinateur ?", 1, ["ROM", "RAM", "Disque dur", "SSD"]),
    q!(Category::Cs, Difficulty::Hard, "Quel algorithme de tri compare des paires adjacentes ?", 2, ["Insertion", "Sélection", "Bulle", "Fusion"]),
    // -- Informatique (ouvertes) --
    q_open!(Category::Cs, Difficulty::Easy, "Que signifie www dans une adresse web ?", "World Wide Web"),
    q_open!(Category::Cs, Difficulty::Easy, "Quelle commande liste les fichiers dans le terminal Linux ?", "ls"),
    q_open!(Category::Cs, Difficulty::Easy, "Quel système d'exploitation est libre et open source ?", "Linux"),
    q_open!(Category::Cs, Difficulty::Medium, "Quelle extension ont les programmes exécutables de Windows ?", "exe"),
    q_open!(Category::Cs, Difficulty::Medium, "Quel protocole envoie le courrier électronique ?", "SMTP"),
    q_open!(Category::Cs, Difficulty::Medium, "Quelle unité d'information équivaut à 1024 gigaoctets ?", "Téraoctet"),
    q_open!(Category::Cs, Difficulty::Hard, "Quel langage de programmation Graydon Hoare a-t-il lancé en 2015 ?", "Rust"),
    q_open!(Category::Cs, Difficulty::Hard, "Quelle commande compile et exécute un projet Rust ?", "cargo run"),
    q_open!(Category::Cs, Difficulty::Hard, "Quel acronyme désigne la mémoire non volatile en lecture seule ?", "ROM"),
    // -- Géographie (fermées) --
    q!(Category::Geography, Difficulty::Easy, "Quel est le plus grand océan du monde ?", 2, ["Atlantique", "Indien", "Pacifique", "Arctique"]),
    q!(Category::Geography, Difficulty::Easy, "Sur quel continent se trouve l'Égypte ?", 0, ["Afrique", "Asie", "Europe", "Amérique"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de la France ?", 1, ["Londres", "Paris", "Rome", "Madrid"]),
    q!(Category::Geography, Difficulty::Easy, "Quel pays a la forme d'une botte ?", 3, ["Espagne", "Grèce", "Portugal", "Italie"]),
    q!(Category::Geography, Difficulty::Easy, "Quel est le plus grand désert chaud du monde ?", 1, ["Atacama", "Sahara", "Gobi", "Kalahari"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle mer sépare l'Espagne de l'Afrique ?", 0, ["Méditerranée", "Cantabrique", "Baltique", "Rouge"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale du Japon ?", 2, ["Pékin", "Séoul", "Tokyo", "Bangkok"]),
    q!(Category::Geography, Difficulty::Easy, "Dans quel océan se trouve Hawaï ?", 1, ["Atlantique", "Pacifique", "Indien", "Arctique"]),
    q!(Category::Geography, Difficulty::Medium, "Quel est le pays le plus vaste du monde ?", 0, ["Russie", "Canada", "Chine", "États-Unis"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de l'Australie ?", 2, ["Sydney", "Melbourne", "Canberra", "Perth"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle chaîne de montagnes sépare l'Europe de l'Asie ?", 1, ["Alpes", "Oural", "Himalaya", "Carpates"]),
    q!(Category::Geography, Difficulty::Medium, "Quel pays a le plus d'habitants au monde ?", 3, ["Chine", "États-Unis", "Indonésie", "Inde"]),
    q!(Category::Geography, Difficulty::Medium, "Quel détroit sépare l'Espagne du Maroc ?", 0, ["Gibraltar", "Suez", "Bosphore", "Magellan"]),
    q!(Category::Geography, Difficulty::Medium, "Quel est le lac le plus profond du monde ?", 1, ["Tanganyika", "Baïkal", "Caspienne", "Supérieur"]),
    q!(Category::Geography, Difficulty::Medium, "Quel pays d'Amérique du Sud n'a pas d'accès à la mer ?", 2, ["Chili", "Pérou", "Bolivie", "Équateur"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale du Canada ?", 3, ["Toronto", "Montréal", "Vancouver", "Ottawa"]),
    q!(Category::Geography, Difficulty::Hard, "Quel est le point le plus profond de l'océan ?", 0, ["Fosse des Mariannes", "Fosse de Porto Rico", "Fosse de Java", "Fosse des Tonga"]),
    q!(Category::Geography, Difficulty::Hard, "Quel pays a le plus grand nombre de fuseaux horaires ?", 1, ["États-Unis", "France", "Russie", "Chine"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale du Kazakhstan ?", 2, ["Almaty", "Tachkent", "Astana", "Bakou"]),
    q!(Category::Geography, Difficulty::Hard, "Quel fleuve traverse la ville du Caire ?", 0, ["Nil", "Euphrate", "Tigre", "Jourdain"]),
    q!(Category::Geography, Difficulty::Hard, "Dans quel pays se trouve le Machu Picchu ?", 1, ["Mexique", "Pérou", "Bolivie", "Chili"]),
    q!(Category::Geography, Difficulty::Hard, "Quel est le plus petit pays du monde ?", 2, ["Monaco", "Saint-Marin", "Vatican", "Liechtenstein"]),
    q!(Category::Geography, Difficulty::Hard, "Quel désert se trouve au Chili ?", 3, ["Sahara", "Gobi", "Kalahari", "Atacama"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale de la Nouvelle-Zélande ?", 0, ["Wellington", "Auckland", "Christchurch", "Melbourne"]),
    // -- Géographie (ouvertes) --
    q_open!(Category::Geography, Difficulty::Easy, "Quel est le fleuve le plus long d'Espagne ?", "Tage"),
    q_open!(Category::Geography, Difficulty::Easy, "Quelle est la capitale du Portugal ?", "Lisbonne"),
    q_open!(Category::Geography, Difficulty::Easy, "Quel continent se trouve au sud de la Méditerranée ?", "Afrique"),
    q_open!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de l'Allemagne ?", "Berlin"),
    q_open!(Category::Geography, Difficulty::Medium, "Quelle est la plus haute montagne du monde ?", "Everest"),
    q_open!(Category::Geography, Difficulty::Medium, "Quel pays a pour capitale Moscou ?", "Russie"),
    q_open!(Category::Geography, Difficulty::Hard, "Quelle est la capitale du Brésil ?", "Brasilia"),
    q_open!(Category::Geography, Difficulty::Hard, "Quel est le point le plus élevé de l'Afrique ?", "Kilimandjaro"),
    q_open!(Category::Geography, Difficulty::Hard, "Quel pays nordique a pour capitale Oslo ?", "Norvège"),
    // -- Science (fermées) --
    q!(Category::Science, Difficulty::Easy, "Quel organe pompe le sang dans le corps ?", 2, ["Poumons", "Reins", "Cœur", "Foie"]),
    q!(Category::Science, Difficulty::Easy, "Combien de pattes a un insecte ?", 0, ["6", "8", "4", "10"]),
    q!(Category::Science, Difficulty::Easy, "Quel gaz les plantes absorbent-elles pour faire la photosynthèse ?", 1, ["Oxygène", "CO2", "Azote", "Hydrogène"]),
    q!(Category::Science, Difficulty::Easy, "Quelle planète est la quatrième depuis le Soleil ?", 3, ["Vénus", "Jupiter", "Saturne", "Mars"]),
    q!(Category::Science, Difficulty::Easy, "Quel animal est un mammifère marin ?", 1, ["Requin", "Dauphin", "Poulpe", "Méduse"]),
    q!(Category::Science, Difficulty::Easy, "De quoi les plantes ont-elles besoin pour fabriquer leur nourriture ?", 0, ["Lumière du soleil", "Obscurité", "Glace", "Sable"]),
    q!(Category::Science, Difficulty::Easy, "Combien de dents a un adulte ?", 2, ["20", "24", "32", "28"]),
    q!(Category::Science, Difficulty::Easy, "Quelle partie de la cellule contient l'ADN ?", 1, ["Membrane", "Noyau", "Mitochondrie", "Cytoplasme"]),
    q!(Category::Science, Difficulty::Medium, "Quel organe produit l'insuline ?", 2, ["Foie", "Rein", "Pancréas", "Estomac"]),
    q!(Category::Science, Difficulty::Medium, "Quel est le métal le plus abondant dans la croûte terrestre ?", 0, ["Aluminium", "Fer", "Cuivre", "Or"]),
    q!(Category::Science, Difficulty::Medium, "Quelle planète est la plus grande géante gazeuse ?", 1, ["Mars", "Jupiter", "Vénus", "Mercure"]),
    q!(Category::Science, Difficulty::Medium, "Combien de temps la Terre met-elle pour tourner sur elle-même ?", 0, ["24 heures", "12 heures", "365 jours", "30 jours"]),
    q!(Category::Science, Difficulty::Medium, "Quel scientifique a formulé la théorie de l'évolution ?", 3, ["Newton", "Einstein", "Galilée", "Darwin"]),
    q!(Category::Science, Difficulty::Medium, "Quel est le plus petit os du corps humain ?", 1, ["Marteau", "Étrier", "Cubitus", "Rotule"]),
    q!(Category::Science, Difficulty::Medium, "Quel groupe sanguin est le donneur universel ?", 2, ["A+", "AB+", "O-", "B-"]),
    q!(Category::Science, Difficulty::Medium, "Quelle est l'unité de mesure du courant électrique ?", 0, ["Ampère", "Volt", "Watt", "Ohm"]),
    q!(Category::Science, Difficulty::Hard, "Quelles particules forment les protons et les neutrons ?", 1, ["Électrons", "Quarks", "Photons", "Neutrinos"]),
    q!(Category::Science, Difficulty::Hard, "Quelle est la formule chimique de l'eau ?", 0, ["H2O", "CO2", "O2", "NaCl"]),
    q!(Category::Science, Difficulty::Hard, "Quelle loi de Newton s'exprime comme F = m · a ?", 2, ["Première", "De la gravitation", "Seconde", "Troisième"]),
    q!(Category::Science, Difficulty::Hard, "Quel organe produit la bile ?", 1, ["Pancréas", "Foie", "Vésicule", "Rate"]),
    q!(Category::Science, Difficulty::Hard, "Quelle unité mesure la fréquence ?", 3, ["Newton", "Joule", "Pascal", "Hertz"]),
    q!(Category::Science, Difficulty::Hard, "Quel élément chimique a le symbole Au ?", 0, ["Or", "Argent", "Aluminium", "Argon"]),
    q!(Category::Science, Difficulty::Hard, "Quel rayonnement a la fréquence la plus élevée ?", 2, ["Radio", "Infrarouge", "Gamma", "Micro-ondes"]),
    q!(Category::Science, Difficulty::Hard, "Quel processus convertit le sucre en énergie dans les cellules ?", 1, ["Photosynthèse", "Respiration cellulaire", "Fermentation lactique", "Digestion"]),
    // -- Science (ouvertes) --
    q_open!(Category::Science, Difficulty::Easy, "Quelle est la cinquième planète du système solaire ?", "Jupiter"),
    q_open!(Category::Science, Difficulty::Easy, "Quel est l'animal le plus rapide du monde ?", "Guépard"),
    q_open!(Category::Science, Difficulty::Easy, "Combien d'os a le crâne humain ?", "22"),
    q_open!(Category::Science, Difficulty::Medium, "Quel métal est liquide à température ambiante ?", "Mercure"),
    q_open!(Category::Science, Difficulty::Medium, "Quel gaz noble est le plus léger ?", "Hélium"),
    q_open!(Category::Science, Difficulty::Medium, "Quel organe filtre le sang ?", "Rein"),
    q_open!(Category::Science, Difficulty::Hard, "Quelle particule a une charge neutre ?", "Neutron"),
    q_open!(Category::Science, Difficulty::Hard, "Quelle unité mesure la pression ?", "Pascal"),
    q_open!(Category::Science, Difficulty::Hard, "Quel scientifique a formulé les lois du mouvement ?", "Newton"),
    // -- Art (fermées) --
    q!(Category::Art, Difficulty::Easy, "Quelle couleur est complémentaire du rouge ?", 2, ["Bleu", "Jaune", "Vert", "Orange"]),
    q!(Category::Art, Difficulty::Easy, "Quel instrument a des touches blanches et noires ?", 0, ["Piano", "Violon", "Trompette", "Guitare"]),
    q!(Category::Art, Difficulty::Easy, "Qui a peint la Joconde ?", 1, ["Michel-Ange", "Léonard de Vinci", "Raphaël", "Le Caravage"]),
    q!(Category::Art, Difficulty::Easy, "Quel peintre s'est coupé une oreille ?", 3, ["Picasso", "Dalí", "Goya", "Van Gogh"]),
    q!(Category::Art, Difficulty::Easy, "Combien de touches noires a un piano ?", 2, ["52", "32", "36", "44"]),
    q!(Category::Art, Difficulty::Easy, "Qu'est-ce qu'un poème ?", 0, ["Un texte avec rythme et rimes", "Un tableau", "Une chanson", "Un livre d'histoire"]),
    q!(Category::Art, Difficulty::Easy, "Dans quelle ville se trouve le musée du Prado ?", 1, ["Barcelone", "Madrid", "Séville", "Valence"]),
    q!(Category::Art, Difficulty::Easy, "Quel instrument est un instrument à vent ?", 0, ["Flûte", "Tambour", "Violon", "Piano"]),
    q!(Category::Art, Difficulty::Medium, "Qui a écrit 'La Divine Comédie' ?", 2, ["Boccace", "Pétrarque", "Dante", "Cervantès"]),
    q!(Category::Art, Difficulty::Medium, "À quel courant artistique appartient Dalí ?", 0, ["Surréalisme", "Cubisme", "Impressionnisme", "Baroque"]),
    q!(Category::Art, Difficulty::Medium, "Qui a composé la marche nuptiale classique ?", 1, ["Beethoven", "Mendelssohn", "Mozart", "Bach"]),
    q!(Category::Art, Difficulty::Medium, "Quelle œuvre a écrit Shakespeare ?", 3, ["L'Odyssée", "Don Quichotte", "Faust", "Hamlet"]),
    q!(Category::Art, Difficulty::Medium, "Quel peintre a peint 'La Persistance de la mémoire' ?", 0, ["Dalí", "Miró", "Picasso", "Gaudí"]),
    q!(Category::Art, Difficulty::Medium, "Quel instrument a des cordes et des pédales ?", 1, ["Lyre", "Harpe", "Guitare", "Cithare"]),
    q!(Category::Art, Difficulty::Medium, "Qui a écrit 'Madame Bovary' ?", 2, ["Zola", "Balzac", "Flaubert", "Dumas"]),
    q!(Category::Art, Difficulty::Medium, "Quel style architectural a l'Alhambra de Grenade ?", 0, ["Islamique", "Gothique", "Renaissance", "Baroque"]),
    q!(Category::Art, Difficulty::Hard, "Quel peintre baroque a peint 'La Reddition de Bréda' ?", 1, ["Zurbarán", "Velázquez", "Murillo", "Le Greco"]),
    q!(Category::Art, Difficulty::Hard, "Qui a écrit 'La vie est un songe' ?", 0, ["Calderón de la Barca", "Lope de Vega", "Quevedo", "Tirso de Molina"]),
    q!(Category::Art, Difficulty::Hard, "Qui a composé 'Les Noces de Figaro' ?", 2, ["Beethoven", "Haydn", "Mozart", "Rossini"]),
    q!(Category::Art, Difficulty::Hard, "Quel peintre est célèbre pour le pointillisme ?", 1, ["Monet", "Seurat", "Renoir", "Degas"]),
    q!(Category::Art, Difficulty::Hard, "Qui a écrit 'Moby Dick' ?", 3, ["Poe", "Hawthorne", "Twain", "Melville"]),
    q!(Category::Art, Difficulty::Hard, "Quel peintre de la Renaissance a peint 'L'École d'Athènes' ?", 0, ["Raphaël", "Michel-Ange", "Léonard", "Titien"]),
    q!(Category::Art, Difficulty::Hard, "Quel mouvement a fondé André Breton ?", 1, ["Dadaïsme", "Surréalisme", "Futurisme", "Cubisme"]),
    q!(Category::Art, Difficulty::Hard, "Qui a composé 'Le Sacre du printemps' ?", 2, ["Debussy", "Ravel", "Stravinski", "Prokofiev"]),
    // -- Art (ouvertes) --
    q_open!(Category::Art, Difficulty::Easy, "Qui a peint le plafond de la chapelle Sixtine ?", "Michel-Ange"),
    q_open!(Category::Art, Difficulty::Easy, "Combien de cordes a un ukulélé ?", "4"),
    q_open!(Category::Art, Difficulty::Easy, "Quelle ville italienne est célèbre pour ses canaux ?", "Venise"),
    q_open!(Category::Art, Difficulty::Medium, "Qui a écrit 'Roméo et Juliette' ?", "Shakespeare"),
    q_open!(Category::Art, Difficulty::Medium, "Quel sculpteur a créé 'Le Penseur' ?", "Rodin"),
    q_open!(Category::Art, Difficulty::Medium, "Qui a composé 'La Flûte enchantée' ?", "Mozart"),
    q_open!(Category::Art, Difficulty::Hard, "Quel écrivain irlandais a écrit 'Ulysse' ?", "Joyce"),
    q_open!(Category::Art, Difficulty::Hard, "Quel peintre espagnol a peint 'Le Sabbat des sorcières' ?", "Goya"),
    q_open!(Category::Art, Difficulty::Hard, "Quel mouvement artistique repose sur de petits points de couleur ?", "Pointillisme"),
    // -- Tabou (fermées) --
    q!(Category::Taboo, Difficulty::Easy, "Il est vert, il saute et il coasse. Qu'est-ce que c'est ?", 2, ["Lézard", "Caméléon", "Grenouille", "Serpent"]),
    q!(Category::Taboo, Difficulty::Easy, "Il a des rayures blanches et on le traverse dans la rue. Qu'est-ce que c'est ?", 0, ["Passage piéton", "Feu tricolore", "Trottoir", "Bordure"]),
    q!(Category::Taboo, Difficulty::Easy, "Il est rond, il tourne et il a des chiffres. Qu'est-ce que c'est ?", 1, ["Boussole", "Montre", "Thermomètre", "Calendrier"]),
    q!(Category::Taboo, Difficulty::Easy, "On le met sur la tête pour se protéger du froid. Qu'est-ce que c'est ?", 3, ["Écharpe", "Gants", "Manteau", "Bonnet"]),
    q!(Category::Taboo, Difficulty::Easy, "Il sert à couper le pain. Qu'est-ce que c'est ?", 0, ["Couteau", "Fourchette", "Cuillère", "Assiette"]),
    q!(Category::Taboo, Difficulty::Easy, "Elle s'ouvre avec une clé et protège les objets de valeur. Qu'est-ce que c'est ?", 1, ["Sac à dos", "Coffre-fort", "Portefeuille", "Armoire"]),
    q!(Category::Taboo, Difficulty::Easy, "Elle a des pétales et sent bon. Qu'est-ce que c'est ?", 2, ["Feuille", "Branche", "Fleur", "Racine"]),
    q!(Category::Taboo, Difficulty::Easy, "Il sert à balayer le sol. Qu'est-ce que c'est ?", 0, ["Balai", "Serpillière", "Tête de loup", "Aspirateur"]),
    q!(Category::Taboo, Difficulty::Medium, "Il sert à mesurer le temps dans une course. Qu'est-ce que c'est ?", 1, ["Sablier", "Chronomètre", "Réveil", "Métronome"]),
    q!(Category::Taboo, Difficulty::Medium, "Il a des touches et un soufflet, il sonne comme un petit piano. Qu'est-ce que c'est ?", 0, ["Accordéon", "Orgue", "Synthétiseur", "Xylophone"]),
    q!(Category::Taboo, Difficulty::Medium, "Les astronautes l'utilisent pour sortir dans l'espace. Qu'est-ce que c'est ?", 2, ["Parachute", "Masque à oxygène", "Combinaison spatiale", "Ballon"]),
    q!(Category::Taboo, Difficulty::Medium, "On le met sur le feu pour cuire la soupe. Qu'est-ce que c'est ?", 3, ["Poêle", "Assiette", "Plateau", "Casserole"]),
    q!(Category::Taboo, Difficulty::Medium, "Il sert à voir de près les petites lettres. Qu'est-ce que c'est ?", 0, ["Loupe", "Lunettes de soleil", "Jumelles", "Télescope"]),
    q!(Category::Taboo, Difficulty::Medium, "C'est un insecte qui produit du miel. Qu'est-ce que c'est ?", 1, ["Guêpe", "Abeille", "Coccinelle", "Fourmi"]),
    q!(Category::Taboo, Difficulty::Medium, "Il sert à attacher les cheveux. Qu'est-ce que c'est ?", 2, ["Collier", "Boucle d'oreille", "Élastique", "Bague"]),
    q!(Category::Taboo, Difficulty::Medium, "Il sert à enfoncer les clous. Qu'est-ce que c'est ?", 0, ["Marteau", "Tournevis", "Pince", "Clé à molette"]),
    q!(Category::Taboo, Difficulty::Hard, "Instrument qui mesure la pression atmosphérique. Qu'est-ce que c'est ?", 1, ["Thermomètre", "Baromètre", "Hydromètre", "Compteur de vitesse"]),
    q!(Category::Taboo, Difficulty::Hard, "On l'utilise au laboratoire pour mesurer des liquides exacts. Qu'est-ce que c'est ?", 2, ["Verre", "Tube à essai", "Éprouvette", "Entonnoir"]),
    q!(Category::Taboo, Difficulty::Hard, "Instrument qui mesure la vitesse du vent. Qu'est-ce que c'est ?", 0, ["Anémomètre", "Baromètre", "Thermomètre", "Hydromètre"]),
    q!(Category::Taboo, Difficulty::Hard, "Il sert à mesurer la pression artérielle. Qu'est-ce que c'est ?", 3, ["Glucomètre", "Thermomètre", "Stéthoscope", "Tensiomètre"]),
    q!(Category::Taboo, Difficulty::Hard, "Instrument pour écouter les battements du cœur. Qu'est-ce que c'est ?", 2, ["Thermomètre", "Tensiomètre", "Stéthoscope", "Ophtalmoscope"]),
    q!(Category::Taboo, Difficulty::Hard, "Appareil qui mesure le sucre dans le sang. Qu'est-ce que c'est ?", 0, ["Glucomètre", "Thermomètre", "Baromètre", "Taximètre"]),
    q!(Category::Taboo, Difficulty::Hard, "Il sert à faire des trous dans le bois. Qu'est-ce que c'est ?", 3, ["Scie", "Rabot", "Papier de verre", "Perceuse"]),
    q!(Category::Taboo, Difficulty::Hard, "Instrument qui mesure la profondeur de la mer. Qu'est-ce que c'est ?", 1, ["Radar", "Sonar", "Périscope", "Kaléidoscope"]),
    // -- Tabou (ouvertes) --
    q_open!(Category::Taboo, Difficulty::Easy, "Il a des aiguilles et ne se fatigue jamais de marcher. Qu'est-ce que c'est ?", "horloge"),
    q_open!(Category::Taboo, Difficulty::Easy, "Il sert à essuyer les assiettes. Qu'est-ce que c'est ?", "torchon"),
    q_open!(Category::Taboo, Difficulty::Easy, "Il sert à écrire sur l'ordinateur. Qu'est-ce que c'est ?", "clavier"),
    q_open!(Category::Taboo, Difficulty::Medium, "Elle se pend au mur et sonne à l'heure. Qu'est-ce que c'est ?", "cloche"),
    q_open!(Category::Taboo, Difficulty::Medium, "Elle sert à ouvrir les portes et les tiroirs. Qu'est-ce que c'est ?", "clé"),
    q_open!(Category::Taboo, Difficulty::Medium, "C'est un animal à bosse qui vit dans le désert. Qu'est-ce que c'est ?", "chameau"),
    q_open!(Category::Taboo, Difficulty::Hard, "Il sert à mesurer le temps de cuisson. Qu'est-ce que c'est ?", "minuteur"),
    q_open!(Category::Taboo, Difficulty::Hard, "Instrument que les marins utilisent pour s'orienter grâce aux étoiles. Qu'est-ce que c'est ?", "sextant"),
    q_open!(Category::Taboo, Difficulty::Hard, "Appareil qui mesure les kilomètres parcourus par une voiture. Qu'est-ce que c'est ?", "compteur kilométrique"),
    // ============ Tanda extra 2 : 315 nouvelles questions ============
    // -- Mathématiques (fermées) --
    q!(Category::Math, Difficulty::Easy, "Combien font 11 + 9 ?", 3, ["18", "19", "21", "20"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 7 x 8 ?", 2, ["54", "55", "56", "57"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 144 ÷ 12 ?", 1, ["11", "12", "13", "14"]),
    q!(Category::Math, Difficulty::Easy, "Quel est le carré de 9 ?", 0, ["81", "72", "90", "64"]),
    q!(Category::Math, Difficulty::Easy, "Combien de centimètres a un mètre ?", 3, ["10", "50", "1000", "100"]),
    q!(Category::Math, Difficulty::Easy, "Quelle est la moitié de 38 ?", 2, ["18", "20", "19", "17"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 25 - 17 ?", 1, ["7", "8", "9", "6"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 6 x 9 ?", 0, ["54", "56", "45", "63"]),
    q!(Category::Math, Difficulty::Easy, "Quel nombre est le double de 15 ?", 2, ["25", "35", "30", "20"]),
    q!(Category::Math, Difficulty::Easy, "Combien font 100 - 37 ?", 3, ["73", "67", "62", "63"]),
    q!(Category::Math, Difficulty::Medium, "Quelle est l'aire d'un rectangle de 8 cm de long et 5 cm de large ?", 1, ["26 cm²", "40 cm²", "45 cm²", "13 cm²"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 3/4 + 1/4 ?", 0, ["1", "1/2", "2/4", "3/8"]),
    q!(Category::Math, Difficulty::Medium, "Lequel de ces nombres est premier ?", 2, ["21", "25", "17", "27"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 2 élevé à la puissance 10 ?", 3, ["512", "1000", "2048", "1024"]),
    q!(Category::Math, Difficulty::Medium, "Quel est le périmètre d'un carré de côté 7 ?", 0, ["28", "49", "14", "35"]),
    q!(Category::Math, Difficulty::Medium, "Combien font 10 % de 350 ?", 1, ["30", "35", "40", "50"]),
    q!(Category::Math, Difficulty::Medium, "Combien font les angles internes d'un triangle ?", 2, ["90°", "270°", "180°", "360°"]),
    q!(Category::Math, Difficulty::Medium, "Si 3x = 21, combien vaut x ?", 0, ["7", "6", "8", "9"]),
    q!(Category::Math, Difficulty::Medium, "Quelle est la puissance de 2 qui suit 32 ?", 1, ["48", "64", "128", "50"]),
    q!(Category::Math, Difficulty::Medium, "Combien vaut 0,25 exprimé en fraction ?", 3, ["1/2", "1/3", "2/5", "1/4"]),
    q!(Category::Math, Difficulty::Hard, "Quelle est l'intégrale de 2x ?", 2, ["2", "2x", "x²", "x"]),
    q!(Category::Math, Difficulty::Hard, "Si 2x + 7 = 19, combien vaut x ?", 0, ["6", "5", "7", "4"]),
    q!(Category::Math, Difficulty::Hard, "Combien vaut le logarithme naturel de e ?", 1, ["0", "1", "e", "2"]),
    q!(Category::Math, Difficulty::Hard, "Quelle est la pente de la droite y = 3x + 2 ?", 2, ["2", "x", "3", "5"]),
    q!(Category::Math, Difficulty::Hard, "Combien font les angles internes d'un hexagone ?", 0, ["720°", "540°", "900°", "1080°"]),
    q!(Category::Math, Difficulty::Hard, "Quelle est la probabilité d'obtenir deux faces en lançant deux pièces ?", 1, ["1/2", "1/4", "1/3", "3/4"]),
    q!(Category::Math, Difficulty::Hard, "Combien font 15 % de 240 ?", 3, ["24", "30", "32", "36"]),
    q!(Category::Math, Difficulty::Hard, "Si x² = 121, combien vaut x ?", 2, ["12", "10", "11", "21"]),
    q!(Category::Math, Difficulty::Hard, "Combien font 8! divisé par 7! ?", 0, ["8", "7", "56", "1"]),
    q!(Category::Math, Difficulty::Hard, "Quelle est la médiane de 3, 5, 7, 9 et 11 ?", 1, ["5", "7", "9", "6"]),
    // -- Mathématiques (ouvertes) --
    q_open!(Category::Math, Difficulty::Easy, "Combien font 12 x 4 ?", "48"),
    q_open!(Category::Math, Difficulty::Easy, "Combien font 30 + 45 ?", "75"),
    q_open!(Category::Math, Difficulty::Easy, "Combien de côtés a un hexagone ?", "6"),
    q_open!(Category::Math, Difficulty::Easy, "Quel est le double de 24 ?", "48"),
    q_open!(Category::Math, Difficulty::Easy, "Combien font 90 ÷ 3 ?", "30"),
    q_open!(Category::Math, Difficulty::Medium, "Quelle est l'aire d'un carré de côté 6 ?", "36"),
    q_open!(Category::Math, Difficulty::Medium, "Combien font 3/4 de 100 ?", "75"),
    q_open!(Category::Math, Difficulty::Medium, "Quel est le nombre premier qui suit 7 ?", "11"),
    q_open!(Category::Math, Difficulty::Medium, "Combien font 2 élevé à la puissance 8 ?", "256"),
    q_open!(Category::Math, Difficulty::Medium, "Quelle est la racine carrée de 144 ?", "12"),
    q_open!(Category::Math, Difficulty::Hard, "Si 4x - 5 = 11, combien vaut x ?", "4"),
    q_open!(Category::Math, Difficulty::Hard, "Quelle est la dérivée de x³ ?", "3x²"),
    q_open!(Category::Math, Difficulty::Hard, "Combien font les angles internes d'un octogone ?", "1080"),
    q_open!(Category::Math, Difficulty::Hard, "Quelle est la probabilité de tirer un as d'un jeu de 40 cartes espagnol ?", "1/10"),
    q_open!(Category::Math, Difficulty::Hard, "Combien font 20 % de 150 ?", "30"),
    // -- Histoire (fermées) --
    q!(Category::History, Difficulty::Easy, "Dans quelle ville se trouve le Colisée ?", 2, ["Athènes", "Paris", "Rome", "Madrid"]),
    q!(Category::History, Difficulty::Easy, "Quel pays a construit la Grande Muraille ?", 3, ["Japon", "Mongolie", "Inde", "Chine"]),
    q!(Category::History, Difficulty::Easy, "Quelle civilisation a construit le Machu Picchu ?", 1, ["Mayas", "Incas", "Aztèques", "Olmèques"]),
    q!(Category::History, Difficulty::Easy, "Dans quel pays se trouve l'Acropole ?", 1, ["Italie", "Grèce", "Turquie", "Égypte"]),
    q!(Category::History, Difficulty::Easy, "Qui a lutté contre l'apartheid en Afrique du Sud ?", 2, ["Luther King", "Gandhi", "Mandela", "Che Guevara"]),
    q!(Category::History, Difficulty::Easy, "En quelle année est tombé l'Empire romain d'Occident ?", 0, ["476", "395", "1453", "1066"]),
    q!(Category::History, Difficulty::Easy, "Quelle reine a financé le voyage de Colomb ?", 1, ["Jeanne la Folle", "Isabelle la Catholique", "Marie Tudor", "Catherine d'Aragon"]),
    q!(Category::History, Difficulty::Easy, "Quel général romain a franchi le Rubicon ?", 0, ["César", "Néron", "Auguste", "Caligula"]),
    q!(Category::History, Difficulty::Easy, "Quelle ville fut la capitale de l'Empire inca ?", 1, ["Cusco", "Lima", "Quito", "Bogotá"]),
    q!(Category::History, Difficulty::Easy, "Quel peuple est arrivé en Amérique avant Colomb ?", 1, ["Saxons", "Vikings", "Francs", "Huns"]),
    q!(Category::History, Difficulty::Medium, "En quelle année a commencé la Seconde Guerre mondiale ?", 1, ["1935", "1939", "1941", "1937"]),
    q!(Category::History, Difficulty::Medium, "Quel pays a lancé les bombes atomiques en 1945 ?", 0, ["États-Unis", "Allemagne", "Japon", "Russie"]),
    q!(Category::History, Difficulty::Medium, "Qui a été assassiné à Sarajevo en 1914 ?", 2, ["Guillaume II", "Nicolas II", "François-Ferdinand", "Bismarck"]),
    q!(Category::History, Difficulty::Medium, "À quelle dynastie appartenait Charles Ier d'Espagne ?", 1, ["Bourbon", "Habsbourg", "Trastamare", "Autriche"]),
    q!(Category::History, Difficulty::Medium, "Quel empire avait sa capitale à Tenochtitlán ?", 3, ["Maya", "Inca", "Olmèque", "Aztèque"]),
    q!(Category::History, Difficulty::Medium, "Quel conquistador a vaincu l'Empire aztèque ?", 0, ["Cortés", "Pizarro", "Balboa", "Magellan"]),
    q!(Category::History, Difficulty::Medium, "Qu'a inventé Gutenberg au XVe siècle ?", 2, ["Télescope", "Boussole", "Imprimerie", "Poudre à canon"]),
    q!(Category::History, Difficulty::Medium, "En quelle année s'est terminée la guerre civile espagnole ?", 1, ["1936", "1939", "1945", "1931"]),
    q!(Category::History, Difficulty::Medium, "Quel traité a mis fin à la guerre de Succession d'Espagne ?", 0, ["Utrecht", "Versailles", "Vienne", "Westphalie"]),
    q!(Category::History, Difficulty::Medium, "Qui a été le premier président du Mexique ?", 2, ["Juárez", "Santa Anna", "Guadalupe Victoria", "Iturbide"]),
    q!(Category::History, Difficulty::Hard, "En quelle année a été proclamée la Première République espagnole ?", 1, ["1868", "1873", "1876", "1898"]),
    q!(Category::History, Difficulty::Hard, "Quelle bataille de 1805 a gagné Napoléon ?", 0, ["Austerlitz", "Waterloo", "Trafalgar", "Leipzig"]),
    q!(Category::History, Difficulty::Hard, "Quel empereur romain a légalisé le christianisme ?", 2, ["Néron", "Dioclétien", "Constantin", "Théodose"]),
    q!(Category::History, Difficulty::Hard, "Quelle bataille de 1066 a gagné Guillaume de Normandie ?", 1, ["Azincourt", "Hastings", "Poitiers", "Covadonga"]),
    q!(Category::History, Difficulty::Hard, "Quel général carthaginois a traversé les Alpes avec des éléphants ?", 3, ["César", "Pompée", "Alexandre", "Hannibal"]),
    q!(Category::History, Difficulty::Hard, "En quelle année a été signé le traité de Tordesillas ?", 2, ["1492", "1493", "1494", "1500"]),
    q!(Category::History, Difficulty::Hard, "Quel sultan ottoman a conquis Constantinople ?", 0, ["Mehmed II", "Soliman", "Bajazet", "Osman Ier"]),
    q!(Category::History, Difficulty::Hard, "Quelle révolution a commencé en 1910 ?", 1, ["Russe", "Mexicaine", "Française", "Chinoise"]),
    q!(Category::History, Difficulty::Hard, "Quelle monarque britannique a régné jusqu'en 2022 ?", 2, ["Victoria", "Élisabeth Ire", "Élisabeth II", "Anne"]),
    q!(Category::History, Difficulty::Hard, "Quelle civilisation a développé le calendrier le plus précis de l'Antiquité ?", 1, ["Aztèque", "Maya", "Inca", "Égyptienne"]),
    // -- Histoire (ouvertes) --
    q_open!(Category::History, Difficulty::Easy, "En quelle année l'homme a-t-il marché sur la Lune ?", "1969"),
    q_open!(Category::History, Difficulty::Easy, "Quel pays européen a colonisé la majeure partie de l'Amérique du Sud ?", "Espagne"),
    q_open!(Category::History, Difficulty::Easy, "En quelle année l'Amérique a-t-elle été découverte ?", "1492"),
    q_open!(Category::History, Difficulty::Easy, "Quel empereur le pape a-t-il couronné en l'an 800 ?", "Charlemagne"),
    q_open!(Category::History, Difficulty::Easy, "Quelle civilisation antique a construit le Parthénon ?", "Grecs"),
    q_open!(Category::History, Difficulty::Medium, "En quelle année s'est terminée la Seconde Guerre mondiale ?", "1945"),
    q_open!(Category::History, Difficulty::Medium, "Qui a mené l'indépendance de l'Inde ?", "Gandhi"),
    q_open!(Category::History, Difficulty::Medium, "Quel président des États-Unis a aboli l'esclavage ?", "Lincoln"),
    q_open!(Category::History, Difficulty::Medium, "En quelle année a été signé le traité de Maastricht ?", "1992"),
    q_open!(Category::History, Difficulty::Medium, "Quel pharaon est célèbre pour son tombeau doré ?", "Toutânkhamon"),
    q_open!(Category::History, Difficulty::Hard, "En quelle année est tombée Constantinople ?", "1453"),
    q_open!(Category::History, Difficulty::Hard, "Qui fut le dernier empereur romain d'Occident ?", "Romulus Augustule"),
    q_open!(Category::History, Difficulty::Hard, "Quel congrès de 1815 a réorganisé l'Europe après Napoléon ?", "Vienne"),
    q_open!(Category::History, Difficulty::Hard, "Quelle bataille de 1521 a marqué la chute de Tenochtitlán ?", "Tenochtitlán"),
    q_open!(Category::History, Difficulty::Hard, "Quel pays a rendu Hong Kong à la Chine en 1997 ?", "Royaume-Uni"),
    // -- Informatique (fermées) --
    q!(Category::Cs, Difficulty::Easy, "Quelle touche efface le caractère à droite du curseur ?", 0, ["Suppr", "Maj", "Alt", "Tab"]),
    q!(Category::Cs, Difficulty::Easy, "Quelle extension ont les photographies numériques ?", 1, [".txt", ".jpg", ".mp3", ".docx"]),
    q!(Category::Cs, Difficulty::Easy, "Quel programme sert à faire des calculs et des tableaux ?", 2, ["Traitement de texte", "Navigateur", "Tableur", "Antivirus"]),
    q!(Category::Cs, Difficulty::Easy, "Quelle touche appuies-tu pour accepter ou entrer ?", 0, ["Entrée", "Échap", "F1", "Maj"]),
    q!(Category::Cs, Difficulty::Easy, "Que signifie le bouton de la disquette dans beaucoup de programmes ?", 3, ["Ouvrir", "Imprimer", "Supprimer", "Enregistrer"]),
    q!(Category::Cs, Difficulty::Easy, "Quel dispositif utilises-tu pour écouter de l'audio ?", 1, ["Clavier", "Écouteurs", "Souris", "Caméra"]),
    q!(Category::Cs, Difficulty::Easy, "Qu'est-ce qu'ouvre le bouton droit de la souris ?", 0, ["Un menu contextuel", "Il sélectionne tout", "Il ferme le programme", "Il copie le texte"]),
    q!(Category::Cs, Difficulty::Easy, "Quelle extension ont les chansons numériques ?", 2, [".jpg", ".exe", ".mp3", ".doc"]),
    q!(Category::Cs, Difficulty::Easy, "Quelle technologie connecte l'ordinateur à Internet sans câbles ?", 1, ["Bluetooth", "Wi-Fi", "USB", "HDMI"]),
    q!(Category::Cs, Difficulty::Easy, "Quelle touche actualise une page web ?", 0, ["F5", "F2", "F10", "F12"]),
    q!(Category::Cs, Difficulty::Medium, "Quel préfixe informatique équivaut à environ un milliard d'octets ?", 2, ["Méga", "Téra", "Giga", "Péta"]),
    q!(Category::Cs, Difficulty::Medium, "Comment sont organisés les dossiers du système de fichiers ?", 1, ["En liste", "En arbre", "En pile", "En graphe"]),
    q!(Category::Cs, Difficulty::Medium, "Que fait print() en Python ?", 3, ["Effacer du texte", "Enregistrer un fichier", "Lire le clavier", "Afficher du texte à l'écran"]),
    q!(Category::Cs, Difficulty::Medium, "Quelle unité mesure la vitesse du processeur ?", 0, ["GHz", "Go", "Mo", "Watt"]),
    q!(Category::Cs, Difficulty::Medium, "Qu'est-ce qu'un bug ?", 2, ["Un virus", "Un hacker", "Une erreur dans le programme", "Une mise à jour"]),
    q!(Category::Cs, Difficulty::Medium, "Quelle combinaison copie sous Windows ?", 1, ["Ctrl + V", "Ctrl + C", "Ctrl + X", "Ctrl + Z"]),
    q!(Category::Cs, Difficulty::Medium, "Quel composant se charge de dessiner à l'écran ?", 0, ["GPU", "CPU", "RAM", "SSD"]),
    q!(Category::Cs, Difficulty::Medium, "Quel protocole transfère des fichiers ?", 2, ["HTTP", "SMTP", "FTP", "DNS"]),
    q!(Category::Cs, Difficulty::Medium, "Que signifie le S de HTTPS ?", 1, ["Serveur", "Sécurisé", "Système", "Seul"]),
    q!(Category::Cs, Difficulty::Medium, "Quelle mémoire est la plus rapide ?", 3, ["Disque dur", "SSD externe", "CD-ROM", "RAM"]),
    q!(Category::Cs, Difficulty::Hard, "Quelle complexité a le tri rapide (quicksort) en moyenne ?", 1, ["O(n)", "O(n log n)", "O(n²)", "O(log n)"]),
    q!(Category::Cs, Difficulty::Hard, "Quelle structure permet un accès par indice en temps constant ?", 0, ["Tableau", "Liste chaînée", "Pile", "File"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce que la récursivité ?", 2, ["Une boucle infinie", "Une erreur", "Une fonction qui s'appelle elle-même", "Une variable globale"]),
    q!(Category::Cs, Difficulty::Hard, "Quel langage compile directement en code machine ?", 0, ["C", "Python", "JavaScript", "Ruby"]),
    q!(Category::Cs, Difficulty::Hard, "Quel protocole convertit les domaines en adresses IP ?", 3, ["HTTP", "FTP", "SMTP", "DNS"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'exprime la notation Big O ?", 0, ["La complexité de l'algorithme", "La taille du fichier", "La vitesse du processeur", "Le nombre d'erreurs"]),
    q!(Category::Cs, Difficulty::Hard, "Qu'est-ce que la mémoire cache ?", 1, ["Mémoire externe", "Mémoire rapide proche du processeur", "Mémoire en lecture seule", "Mémoire virtuelle"]),
    q!(Category::Cs, Difficulty::Hard, "Quelle recherche parcourt les éléments un par un ?", 2, ["Dichotomique", "En arbre", "Linéaire", "Par hachage"]),
    q!(Category::Cs, Difficulty::Hard, "Que signifie API ?", 0, ["Application Programming Interface", "Application de protocoles internes", "Automatisation de processus informatiques", "Accès personnel à Internet"]),
    q!(Category::Cs, Difficulty::Hard, "Quelle structure implémente le bouton 'retour' du navigateur ?", 1, ["File", "Pile", "Tableau", "Hachage"]),
    // -- Informatique (ouvertes) --
    q_open!(Category::Cs, Difficulty::Easy, "Quelle touche sert à quitter ou annuler ?", "Échap"),
    q_open!(Category::Cs, Difficulty::Easy, "Quel dispositif sert à imprimer ?", "Imprimante"),
    q_open!(Category::Cs, Difficulty::Easy, "Quelle extension ont les vidéos ?", "mp4"),
    q_open!(Category::Cs, Difficulty::Easy, "Qu'est-ce qu'on utilise pour écrire sur l'ordinateur ?", "Clavier"),
    q_open!(Category::Cs, Difficulty::Easy, "Quelle application joue de la musique et des vidéos ?", "Lecteur"),
    q_open!(Category::Cs, Difficulty::Medium, "Quel langage crée des pages web interactives ?", "JavaScript"),
    q_open!(Category::Cs, Difficulty::Medium, "Quelle commande crée un dossier sous Linux ?", "mkdir"),
    q_open!(Category::Cs, Difficulty::Medium, "Quelle unité est plus grande, Ko ou Mo ?", "Mo"),
    q_open!(Category::Cs, Difficulty::Medium, "Quel langage met en forme les pages web ?", "CSS"),
    q_open!(Category::Cs, Difficulty::Medium, "Quelle touche capture l'écran sous Windows ?", "Impr écran"),
    q_open!(Category::Cs, Difficulty::Hard, "Quel algorithme de tri est stable et efficace avec des listes presque triées ?", "Insertion"),
    q_open!(Category::Cs, Difficulty::Hard, "Quelle structure permet d'insérer et de supprimer aux deux extrémités ?", "Deque"),
    q_open!(Category::Cs, Difficulty::Hard, "Quelle commande git envoie les changements au dépôt distant ?", "git push"),
    q_open!(Category::Cs, Difficulty::Hard, "Quelle attaque imite un site légitime pour voler des données ?", "Phishing"),
    q_open!(Category::Cs, Difficulty::Hard, "Quel langage de programmation utilise le framework Spring ?", "Java"),
    // -- Géographie (fermées) --
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de l'Italie ?", 2, ["Milan", "Naples", "Rome", "Venise"]),
    q!(Category::Geography, Difficulty::Easy, "Quel est le plus grand continent ?", 0, ["Asie", "Afrique", "Amérique", "Europe"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de l'Argentine ?", 1, ["Rosario", "Buenos Aires", "Córdoba", "La Plata"]),
    q!(Category::Geography, Difficulty::Easy, "Quel pays a la tour Eiffel ?", 3, ["Italie", "Allemagne", "Royaume-Uni", "France"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale du Mexique ?", 2, ["Guadalajara", "Monterrey", "Mexico", "Puebla"]),
    q!(Category::Geography, Difficulty::Easy, "Quel est le pays le plus peuplé d'Afrique ?", 1, ["Égypte", "Nigeria", "Éthiopie", "Afrique du Sud"]),
    q!(Category::Geography, Difficulty::Easy, "Quel fleuve traverse Paris ?", 0, ["Seine", "Rhône", "Loire", "Garonne"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale du Chili ?", 3, ["Valparaíso", "Concepción", "Viña del Mar", "Santiago"]),
    q!(Category::Geography, Difficulty::Easy, "Quelle est la capitale du Pérou ?", 1, ["Arequipa", "Lima", "Cusco", "Trujillo"]),
    q!(Category::Geography, Difficulty::Easy, "Sur quel continent se trouve l'Australie ?", 0, ["Océanie", "Asie", "Europe", "Afrique"]),
    q!(Category::Geography, Difficulty::Medium, "Quel est le fleuve le plus puissant du monde ?", 2, ["Nil", "Yangtsé", "Amazone", "Mississippi"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de la Suède ?", 1, ["Oslo", "Stockholm", "Copenhague", "Helsinki"]),
    q!(Category::Geography, Difficulty::Medium, "Quel détroit sépare l'Asie de l'Amérique ?", 0, ["Béring", "Panama", "Suez", "Magellan"]),
    q!(Category::Geography, Difficulty::Medium, "Quel est le plus haut sommet d'Europe ?", 1, ["Mont Blanc", "Elbrouz", "Teide", "Aneto"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de la Turquie ?", 2, ["Istanbul", "Izmir", "Ankara", "Antalya"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de la Pologne ?", 0, ["Varsovie", "Cracovie", "Gdansk", "Lodz"]),
    q!(Category::Geography, Difficulty::Medium, "Quel désert se trouve en Mongolie ?", 1, ["Sahara", "Gobi", "Kalahari", "Atacama"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de l'Autriche ?", 3, ["Salzbourg", "Graz", "Innsbruck", "Vienne"]),
    q!(Category::Geography, Difficulty::Medium, "Quel pays a la plus grande population d'Amérique du Sud ?", 0, ["Brésil", "Argentine", "Colombie", "Pérou"]),
    q!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de l'Irlande ?", 1, ["Belfast", "Dublin", "Cork", "Galway"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale de l'Ouzbékistan ?", 2, ["Samarcande", "Boukhara", "Tachkent", "Almaty"]),
    q!(Category::Geography, Difficulty::Hard, "Quel est le fleuve le plus long d'Asie ?", 0, ["Yangtsé", "Gange", "Euphrate", "Ob"]),
    q!(Category::Geography, Difficulty::Hard, "Quel est le point le plus bas de la surface émergée ?", 1, ["Mer Caspienne", "Mer Morte", "Lac Baïkal", "Vallée de la Mort"]),
    q!(Category::Geography, Difficulty::Hard, "Quel pays d'Océanie est à la fois un continent ?", 3, ["Nouvelle-Zélande", "Papouasie", "Fidji", "Australie"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale de l'Éthiopie ?", 0, ["Addis-Abeba", "Le Caire", "Nairobi", "Khartoum"]),
    q!(Category::Geography, Difficulty::Hard, "Quel pays a le plus d'îles au monde ?", 1, ["Japon", "Suède", "Indonésie", "Philippines"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale du Viêt Nam ?", 2, ["Hô Chi Minh-Ville", "Da Nang", "Hanoï", "Hué"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la plus longue chaîne de montagnes du monde ?", 1, ["Himalaya", "Andes", "Alpes", "Rocheuses"]),
    q!(Category::Geography, Difficulty::Hard, "Quel pays s'étend sur deux continents ?", 0, ["Russie", "Espagne", "Italie", "Pologne"]),
    q!(Category::Geography, Difficulty::Hard, "Quelle est la capitale de l'Islande ?", 3, ["Copenhague", "Helsinki", "Oslo", "Reykjavik"]),
    // -- Géographie (ouvertes) --
    q_open!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de l'Angleterre ?", "Londres"),
    q_open!(Category::Geography, Difficulty::Easy, "Quel est le plus petit océan ?", "Arctique"),
    q_open!(Category::Geography, Difficulty::Easy, "Sur quel continent se trouve le Brésil ?", "Amérique"),
    q_open!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de la Grèce ?", "Athènes"),
    q_open!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de Cuba ?", "La Havane"),
    q_open!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de la Corée du Sud ?", "Séoul"),
    q_open!(Category::Geography, Difficulty::Medium, "Quel est le fleuve le plus long d'Amérique ?", "Amazone"),
    q_open!(Category::Geography, Difficulty::Medium, "Quelle est la capitale de la Suisse ?", "Berne"),
    q_open!(Category::Geography, Difficulty::Medium, "Quel pays nordique a pour capitale Helsinki ?", "Finlande"),
    q_open!(Category::Geography, Difficulty::Medium, "Quelle est la capitale du Maroc ?", "Rabat"),
    q_open!(Category::Geography, Difficulty::Hard, "Quel est le plus grand désert d'Asie ?", "Gobi"),
    q_open!(Category::Geography, Difficulty::Hard, "Quelle est la capitale de la Birmanie ?", "Naypyidaw"),
    q_open!(Category::Geography, Difficulty::Hard, "Quel pays a la capitale la plus haute du monde ?", "Bolivie"),
    q_open!(Category::Geography, Difficulty::Hard, "Quel est le plus haut sommet d'Amérique du Nord ?", "Denali"),
    q_open!(Category::Geography, Difficulty::Hard, "Quel pays scandinave a pour capitale Copenhague ?", "Danemark"),
    // -- Science (fermées) --
    q!(Category::Science, Difficulty::Easy, "Quel organe utilises-tu pour penser ?", 2, ["Cœur", "Poumons", "Cerveau", "Estomac"]),
    q!(Category::Science, Difficulty::Easy, "Combien de pattes a un chat ?", 0, ["4", "2", "6", "8"]),
    q!(Category::Science, Difficulty::Easy, "Avec quelle partie du corps vois-tu ?", 1, ["Oreilles", "Yeux", "Nez", "Peau"]),
    q!(Category::Science, Difficulty::Easy, "Quel animal pond des œufs ?", 3, ["Vache", "Chien", "Chat", "Poule"]),
    q!(Category::Science, Difficulty::Easy, "Avec quel organe sens-tu les odeurs ?", 2, ["Yeux", "Bouche", "Nez", "Mains"]),
    q!(Category::Science, Difficulty::Easy, "Quel est le plus grand animal terrestre ?", 0, ["Éléphant", "Girafe", "Rhinocéros", "Hippopotame"]),
    q!(Category::Science, Difficulty::Easy, "De quoi le feu a-t-il besoin pour brûler ?", 1, ["Eau", "Oxygène", "Sable", "Terre"]),
    q!(Category::Science, Difficulty::Easy, "Quelle est la plus petite planète du système solaire ?", 2, ["Mars", "Vénus", "Mercure", "Pluton"]),
    q!(Category::Science, Difficulty::Easy, "Quel gaz expires-tu en respirant ?", 0, ["CO2", "Oxygène", "Azote", "Hydrogène"]),
    q!(Category::Science, Difficulty::Easy, "Quel animal vit en Antarctique ?", 1, ["Ours polaire", "Manchot", "Lion", "Chameau"]),
    q!(Category::Science, Difficulty::Medium, "Quelle énergie a un ballon en mouvement ?", 2, ["Potentielle", "Chimique", "Cinétique", "Thermique"]),
    q!(Category::Science, Difficulty::Medium, "Quelle planète a des jours plus longs que son année ?", 0, ["Vénus", "Mars", "Mercure", "Neptune"]),
    q!(Category::Science, Difficulty::Medium, "Quel est l'oiseau le plus rapide en piqué ?", 1, ["Aigle", "Faucon pèlerin", "Hirondelle", "Colibri"]),
    q!(Category::Science, Difficulty::Medium, "Quel métal est utilisé dans les câbles électriques ?", 2, ["Fer", "Aluminium", "Cuivre", "Or"]),
    q!(Category::Science, Difficulty::Medium, "Quelle couche de l'atmosphère contient la couche d'ozone ?", 0, ["Stratosphère", "Troposphère", "Mésosphère", "Exosphère"]),
    q!(Category::Science, Difficulty::Medium, "Quelle force maintient les planètes en orbite autour du Soleil ?", 1, ["Magnétisme", "Gravité", "Friction", "Inertie"]),
    q!(Category::Science, Difficulty::Medium, "Combien de temps met la lumière du Soleil pour atteindre la Terre ?", 2, ["1 seconde", "1 heure", "8 minutes", "24 heures"]),
    q!(Category::Science, Difficulty::Medium, "Quelle planète a le jour le plus court ?", 1, ["Mars", "Jupiter", "Vénus", "Mercure"]),
    q!(Category::Science, Difficulty::Medium, "Quelle substance donne la couleur verte aux plantes ?", 3, ["Mélanine", "Hémoglobine", "Kératine", "Chlorophylle"]),
    q!(Category::Science, Difficulty::Medium, "Quel organe élimine le dioxyde de carbone ?", 0, ["Poumons", "Reins", "Foie", "Cœur"]),
    q!(Category::Science, Difficulty::Hard, "Quelle est l'unité de la résistance électrique ?", 2, ["Ampère", "Volt", "Ohm", "Watt"]),
    q!(Category::Science, Difficulty::Hard, "Quelle loi de Newton explique l'inertie au freinage ?", 1, ["Seconde", "Première", "Troisième", "De la gravitation"]),
    q!(Category::Science, Difficulty::Hard, "Quelle particule orbite autour du noyau de l'atome ?", 0, ["Électron", "Proton", "Neutron", "Quark"]),
    q!(Category::Science, Difficulty::Hard, "Quel processus divise une cellule en deux ?", 3, ["Photosynthèse", "Méiose", "Digestion", "Mitose"]),
    q!(Category::Science, Difficulty::Hard, "Quel est l'élément le plus abondant du corps humain ?", 1, ["Carbone", "Oxygène", "Hydrogène", "Azote"]),
    q!(Category::Science, Difficulty::Hard, "Que se passe-t-il quand la Lune s'interpose entre le Soleil et la Terre ?", 2, ["Éclipse lunaire", "Marée haute", "Éclipse solaire", "Solstice"]),
    q!(Category::Science, Difficulty::Hard, "Quelle grandeur mesure le newton ?", 0, ["Force", "Énergie", "Puissance", "Vitesse"]),
    q!(Category::Science, Difficulty::Hard, "Quelle est la vitesse approximative du son dans l'air ?", 1, ["300 m/s", "343 m/s", "1000 m/s", "1500 m/s"]),
    q!(Category::Science, Difficulty::Hard, "Quel type de liaison partage des électrons ?", 3, ["Ionique", "Métallique", "Van der Waals", "Covalente"]),
    q!(Category::Science, Difficulty::Hard, "Quelle planète a le champ magnétique le plus intense ?", 0, ["Jupiter", "Terre", "Saturne", "Uranus"]),
    // -- Science (ouvertes) --
    q_open!(Category::Science, Difficulty::Easy, "Combien d'yeux a un être humain ?", "2"),
    q_open!(Category::Science, Difficulty::Easy, "Quel est l'animal le plus grand du monde ?", "Girafe"),
    q_open!(Category::Science, Difficulty::Easy, "Quelle est l'étoile la plus proche de la Terre ?", "Soleil"),
    q_open!(Category::Science, Difficulty::Easy, "Quelle partie de la plante absorbe l'eau du sol ?", "Racine"),
    q_open!(Category::Science, Difficulty::Easy, "Combien d'heures a un jour ?", "24"),
    q_open!(Category::Science, Difficulty::Medium, "Quel type d'animal est le dauphin ?", "Mammifère"),
    q_open!(Category::Science, Difficulty::Medium, "Quelle est la planète la plus chaude du système solaire ?", "Vénus"),
    q_open!(Category::Science, Difficulty::Medium, "Quelle cellule combat les infections ?", "Globule blanc"),
    q_open!(Category::Science, Difficulty::Medium, "Quel phénomène produit les éclairs lors des orages ?", "Électricité"),
    q_open!(Category::Science, Difficulty::Medium, "Quel métal est le meilleur conducteur d'électricité ?", "Argent"),
    q_open!(Category::Science, Difficulty::Hard, "Quelle est la formule de l'acide sulfurique ?", "H2SO4"),
    q_open!(Category::Science, Difficulty::Hard, "Quel scientifique a proposé la relativité générale ?", "Einstein"),
    q_open!(Category::Science, Difficulty::Hard, "Quelle est l'unité de puissance du SI ?", "Watt"),
    q_open!(Category::Science, Difficulty::Hard, "Quelle particule est sa propre antiparticule ?", "Photon"),
    q_open!(Category::Science, Difficulty::Hard, "Quel processus convertit l'azote de l'air en composés utiles aux plantes ?", "Fixation"),
    // -- Art (fermées) --
    q!(Category::Art, Difficulty::Easy, "Quel instrument à cordes se joue avec un archet ?", 0, ["Violon", "Guitare", "Piano", "Batterie"]),
    q!(Category::Art, Difficulty::Easy, "Quelles sont les couleurs primaires ?", 1, ["Vert, orange et violet", "Rouge, bleu et jaune", "Noir, blanc et gris", "Rose, lilas et turquoise"]),
    q!(Category::Art, Difficulty::Easy, "Qui a peint 'Le Cri' ?", 2, ["Dalí", "Picasso", "Munch", "Klimt"]),
    q!(Category::Art, Difficulty::Easy, "Quelle œuvre se suspend au mur ?", 1, ["Sculpture", "Tableau", "Pot", "Tapisserie"]),
    q!(Category::Art, Difficulty::Easy, "Quel célèbre compositeur était sourd ?", 0, ["Beethoven", "Mozart", "Bach", "Vivaldi"]),
    q!(Category::Art, Difficulty::Easy, "Quel instrument de percussion a une forme triangulaire ?", 3, ["Flûte", "Hautbois", "Xylophone", "Triangle"]),
    q!(Category::Art, Difficulty::Easy, "Quelle couleur obtient-on en mélangeant rouge et bleu ?", 2, ["Vert", "Orange", "Violet", "Rose"]),
    q!(Category::Art, Difficulty::Easy, "Quel musée de Paris abrite la Joconde ?", 1, ["Prado", "Louvre", "Met", "Hermitage"]),
    q!(Category::Art, Difficulty::Easy, "Qu'est-ce qu'un portrait ?", 0, ["La peinture d'une personne", "La peinture d'un paysage", "La peinture de fruits", "La peinture abstraite"]),
    q!(Category::Art, Difficulty::Easy, "Quel instrument de percussion se joue avec des baguettes ?", 1, ["Harpe", "Batterie", "Violoncelle", "Saxophone"]),
    q!(Category::Art, Difficulty::Medium, "Quel peintre espagnol a peint 'Los fusilamientos del 3 de mayo' ?", 2, ["Le Greco", "Velázquez", "Goya", "Zurbarán"]),
    q!(Category::Art, Difficulty::Medium, "Quel mouvement utilise des couleurs vives et des figures de bande dessinée ?", 0, ["Pop Art", "Baroque", "Renaissance", "Réalisme"]),
    q!(Category::Art, Difficulty::Medium, "Qui a écrit 'Orgueil et Préjugés' ?", 1, ["Eliot", "Austen", "Bronte", "Woolf"]),
    q!(Category::Art, Difficulty::Medium, "Quelle œuvre est de Botticelli ?", 2, ["La Joconde", "Le David", "La Naissance de Vénus", "La Cène"]),
    q!(Category::Art, Difficulty::Medium, "Quel instrument à cordes frottées est le plus grave du quatuor ?", 0, ["Violoncelle", "Flûte", "Trompette", "Batterie"]),
    q!(Category::Art, Difficulty::Medium, "Quelle artiste mexicaine a peint de célèbres autoportraits ?", 1, ["Rivera", "Frida Kahlo", "Orozco", "Tamayo"]),
    q!(Category::Art, Difficulty::Medium, "Qui a composé 'Le Beau Danube bleu' ?", 3, ["Beethoven", "Schubert", "Mahler", "Strauss"]),
    q!(Category::Art, Difficulty::Medium, "Qui a écrit 'Les Trois Mousquetaires' ?", 0, ["Dumas", "Hugo", "Verne", "Zola"]),
    q!(Category::Art, Difficulty::Medium, "Quel style peignait la vie quotidienne telle qu'elle est ?", 2, ["Cubisme", "Baroque", "Réalisme", "Surréalisme"]),
    q!(Category::Art, Difficulty::Medium, "Quel instrument à soufflet est utilisé dans le tango ?", 1, ["Accordéon", "Bandoneón", "Orgue", "Harmonica"]),
    q!(Category::Art, Difficulty::Hard, "Quel peintre hollandais a peint 'La Ronde de nuit' ?", 2, ["Vermeer", "Van Gogh", "Rembrandt", "Rubens"]),
    q!(Category::Art, Difficulty::Hard, "Qui a écrit 'Guerre et Paix' ?", 0, ["Tolstoï", "Dostoïevski", "Tchekhov", "Pouchkine"]),
    q!(Category::Art, Difficulty::Hard, "Quel compositeur polonais a écrit presque uniquement pour piano ?", 1, ["Liszt", "Chopin", "Debussy", "Satie"]),
    q!(Category::Art, Difficulty::Hard, "Quel peintre autrichien a peint 'Le Baiser' ?", 2, ["Schiele", "Kandinsky", "Klimt", "Munch"]),
    q!(Category::Art, Difficulty::Hard, "Quel écrivain tchèque a écrit 'La Métamorphose' ?", 0, ["Kafka", "Hesse", "Mann", "Musil"]),
    q!(Category::Art, Difficulty::Hard, "Quel peintre impressionniste a peint 'Impression, soleil levant' ?", 1, ["Degas", "Monet", "Renoir", "Pissarro"]),
    q!(Category::Art, Difficulty::Hard, "Quel opéra a composé Verdi ?", 2, ["Tosca", "Carmen", "Aïda", "Turandot"]),
    q!(Category::Art, Difficulty::Hard, "Quel poète a écrit 'Campos de Castilla' ?", 3, ["Unamuno", "Azorín", "Valle-Inclán", "Machado"]),
    q!(Category::Art, Difficulty::Hard, "Quel style musical a prospéré à Vienne au XVIIIe siècle ?", 0, ["Classicisme", "Romantisme", "Baroque", "Renaissance"]),
    q!(Category::Art, Difficulty::Hard, "Quel artiste a créé 'Maman', l'araignée géante ?", 1, ["Hirst", "Louise Bourgeois", "Kapoor", "Calder"]),
    // -- Art (ouvertes) --
    q_open!(Category::Art, Difficulty::Easy, "Quel instrument a 6 cordes et se joue avec un médiator ?", "Guitare"),
    q_open!(Category::Art, Difficulty::Easy, "Qui a peint 'La Cène' ?", "Léonard de Vinci"),
    q_open!(Category::Art, Difficulty::Easy, "Quel célèbre tableau de Léonard se trouve au Louvre ?", "La Joconde"),
    q_open!(Category::Art, Difficulty::Easy, "Comment s'appelle l'art de plier le papier ?", "Origami"),
    q_open!(Category::Art, Difficulty::Easy, "Quel compositeur a écrit la Cinquième Symphonie ?", "Beethoven"),
    q_open!(Category::Art, Difficulty::Medium, "Qui a écrit 'Crime et Châtiment' ?", "Dostoïevski"),
    q_open!(Category::Art, Difficulty::Medium, "Quel peintre français est célèbre pour ses nymphéas ?", "Monet"),
    q_open!(Category::Art, Difficulty::Medium, "Qui a composé 'Le Carnaval des animaux' ?", "Saint-Saëns"),
    q_open!(Category::Art, Difficulty::Medium, "Quel écrivain espagnol a écrit 'La Colmena' ?", "Cela"),
    q_open!(Category::Art, Difficulty::Medium, "Quel instrument à vent en métal a une forme de S ?", "Saxophone"),
    q_open!(Category::Art, Difficulty::Hard, "Quel écrivain a écrit 'Gatsby le Magnifique' ?", "Fitzgerald"),
    q_open!(Category::Art, Difficulty::Hard, "Quel compositeur a laissé un Requiem inachevé en mourant à 35 ans ?", "Mozart"),
    q_open!(Category::Art, Difficulty::Hard, "Quel mouvement est né en Italie avec le manifeste de Marinetti ?", "Futurisme"),
    q_open!(Category::Art, Difficulty::Hard, "Quel peintre baroque a peint 'Les Fileuses' ?", "Velázquez"),
    q_open!(Category::Art, Difficulty::Hard, "Quel opéra de Puccini se déroule au Japon ?", "Madama Butterfly"),
    // -- Tabou (fermées) --
    q!(Category::Taboo, Difficulty::Easy, "Il est long, il s'enroule et sert à mesurer. Qu'est-ce que c'est ?", 2, ["Règle", "Compas", "Mètre", "Équerre"]),
    q!(Category::Taboo, Difficulty::Easy, "Il sert à effacer ce que tu écris au crayon. Qu'est-ce que c'est ?", 0, ["Gomme", "Taille-crayon", "Règle", "Stylo"]),
    q!(Category::Taboo, Difficulty::Easy, "Il a beaucoup de pages et une couverture. Qu'est-ce que c'est ?", 1, ["Miroir", "Livre", "Ballon", "Sac à dos"]),
    q!(Category::Taboo, Difficulty::Easy, "On la met à la fenêtre pour que le soleil n'entre pas. Qu'est-ce que c'est ?", 3, ["Tapis", "Couverture", "Serviette", "Rideau"]),
    q!(Category::Taboo, Difficulty::Easy, "C'est un animal qui miaule. Qu'est-ce que c'est ?", 0, ["Chat", "Chien", "Oiseau", "Lapin"]),
    q!(Category::Taboo, Difficulty::Easy, "Elle donne de la lumière la nuit et s'allume en un clic. Qu'est-ce que c'est ?", 2, ["Ventilateur", "Télévision", "Lampe", "Montre"]),
    q!(Category::Taboo, Difficulty::Easy, "Il sert à s'asseoir et a un dossier. Qu'est-ce que c'est ?", 1, ["Table", "Chaise", "Lit", "Tabouret"]),
    q!(Category::Taboo, Difficulty::Easy, "Il sert à se laver les mains. Qu'est-ce que c'est ?", 3, ["Shampoing", "Dentifrice", "Serviette", "Savon"]),
    q!(Category::Taboo, Difficulty::Easy, "Il sert à sécher les cheveux. Qu'est-ce que c'est ?", 0, ["Sèche-cheveux", "Peigne", "Miroir", "Brosse"]),
    q!(Category::Taboo, Difficulty::Easy, "On la met sous la tête pour dormir. Qu'est-ce que c'est ?", 2, ["Couverture", "Drap", "Oreiller", "Matelas"]),
    q!(Category::Taboo, Difficulty::Medium, "Il sert à presser le jus des oranges. Qu'est-ce que c'est ?", 1, ["Mixeur", "Presse-agrumes", "Grille-pain", "Centrifugeuse"]),
    q!(Category::Taboo, Difficulty::Medium, "Elle sert à repasser les vêtements. Qu'est-ce que c'est ?", 0, ["Fer à repasser", "Cintre", "Corde", "Étendoir"]),
    q!(Category::Taboo, Difficulty::Medium, "Il sert à accrocher des tableaux au mur. Qu'est-ce que c'est ?", 2, ["Vis", "Écrou", "Clou", "Rondelle"]),
    q!(Category::Taboo, Difficulty::Medium, "Elle sert à garder l'argent et les documents. Qu'est-ce que c'est ?", 1, ["Sac à dos", "Portefeuille", "Sac à main", "Valise"]),
    q!(Category::Taboo, Difficulty::Medium, "Elle sert à faire dormir le bébé. Qu'est-ce que c'est ?", 3, ["Canapé", "Fauteuil", "Hamac", "Berceau"]),
    q!(Category::Taboo, Difficulty::Medium, "Il sert à couper l'herbe. Qu'est-ce que c'est ?", 0, ["Tondeuse", "Faux", "Sécateur", "Arrosoir"]),
    q!(Category::Taboo, Difficulty::Medium, "Elle sert à manger la soupe. Qu'est-ce que c'est ?", 2, ["Fourchette", "Couteau", "Cuillère", "Baguette"]),
    q!(Category::Taboo, Difficulty::Medium, "Il sert à ouvrir les bouteilles. Qu'est-ce que c'est ?", 1, ["Ouvre-boîte", "Décapsuleur", "Tire-bouchon", "Ciseaux"]),
    q!(Category::Taboo, Difficulty::Medium, "On le met sur la table et il est en tissu. Qu'est-ce que c'est ?", 0, ["Nappe", "Serviette", "Tablier", "Chiffon"]),
    q!(Category::Taboo, Difficulty::Medium, "Il sert à suspendre les vêtements mouillés. Qu'est-ce que c'est ?", 2, ["Cintre", "Fer à repasser", "Étendoir", "Armoire"]),
    q!(Category::Taboo, Difficulty::Hard, "Il sert à mesurer l'essence que tu mets dans la voiture. Qu'est-ce que c'est ?", 1, ["Manomètre", "Distributeur", "Taximètre", "Chronomètre"]),
    q!(Category::Taboo, Difficulty::Hard, "On l'utilise au théâtre pour projeter la lumière. Qu'est-ce que c'est ?", 0, ["Projecteur", "Mégaphone", "Haut-parleur", "Microphone"]),
    q!(Category::Taboo, Difficulty::Hard, "Appareil qui mesure la vitesse de la voiture. Qu'est-ce que c'est ?", 2, ["Taximètre", "Compteur kilométrique", "Compteur de vitesse", "Manomètre"]),
    q!(Category::Taboo, Difficulty::Hard, "Il régule la température du four. Qu'est-ce que c'est ?", 1, ["Thermomètre", "Thermostat", "Baromètre", "Hydromètre"]),
    q!(Category::Taboo, Difficulty::Hard, "Il sert à polir et faire briller les métaux. Qu'est-ce que c'est ?", 3, ["Brosse", "Pinceau", "Grattoir", "Papier de verre"]),
    q!(Category::Taboo, Difficulty::Hard, "Appareil avec lequel les médecins examinent l'oreille. Qu'est-ce que c'est ?", 0, ["Otoscope", "Ophtalmoscope", "Laryngoscope", "Stéthoscope"]),
    q!(Category::Taboo, Difficulty::Hard, "Il mesure la pression des pneus de la voiture. Qu'est-ce que c'est ?", 2, ["Baromètre", "Thermomètre", "Manomètre", "Anémomètre"]),
    q!(Category::Taboo, Difficulty::Hard, "Il enregistre l'activité électrique du cœur. Qu'est-ce que c'est ?", 1, ["Électroencéphalographe", "Électrocardiographe", "Tensiomètre", "Glucomètre"]),
    q!(Category::Taboo, Difficulty::Hard, "Il sert à accorder les instruments à cordes. Qu'est-ce que c'est ?", 3, ["Métronome", "Partition", "Archet", "Diapason"]),
    q!(Category::Taboo, Difficulty::Hard, "Il mesure la distance parcourue par un bateau. Qu'est-ce que c'est ?", 0, ["Loch", "Sextant", "Boussole", "Astrolabe"]),
    // -- Tabou (ouvertes) --
    q_open!(Category::Taboo, Difficulty::Easy, "Il a quatre pattes et fait 'ouaf'. Qu'est-ce que c'est ?", "chien"),
    q_open!(Category::Taboo, Difficulty::Easy, "Il sert à écrire sur du papier. Qu'est-ce que c'est ?", "crayon"),
    q_open!(Category::Taboo, Difficulty::Easy, "Il sert à boire de l'eau. Qu'est-ce que c'est ?", "verre"),
    q_open!(Category::Taboo, Difficulty::Easy, "On l'accroche au cou pour ne pas perdre les clés. Qu'est-ce que c'est ?", "porte-clés"),
    q_open!(Category::Taboo, Difficulty::Easy, "Il sert à ranger les crayons. Qu'est-ce que c'est ?", "trousse"),
    q_open!(Category::Taboo, Difficulty::Medium, "C'est un appareil qui chauffe la maison en hiver. Qu'est-ce que c'est ?", "chauffage"),
    q_open!(Category::Taboo, Difficulty::Medium, "Il sert à ramasser les feuilles du jardin. Qu'est-ce que c'est ?", "râteau"),
    q_open!(Category::Taboo, Difficulty::Medium, "C'est un animal qui fait 'coin-coin'. Qu'est-ce que c'est ?", "canard"),
    q_open!(Category::Taboo, Difficulty::Medium, "Elle sert à sécher le sol de la salle de bain. Qu'est-ce que c'est ?", "serpillière"),
    q_open!(Category::Taboo, Difficulty::Medium, "Il sert à laver la vaisselle à la main. Qu'est-ce que c'est ?", "éponge"),
    q_open!(Category::Taboo, Difficulty::Hard, "Il mesure l'humidité de l'air. Qu'est-ce que c'est ?", "hygromètre"),
    q_open!(Category::Taboo, Difficulty::Hard, "Il chauffe des substances à la flamme au laboratoire. Qu'est-ce que c'est ?", "bec Bunsen"),
    q_open!(Category::Taboo, Difficulty::Hard, "Il sert à voir de minuscules objets agrandis. Qu'est-ce que c'est ?", "microscope"),
    q_open!(Category::Taboo, Difficulty::Hard, "Il mesure la quantité de pluie tombée. Qu'est-ce que c'est ?", "pluviomètre"),
    q_open!(Category::Taboo, Difficulty::Hard, "Elle indique la direction du vent. Qu'est-ce que c'est ?", "girouette"),
];
