//! Partie 4 du banc français : Tabou.
use super::super::questions::{q, q_open, Category, Difficulty, Question};

pub static QUESTIONS_FR_4: &[Question] = &[
    // ================= Art =================
    q!(Category::Art, Difficulty::Hard, "Quel opéra de Verdi se déroule en Égypte ?", 1, ["Rigoletto", "Aïda", "La Traviata", "Otello"]),
    q!(Category::Art, Difficulty::Hard, "Quel peintre espagnol a peint 'La maja desnuda' ?", 1, ["Velázquez", "Goya", "Murillo", "Zurbarán"]),
    q!(Category::Art, Difficulty::Hard, "Quel écrivain a écrit 'El Buscón' ?", 1, ["Cervantes", "Quevedo", "Lope", "Gracián"]),
    q!(Category::Art, Difficulty::Hard, "Quel mouvement artistique a Dalí pour plus grand représentant ?", 1, ["Le cubisme", "Le surréalisme", "Le dadaïsme", "Le futurisme"]),
    // ================= Tabou =================
    // -- Facile --
    q!(Category::Taboo, Difficulty::Easy, "C'est un animal de la ferme qui pond des œufs. Qu'est-ce que c'est ?", 0, ["La poule", "La vache", "Le cochon", "La brebis"]),
    q!(Category::Taboo, Difficulty::Easy, "Il a 8 pattes et tisse des toiles. Qu'est-ce que c'est ?", 1, ["La fourmi", "L'araignée", "L'abeille", "La mouche"]),
    q!(Category::Taboo, Difficulty::Easy, "Il est jaune, allongé et les singes l'adorent. Qu'est-ce que c'est ?", 0, ["La banane", "La poire", "Le citron", "La mangue"]),
    q!(Category::Taboo, Difficulty::Easy, "Il sert à écrire et à effacer au tableau. Qu'est-ce que c'est ?", 1, ["Le feutre", "La craie", "Le crayon", "Le stylo à bille"]),
    q!(Category::Taboo, Difficulty::Easy, "Il a des aiguilles et indique l'heure. Qu'est-ce que c'est ?", 2, ["Le calendrier", "La boussole", "La montre", "Le chronomètre"]),
    q!(Category::Taboo, Difficulty::Easy, "C'est un moyen de transport à deux roues. Qu'est-ce que c'est ?", 3, ["La voiture", "La moto", "La trottinette", "La bicyclette"]),
    q!(Category::Taboo, Difficulty::Easy, "Tu l'utilises pour attacher tes chaussures. Qu'est-ce que c'est ?", 0, ["Le lacet", "La ceinture", "Le velcro", "La fermeture éclair"]),
    q!(Category::Taboo, Difficulty::Easy, "C'est un instrument de musique long, en métal et qui sonne fort. Qu'est-ce que c'est ?", 2, ["La flûte", "Le violon", "La trompette", "Le tambour"]),
    q!(Category::Taboo, Difficulty::Easy, "C'est un endroit où l'on prête des livres. Qu'est-ce que c'est ?", 1, ["La librairie", "La bibliothèque", "La papeterie", "L'imprimerie"]),
    q!(Category::Taboo, Difficulty::Easy, "Il sert à te regarder et à voir ton reflet. Qu'est-ce que c'est ?", 1, ["La fenêtre", "Le miroir", "La photo", "L'écran"]),
    // -- Moyen --
    q!(Category::Taboo, Difficulty::Medium, "Il sert à mesurer la fièvre. Qu'est-ce que c'est ?", 0, ["Le thermomètre", "Le baromètre", "Le tensiomètre", "La montre"]),
    q!(Category::Taboo, Difficulty::Medium, "Il a des touches et sert à faire des calculs. Qu'est-ce que c'est ?", 1, ["Le clavier", "La calculatrice", "La machine à écrire", "L'ordinateur"]),
    q!(Category::Taboo, Difficulty::Medium, "Elle garde la nourriture et la maintient froide. Qu'est-ce que c'est ?", 0, ["Le réfrigérateur", "Le four", "Le congélateur", "Le garde-manger"]),
    q!(Category::Taboo, Difficulty::Medium, "Les pompiers l'utilisent pour éteindre les feux. Qu'est-ce que c'est ?", 1, ["L'échelle", "Le tuyau", "La pelle", "L'extincteur"]),
    q!(Category::Taboo, Difficulty::Medium, "On l'accroche au mur et il montre le jour et le mois. Qu'est-ce que c'est ?", 3, ["L'emploi du temps", "La carte", "L'agenda", "Le calendrier"]),
    q!(Category::Taboo, Difficulty::Medium, "Il a des pages et sert à prendre des notes. Qu'est-ce que c'est ?", 0, ["Le cahier", "Le livre", "Le journal", "La feuille"]),
    q!(Category::Taboo, Difficulty::Medium, "Il sonne le matin pour te réveiller. Qu'est-ce que c'est ?", 2, ["La cloche", "La sirène", "Le réveil", "La sonnette"]),
    q!(Category::Taboo, Difficulty::Medium, "On la plante dans la terre et une plante en naît. Qu'est-ce que c'est ?", 3, ["La racine", "La fleur", "La feuille", "La graine"]),
    q!(Category::Taboo, Difficulty::Medium, "Tu l'ouvres pour entrer ou sortir d'une pièce. Qu'est-ce que c'est ?", 1, ["La fenêtre", "La porte", "Le portail", "La grille"]),
    q!(Category::Taboo, Difficulty::Medium, "Elle sert à pêcher dans la rivière avec une ligne. Qu'est-ce que c'est ?", 1, ["Le filet", "La canne à pêche", "Le harpon", "La barque"]),
    // -- Difficile --
    q!(Category::Taboo, Difficulty::Hard, "Instrument optique que les marins utilisaient pour voir de loin. Qu'est-ce que c'est ?", 0, ["La longue-vue", "Le télescope", "Les jumelles", "Le microscope"]),
    q!(Category::Taboo, Difficulty::Hard, "Il vole dans le ciel et décolle depuis une piste. Qu'est-ce que c'est ?", 2, ["L'hélicoptère", "Le ballon", "L'avion", "Le drone"]),
    q!(Category::Taboo, Difficulty::Hard, "Il sert à couper le papier en ligne droite. Qu'est-ce que c'est ?", 1, ["Le cutter", "Les ciseaux", "Le couteau", "L'ouvre-lettres"]),
    q!(Category::Taboo, Difficulty::Hard, "Il a une trompe, de grandes oreilles et il est très lourd. Qu'est-ce que c'est ?", 0, ["L'éléphant", "Le rhinocéros", "L'hippopotame", "Le mammouth"]),
    q!(Category::Taboo, Difficulty::Hard, "On le met sur la tête pour te protéger du soleil. Qu'est-ce que c'est ?", 2, ["La casquette", "La visière", "Le chapeau", "Le casque"]),
    q!(Category::Taboo, Difficulty::Hard, "Il sert à ouvrir les boîtes de conserve. Qu'est-ce que c'est ?", 0, ["L'ouvre-boîte", "Le décapsuleur", "Le couteau", "Les pinces"]),
    q!(Category::Taboo, Difficulty::Hard, "Elle donne de la lumière la nuit et fonctionne avec des piles. Qu'est-ce que c'est ?", 1, ["La bougie", "La lampe torche", "La lampe", "Le phare"]),
    q!(Category::Taboo, Difficulty::Hard, "C'est l'endroit où l'on soigne les malades. Qu'est-ce que c'est ?", 3, ["La pharmacie", "La clinique", "Le centre de santé", "L'hôpital"]),
    q!(Category::Taboo, Difficulty::Hard, "Il sert à dessiner à l'école et il a une mine. Qu'est-ce que c'est ?", 0, ["Le crayon", "Le stylo à bille", "La craie", "Le feutre"]),
    q!(Category::Taboo, Difficulty::Hard, "C'est un appareil à roues pour porter les courses. Qu'est-ce que c'est ?", 1, ["Le sac à dos", "Le chariot", "La valise", "Le panier"]),
    // -- Facile (grande série) --
    q!(Category::Taboo, Difficulty::Easy, "C'est un fruit rouge, rond et avec des pépins au centre. Qu'est-ce que c'est ?", 1, ["La poire", "La pomme", "L'orange", "La fraise"]),
    q!(Category::Taboo, Difficulty::Easy, "Il a quatre pattes, une queue et il aboie. Qu'est-ce que c'est ?", 2, ["Le chat", "Le lapin", "Le chien", "Le cheval"]),
    q!(Category::Taboo, Difficulty::Easy, "Tu le portes à la main pour ne pas te mouiller quand il pleut. Qu'est-ce que c'est ?", 0, ["Le parapluie", "La gabardine", "L'imperméable", "L'anorak"]),
    q!(Category::Taboo, Difficulty::Easy, "C'est un animal qui donne du lait et qui fait 'meuh'. Qu'est-ce que c'est ?", 1, ["La brebis", "La vache", "La chèvre", "La truie"]),
    q!(Category::Taboo, Difficulty::Easy, "Il sert à voir l'heure au poignet. Qu'est-ce que c'est ?", 1, ["Le réveil", "La montre-bracelet", "Le chronomètre", "L'horloge murale"]),
    q!(Category::Taboo, Difficulty::Easy, "Il est rond, en verre et sert à boire. Qu'est-ce que c'est ?", 1, ["La tasse", "Le verre", "La bouteille", "L'assiette"]),
    q!(Category::Taboo, Difficulty::Easy, "Tu l'utilises pour couper la nourriture sur la table. Qu'est-ce que c'est ?", 1, ["La cuillère", "Le couteau", "La fourchette", "La serviette"]),
    q!(Category::Taboo, Difficulty::Easy, "C'est un endroit avec beaucoup d'arbres où l'on va se promener. Qu'est-ce que c'est ?", 0, ["La forêt", "La plage", "Le désert", "La rivière"]),
    q!(Category::Taboo, Difficulty::Easy, "Il a des ailes et chante le matin. Qu'est-ce que c'est ?", 1, ["Le chat", "L'oiseau", "Le poisson", "Le chien"]),
    q!(Category::Taboo, Difficulty::Easy, "Tu l'utilises pour dormir et il a un oreiller. Qu'est-ce que c'est ?", 1, ["Le canapé", "Le lit", "La chaise", "La table"]),
    q!(Category::Taboo, Difficulty::Easy, "C'est un animal qui nage et qui a des écailles. Qu'est-ce que c'est ?", 1, ["La baleine", "Le poisson", "Le dauphin", "Le phoque"]),
    q!(Category::Taboo, Difficulty::Easy, "Tu le portes sur le dos pour l'école. Qu'est-ce que c'est ?", 1, ["La valise", "Le sac à dos", "Le sac", "Le cartable"]),
    q!(Category::Taboo, Difficulty::Easy, "C'est sucré, coloré et les enfants en mangent. Qu'est-ce que c'est ?", 1, ["Le légume", "Le bonbon", "Le pain", "La soupe"]),
    q!(Category::Taboo, Difficulty::Easy, "Il a une sonnette et il sonne quand quelqu'un arrive. Qu'est-ce que c'est ?", 1, ["La cloche", "La sonnette de la porte", "L'alarme", "La sirène"]),
    q!(Category::Taboo, Difficulty::Easy, "Elle est blanche et sert à écrire au tableau. Qu'est-ce que c'est ?", 1, ["Le crayon", "La craie", "Le feutre", "Le stylo à bille"]),
    q!(Category::Taboo, Difficulty::Easy, "Tu l'utilises pour te sécher les mains. Qu'est-ce que c'est ?", 1, ["Le papier", "La serviette", "Le mouchoir", "L'éponge"]),
    q!(Category::Taboo, Difficulty::Easy, "C'est un animal qui vole et qui fait 'piou piou'. Qu'est-ce que c'est ?", 1, ["Le papillon", "Le poussin", "L'abeille", "La mouche"]),
    q!(Category::Taboo, Difficulty::Easy, "Il sert à allumer la lumière de la pièce. Qu'est-ce que c'est ?", 1, ["La bougie", "L'interrupteur", "La lampe", "Le projecteur"]),
    q!(Category::Taboo, Difficulty::Easy, "C'est une boisson chaude et marron que tu prends le matin. Qu'est-ce que c'est ?", 1, ["Le thé", "Le café", "Le chocolat", "Le lait"]),
    q!(Category::Taboo, Difficulty::Easy, "Tu l'utilises pour te nettoyer les dents. Qu'est-ce que c'est ?", 1, ["Le savon", "La brosse à dents", "Le peigne", "La serviette"]),
    q!(Category::Taboo, Difficulty::Easy, "C'est un grand animal avec une trompe et des défenses. Qu'est-ce que c'est ?", 1, ["Le rhinocéros", "L'éléphant", "L'hippopotame", "La girafe"]),
    q!(Category::Taboo, Difficulty::Easy, "Il sert à réchauffer la nourriture. Qu'est-ce que c'est ?", 1, ["Le réfrigérateur", "Le micro-ondes", "Le lave-vaisselle", "Le lave-linge"]),
    q!(Category::Taboo, Difficulty::Easy, "C'est un moyen de transport qui vole haut. Qu'est-ce que c'est ?", 1, ["Le bateau", "L'avion", "Le train", "L'autobus"]),
    q!(Category::Taboo, Difficulty::Easy, "Tu l'utilises pour attacher tes cheveux. Qu'est-ce que c'est ?", 1, ["La fermeture éclair", "L'élastique à cheveux", "La ceinture", "Le lacet"]),
    q!(Category::Taboo, Difficulty::Easy, "C'est un animal qui saute et qui mange des carottes. Qu'est-ce que c'est ?", 1, ["Le hamster", "Le lapin", "Le lièvre", "La souris"]),
    q!(Category::Taboo, Difficulty::Easy, "Il sert à ouvrir la porte avec une clé. Qu'est-ce que c'est ?", 1, ["La serrure", "La poignée", "La clé", "Le verrou"]),
    q!(Category::Taboo, Difficulty::Easy, "C'est un endroit où les enfants jouent sur des balançoires. Qu'est-ce que c'est ?", 1, ["Le parc", "La place", "La cour", "Le jardin"]),
    q!(Category::Taboo, Difficulty::Easy, "Il est sucré et on le met sur le gâteau d'anniversaire. Qu'est-ce que c'est ?", 1, ["Le chocolat", "La bougie", "Le sucre", "Le miel"]),
    q!(Category::Taboo, Difficulty::Easy, "C'est un animal qui vit dans l'eau et qui a une carapace. Qu'est-ce que c'est ?", 1, ["La grenouille", "La tortue", "Le crabe", "L'escargot"]),
    q!(Category::Taboo, Difficulty::Easy, "Il sert à regarder la télévision. Qu'est-ce que c'est ?", 1, ["La radio", "La télécommande", "L'ordinateur", "Le téléphone"]),
    q!(Category::Taboo, Difficulty::Easy, "C'est un animal avec une crinière qui rugit. Qu'est-ce que c'est ?", 1, ["Le tigre", "Le lion", "Le loup", "L'ours"]),
    q!(Category::Taboo, Difficulty::Easy, "Tu l'utilises pour prendre des photos. Qu'est-ce que c'est ?", 1, ["Le portable", "L'appareil photo", "La tablette", "Le miroir"]),
    q!(Category::Taboo, Difficulty::Easy, "C'est un légume long, orange et que les lapins mangent. Qu'est-ce que c'est ?", 1, ["Le concombre", "La carotte", "La courgette", "La pomme de terre"]),
    q!(Category::Taboo, Difficulty::Easy, "Elle sert à laver le linge sale. Qu'est-ce que c'est ?", 1, ["Le micro-ondes", "Le lave-linge", "Le fer à repasser", "Le lave-vaisselle"]),
    q!(Category::Taboo, Difficulty::Easy, "C'est un animal qui a des rayures blanches et noires. Qu'est-ce que c'est ?", 1, ["Le zèbre", "La vache", "Le panda", "Le tigre"]),
    q!(Category::Taboo, Difficulty::Easy, "Tu l'utilises pour écrire avec de l'encre. Qu'est-ce que c'est ?", 1, ["Le crayon", "Le stylo à bille", "La craie", "Le feutre"]),
    q!(Category::Taboo, Difficulty::Easy, "C'est un endroit où tu achètes du pain. Qu'est-ce que c'est ?", 1, ["Le marché", "La boulangerie", "Le magasin de fruits", "La boucherie"]),
    q!(Category::Taboo, Difficulty::Easy, "C'est un animal qui miaule et qui chasse les souris. Qu'est-ce que c'est ?", 1, ["Le chien", "Le chat", "La souris", "Le hibou"]),
    q!(Category::Taboo, Difficulty::Easy, "Il sert à garder la nourriture et à la garder fraîche. Qu'est-ce que c'est ?", 1, ["L'armoire", "Le garde-manger", "Le réfrigérateur", "Le panier"]),
    q!(Category::Taboo, Difficulty::Easy, "C'est un jouet rond qui rebondit. Qu'est-ce que c'est ?", 1, ["Le dé", "Le ballon", "Le ballon de baudruche", "La bille"]),
    // -- Moyen (grande série) --
    q!(Category::Taboo, Difficulty::Medium, "Il sert à voir les os du corps à l'hôpital. Qu'est-ce que c'est ?", 1, ["L'échographie", "La radiographie", "L'IRM", "Le thermomètre"]),
    q!(Category::Taboo, Difficulty::Medium, "C'est un appareil qui aspire la poussière du sol. Qu'est-ce que c'est ?", 1, ["Le balai", "L'aspirateur", "La serpillière", "Le chiffon"]),
    q!(Category::Taboo, Difficulty::Medium, "Elle se porte autour du cou et sert à te réchauffer. Qu'est-ce que c'est ?", 1, ["La veste", "L'écharpe", "Le pull", "Le manteau"]),
    q!(Category::Taboo, Difficulty::Medium, "C'est un endroit où l'on range les voitures. Qu'est-ce que c'est ?", 1, ["L'atelier", "Le garage", "La station-service", "Le parking"]),
    q!(Category::Taboo, Difficulty::Medium, "Il sert à monter les escaliers sans effort. Qu'est-ce que c'est ?", 1, ["L'escalier", "L'ascenseur", "La rampe", "Le tapis"]),
    q!(Category::Taboo, Difficulty::Medium, "C'est un instrument qui mesure la pression de l'air. Qu'est-ce que c'est ?", 1, ["Le thermomètre", "Le baromètre", "L'hygromètre", "Le pluviomètre"]),
    q!(Category::Taboo, Difficulty::Medium, "On les met sur les yeux pour mieux voir. Qu'est-ce que c'est ?", 1, ["Les lunettes de soleil", "Les lunettes de vue", "La loupe", "Le monocle"]),
    q!(Category::Taboo, Difficulty::Medium, "C'est un animal qui hiberne et qui mange du miel. Qu'est-ce que c'est ?", 1, ["Le loup", "L'ours", "Le cerf", "Le sanglier"]),
    q!(Category::Taboo, Difficulty::Medium, "Il sert à pêcher en mer depuis un bateau. Qu'est-ce que c'est ?", 1, ["La canne à pêche", "Le filet", "Le harpon", "L'hameçon"]),
    q!(Category::Taboo, Difficulty::Medium, "C'est un appareil qui mesure le temps dans les courses. Qu'est-ce que c'est ?", 1, ["La montre", "Le chronomètre", "Le minuteur", "Le réveil"]),
    q!(Category::Taboo, Difficulty::Medium, "Il se met dans la voiture pour protéger la tête en cas de choc. Qu'est-ce que c'est ?", 1, ["La ceinture", "L'airbag", "Le casque", "L'oreiller"]),
    q!(Category::Taboo, Difficulty::Medium, "C'est un endroit où l'on range les livres en ordre. Qu'est-ce que c'est ?", 1, ["La librairie", "La bibliothèque", "L'étagère", "Le kiosque"]),
    q!(Category::Taboo, Difficulty::Medium, "Il sert à couper la pelouse du jardin. Qu'est-ce que c'est ?", 1, ["Les ciseaux", "La tondeuse", "La faucille", "La pelle"]),
    q!(Category::Taboo, Difficulty::Medium, "C'est une petite pièce de couleur marron. Qu'est-ce que c'est ?", 1, ["Le billet", "Le centime", "La carte", "L'euro"]),
    q!(Category::Taboo, Difficulty::Medium, "Il sert à allumer le feu de la cheminée. Qu'est-ce que c'est ?", 1, ["Le briquet", "Les allumettes", "La flamme", "L'étincelle"]),
    q!(Category::Taboo, Difficulty::Medium, "C'est un animal qui vit dans le désert et qui a une bosse. Qu'est-ce que c'est ?", 1, ["Le lama", "Le chameau", "Le dromadaire", "L'alpaga"]),
    q!(Category::Taboo, Difficulty::Medium, "Il sert à écrire sur l'ordinateur. Qu'est-ce que c'est ?", 1, ["La souris", "Le clavier", "L'écran", "L'imprimante"]),
    q!(Category::Taboo, Difficulty::Medium, "C'est une friandise que l'on mange à Noël. Qu'est-ce que c'est ?", 1, ["La galette des rois", "Le nougat", "Le massepain", "Les sablés"]),
    q!(Category::Taboo, Difficulty::Medium, "Il sert à mesurer la taille des personnes. Qu'est-ce que c'est ?", 1, ["Le mètre", "La toise", "La règle", "Le mètre ruban"]),
    q!(Category::Taboo, Difficulty::Medium, "C'est un endroit où l'on fait les films. Qu'est-ce que c'est ?", 1, ["Le théâtre", "Le plateau", "Le cinéma", "Le studio"]),
    q!(Category::Taboo, Difficulty::Medium, "Elles servent à protéger les yeux du soleil à la plage. Qu'est-ce que c'est ?", 1, ["La casquette", "Les lunettes de soleil", "Le chapeau", "La visière"]),
    q!(Category::Taboo, Difficulty::Medium, "C'est un animal qui se camoufle et change de couleur. Qu'est-ce que c'est ?", 1, ["Le caméléon", "Le serpent", "Le lézard", "La grenouille"]),
    q!(Category::Taboo, Difficulty::Medium, "Il sert à piler la glace en été. Qu'est-ce que c'est ?", 1, ["Le verre", "Le mixeur", "La centrifugeuse", "Le blender"]),
    q!(Category::Taboo, Difficulty::Medium, "C'est un appareil qui vole sans pilote. Qu'est-ce que c'est ?", 1, ["L'hélicoptère", "Le drone", "L'avion", "Le ballon"]),
    q!(Category::Taboo, Difficulty::Medium, "Il sert à nettoyer les vitres de la fenêtre. Qu'est-ce que c'est ?", 1, ["Le chiffon", "La lavette", "La raclette", "L'éponge"]),
    q!(Category::Taboo, Difficulty::Medium, "C'est un animal qui a une corne sur la tête. Qu'est-ce que c'est ?", 1, ["Le rhinocéros", "La licorne", "Le taureau", "L'antilope"]),
    q!(Category::Taboo, Difficulty::Medium, "Elle sert à payer dans les magasins sans argent. Qu'est-ce que c'est ?", 1, ["Le billet", "La carte", "Le chèque", "La pièce"]),
    q!(Category::Taboo, Difficulty::Medium, "C'est un endroit où l'on regarde des films sur un grand écran. Qu'est-ce que c'est ?", 1, ["Le théâtre", "Le cinéma", "Le parc", "Le musée"]),
    q!(Category::Taboo, Difficulty::Medium, "Il sert à faire du jus d'orange. Qu'est-ce que c'est ?", 1, ["Le mixeur", "Le presse-agrumes", "La centrifugeuse", "Le pressoir"]),
    q!(Category::Taboo, Difficulty::Medium, "C'est un animal qui a une poche pour ses petits. Qu'est-ce que c'est ?", 1, ["Le koala", "Le kangourou", "Le paresseux", "Le wombat"]),
    q!(Category::Taboo, Difficulty::Medium, "Il sert à voir les étoiles la nuit. Qu'est-ce que c'est ?", 1, ["La longue-vue", "Le télescope", "Les jumelles", "Le microscope"]),
    q!(Category::Taboo, Difficulty::Medium, "C'est un jeu de société avec des cases et des dés. Qu'est-ce que c'est ?", 1, ["Les échecs", "Le jeu de l'oie", "Les cartes", "Le domino"]),
    q!(Category::Taboo, Difficulty::Medium, "Il sert à transporter les malades à l'hôpital. Qu'est-ce que c'est ?", 1, ["L'ambulance", "Le brancard", "Le fauteuil roulant", "L'escalier"]),
    q!(Category::Taboo, Difficulty::Medium, "C'est un appareil qui diffuse de la musique sans fils. Qu'est-ce que c'est ?", 1, ["La radio", "L'enceinte", "Le casque", "Le tourne-disque"]),
    q!(Category::Taboo, Difficulty::Medium, "Il sert à faire les devoirs et il est en bois. Qu'est-ce que c'est ?", 1, ["La chaise", "La table", "Le pupitre", "L'armoire"]),
    q!(Category::Taboo, Difficulty::Medium, "C'est un animal qui a des plumes et qui ne vole pas. Qu'est-ce que c'est ?", 1, ["Le poulet", "Le pingouin", "L'autruche", "La dinde"]),
    q!(Category::Taboo, Difficulty::Medium, "Elle sert à garder l'argent à la banque. Qu'est-ce que c'est ?", 1, ["La tirelire", "Le compte", "Le portefeuille", "La caisse"]),
    q!(Category::Taboo, Difficulty::Medium, "C'est un instrument qui fait des bulles de savon. Qu'est-ce que c'est ?", 1, ["La paille", "L'anneau", "La baguette", "Le ballon"]),
    q!(Category::Taboo, Difficulty::Medium, "Il sert à mesurer le temps en cuisine. Qu'est-ce que c'est ?", 1, ["La montre", "Le minuteur", "Le chronomètre", "La cloche"]),
    q!(Category::Taboo, Difficulty::Medium, "C'est un endroit où l'on garde les bateaux. Qu'est-ce que c'est ?", 1, ["Le port", "Le chantier naval", "La plage", "Le quai"]),
    // -- Difficile (grande série) --
    q!(Category::Taboo, Difficulty::Hard, "Instrument de navigation qui indique le nord. Qu'est-ce que c'est ?", 1, ["La carte", "La boussole", "Le sextant", "Le GPS"]),
    q!(Category::Taboo, Difficulty::Hard, "Appareil qui mesure la vitesse du vent. Qu'est-ce que c'est ?", 1, ["Le baromètre", "L'anémomètre", "Le pluviomètre", "Le thermomètre"]),
    q!(Category::Taboo, Difficulty::Hard, "Science qui étudie les fossiles. Qu'est-ce que c'est ?", 1, ["L'archéologie", "La paléontologie", "La géologie", "La biologie"]),
    q!(Category::Taboo, Difficulty::Hard, "Appareil qui capte les ondes radio et les convertit en son. Qu'est-ce que c'est ?", 1, ["L'antenne", "La radio", "L'enceinte", "L'amplificateur"]),
    q!(Category::Taboo, Difficulty::Hard, "Outil du charpentier pour enfoncer des clous. Qu'est-ce que c'est ?", 1, ["La scie", "Le marteau", "Le tournevis", "Les tenailles"]),
    q!(Category::Taboo, Difficulty::Hard, "Instrument qui sert à mesurer les angles à l'école. Qu'est-ce que c'est ?", 1, ["La règle", "Le rapporteur", "Le compas", "L'équerre"]),
    q!(Category::Taboo, Difficulty::Hard, "Appareil qui projette des images sur le mur de la classe. Qu'est-ce que c'est ?", 1, ["La télévision", "Le projecteur", "Le rétroprojecteur", "Le tableau"]),
    q!(Category::Taboo, Difficulty::Hard, "Objet qui sert à accrocher les tableaux au mur. Qu'est-ce que c'est ?", 1, ["La punaise", "Le clou", "La vis", "L'agrafe"]),
    q!(Category::Taboo, Difficulty::Hard, "Appareil qui détecte les métaux sous terre. Qu'est-ce que c'est ?", 1, ["Le radar", "Le détecteur de métaux", "La boussole", "Le sonar"]),
    q!(Category::Taboo, Difficulty::Hard, "Instrument du médecin pour écouter le cœur. Qu'est-ce que c'est ?", 1, ["Le thermomètre", "Le stéthoscope", "Le tensiomètre", "Le cardiofréquencemètre"]),
    q!(Category::Taboo, Difficulty::Hard, "Outil du jardinier pour creuser la terre. Qu'est-ce que c'est ?", 1, ["Le râteau", "La pelle", "La houe", "La fourche"]),
    q!(Category::Taboo, Difficulty::Hard, "Appareil qui convertit la lumière du soleil en électricité. Qu'est-ce que c'est ?", 1, ["La turbine", "Le panneau solaire", "Le générateur", "La batterie"]),
    q!(Category::Taboo, Difficulty::Hard, "Instrument qui sert à dessiner des cercles. Qu'est-ce que c'est ?", 1, ["La règle", "Le compas", "L'équerre", "Le rapporteur"]),
    q!(Category::Taboo, Difficulty::Hard, "Appareil qui mesure l'altitude d'un avion. Qu'est-ce que c'est ?", 1, ["Le baromètre", "L'altimètre", "Le compteur de vitesse", "Le radar"]),
    q!(Category::Taboo, Difficulty::Hard, "Outil du serrurier pour ouvrir les serrures. Qu'est-ce que c'est ?", 1, ["La clé", "Le crochet", "Le tournevis", "Les pinces"]),
    q!(Category::Taboo, Difficulty::Hard, "Appareil qui stocke l'énergie électrique pour l'utiliser ensuite. Qu'est-ce que c'est ?", 1, ["Le générateur", "La batterie", "Le transformateur", "Le moteur"]),
    q!(Category::Taboo, Difficulty::Hard, "Instrument de l'astronome pour observer les planètes. Qu'est-ce que c'est ?", 1, ["La longue-vue", "Le télescope", "Le microscope", "Les jumelles"]),
    q!(Category::Taboo, Difficulty::Hard, "Science qui étudie les tremblements de terre. Qu'est-ce que c'est ?", 1, ["La météorologie", "La sismologie", "La volcanologie", "La géologie"]),
    q!(Category::Taboo, Difficulty::Hard, "Appareil utilisé au bloc opératoire pour voir l'intérieur du corps. Qu'est-ce que c'est ?", 1, ["La radiographie", "L'endoscope", "L'échographie", "Le scanner"]),
    q!(Category::Taboo, Difficulty::Hard, "Outil de l'électricien pour couper les câbles. Qu'est-ce que c'est ?", 1, ["Le cutter", "Les pinces coupantes", "Les ciseaux", "La scie"]),
    q!(Category::Taboo, Difficulty::Hard, "Instrument qui mesure l'humidité de l'air. Qu'est-ce que c'est ?", 1, ["Le baromètre", "L'hygromètre", "Le pluviomètre", "Le thermomètre"]),
    q!(Category::Taboo, Difficulty::Hard, "Appareil qui fait sortir l'eau d'un robinet. Qu'est-ce que c'est ?", 1, ["La pompe", "La canalisation", "Le réservoir", "La citerne"]),
    q!(Category::Taboo, Difficulty::Hard, "Outil du maçon pour mettre à niveau. Qu'est-ce que c'est ?", 1, ["Le fil à plomb", "Le niveau", "L'équerre", "Le mètre"]),
    q!(Category::Taboo, Difficulty::Hard, "Appareil qui enregistre la voix et la reproduit. Qu'est-ce que c'est ?", 1, ["Le microphone", "L'enregistreur", "L'enceinte", "L'écouteur"]),
    q!(Category::Taboo, Difficulty::Hard, "Instrument à vent avec trois pistons. Qu'est-ce que c'est ?", 1, ["La trompette", "Le trombone", "Le tuba", "La clarinette"]),
    q!(Category::Taboo, Difficulty::Hard, "Appareil qui sert à cuisiner à la vapeur. Qu'est-ce que c'est ?", 1, ["La friteuse", "L'autocuiseur", "Le cuit-vapeur", "La poêle"]),
    q!(Category::Taboo, Difficulty::Hard, "Outil du mécanicien pour serrer les écrous. Qu'est-ce que c'est ?", 1, ["Le tournevis", "La clé anglaise", "Les pinces", "La pince"]),
    q!(Category::Taboo, Difficulty::Hard, "Science qui étudie les étoiles et les planètes. Qu'est-ce que c'est ?", 1, ["L'astrologie", "L'astronomie", "La cosmologie", "L'astrophysique"]),
    q!(Category::Taboo, Difficulty::Hard, "Appareil utilisé au laboratoire pour peser. Qu'est-ce que c'est ?", 1, ["La balance", "L'éprouvette", "Le ballon", "Le bécher"]),
    q!(Category::Taboo, Difficulty::Hard, "Instrument qui mesure la quantité de pluie. Qu'est-ce que c'est ?", 1, ["L'hygromètre", "Le pluviomètre", "Le baromètre", "L'anémomètre"]),
    q!(Category::Taboo, Difficulty::Hard, "Appareil qui projette l'ombre d'un objet. Qu'est-ce que c'est ?", 1, ["La lampe", "Le rétroprojecteur", "Le vidéoprojecteur", "Le spot"]),
    q!(Category::Taboo, Difficulty::Hard, "Outil du tailleur pour coudre. Qu'est-ce que c'est ?", 1, ["L'aiguille", "La machine à coudre", "Le dé à coudre", "Les ciseaux"]),
    q!(Category::Taboo, Difficulty::Hard, "Appareil utilisé sur les bateaux pour mesurer la profondeur. Qu'est-ce que c'est ?", 1, ["Le radar", "Le sonar", "Le sextant", "La sonde"]),
    q!(Category::Taboo, Difficulty::Hard, "Instrument de musique à touches et à soufflet. Qu'est-ce que c'est ?", 1, ["L'orgue", "L'accordéon", "Le piano", "La concertina"]),
    q!(Category::Taboo, Difficulty::Hard, "Appareil qui dessale l'eau de mer. Qu'est-ce que c'est ?", 1, ["La station d'épuration", "L'usine de dessalement", "L'usine de potabilisation", "L'usine de filtration"]),
    q!(Category::Taboo, Difficulty::Hard, "Outil du sculpteur pour donner forme à la pierre. Qu'est-ce que c'est ?", 1, ["Le ciseau", "Le marteau", "La gouge", "La râpe"]),
    q!(Category::Taboo, Difficulty::Hard, "Science qui étudie les plantes. Qu'est-ce que c'est ?", 1, ["La zoologie", "La botanique", "L'écologie", "L'agronomie"]),
    q!(Category::Taboo, Difficulty::Hard, "Appareil qui sert à mesurer le pouls. Qu'est-ce que c'est ?", 1, ["Le thermomètre", "Le cardiofréquencemètre", "Le tensiomètre", "Le lecteur de glycémie"]),
    q!(Category::Taboo, Difficulty::Hard, "Instrument du géomètre pour mesurer les distances. Qu'est-ce que c'est ?", 1, ["La règle", "Le théodolite", "Le niveau", "Le fil à plomb"]),
    q!(Category::Taboo, Difficulty::Hard, "Outil du barbier pour raser. Qu'est-ce que c'est ?", 1, ["La lame", "Le rasoir électrique", "Le rasoir", "Les ciseaux"]),
    // ================= Questions ouvertes =================
    // -- Mathématiques --
    q_open!(Category::Math, Difficulty::Easy, "Combien font 6 x 7 ?", "42"),
    q_open!(Category::Math, Difficulty::Medium, "Quelle est la racine carrée de 144 ?", "12"),
    q_open!(Category::Math, Difficulty::Hard, "Combien de degrés mesurent les angles d'un triangle ?", "180"),
    // -- Histoire --
    q_open!(Category::History, Difficulty::Easy, "En quelle année Colomb a-t-il découvert l'Amérique ?", "1492"),
    q_open!(Category::History, Difficulty::Medium, "En quelle année a commencé la Seconde Guerre mondiale ?", "1939"),
    q_open!(Category::History, Difficulty::Hard, "En quelle année est tombé le mur de Berlin ?", "1989"),
    // -- Informatique --
    q_open!(Category::Cs, Difficulty::Easy, "Combien de bits y a-t-il dans un octet ?", "8"),
    q_open!(Category::Cs, Difficulty::Medium, "Dans quel langage ce jeu est-il programmé ?", "Rust"),
    q_open!(Category::Cs, Difficulty::Hard, "Que signifie IA ?", "Intelligence artificielle"),
    // -- Géographie --
    q_open!(Category::Geography, Difficulty::Easy, "Quelle est la capitale de la France ?", "Paris"),
    q_open!(Category::Geography, Difficulty::Medium, "Quel est le plus grand pays du monde ?", "Russie"),
    q_open!(Category::Geography, Difficulty::Hard, "Quel détroit sépare l'Espagne du Maroc ?", "Gibraltar"),
    // -- Sciences --
    q_open!(Category::Science, Difficulty::Easy, "Combien de planètes compte le système solaire ?", "8"),
    q_open!(Category::Science, Difficulty::Medium, "Quelle est la formule chimique de l'eau ?", "H2O"),
    q_open!(Category::Science, Difficulty::Hard, "Quel scientifique a formulé la théorie de la relativité ?", "Einstein"),
    // -- Art --
    q_open!(Category::Art, Difficulty::Easy, "Combien de couleurs a l'arc-en-ciel ?", "7"),
    q_open!(Category::Art, Difficulty::Medium, "Qui a peint 'Les Ménines' ?", "Velázquez"),
];
